Repository spiceai/spiceai, pull requests merged in 2021-10, with the labels that each got.

#269 Mitigates race in dashboard build
  dashboard/package.json
Labels: bug

#277 Fixes serving of acknowledgements
  pkg/dashboard/embedded.go
Labels: bug

#276 Add v0.2 release notes
  docs/PRINCIPLES.md
  docs/RELEASE.md
  docs/ROADMAP.md
  docs/release_notes/v0.2-alpha.md
Labels: documentation

#281 Fixes no data on missing epoch bug
  pkg/pods/pod.go
Labels: bug

#271 Bumps version to 0.2.1-alpha-rc
  version.txt
Labels: endgame
