Repository spiceai/spiceai, pull requests merged in 2021-11, with the labels that each got.

#383 Add support for specifying seed data
  pkg/aiengine/data_test.go
  pkg/aiengine/init.go
  pkg/dataspace/dataspace.go
  pkg/dataspace/dataspace_test.go
  pkg/spec/dataspace.go
  test/assets/pods/manifests/trader-seed.yaml
  test/assets/snapshots/aiengine/TestPod-InitializePod()_-_event-categories.yaml
  test/assets/snapshots/aiengine/TestPod-InitializePod()_-_event-tags.yaml
  test/assets/snapshots/aiengine/TestPod-InitializePod()_-_trader.yaml
  test/assets/snapshots/aiengine/TestPod-testGetPodInitForTrainingFunc()_-_event-categories.yaml
  test/assets/snapshots/aiengine/TestPod-testGetPodInitForTrainingFunc()_-_event-tags.yaml
  test/assets/snapshots/aiengine/TestPod-testGetPodInitForTrainingFunc()_-_trader-infer.yaml
  test/assets/snapshots/aiengine/TestPod-testGetPodInitForTrainingFunc()_-_trader.yaml
  test/assets/snapshots/aiengine/testutils-Snapshotter-SnapshotMultiJson-event-tags.yaml.json
  test/assets/snapshots/aiengine/testutils-Snapshotter-SnapshotMultiJson-trader-infer.yaml.json
  test/assets/snapshots/aiengine/testutils-Snapshotter-SnapshotMultiJson-trader.yaml.json
  test/assets/snapshots/dataspace/dataspace-testGetCategoriesFunc-func1-btcusd_with_seed_categories
  test/assets/snapshots/dataspace/dataspace-testGetCategoriesFunc-func1-btcusd_with_seed_category_names
  test/assets/snapshots/dataspace/dataspace-testGetCategoriesFunc-func1-btcusd_with_seed_category_selectors
  test/assets/snapshots/dataspace/dataspace-testGetMeasurementsFunc-func1-btcusd_with_seed_measurement_selectors
  test/assets/snapshots/dataspace/dataspace-testGetMeasurementsFunc-func1-btcusd_with_seed_measurements
  test/assets/snapshots/dataspace/dataspace-testGetTagSelectorsFunc-func1-btcusd_with_seed_tag_selectors
  test/assets/snapshots/dataspace/dataspace-testGetTagsFunc-func1-btcusd_with_seed_fqtags
  test/assets/snapshots/dataspace/dataspace-testGetTagsFunc-func1-btcusd_with_seed_tags
  test/assets/snapshots/dataspace/dataspace-testMeasurementsFunc-func1-coinbase_btcusd_with_seed
  test/assets/snapshots/e2e/TestCLICmdPodsList
  test/assets/snapshots/e2e/TestPods
  test/assets/snapshots/e2e/TestSeedAndStreamingObservations
  test/assets/snapshots/e2e/e2e-TestDataspaceData-trader-seed-streaming_initial_observations.csv
  test/e2e/e2e_test.go
Labels: enhancement

#386 Add v0.3.1 release notes
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e_test.yml
  .github/workflows/license_check.yml
  .github/workflows/linter.yml
  .github/workflows/pr_test.yml
  docs/ROADMAP.md
  docs/release_notes/v0.3.1-alpha.md
Labels: documentation

#375 Add support for external reward functions
  ai/src/data.py
  ai/src/exec.py
  ai/src/main.py
  ai/src/proto/aiengine/v1/aiengine_pb2.py
  ai/src/tests/test_datamanager.py
  ai/src/tests/test_stateful.py
  ai/src/validation.py
  pkg/aiengine/init.go
  pkg/aiengine/init_test.go
  pkg/flights/flight.go
  pkg/pods/pod.go
  pkg/proto/aiengine_pb/aiengine.pb.go
  pkg/spec/pods.go
  proto/aiengine/v1/aiengine.proto
  test/assets/pods/manifests/trader-external-reward.yaml
  test/assets/rewards/trader_rewards.py
  test/assets/snapshots/aiengine/testutils-Snapshotter-SnapshotMultiJson-trader-external-reward.yaml.json
  test/assets/snapshots/e2e/TestCLICmdPodsList
  test/assets/snapshots/e2e/TestPods
  test/assets/snapshots/e2e/e2e-TestDataspaceData-trader-external-funcs_initial_observations.csv
  test/e2e/e2e_test.go
Labels: enhancement

#401 Add support for automatic time categorization
  .vscode/launch.json
  pkg/aiengine/data.go
  pkg/aiengine/data_test.go
  pkg/pods/pod.go
  pkg/pods/pod_test.go
  pkg/spec/pods.go
  pkg/time/categories.go
  pkg/time/categories_test.go
  test/assets/pods/manifests/event-categories.yaml
  test/assets/pods/manifests/trader.yaml
  test/assets/snapshots/aiengine/TestGetAddDataRequest
  test/assets/snapshots/aiengine/TestGetData-getData()_-_All_headers_with_preview
  test/assets/snapshots/aiengine/TestGetData-getData()_-_Select_headers_with_preview
  test/assets/snapshots/aiengine/TestGetData-getData()_-_With_categories
  test/assets/snapshots/aiengine/TestGetData-getData()_-_With_tags
  test/assets/snapshots/aiengine/TestObservations-getAddDataRequest()
  test/assets/snapshots/time/categories/TestGenerateTimeCategoryColumnsDayOfMonth
  test/assets/snapshots/time/categories/TestGenerateTimeCategoryColumnsDayOfWeek
  test/assets/snapshots/time/categories/TestGenerateTimeCategoryColumnsHour
  test/assets/snapshots/time/categories/TestGenerateTimeCategoryColumnsMonth
  test/assets/snapshots/time/categories/TestGenerateTimeCategoryFieldsDayOfMonth
  test/assets/snapshots/time/categories/TestGenerateTimeCategoryFieldsDayOfWeek
  test/assets/snapshots/time/categories/TestGenerateTimeCategoryFieldsHour
  test/assets/snapshots/time/categories/TestGenerateTimeCategoryFieldsMonth
  test/assets/snapshots/time/categories/testutils-Snapshotter-SnapshotMultiJson-dayofmonth.json
  test/assets/snapshots/time/categories/testutils-Snapshotter-SnapshotMultiJson-dayofweek.json
  test/assets/snapshots/time/categories/testutils-Snapshotter-SnapshotMultiJson-hour.json
  test/assets/snapshots/time/categories/testutils-Snapshotter-SnapshotMultiJson-month.json
Labels: enhancement

#402 Get a recommendation for a specific time
  ai/src/data.py
  ai/src/inference.py
  ai/src/main.py
  ai/src/proto/aiengine/v1/aiengine_pb2.py
  ai/src/tests/test_main.py
  pkg/aiengine/aiengine_test.go
  pkg/aiengine/inferencing.go
  pkg/http/server.go
  pkg/proto/aiengine_pb/aiengine.pb.go
  proto/aiengine/v1/aiengine.proto
Labels: enhancement

#405 Update to TensorFlow 2.6.1 and freeze Keras to 2.6.0
  ai/src/requirements/common.txt
  test/e2e/e2e_test.go
  test/e2e/runtime.go
Labels: dependencies

#407 Wire up identifiers
  go.mod
  go.sum
  pkg/aiengine/data_test.go
  pkg/dataspace/dataspace.go
  pkg/observations/observation_test.go
  test/assets/snapshots/observations/TestObservations-GetCsv()_-_With_tags
  test/e2e/runtime.go
Labels: enhancement

#409 Add validation for dataspace 'from' and 'name' in manifest
  pkg/pods/pod.go
  pkg/pods/pod_test.go
  pkg/validator/validator.go
  pkg/validator/validator_test.go
  spiceai.code-workspace
  test/assets/pods/manifests/event-tags-invalid.yaml
  test/assets/snapshots/pods/TestPod-CachedCsv()_-_event-tags-invalid.yaml
  test/assets/snapshots/pods/pods-testTagsFunc-func1-event-tags-invalid_tags
Labels: bug

#411 Upgrade to TensorFlow 2.7 & Keras 2.7
  ai/src/requirements/common.txt
Labels: dependencies

#410 Add number of episodes and learning algorithm to dashboard training charts
  ai/src/algorithms/dql/dql.json
  ai/src/algorithms/vpg/vpg.json
  dashboard/package.json
  dashboard/src/components/flights/FlightChart.tsx
  dashboard/src/models/flight.ts
  dashboard/src/models/pod.ts
  dashboard/src/pages/PodPage.tsx
  dashboard/yarn.lock
  pkg/aiengine/aiengine_test.go
  pkg/aiengine/algorithm.go
  pkg/aiengine/init.go
  pkg/aiengine/pod.go
  pkg/aiengine/training.go
  pkg/api/flight.go
  pkg/api/pod.go
  pkg/flights/flight.go
  pkg/flights/flights_test.go
  pkg/http/server.go
  pkg/runtime/runtime.go
  pkg/runtime/watcher.go
  test/assets/snapshots/api/pod/TestNewPod
  test/assets/snapshots/e2e/TestCLICmdPodsList
  test/assets/snapshots/e2e/TestPods
Labels: enhancement

#414 Fix Data Processor using Data Connector params
  pkg/dataspace/dataspace.go
Labels: bug

#412 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#415 Trim spaces from selectors
  pkg/dataspace/dataspace.go
Labels: bug

#419 Fix crash on load pod if `training` section is not included in manifest
  pkg/pods/pod.go
Labels: bug

#417 Construct header names from pod definition of fields
  dashboard/src/models/observation.ts
  dashboard/src/models/pod.ts
  dashboard/src/pages/PodPage.tsx
Labels: bug

#406 Create a separate metrics instance per data_manager
  ai/src/data.py
  ai/src/progress.py
  ai/src/train.py
Labels: bug

#418 Upgrade to glide-data-grid v3.0.3
  dashboard/package.json
  dashboard/src/pages/PodPage.tsx
  dashboard/yarn.lock
Labels: dependencies

#423 Update dashboard packages autoprefixer, lodash, swr, tailwindcss & typescript
  dashboard/package.json
  dashboard/yarn.lock
Labels: dependencies

#430 Support dashboard observations grid column resizing
  dashboard/package.json
  dashboard/src/pages/PodPage.tsx
  dashboard/yarn.lock
Labels: enhancement, dependencies, dashboard

#429 v0.4-alpha endgame
  Makefile
  dashboard/src/content/acknowledgements.md
  docs/ROADMAP.md
  docs/release_notes/v0.4-alpha.md
  go.mod
  go.sum
Labels: documentation, dependencies

#438 Fix error attemping to load non-manifest file as manifest
  pkg/runtime/runtime.go
Labels: bug

#439 Sanitize zip extract path
  pkg/util/zip.go
Labels: bug

#443 Adds `lint` target to Makefile for AI Engine, handle graceful shutdown
  Makefile
  ai/src/Makefile
  ai/src/cleanup.py
  ai/src/main.py
Labels: enhancement

#425 Added functionality to prompt update for version ,run and add commands when required #388
  pkg/cli/cmd/add.go
  pkg/cli/cmd/run.go
  pkg/cli/cmd/upgrade.go
  pkg/cli/cmd/version.go
  pkg/github/runtime_release.go
Labels: enhancement

#444 Support parsing time encoded as hex
  pkg/time/time.go
  pkg/time/time_test.go
  pkg/util/zip.go
Labels: enhancement

#445 Upgrade Go dependencies
  go.mod
  go.sum
Labels: dependencies

#446 Support resizing observations data grid
  dashboard/package.json
  dashboard/src/pages/PodPage.tsx
  dashboard/yarn.lock
Labels: enhancement

#448 Sanitize extract path for Spicerack client
  pkg/registry/spicerack.go
  pkg/util/zip.go
Labels: bug

#450 Fix sanitize order
  pkg/registry/spicerack.go
Labels: bug

#452 Only check for latest version once every 24 hours
  pkg/aiengine/aiengine_test.go
  pkg/cli/cmd/add.go
  pkg/cli/cmd/run.go
  pkg/cli/cmd/util.go
  pkg/cli/cmd/version.go
  pkg/context/metal/metal.go
  pkg/context/metal/metal_test.go
  pkg/github/runtime_release.go
Labels: bug

#453 Upgrade postcss to 8.3.11 and set default height for grid
  dashboard/package.json
  dashboard/src/pages/PodPage.tsx
  dashboard/yarn.lock
Labels: bug, dependencies, dashboard

#454 Dashboard: Support dataspace header groupings
  dashboard/src/pages/PodPage.tsx
Labels: enhancement, dashboard

#451 Remove table_lock during a training run
  ai/src/connector/stateful.py
  ai/src/data_manager/base_manager.py
  ai/src/data_manager/event_manager.py
  ai/src/data_manager/time_series_manager.py
  ai/src/inference.py
  ai/src/main.py
  ai/src/tests/test_datamanager.py
  ai/src/tests/test_stateful.py
  ai/src/tests/test_train_loop.py
  ai/src/train.py
Labels: enhancement

#459 Update Go module dependencies and OSS acknowledgements
  dashboard/src/content/acknowledgements.md
  go.mod
  go.sum
Labels: documentation, dependencies

#457 Roadmap updates (Nov 2021)
  docs/ROADMAP.md
Labels: documentation

#456 Create v0.4.1-alpha.md
  docs/release_notes/v0.4.1-alpha.md
Labels: documentation

#461 Add blog post
  README.md
Labels: documentation

#468 Update Roadmap for next 3-months
  docs/ROADMAP.md
Labels: documentation
