Repository spiceai/spiceai, pull requests merged in 2021-09, with the labels that each got.

#148 Make project public
  .github/workflows/e2e_test.yml
  .github/workflows/license_check.yml
  .github/workflows/linter.yml
  .github/workflows/pr_test.yml
  .github/workflows/spice.yml
  .github/workflows/spiced.yml
  .github/workflows/spiced_docker.yml
  Makefile
  docker/Dockerfile
  docs/release_notes/v0.1.0-alpha.md
  install/install.sh
  pkg/github/asset.go
  pkg/github/github.go
  pkg/github/runtime_release.go
  version.txt
Labels: enhancement

#169 Remove self-hosted agent and cross-compile darwin/arm64
  .github/workflows/spice.yml
  .github/workflows/spiced.yml
Labels: enhancement

#168 README tweaks with arch diagram
  README.md
Labels: documentation

#173 Update go mod/sum
  go.mod
  go.sum
Labels: enhancement

#174 Remove ARM64 from publish
  .github/workflows/spice.yml
  .github/workflows/spiced.yml
Labels: bug

#176 Update Discord server link
  README.md
Labels: bug, documentation

#177 Serve open source acknowledgements as static media
  dashboard/package.json
  dashboard/src/App.tsx
  dashboard/src/components/layout/Footer.tsx
  dashboard/src/components/layout/Header.tsx
  dashboard/src/constants.ts
  dashboard/src/content/acknowledgements.md
  dashboard/src/pages/Acknowledgements.tsx
  dashboard/src/tailwind.css
  dashboard/tsconfig.json
  dashboard/typings/markdown.d.ts
  dashboard/yarn.lock
  pkg/dashboard/dashboard.go
  pkg/dashboard/dashboard_test.go
  pkg/dashboard/embedded.go
  pkg/http/server.go
Labels: enhancement

#182 Fix dashboard refresh bug
  dashboard/src/models/flight.ts
Labels: bug

#183 Set User-Agent on HTTP client calls
  cmd/spice/main.go
  cmd/spiced/main.go
  pkg/http/client.go
  pkg/registry/spicerack.go
  pkg/version/version.go
Labels: enhancement

#186 Change Docker image to `spiceai/spiceai` and push to DockerHub
  .github/workflows/e2e_test.yml
  .github/workflows/spiced_docker.yml
  Makefile
  docs/RELEASE.md
  pkg/context/docker/docker.go
Labels: enhancement

#199 Improve clarity of what Spice.ai is
  README.md
Labels: documentation

#200 Add why Spice.ai section
  README.md
Labels: documentation

#201 Remove duplicate paragraph
  README.md
Labels: documentation

#208 Do not catch-all for API calls
  pkg/http/server.go
Labels: bug

#209 Use fasthttp String specific funcs
  pkg/http/server.go
Labels: enhancement

#210 Add interpretations API
  ai/src/proto/runtime/v1/runtime_pb2.py
  go.sum
  pkg/api/interpretation.go
  pkg/http/client.go
  pkg/http/server.go
  pkg/http/server_test.go
  pkg/interpretations/interpretation.go
  pkg/interpretations/interpretation_test.go
  pkg/pods/pod.go
  pkg/pods/pod_test.go
  pkg/proto/runtime_pb/runtime.pb.go
  proto/runtime/v1/runtime.proto
  test/assets/data/json/e2e_additional_interpretations.json
  test/assets/snapshots/e2e/e2e-TestInterpretations
  test/e2e/e2e_test.go
  test/e2e/runtime.go
Labels: enhancement

#213 Add sleep to set-version to ensure flush
  dashboard/package.json
Labels: bug

#212 Fix interpretations marshalling
  pkg/api/interpretation.go
  pkg/http/server.go
  pkg/http/server_test.go
  pkg/interpretations/interpretation.go
Labels: bug

#214 Import/export interpretations
  pkg/aiengine/pod.go
  pkg/api/interpretation.go
  pkg/http/server.go
  test/assets/snapshots/e2e/e2e-TestImportExport
  test/e2e/e2e_test.go
Labels: enhancement

#225 Display action counts in training run chart
  dashboard/src/components/flights/FlightChart.tsx
  dashboard/src/models/episode.ts
Labels: enhancement

#226 Fix Incorrect conversion between integer types
  pkg/pods/pod.go
Labels: bug

#228 Update install instructions for running on Codespaces
  CONTRIBUTING.md
  ai/src/Makefile
Labels: documentation

#218 Make interpretations available to reward function
  Makefile
  ai/src/.vscode/settings.json
  ai/src/Makefile
  ai/src/data.py
  ai/src/main.py
  ai/src/proto/aiengine/v1/aiengine_pb2.py
  ai/src/proto/aiengine/v1/aiengine_pb2_grpc.py
  ai/src/proto/common/v1/common_pb2.py
  ai/src/proto/common/v1/common_pb2_grpc.py
  ai/src/proto/runtime/v1/runtime_pb2.py
  ai/src/train.py
  pkg/aiengine/grpc.go
  pkg/aiengine/grpc_mock.go
  pkg/aiengine/interpretations.go
  pkg/aiengine/pod.go
  pkg/aiengine/training.go
  pkg/environment/environment_test.go
  pkg/http/server.go
  pkg/http/server_test.go
  pkg/interpretations/interpretations.go
  pkg/interpretations/interpretations_test.go
  pkg/pods/pod.go
  pkg/pods/pod_test.go
  pkg/proto/aiengine_pb/aiengine.pb.go
  pkg/proto/aiengine_pb/aiengine_grpc.pb.go
  pkg/proto/common_pb/common.pb.go
  pkg/proto/runtime_pb/runtime.pb.go
  pkg/util/time.go
  pkg/util/time_test.go
  proto/aiengine/v1/aiengine.proto
  proto/common/v1/common.proto
  proto/runtime/v1/runtime.proto
  test/assets/snapshots/interpretations/TestInterpretations-TimeIndex()
Labels: enhancement

#236 Remove latest tag from trunk
  .github/workflows/spiced_docker.yml
Labels: bug

#241 Use github-release v2.0.0
  .github/workflows/spice.yml
  .github/workflows/spiced.yml
Labels: enhancement

#243 Support downloading zipped Spicepods
  go.mod
  go.sum
  pkg/http/client.go
  pkg/registry/spicerack.go
  test/e2e/e2e_test.go
Labels: enhancement

#246 Adding required dependency for release client
  .github/workflows/spice.yml
  .github/workflows/spiced.yml
Labels: bug

#255 Use the latest 3.8 Python available
  .github/workflows/license_check.yml
Labels: bug

#254 Separate AI engine data serialization and filter data before epoch
  pkg/aiengine/data.go
  pkg/aiengine/data_test.go
  pkg/observations/observation.go
  pkg/observations/observation_test.go
  pkg/pods/pod.go
  test/assets/snapshots/aiengine/TestObservations-getData()_-_All_headers_with_preview
  test/assets/snapshots/observations/TestObservations-GetCsv()_-_All_headers
  test/assets/snapshots/observations/TestObservations-GetCsv()_-_Select_headers
Labels: enhancement

#253 Switch to streaming data instead of fetching
  docs/ROADMAP.md
  go.mod
  go.sum
  pkg/aiengine/data.go
  pkg/aiengine/interpretations.go
  pkg/aiengine/model.go
  pkg/aiengine/pod.go
  pkg/cli/cmd/export.go
  pkg/cli/cmd/import.go
  pkg/cli/runtime/client.go
  pkg/dataspace/dataspace.go
  pkg/dataspace/dataspace_test.go
  pkg/environment/environment.go
  pkg/environment/environment_test.go
  pkg/http/server.go
  pkg/pods/pod.go
  pkg/pods/pod_test.go
  pkg/pods/pods.go
  pkg/runtime/runtime.go
  pkg/runtime/watcher.go
  pkg/state/state.go
  pkg/util/file.go
  test/assets/snapshots/e2e/TestPods
  test/e2e/e2e_test.go
  test/e2e/runtime.go
Labels: enhancement

#251 Fixing build instructions
  CONTRIBUTING.md
  Makefile
Labels: documentation

#257 Support custom time formats for "time" column
  pkg/http/server.go
  pkg/interpretations/interpretations.go
  pkg/time/time.go
  pkg/time/time_test.go
  pkg/util/time_test.go
Labels: enhancement

#258 Add read lock around interpretations
  pkg/interpretations/interpretations.go
Labels: bug

#266 Updates to Roadmap based on progress, community and customer feedback
  docs/ROADMAP.md
Labels: documentation

#267 Add basic diagnostics API
  pkg/context/context.go
  pkg/context/docker/docker.go
  pkg/context/metal/metal.go
  pkg/diagnostics/diagnostics.go
  pkg/http/server.go
Labels: enhancement
