Repository spiceai/spiceai, pull requests merged in 2021-12, with the labels that each got.

#469 Fix issue upgrade CLI on Linux
  pkg/cli/cmd/upgrade.go
Labels: bug

#470 Fix `spice upgrade` recommending wrong version
  .vscode/launch.json
  pkg/cli/cmd/version.go
Labels: bug

#483 Update Roadmap based upon v0.6 planning
  docs/ROADMAP.md
Labels: documentation

#484 Add 'Start Training' button to Dashboard Pod page
  dashboard/.prettierignore
  dashboard/.prettierrc
  dashboard/src/components/alerts/Error.tsx
  dashboard/src/components/app/PodHeader.tsx
  dashboard/src/models/flight.ts
  dashboard/src/pages/PodPage.tsx
  dashboard/tailwind.config.js
Labels: enhancement

#486 Add TensorBoard support - DQL only
  ai/src/.pylintrc
  ai/src/algorithms/agent_interface.py
  ai/src/algorithms/dql/agent.py
  ai/src/algorithms/factory.py
  ai/src/algorithms/sacd/agent.py
  ai/src/algorithms/vpg/agent.py
  ai/src/inference.py
  ai/src/main.py
  ai/src/proto/aiengine/v1/aiengine_pb2.py
  ai/src/proto/runtime/v1/runtime_pb2.py
  ai/src/train.py
  dashboard/src/components/flights/FlightChart.tsx
  dashboard/src/components/flights/TrainingLogger.tsx
  dashboard/src/constants.ts
  dashboard/src/models/flight.ts
  dashboard/src/pages/PodPage.tsx
  go.mod
  go.sum
  pkg/aiengine/aiengine_test.go
  pkg/aiengine/training.go
  pkg/api/episode.go
  pkg/api/flight.go
  pkg/api/pod.go
  pkg/cli/cmd/spice.go
  pkg/cli/cmd/train.go
  pkg/context/context.go
  pkg/context/docker/docker.go
  pkg/context/metal/metal.go
  pkg/flights/episode.go
  pkg/flights/flight.go
  pkg/flights/flights_test.go
  pkg/flights/logger.go
  pkg/flights/loggers/tensorboard_logger.go
  pkg/http/server.go
  pkg/pods/pod.go
  pkg/pods/podparams.go
  pkg/proto/aiengine_pb/aiengine.pb.go
  pkg/proto/runtime_pb/runtime.pb.go
  pkg/registry/spicerack.go
  pkg/runtime/runtime.go
  pkg/runtime/watcher.go
  pkg/tempdir/tempdir.go
  proto/aiengine/v1/aiengine.proto
  proto/runtime/v1/runtime.proto
Labels: enhancement

#487 Upgrade to Tailwind 3 (3.0.6)
  dashboard/package.json
  dashboard/tailwind.config.js
  dashboard/yarn.lock
Labels: enhancement

#495 Add missing comments to ai_engine proto file
  pkg/proto/aiengine_pb/aiengine_grpc.pb.go
Labels: bug

#494 Upgrade to glide-data-grid 3.2.1
  dashboard/package.json
  dashboard/yarn.lock
Labels: dependencies

#490 Add SACD tensorboard
  Makefile
  ai/src/algorithms/dql/agent.py
  ai/src/algorithms/sacd/agent.py
  ai/src/algorithms/vpg/agent.py
  ai/src/main.py
  ai/src/tests/test_train_loop.py
Labels: enhancement

#497 Use single TensorBoard instance per pod
  ai/src/algorithms/dql/agent.py
  ai/src/algorithms/sacd/agent.py
  ai/src/train.py
  dashboard/src/components/flights/TrainingLogger.tsx
  pkg/aiengine/training.go
  pkg/flights/flight.go
  pkg/flights/flights_test.go
  pkg/flights/logger.go
  pkg/flights/loggers/tensorboard_logger.go
  pkg/pods/pod.go
Labels: enhancement

#500 Add v0.5.1-alpha release notes
  docs/release_notes/v0.5.1-alpha.md
Labels: documentation

#502 TensorBoard improvements and Docker fix
  pkg/cli/cmd/add.go
  pkg/cli/cmd/run.go
  pkg/cli/cmd/util.go
  pkg/cli/cmd/version.go
  pkg/context/docker/docker.go
  pkg/flights/logger.go
  pkg/flights/loggers/tensorboard_logger.go
  pkg/http/server.go
  pkg/loggers/zaplogger.go
  pkg/pods/pod.go
  pkg/pods/podparams.go
  pkg/spec/pods.go
  pkg/util/debug.go
Labels: bug, enhancement
