Repository spiceai/spiceai, pull requests merged in 2022-02, with the labels that each got.

#517 Initial arrow migration commit
  dashboard/src/constants.ts
  go.mod
  go.sum
  pkg/aiengine/data_test.go
  pkg/dataspace/converter.go
  pkg/dataspace/dataspace.go
  pkg/observations/observation_test.go
  test/assets/snapshots/e2e/e2e-TestDataspaceData-event-categories_initial_observations.csv
  test/assets/snapshots/observations/TestObservations-GetCsv()_-_With_tags
Labels: enhancement

#523 Upgrade to pyarrow 7.0, Tensorflow 2.8, Keras 2.8, numpy 1.22.2 and pandas 1.4.0
  ai/src/.pylintrc
  ai/src/requirements/common.txt
  docker/Dockerfile
Labels: dependencies

#532 Add release notes for v0.6 and update roadmap
  docs/ROADMAP.md
  docs/release_notes/v0.6-alpha.md
Labels: documentation
