Repository spiceai/spiceai, pull requests merged in 2024-10, with the labels that each got.

#2892 Release notes for v0.18.3-beta
  docs/ROADMAP.md
  docs/release_notes/v0.18.3-beta.md
Labels: kind/documentation

#2902 Verify benchmark query results using snapshot testing (s3 connector)
  crates/runtime/benches/bench_s3/mod.rs
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q16_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q17_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q18_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q20_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q21_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q22_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q2_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q4_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q2_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q6_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q7_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q16_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q17_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q18_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q20_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q21_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q22_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q2_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q4_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q9.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_simple_q2_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_simple_q6_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_simple_q7_explain.snap
Labels: kind/optimization

#2906 Fix `paths-ignore:`
  .github/workflows/integration.yml
Labels: kind/bug

#2899 Rename `spiceai` data connector to `spice.ai`
  crates/runtime/benches/setup/mod.rs
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q10_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q12_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q13_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q14_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q17_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q18_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q19_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q1_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q21_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q2_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q3_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q5_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q6_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q7_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q8_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q9_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q1_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q2_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q3_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q4_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q5_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q6_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q7_explain.snap
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/tests/catalog/mod.rs
  crates/runtime/tests/federation/mod.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_avg_gas_used.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_eth_logs.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_max_blocks_number.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_max_num.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_number_filter.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_number_subquery.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_sum_tx_receipt_gas_used.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_union_all.snap
  crates/spice_cloud/src/catalog.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/optimization

#2907 Update ROADMAP.md
  docs/ROADMAP.md
Labels: kind/documentation

#2910 Helm update for helm for 0.18.3-beta
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement, kind/task

#2911 Fix `paths-ignore` for docs.
  .github/workflows/e2e_test_ci.yml
  .github/workflows/license_check.yml
  crates/llms/src/embeddings/candle/mod.rs
Labels: kind/bug

#2903 feat: Support LIKE expressions in GitHub filter pushdown
  Cargo.lock
  Cargo.toml
  crates/data_components/src/graphql/client.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector/github/mod.rs
Labels: kind/enhancement, data-connector/github

#2904 feat: Support date comparison pushdown in GitHub connector
  crates/runtime/src/dataconnector/github/mod.rs
Labels: kind/enhancement, data-connector/github

#2925 Improve aggregation and union queries unparsing
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2923 Initialize file based accelerators on dataset reload
  crates/runtime/src/lib.rs
Labels: kind/bug

#2927 Verify TPC-H benchmark query results for arrow acceleration
  crates/runtime/benches/bench_s3/mod.rs
  crates/runtime/benches/bench_spicecloud/mod.rs
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q9.snap
Labels: kind/optimization

#2922 Use structured output for NSQL
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  crates/llms/src/chat/mod.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/tools/mod.rs
Labels: kind/enhancement

#2930 Update TPC-DS queries to use supported date addition format
  crates/runtime/benches/queries/README.md
  crates/runtime/benches/queries/tpcds/q12.sql
  crates/runtime/benches/queries/tpcds/q16.sql
  crates/runtime/benches/queries/tpcds/q20.sql
  crates/runtime/benches/queries/tpcds/q21.sql
  crates/runtime/benches/queries/tpcds/q32.sql
  crates/runtime/benches/queries/tpcds/q37.sql
  crates/runtime/benches/queries/tpcds/q40.sql
  crates/runtime/benches/queries/tpcds/q5.sql
  crates/runtime/benches/queries/tpcds/q77.sql
  crates/runtime/benches/queries/tpcds/q80.sql
  crates/runtime/benches/queries/tpcds/q82.sql
  crates/runtime/benches/queries/tpcds/q92.sql
  crates/runtime/benches/queries/tpcds/q94.sql
  crates/runtime/benches/queries/tpcds/q95.sql
  crates/runtime/benches/queries/tpcds/q98.sql
Labels: kind/optimization

#2855 Add busy_timeout accelerator param for Sqlite
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/sqlite.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/tests/acceleration/checkpoint_sqlite.rs
  crates/runtime/tests/rehydration/sqlite.rs
  test/scripts/setup-data-mysql.sql
Labels: kind/bug

#2932 Use Cosine Similarity in vector search
  crates/runtime/src/datafusion.rs
  crates/runtime/src/embeddings/array_distance.rs
  crates/runtime/src/embeddings/cosine_distance.rs
  crates/runtime/src/embeddings/mod.rs
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/enhancement, area/ai

#2934 Add support for passing `x-spiceai-app-id` metadata in spiceai data connector
  crates/flight_client/src/lib.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/mssql.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/sharepoint.rs
  crates/runtime/src/dataconnector/sink.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/dataconnector/unity_catalog.rs
  crates/runtime/src/http/v1/status.rs
  crates/runtime/src/lib.rs
  crates/spice_cloud/src/lib.rs
  crates/telemetry/src/exporter.rs
Labels: kind/enhancement

#2905 docs: update beta accelerator criteria
  docs/criteria/accelerators/beta.md
Labels: kind/documentation

#2926 Azure Connector implementation
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/object_store_registry.rs
  crates/runtime/tests/abfs/mod.rs
  crates/runtime/tests/integration.rs
Labels: kind/enhancement

#2908 Local embedding model from relative paths
  crates/llms/src/embeddings/candle/mod.rs
  crates/spicepod/src/component/embeddings.rs
  crates/spicepod/src/component/model.rs
Labels: kind/bug, area/ai

#2943 Add Markdown aware chunker when `params.file_format: md`.
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/chunking/mod.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/table.rs
Labels: kind/enhancement, area/ai

#2945 feat: GraphQL commit query parameters
  crates/runtime/src/dataconnector/github/commits.rs
  crates/runtime/src/dataconnector/github/issues.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/github/pull_requests.rs
Labels: kind/enhancement

#2951 Update OpenAI client and use new request fields
  Cargo.lock
  Cargo.toml
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/model/chat.rs
Labels: kind/enhancement, area/ai

#2954 refactor: Rename GitHub pulls login to author
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/github/pull_requests.rs
Labels: kind/refactor

#2853 Run tpcds benchmarks for accelerators
  .github/workflows/benchmarks.yml
  Cargo.lock
  Cargo.toml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_s3/mod.rs
  crates/runtime/benches/bench_spark/mod.rs
  crates/runtime/benches/bench_spicecloud/mod.rs
  crates/runtime/benches/setup/mod.rs
Labels: kind/enhancement, area/data-accelerators

#2953 Add spiced arg `--pods-watcher-enabled`. Watcher disabled by default for spiced.
  bin/spice/pkg/context/context.go
  bin/spiced/src/lib.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#2952 Add error message when spicepod has embeddings or models without '--features models'
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/mod.rs
Labels: kind/enhancement, area/ai

#2949 Adding multi-line editing and tab indentation to sql REPL
  .github/workflows/e2e_test_ci.yml
  Cargo.lock
  crates/flightrepl/Cargo.toml
  crates/flightrepl/src/lib.rs
Labels: kind/enhancement

#2941 Update MySQL ghcr image to include tpcds data
  .github/workflows/spice_mysql_bench_docker.yml
  .gitignore
  test/tpc-bench/Makefile
  test/tpc-bench/Readme.md
  test/tpc-bench/mysql-bench/Dockerfile
  test/tpc-bench/mysql-bench/conf.d/my.cnf
  test/tpc-bench/postgres-bench/Dockerfile
  test/tpc-bench/postgres-bench/postgres-entrypoint.sh
  test/tpc-bench/tpch-spicepod/spicepod.yaml
  test/tpc-bench/tpch_index.sql
  test/tpc-bench/tpch_queries.sql
Labels: kind/enhancement, kind/task

#2970 Document DataFusion limitation: The context only support single SQL Statement, Date Arithmetic like date + 3 not supported
  crates/runtime/benches/queries/README.md
  crates/runtime/benches/queries/tpcds/q72.sql
Labels: kind/bug, kind/documentation

#2972 Verify TPC-H benchmark query results for MySQL
  crates/runtime/benches/bench_mysql/mod.rs
  crates/runtime/benches/snapshots/bench__mysql_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__mysql_tpch_q9.snap
Labels: kind/optimization

#2973 Verify TPCH benchmark query results for Postgres
  crates/runtime/benches/bench_postgres/mod.rs
  crates/runtime/benches/snapshots/bench__postgres_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__postgres_tpch_q9.snap
Labels: kind/optimization

#2974 Verify TPCH benchmark query results for sqlite acceleration
  crates/runtime/benches/bench_s3/mod.rs
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_file_tpch_q9.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__s3_sqlite_memory_tpch_q9.snap
Labels: kind/optimization

#2975 Verify TPCH benchmark query results for duckdb (in-memory) acceleration
  crates/runtime/benches/bench_s3/mod.rs
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_memory_tpch_q9.snap
Labels: kind/optimization

#2977 Support for `mdx` file extensions to apply a markdown splitter
  crates/llms/src/chunking/mod.rs
Labels: kind/enhancement

#2940 Don't assume first vector or content will be non-null/zero
  crates/runtime/src/embeddings/execution_plan.rs
Labels: kind/bug

#2971 use custom chunk sizers for HF, local and OpenAI models
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/chunking/mod.rs
  crates/llms/src/embeddings/candle/mod.rs
  crates/llms/src/embeddings/mod.rs
  crates/llms/src/openai/mod.rs
  crates/runtime/src/embeddings/task.rs
Labels: kind/enhancement, area/ai

#2976 Ensure we return N unique documents, not N unique chunks
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/enhancement, area/ai

#2957 Fix issues parsing `messages[*].tool_calls` for local models
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
Labels: kind/bug, area/ai

#2942 text -> SQL trait to customise per model.
  Cargo.lock
  Cargo.toml
  crates/llms/Cargo.toml
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/llms/src/chat/nsql/default.rs
  crates/llms/src/chat/nsql/json.rs
  crates/llms/src/chat/nsql/mod.rs
  crates/llms/src/chat/nsql/snapshots/llms__chat__nsql__tests__sql_gen_default.snap
  crates/llms/src/chat/nsql/snapshots/llms__chat__nsql__tests__sql_gen_json.snap
  crates/llms/src/chat/nsql/snapshots/llms__chat__nsql__tests__sql_gen_structured.snap
  crates/llms/src/chat/nsql/structured_output.rs
  crates/llms/src/openai/mod.rs
  crates/model_components/src/modelruntime/tract.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement, area/ai

#2978 Remove system message from ToolUsingChat.
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement, area/ai

#2984 Make logical plan to sql more robust (improve ORDER BY; support `round` for Postgres)
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2991 Fix dataset configure prompt
  bin/spice/cmd/dataset.go
Labels: kind/bug

#2989 Verify TPCH benchmark query results for Databricks(odbc)
  crates/runtime/benches/bench_odbc_databricks/mod.rs
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__odbc-databricks_tpch_q9.snap
Labels: kind/optimization

#2982 Verify TPCH benchmark query results for Databricks (delta_lake)
  crates/runtime/benches/bench_delta/mod.rs
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__databricks_delta_tpch_q9.snap
Labels: kind/optimization

#2995 Set log level for anonymous telemetry traces to `trace`
  crates/telemetry/src/anonymous.rs
  crates/telemetry/src/exporter.rs
Labels: kind/bug

#2992 Improvements to issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/end_game.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: kind/enhancement

#2996 `spice login` writes to `.env.local` if present
  bin/spice/cmd/login.go
Labels: kind/enhancement

#2985 docs: v0.19.0 release notes
  docs/release_notes/v0.19.0-beta.md
Labels: kind/documentation

#3024 release: Update helm chart for v0.19.0-beta
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#3033 release: Update next version and ROADMAP
  Cargo.lock
  Cargo.toml
  docs/ROADMAP.md
  version.txt
Labels: kind/documentation

#2993 Verify TPCH benchmark query results for Spark connector
  crates/runtime/benches/bench_spark/mod.rs
  crates/runtime/benches/snapshots/bench__spark_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__spark_tpch_q9.snap
Labels: kind/optimization

#2979 feat: Add x-spice-user-agent header to Spice REPL
  Cargo.lock
  crates/flightrepl/Cargo.toml
  crates/flightrepl/src/config.rs
  crates/flightrepl/src/lib.rs
Labels: kind/enhancement

#3036 Update to object store file formats documentation link
  docs/release_notes/v0.19.0-beta.md
Labels: kind/documentation

#3042 Use teraswitch-runners for Linux x64 workflows + builds
  .github/actions/setup-cc/action.yml
  .github/actions/setup-make/action.yml
  .github/workflows/build_and_release.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_release_install.yml
  .github/workflows/enforce-labels.yml
  .github/workflows/features.yml
  .github/workflows/generate_acknowledgements.yml
  .github/workflows/generate_json_schema.yml
  .github/workflows/integration.yml
  .github/workflows/license_check.yml
  .github/workflows/makefile_targets.yml
  .github/workflows/pr.yml
  .github/workflows/spiced_docker.yml
  .github/workflows/types_check.yml
  Makefile
  crates/runtime/tests/docker/mod.rs
  crates/runtime/tests/federation/mysql.rs
Labels: kind/enhancement

#2983 feat: Support array contains in GitHub pushdown
  crates/data_components/src/graphql/builder.rs
  crates/data_components/src/graphql/mod.rs
  crates/runtime/src/dataconnector/github/mod.rs
Labels: kind/enhancement

#3046 Revert integration tests back to hosted runner
  .github/workflows/integration.yml
Labels: kind/bug

#3025 Tune Github runner resources to allow in memory TPCDS benchmark to run
  .github/workflows/benchmarks.yml
Labels: kind/bug

#3054 fix: add winver
  Cargo.lock
  crates/flightrepl/Cargo.toml
Labels: kind/bug

#3056 refactor: Use is modifier for checking GitHub state filter
  crates/runtime/src/dataconnector/github/mod.rs
Labels: kind/refactor

#3058 Enable `merge_group` checks for PR workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/integration.yml
  .github/workflows/makefile_targets.yml
  .github/workflows/pr.yml
Labels: kind/enhancement, github_actions

#3032 Use 'Accept' header for `/v1/sql/` and `/v1/nsql`
  Cargo.lock
  crates/llms/src/openai/mod.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/http/v1/query.rs
Labels: kind/enhancement

#2856 Add NSQL CLI REPL command
  bin/spice/cmd/nsql.go
Labels: kind/enhancement, area/cli

#3034 Preserve query results order and add TPCH benchmark results verification for duckdb:file mode
  Cargo.lock
  Cargo.toml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_s3/mod.rs
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpch_q9.snap
  crates/runtime/src/datafusion/extension/bytes_processed.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/snapshots/integration__mysql_federation_inner_join_with_acc_inner_join_0.snap
  crates/runtime/tests/snapshots/integration__mysql_federation_inner_join_with_acc_inner_join_1.snap
  crates/runtime/tests/snapshots/integration__mysql_federation_push_down_select_limit_10.snap
  crates/runtime/tests/snapshots/integration__mysql_federation_push_down_select_order_by_limit_10.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_avg_gas_used.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_eth_logs.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_max_blocks_number.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_max_num.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_number_filter.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_number_subquery.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_sum_tx_receipt_gas_used.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_union_all.snap
  crates/runtime/tests/snapshots/integration__test_graphql_pagination_select_limit_1_id_4.snap
Labels: kind/optimization

#2967 Refactor benchmark to include MySQL tpcds bench, tweaks to makefile target for generating mysql tpcds data
  .github/workflows/benchmarks.yml
  .github/workflows/spice_mysql_bench_docker.yml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_delta/mod.rs
  crates/runtime/benches/bench_mysql/mod.rs
  crates/runtime/benches/bench_odbc_athena/mod.rs
  crates/runtime/benches/bench_odbc_databricks/mod.rs
  crates/runtime/benches/bench_postgres/mod.rs
  crates/runtime/benches/bench_s3/mod.rs
  crates/runtime/benches/bench_spark/mod.rs
  crates/runtime/benches/bench_spicecloud/mod.rs
  crates/runtime/benches/setup/mod.rs
  test/tpc-bench/Makefile
Labels: kind/enhancement, kind/task

#3065 Support runtime parameter for `sql_query_keep_partition_by_columns` & enable by default
  crates/app/src/lib.rs
  crates/runtime/benches/setup/mod.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/tests/integration.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#3069 Document TPC-DS limitations: `EXCEPT`, `INTERSECT`, duplicate names
  crates/runtime/benches/queries/README.md
  crates/runtime/benches/queries/tpcds/q35.sql
Labels: kind/optimization

#3062 Adding ABFS benchmark
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_mysql/mod.rs
  crates/runtime/benches/bench_object_store/abfs.rs
  crates/runtime/benches/bench_object_store/mod.rs
  crates/runtime/benches/bench_object_store/s3.rs
  crates/runtime/benches/setup/mod.rs
  crates/runtime/benches/snapshots/bench__abfs_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__abfs_tpch_q9.snap
  crates/runtime/tests/abfs/mod.rs
Labels: kind/enhancement

#3063 Add support for GitHub app installation auth for GitHub connector
  Cargo.lock
  crates/data_components/src/github.rs
  crates/data_components/src/graphql/builder.rs
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/token_provider.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector/github/github_app_token_provider.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/enhancement

#3070 docs: Document stack overflow workaround, add helper script
  crates/runtime/benches/queries/README.md
  test/scripts/run-query.bash
Labels: kind/documentation

#3067 Tune MySQL TPCDS image to allow for successful benchmark test run
  .github/workflows/benchmarks.yml
  .github/workflows/spice_mysql_tpcds_bench_docker.yml
  test/tpc-bench/Makefile
  test/tpc-bench/mysql-tpcds-bench/Dockerfile
  test/tpc-bench/mysql-tpcds-bench/conf.d/my.cnf
  test/tpc-bench/tpcds_index.sql
Labels: kind/enhancement, kind/task

#3073 Automatically infer partitions for hive-style partitioned files for object store based connectors
  crates/app/src/lib.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/listing/infer.rs
  crates/runtime/src/dataconnector/listing/mod.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/tests/s3/mod.rs
  crates/runtime/tests/s3/snapshots/integration__s3__s3_hive_partitioning-2.snap
  crates/runtime/tests/s3/snapshots/integration__s3__s3_hive_partitioning.snap
Labels: kind/enhancement

#3071 Support `hf_token` from params/secrets
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/llms/src/embeddings/candle/mod.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/embed.rs
Labels: kind/enhancement

#3045 Inherit embedding columns from source, when available.
  crates/llms/src/chunking/mod.rs
  crates/llms/src/embeddings/candle/mod.rs
  crates/llms/src/embeddings/mod.rs
  crates/llms/src/openai/mod.rs
  crates/runtime/src/embeddings/common.rs
  crates/runtime/src/embeddings/execution_plan.rs
  crates/runtime/src/embeddings/mod.rs
  crates/runtime/src/embeddings/table.rs
  crates/runtime/src/embeddings/task.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement, area/ai

#3079 Validate identifiers for component names
  crates/runtime/src/component/catalog.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/mod.rs
  crates/runtime/src/component/view.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#3080 docs: Add workaround for TPC-DS Q97 in MySQL
  crates/runtime/benches/queries/README.md
Labels: kind/documentation

#3083 Document TPC-DS Postgres column alias in a CASE statement limitation
  crates/runtime/benches/queries/README.md
Labels: kind/optimization

#3088 Update plan snapshots for TPC-H bench queries
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q10_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q2_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q5_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q8_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q9_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q14_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q20_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q21_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q2_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q5_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q7_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q8_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q9_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q10_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q12_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q13_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q14_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q17_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q18_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q19_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q1_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q21_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q2_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q3_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q5_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q6_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q7_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q8_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q9_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q1_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q2_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q3_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q4_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q5_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q6_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q7_explain.snap
Labels: kind/optimization

#3089 Update Datafusion crate to include recent unparsing fixes
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#3081 Sample SQL table data tool and API
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/builder.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/http/v1/query.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/tools/builtin/mod.rs
  crates/runtime/src/tools/builtin/sample_data.rs
  crates/runtime/src/tools/factory/builtin.rs
Labels: kind/enhancement, area/ai

#3090 chore: Update datafusion-table-providers
  Cargo.lock
  Cargo.toml
Labels: kind/dependencies

#3086 Add `hive_infer_partitions` to remaining object store connectors
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/sftp.rs
Labels: kind/enhancement

#3093 deps: Update datafusion-table-providers
  Cargo.lock
  Cargo.toml
Labels: kind/documentation

#3095 For local embedding models, return usage input tokens.
  crates/llms/src/embeddings/candle/mod.rs
Labels: kind/bug, area/ai

#3092 Update end_game.md with Accelerator/Connector criteria check
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#3094 Update TPC-DS Q90
  crates/runtime/benches/queries/tpcds/q35.sql
  crates/runtime/benches/queries/tpcds/q90.sql
Labels: kind/optimization

#3026 docs: Add RC connector criteria
  docs/criteria/accelerators/beta.md
  docs/criteria/connectors/rc.md
  docs/criteria/definitions.md
Labels: kind/documentation

#3101 Update version to 0.19.1-beta
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/optimization

#3091 Return all datasets, when Null `datasets` provided.
  crates/runtime/src/datafusion.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/tools/builtin/sample_data.rs
Labels: kind/enhancement, area/ai

#3104 Update acknowledgements.md
  acknowledgements.md
Labels: kind/documentation

#3103 v0.19.1-beta Release Notes
  docs/release_notes/v0.19.1-beta.md
Labels: kind/documentation

#3106 Update Helm chart for v0.19.1-beta
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#3109 Bumping version to 1.0.0-rc.1
  Cargo.lock
  Cargo.toml
  crates/flightrepl/src/config.rs
  version.txt
Labels: kind/enhancement

#3110 Add Postgres acceleration E2E test for MySQL
  .github/workflows/e2e_test_ci.yml
Labels: kind/optimization

#3111 Update datafusion logical plan to avoid wrong group_by columns in aggregation
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#3120 Warn if user tries to embed column that does not exist
  crates/runtime/src/embeddings/table.rs
Labels: kind/bug

#3134 Changes for Rust version upgrade
  .github/actions/setup-rust/action.yml
  crates/runtime/src/opentelemetry.rs
Labels: kind/optimization

#3133 Add `unnest` support for federated plans
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#3128 Don't `.clone()` unnecessarily
  crates/runtime/src/datafusion.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/flight/do_exchange.rs
  crates/runtime/src/flight/get_schema.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/tools/builtin/sample/distinct.rs
Labels: kind/refactor

#3131 Fix Flight `get_schema` to construct logical plan and return that schema.
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/builder.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/do_exchange.rs
  crates/runtime/src/http/v1/mod.rs
Labels: kind/bug

#3140 Add GitHub Workflow to build `spice-postgres-tpcds-bench` image
  .github/workflows/spice_postgres_tpcds_bench_docker.yml
  test/tpc-bench/Makefile
  test/tpc-bench/postgres-tpcds-bench/Dockerfile
  test/tpc-bench/postgres-tpcds-bench/postgres-entrypoint.sh
Labels: kind/enhancement

#3143 test: Add basic MySQL integration test
  crates/runtime/tests/mysql/mod.rs
  crates/runtime/tests/snapshots/integration__mysql__mysql_integration_test_select.snap
  crates/runtime/tests/snapshots/integration__mysql_integration_test_select.snap
Labels: kind/enhancement

#3148 Bump datafusion-federation and datafusion-table-providers crates
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#3144 docs: Add MySQL limitation for division by zero
  crates/runtime/benches/queries/README.md
Labels: kind/documentation

#3147 fix: Dataset refresh
  bin/spice/cmd/refresh.go
  bin/spice/pkg/api/util.go
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/http/v1/datasets.rs
Labels: kind/bug

#3137 Update E2E test ci to include tests for accelerating Postgres into accelerators
  .github/workflows/e2e_test_ci.yml
  test/scripts/setup-data-postgresql.sql
Labels: kind/enhancement, kind/task

#3157 [cli] Include 200 in acceptable response codes for `doRuntimeApiRequest`
  bin/spice/pkg/api/util.go
Labels: kind/bug

#3159 Use `-build.{GIT_SHA}` for unreleased versions
  bin/spice/Makefile
  bin/spiced/src/main.rs
Labels: kind/bug

#3158 Upgrade to Rust 1.82
  .github/actions/setup-rust/action.yml
  Cargo.toml
  Dockerfile
Labels: kind/dependencies

#3160 Disable `hive_infer_partitions` by default
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
Labels: kind/bug

#3161 Upgrade to DuckDB 1.1.1
  Cargo.lock
  Cargo.toml
Labels: kind/dependencies

#3166 Fix task_history output for sql, add output to table_schema & list_datasets tool
  Cargo.lock
  Cargo.toml
  bin/spice/cmd/chat.go
  bin/spiced/Cargo.toml
  bin/spiced/src/lib.rs
  bin/spiced/src/tracing.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/tools/builtin/list_datasets.rs
  crates/runtime/src/tools/builtin/table_schema.rs
Labels: kind/bug

#3169 feat: Add ClickBench queries as separate files
  test/scripts/clickbench/.gitignore
  test/scripts/clickbench/queries/q01.sql
  test/scripts/clickbench/queries/q02.sql
  test/scripts/clickbench/queries/q03.sql
  test/scripts/clickbench/queries/q04.sql
  test/scripts/clickbench/queries/q05.sql
  test/scripts/clickbench/queries/q06.sql
  test/scripts/clickbench/queries/q07.sql
  test/scripts/clickbench/queries/q08.sql
  test/scripts/clickbench/queries/q09.sql
  test/scripts/clickbench/queries/q10.sql
  test/scripts/clickbench/queries/q11.sql
  test/scripts/clickbench/queries/q12.sql
  test/scripts/clickbench/queries/q13.sql
  test/scripts/clickbench/queries/q14.sql
  test/scripts/clickbench/queries/q15.sql
  test/scripts/clickbench/queries/q16.sql
  test/scripts/clickbench/queries/q17.sql
  test/scripts/clickbench/queries/q18.sql
  test/scripts/clickbench/queries/q19.sql
  test/scripts/clickbench/queries/q20.sql
  test/scripts/clickbench/queries/q21.sql
  test/scripts/clickbench/queries/q22.sql
  test/scripts/clickbench/queries/q23.sql
  test/scripts/clickbench/queries/q24.sql
  test/scripts/clickbench/queries/q25.sql
  test/scripts/clickbench/queries/q26.sql
  test/scripts/clickbench/queries/q27.sql
  test/scripts/clickbench/queries/q28.sql
  test/scripts/clickbench/queries/q29.sql
  test/scripts/clickbench/queries/q30.sql
  test/scripts/clickbench/queries/q31.sql
  test/scripts/clickbench/queries/q32.sql
  test/scripts/clickbench/queries/q33.sql
  test/scripts/clickbench/queries/q34.sql
  test/scripts/clickbench/queries/q35.sql
  test/scripts/clickbench/queries/q36.sql
  test/scripts/clickbench/queries/q37.sql
  test/scripts/clickbench/queries/q38.sql
  test/scripts/clickbench/queries/q39.sql
  test/scripts/clickbench/queries/q40.sql
  test/scripts/clickbench/queries/q41.sql
  test/scripts/clickbench/queries/q42.sql
  test/scripts/clickbench/queries/q43.sql
Labels: kind/enhancement

#3170 Calculate embeddings in a separate blocking thread
  crates/llms/src/embeddings/candle/mod.rs
Labels: kind/bug

#3124 docs: Update ROADMAP.md and release criterias
  docs/ROADMAP.md
  docs/criteria/accelerators/alpha.md
  docs/criteria/accelerators/beta.md
  docs/criteria/accelerators/rc.md
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
  docs/criteria/connectors/rc.md
  docs/criteria/definitions.md
Labels: kind/documentation

#3173 Handle OpenTelemetry errors
  bin/spiced/src/tracing.rs
Labels: kind/enhancement

#3182 Update version to 0.19.2-beta
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/optimization

#3187 Add spark back to default connectors
  bin/spiced/Cargo.toml
Labels: kind/bug

#3181 Add abfs connector in README
  README.md
Labels: kind/documentation

#3189 Revert "fix: Dataset refresh (#3147)"
  bin/spice/cmd/refresh.go
  bin/spice/pkg/api/util.go
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/http/v1/datasets.rs
Labels: kind/bug

#3192 Rename `hive_infer_partitions` to `hive_partitioning_enabled`
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/tests/s3/mod.rs
Labels: kind/enhancement

#3193 Mark Postgres Data Accelerator as Beta
  README.md
Labels: kind/optimization

#3186 v0.19.2-beta release note
  docs/release_notes/v0.19.2-beta.md
Labels: kind/documentation

#3194 Move "generate_json_schema" workflow back to ubuntu runner
  .github/workflows/generate_json_schema.yml
Labels: kind/enhancement

#3191 Move `generate_acknowledgements.yml` back to Github runners
  .github/workflows/generate_acknowledgements.yml
Labels: kind/bug

#3190 Mark PostgreSQL as Beta Quality
  docs/criteria/accelerators/beta.md
Labels: kind/documentation

#3087 Make Anthropic OpenAI compatible.
  Cargo.lock
  Cargo.toml
  crates/llms/Cargo.toml
  crates/llms/src/anthropic/chat.rs
  crates/llms/src/anthropic/mod.rs
  crates/llms/src/anthropic/types.rs
  crates/llms/src/anthropic/types_stream.rs
  crates/llms/src/chat/mod.rs
  crates/llms/src/lib.rs
  crates/llms/src/openai/chat.rs
  crates/llms/src/openai/embed.rs
  crates/llms/src/openai/mod.rs
  crates/runtime/src/model/chat.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement, area/ai

#3202 Bump version to 1.0.0-rc.1
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/optimization

#3201 Fix clickhouse schema inference for non-default database
  crates/db_connection_pool/src/clickhousepool.rs
  crates/db_connection_pool/src/dbconnection/clickhouseconn.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/github/github_app_token_provider.rs
Labels: kind/bug

#3198 Update endgame template
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/optimization

#3204 Use ubuntu-latest-16-cores for spiced-docker workflow
  .github/workflows/spiced_docker.yml
Labels: kind/optimization

#3205 fix: dataset refresh defaults properties to None
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/http/v1/datasets.rs
Labels: kind/bug

#3203 Upgrade OTEL to v0.26 and make seconds based metrics reported precisely
  Cargo.lock
  Cargo.toml
  crates/otel-arrow/src/exporter.rs
  crates/runtime/src/datafusion/query/metrics.rs
  crates/runtime/src/http/metrics.rs
  crates/runtime/src/spice_metrics.rs
  crates/telemetry/src/anonymous.rs
  crates/telemetry/src/exporter.rs
  crates/telemetry/src/lib.rs
  crates/telemetry/src/meter.rs
Labels: kind/bug

#3199 use `text_embedding_inference::Infer` for more complete embedding solution
  Cargo.lock
  bin/spiced/src/tracing.rs
  crates/llms/Cargo.toml
  crates/llms/src/embeddings/candle/mod.rs
  crates/llms/src/embeddings/candle/tei.rs
  crates/llms/src/embeddings/candle/util.rs
  crates/runtime/src/model/embed.rs
Labels: kind/enhancement, area/ai

#3210 Update helm chart version to v0.19.2
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/optimization

#3105 Add sample dataset option in `v1/nsql`.
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/tools/builtin/sample/distinct.rs
  crates/runtime/src/tools/builtin/sample/mod.rs
  crates/runtime/src/tools/builtin/sample/random.rs
  crates/runtime/src/tools/builtin/sample/tool.rs
  crates/runtime/src/tools/builtin/sample/top_samples.rs
Labels: kind/enhancement, area/ai

#3206 Split spiced_docker build across architectures
  .github/workflows/build_and_release.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_release_install.yml
  .github/workflows/features.yml
  .github/workflows/license_check.yml
  .github/workflows/makefile_targets.yml
  .github/workflows/pr.yml
  .github/workflows/spiced_docker.yml
  .github/workflows/types_check.yml
  docs/release_notes/v0.19.1-beta.md
Labels: kind/enhancement

#3207 feat(helm): do not install demo dataset by default
  deploy/chart/values.yaml
Labels: kind/enhancement

#3215 Split integration test across build/run steps
  .github/workflows/integration.yml
  Makefile
Labels: kind/enhancement

#3208 feat(helm): Refactoring Kubernetes labels
  deploy/chart/templates/_helpers.tpl
  deploy/chart/templates/deployment.yaml
  deploy/chart/templates/podmonitor.yaml
  deploy/chart/templates/service.yaml
  deploy/chart/templates/spiceai-config.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#3214 Define 'tool_recursion_limit' for LLMs, and limit internal tool calling recursion.
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/bug, area/ai

#3183 Improve filters pushdown for federated queries
  Cargo.lock
  Cargo.toml
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q12_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q13_explain.snap
Labels: kind/enhancement

#3209 Implement native schema inference for PostgreSQL
  .github/workflows/integration.yml
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/tests/abfs/mod.rs
  crates/runtime/tests/duckdb/mod.rs
Labels: kind/enhancement

#3219 docs: Update release criteria
  docs/criteria/accelerators/beta.md
  docs/criteria/accelerators/rc.md
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
  docs/criteria/connectors/rc.md
Labels: kind/documentation

#3227 Run SQLite acceleration TPC-DS tests using 0.01 scale
  crates/runtime/benches/bench_object_store/s3.rs
  crates/runtime/benches/setup/mod.rs
Labels: kind/optimization

#3228 bind the serviceAccount if a name is given or if we're creating one
  deploy/chart/Chart.yaml
  deploy/chart/templates/deployment.yaml
Labels: kind/enhancement

#3230 Only emit channel send error log when its not a closed channel error
  crates/runtime/src/model/tool_use.rs
Labels: kind/bug

#3216 Enable Parquet Exec filter pushdown in Spice
  Cargo.lock
  Cargo.toml
  crates/runtime/benches/snapshots/bench__s3_tpcds_q11.snap
  crates/runtime/benches/snapshots/bench__s3_tpcds_q4.snap
  crates/runtime/benches/snapshots/bench__s3_tpcds_q74.snap
Labels: kind/bug, area/data-connectors

#3256 docs: Add SDK release checks to endgame
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/optimization

#3249 Implement `localpod` Data Connector
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/localpod.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement
