Repository spiceai/spiceai, pull requests merged in 2024-11, with the labels that each got.

#3322 docs: Update ROADMAP.md
  docs/ROADMAP.md
Labels: kind/documentation

#3325 feat: Enable federation for in-memory accelerators
  Cargo.lock
  Cargo.toml
  crates/runtime/tests/snapshots/integration__test_sqlite_decimal_memory_non_federated.snap
Labels: kind/enhancement

#3327 fix: Only allow env files from the current dir
  crates/runtime/src/secrets/stores/env.rs
Labels: kind/bug

#3330 Always read TimezoneTZ from PostgreSQL as UTC
  Cargo.lock
  Cargo.toml
  crates/runtime/tests/postgres/mod.rs
Labels: kind/bug

#3245 Enable parquet pushdown in Spice
  crates/runtime/benches/snapshots/bench__s3_tpcds_q11.snap
  crates/runtime/benches/snapshots/bench__s3_tpcds_q4.snap
  crates/runtime/benches/snapshots/bench__s3_tpcds_q74.snap
  crates/runtime/src/dataconnector/listing/connector.rs
Labels: kind/bug

#3304 Use spice object_store fork to fix S3 ambiguous error
  Cargo.lock
  Cargo.toml
Labels: kind/optimization

#3331 Don't mix commented out queries for s3 connectors and accelerators
  crates/runtime/benches/bench_object_store/mod.rs
Labels: kind/bug

#3335 Allow only valid WHERE conditions in vector searches
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
Labels: kind/enhancement

#3324 fix: Allow only ODBC profiles
  crates/runtime/src/dataconnector/odbc.rs
Labels: kind/bug

#3339 Track how many times an acceleration falls back during initialization
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/metrics.rs
Labels: kind/enhancement

#3334 Anthropic model regex and fix tool parsing aggregation bug
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/anthropic/chat.rs
  crates/llms/src/anthropic/mod.rs
  crates/llms/src/anthropic/types.rs
  crates/llms/src/anthropic/types_stream.rs
  crates/llms/src/openai/chat.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/bug

#3341 Upgrade runtime along with CLI on `spice upgrade`
  bin/spice/cmd/install.go
  bin/spice/cmd/upgrade.go
  bin/spice/pkg/runtime/runtime.go
Labels: kind/enhancement

#3343 Update upcoming Roadmap
  docs/ROADMAP.md
Labels: kind/documentation

#3340 fix: Prevent acceleration files outside of working directory
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/spice_sys.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/tests/acceleration/single_instance_duckdb.rs
Labels: kind/bug

#3333 Document S3 connector limitations
  crates/runtime/benches/queries/README.md
Labels: kind/documentation

#3361 Update Object Store Patch
  Cargo.lock
  Cargo.toml
Labels: kind/optimization

#3365 Promote SQLite Data Accelerator to Beta
  README.md
  docs/criteria/accelerators/alpha.md
  docs/criteria/accelerators/beta.md
Labels: kind/optimization

#3362 Promote S3 connector to RC quality
  README.md
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
  docs/criteria/connectors/rc.md
Labels: kind/enhancement

#3368 Revert "fix: Only allow env files from the current dir"
  crates/runtime/src/secrets/stores/env.rs
Labels: kind/bug

#3370 docs: Fix typo for S3 release status in README.md
  README.md
Labels: kind/documentation

#3363 Include unnecessary columns pruning step during federated plan creation
  Cargo.lock
  Cargo.toml
  crates/runtime/benches/snapshots/bench__s3_duckdb_file_tpcds_q49.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q10_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q12_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q13_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q14_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q17_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q18_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q19_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q1_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q21_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q2_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q3_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q5_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q6_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q7_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q8_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q9_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q1_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q2_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q3_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q4_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q5_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q6_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q7_explain.snap
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/snapshots/integration__mysql_federation_inner_join_with_acc_inner_join_0.snap
  crates/runtime/tests/snapshots/integration__mysql_federation_inner_join_with_acc_inner_join_1.snap
  crates/runtime/tests/snapshots/integration__mysql_federation_push_down_select_limit_10.snap
  crates/runtime/tests/snapshots/integration__mysql_federation_push_down_select_order_by_limit_10.snap
  crates/runtime/tests/snapshots/integration__mysql_integration_test_select.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_avg_gas_used.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_eth_logs.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_max_blocks_number.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_max_num.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_number_filter.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_number_subquery.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_sum_tx_receipt_gas_used.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_union_all.snap
  crates/runtime/tests/snapshots/integration__test_sqlite_decimal_memory_non_federated.snap
Labels: kind/enhancement

#3371 Tweaks to enhancement & issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: kind/documentation

#3356 v0.20.0-beta Release Notes
  Cargo.lock
  Cargo.toml
  docs/release_notes/v0.20.0-beta.md
  version.txt
Labels: kind/enhancement

#3369 Update README.md
  README.md
Labels: kind/documentation

#3372 Update to next release version
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/enhancement

#3373 Update Helm chart to v0.20.0-beta
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#3375 Upgrade dependencies
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/model_components/Cargo.toml
  crates/ns_lookup/Cargo.toml
  go.mod
  go.sum
Labels: kind/dependencies

#3374 E2E: Add a test to confirm refreshing with custom `refresh-sql` via CLI
  .github/workflows/e2e_test_ci.yml
Labels: kind/optimization

#3376 Fix regression in inferring embedding model vector size for non-default models
  crates/llms/src/openai/embed.rs
Labels: kind/bug, area/ai

#3378 add AI quickstarts to endgame
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/enhancement, area/ai

#3342 Remove need for `params.model_type` for most HF LLMs
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/runtime/src/model/chat.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement, area/ai

#3251 Replace `query_duration_seconds` and `http_requests_duration_seconds` with `milliseconds` metrics
  crates/runtime/src/datafusion/query/metrics.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/http/metrics.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/metrics.rs
  crates/telemetry/src/lib.rs
  monitoring/datadog-dashboard.json
  monitoring/grafana-dashboard.json
Labels: kind/optimization

#3384 Add `Extension<Runtime>` to HTTP routes to simplify tooling in NSQL.
  bin/spiced/src/lib.rs
  crates/runtime/src/http.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/tools/mod.rs
  crates/runtime/tests/tls/mod.rs
Labels: kind/refactor

#3386 Update datafusion patch
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#3395 Ensure hyperparameters are obeyed in recursive chat/completion calls.
  crates/runtime/src/model/tool_use.rs
Labels: kind/bug

#3394 fix: update odbc benchmarks
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench_odbc_athena/mod.rs
  crates/runtime/benches/bench_odbc_databricks/mod.rs
Labels: kind/bug

#3398 Add allow_http parameter for S3 data connector
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/object_store_registry.rs
Labels: kind/optimization

#3336 Add column field to dataset spicepod component
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/tools/builtin/table_schema.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/embeddings.rs
Labels: kind/enhancement

#3402 Add integration tests for OpenAI NSQL functionality
  Makefile
  crates/runtime/tests/acceleration/checkpoint_duckdb.rs
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
  crates/runtime/tests/acceleration/checkpoint_sqlite.rs
  crates/runtime/tests/acceleration/file_watcher.rs
  crates/runtime/tests/acceleration/on_conflict.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/acceleration/single_instance_duckdb.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/integration_models.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/odbc/mod.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/rehydration/mod.rs
  crates/runtime/tests/sqlite/mod.rs
  crates/runtime/tests/utils/mod.rs
  crates/spicepod/src/component/model.rs
Labels: kind/optimization

#3405 Implement optional api-key auth for the HTTP endpoint
  bin/spiced/src/lib.rs
  crates/runtime-auth/src/api_key/mod.rs
  crates/runtime-auth/src/lib.rs
  crates/runtime/src/auth/mod.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/lib.rs
  crates/runtime/tests/endpoint_auth/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/tls/mod.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#3410 Add integration tests for Search API (OpenAI and HF models)
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__hf__search_1.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__search_1.snap
  crates/spicepod/src/component/embeddings.rs
Labels: kind/optimization

#3404 HTTP APIs: list tools, call tool
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/tools.rs
Labels: kind/enhancement, area/ai

#3419 Support Kafka-native authentication and TLS connections for Debezium connector
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/kafka.rs
  crates/runtime/src/dataconnector/debezium.rs
Labels: kind/enhancement, breaking change

#3416 Add integration tests for Embeddings API (OpenAI and HF models)
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__hf__embeddings_1.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__embeddings_2.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__embeddings_3.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__embeddings_1.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__embeddings_2.snap
Labels: kind/optimization

#3418 Support base64 embedding format
  Cargo.lock
  Cargo.toml
  crates/llms/src/embeddings/candle/tei.rs
  crates/llms/src/embeddings/mod.rs
  crates/llms/src/openai/chat.rs
  crates/llms/src/openai/embed.rs
  crates/llms/src/openai/mod.rs
Labels: kind/bug, area/ai

#3425 Give local models some love
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/runtime/src/model/chat.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement, area/ai

#3428 Have views update on `--pods-watcher-enabled`
  crates/runtime/src/datafusion.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/metrics.rs
  crates/runtime/src/status.rs
  crates/runtime/src/topological_ordering.rs
Labels: kind/enhancement

#3424 Simplify running models integration tests locally
  Makefile
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
Labels: kind/optimization

#3432 Make Debezium connector MySQL compatible
  crates/data_components/src/debezium/change_event.rs
Labels: kind/enhancement

#3413 Store + load memory tooling, enable
  Cargo.lock
  crates/app/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/builder.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/memory.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/http/v1/tools.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/status.rs
  crates/runtime/src/tools/builtin/catalog.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
  crates/runtime/src/tools/builtin/get_readiness.rs
  crates/runtime/src/tools/builtin/list_datasets.rs
  crates/runtime/src/tools/builtin/mod.rs
  crates/runtime/src/tools/builtin/sample/tool.rs
  crates/runtime/src/tools/builtin/sql.rs
  crates/runtime/src/tools/builtin/table_schema.rs
  crates/runtime/src/tools/catalog.rs
  crates/runtime/src/tools/factory/builtin.rs
  crates/runtime/src/tools/factory/mod.rs
  crates/runtime/src/tools/memory/catalog.rs
  crates/runtime/src/tools/memory/load.rs
  crates/runtime/src/tools/memory/mod.rs
  crates/runtime/src/tools/memory/store.rs
  crates/runtime/src/tools/mod.rs
  crates/runtime/src/tools/utils.rs
Labels: kind/enhancement, area/ai

#3434 Statically compile OpenSSL
  Cargo.lock
  crates/data_components/Cargo.toml
Labels: kind/enhancement

#3435 Build macOS x64 on macos-14 (Sonoma)
  .github/workflows/build_and_release.yml
  .github/workflows/e2e_test_ci.yml
Labels: kind/bug

#3443 Upgrade dependencies
  Cargo.lock
  crates/runtime/Cargo.toml
  go.mod
  go.sum
  tools/otelpublisher/Cargo.toml
Labels: kind/dependencies

#3433 Add integration tests for chat completion API (HF and OpenAI)
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/model/mod.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/tests/integration_models.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_1_choices.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_completion.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_ai_completion_input.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_choices.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_completion.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__embeddings_1.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__embeddings_2.snap
Labels: kind/optimization

#3389 Run Clickbench with Spice Benchmark Binary
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_object_store/mod.rs
  crates/runtime/benches/bench_object_store/s3.rs
  crates/runtime/benches/queries/clickbench/q1.sql
  crates/runtime/benches/queries/clickbench/q10.sql
  crates/runtime/benches/queries/clickbench/q11.sql
  crates/runtime/benches/queries/clickbench/q12.sql
  crates/runtime/benches/queries/clickbench/q13.sql
  crates/runtime/benches/queries/clickbench/q14.sql
  crates/runtime/benches/queries/clickbench/q15.sql
  crates/runtime/benches/queries/clickbench/q16.sql
  crates/runtime/benches/queries/clickbench/q17.sql
  crates/runtime/benches/queries/clickbench/q18.sql
  crates/runtime/benches/queries/clickbench/q19.sql
  crates/runtime/benches/queries/clickbench/q2.sql
  crates/runtime/benches/queries/clickbench/q20.sql
  crates/runtime/benches/queries/clickbench/q21.sql
  crates/runtime/benches/queries/clickbench/q22.sql
  crates/runtime/benches/queries/clickbench/q23.sql
  crates/runtime/benches/queries/clickbench/q24.sql
  crates/runtime/benches/queries/clickbench/q25.sql
  crates/runtime/benches/queries/clickbench/q26.sql
  crates/runtime/benches/queries/clickbench/q27.sql
  crates/runtime/benches/queries/clickbench/q28.sql
  crates/runtime/benches/queries/clickbench/q29.sql
  crates/runtime/benches/queries/clickbench/q3.sql
  crates/runtime/benches/queries/clickbench/q30.sql
  crates/runtime/benches/queries/clickbench/q31.sql
  crates/runtime/benches/queries/clickbench/q32.sql
  crates/runtime/benches/queries/clickbench/q33.sql
  crates/runtime/benches/queries/clickbench/q34.sql
  crates/runtime/benches/queries/clickbench/q35.sql
  crates/runtime/benches/queries/clickbench/q36.sql
  crates/runtime/benches/queries/clickbench/q37.sql
  crates/runtime/benches/queries/clickbench/q38.sql
  crates/runtime/benches/queries/clickbench/q39.sql
  crates/runtime/benches/queries/clickbench/q4.sql
  crates/runtime/benches/queries/clickbench/q40.sql
  crates/runtime/benches/queries/clickbench/q41.sql
  crates/runtime/benches/queries/clickbench/q42.sql
  crates/runtime/benches/queries/clickbench/q43.sql
  crates/runtime/benches/queries/clickbench/q5.sql
  crates/runtime/benches/queries/clickbench/q6.sql
  crates/runtime/benches/queries/clickbench/q7.sql
  crates/runtime/benches/queries/clickbench/q8.sql
  crates/runtime/benches/queries/clickbench/q9.sql
  crates/runtime/benches/setup/mod.rs
Labels: kind/enhancement, kind/task

#3423 Use `datatype_is_semantically_equal` in `verify_schema`
  Cargo.lock
  Cargo.toml
  crates/arrow_tools/Cargo.toml
  crates/arrow_tools/src/schema.rs
Labels: kind/bug

#3446 Use spiceai-large-runners to build benchmark binary
  .github/workflows/benchmarks.yml
Labels: kind/optimization

#3445 Skip reqwest_retry::middleware tracing in non verbose configuration
  bin/spiced/src/tracing.rs
Labels: kind/bug

#3430 feat: Add invalid type action handling for DuckDB
  Cargo.lock
  Cargo.toml
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/memory.rs
  crates/runtime/src/dataconnector/mssql.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/sharepoint.rs
  crates/runtime/src/dataconnector/sink.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/dataconnector/unity_catalog.rs
  crates/runtime/src/lib.rs
  crates/spice_cloud/src/lib.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#3457 Fix benchmark: Lock poisoning issue from INSTA
  .github/workflows/benchmarks.yml
Labels: kind/bug

#3459 docs: Release DuckDB Connector RC
  README.md
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
  docs/criteria/connectors/rc.md
Labels: kind/documentation

#3460 DR: Code Pattern For Obtaining Milliseconds-Based Duration
  docs/decisions/003-duration-ms.md
Labels: kind/optimization

#3463 Improve ClickBench setup script: avoid re-downloading test data every time
  test/scripts/clickbench/setup-clickbench-spicepod.bash
Labels: kind/optimization

#3461 Fix `TableReference` quoting for MySQL
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataconnector/mysql.rs
Labels: kind/bug

#3458 Tool use and model name for local models
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/runtime/src/model/chat.rs
Labels: kind/bug, area/ai

#3473 `params.tools`, not `params.spice_tools`. Allow backwards compatibility to `params.spice_tools`.
  crates/llms/src/chat/mod.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/openai.rs
Labels: kind/enhancement, area/ai

#3474 fix: Support DuckDB boolean list
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#3462 Upgrade to DataFusion 43
  Cargo.lock
  Cargo.toml
  crates/data_components/src/arrow.rs
  crates/data_components/src/arrow/struct_builder.rs
  crates/data_components/src/arrow/write.rs
  crates/data_components/src/debezium_kafka.rs
  crates/data_components/src/delete.rs
  crates/data_components/src/delta_lake.rs
  crates/data_components/src/flight.rs
  crates/data_components/src/flight/stream.rs
  crates/data_components/src/flight/write.rs
  crates/data_components/src/flightsql.rs
  crates/data_components/src/github.rs
  crates/data_components/src/graphql/mod.rs
  crates/data_components/src/graphql/provider.rs
  crates/data_components/src/mssql/mod.rs
  crates/data_components/src/object/metadata.rs
  crates/data_components/src/object/text.rs
  crates/data_components/src/poly.rs
  crates/data_components/src/sharepoint/table.rs
  crates/data_components/src/spark_connect.rs
  crates/data_components/src/token_provider.rs
  crates/data_components/src/unity_catalog/provider.rs
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/accelerated_table/sink/mod.rs
  crates/runtime/src/accelerated_table/sink/multi.rs
  crates/runtime/src/accelerated_table/sink/table.rs
  crates/runtime/src/accelerated_table/synchronized_table.rs
  crates/runtime/src/component/dataset/acceleration/constraints.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/dataconnector/github/commits.rs
  crates/runtime/src/dataconnector/github/github_app_token_provider.rs
  crates/runtime/src/dataconnector/github/issues.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/github/pull_requests.rs
  crates/runtime/src/dataconnector/sink.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/extension/bytes_processed.rs
  crates/runtime/src/datafusion/extension/mod.rs
  crates/runtime/src/datafusion/schema.rs
  crates/runtime/src/embeddings/table.rs
  crates/runtime/src/execution_plan/schema_cast.rs
  crates/runtime/src/federated_table/mod.rs
  crates/runtime/src/object_store_registry.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/spice_cloud/src/catalog.rs
  crates/spice_cloud/src/schema.rs
Labels: kind/enhancement

#3476 Build explicit ODBC Docker image
  .github/workflows/spiced_docker.yml
Labels: kind/enhancement

#3478 Promote Arrow acceleration to RC
  README.md
  docs/criteria/accelerators/rc.md
Labels: kind/optimization

#3479 Update benchmark workflow to create PR for updating snapshot
  .github/workflows/benchmarks.yml
Labels: kind/enhancement

#3488 Update setup-make action
  .github/actions/setup-make/action.yml
Labels: kind/optimization

#3487 Option to return sql from `v1/nsql`
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/tools/builtin/sample/mod.rs
  crates/runtime/src/tools/builtin/sample/tool.rs
  crates/runtime/src/tools/utils.rs
Labels: kind/enhancement, area/ai

#3483 Adding scripts to run and monitor TPC-H/-DS queries at larger scale factors
  test/scripts/process_results.bash
  test/scripts/run-queries.bash
  test/scripts/run_queries_and_monitor.bash
  test/scripts/run_spice_and_monitor.bash
  test/scripts/setup-tpc-spicepod.bash
Labels: kind/enhancement

#3489 Update Datafusion and Datafusion-Table-Providers patch
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#3490 docs: Update Accelerator RC to specify clickbench in all modes
  docs/criteria/accelerators/rc.md
Labels: kind/documentation

#3485 Add logos and marks
  media/Logo - Orange on Transparant.png
  media/Logo - Orange on Transparant.svg
  media/Logo - Orange on White.png
  media/Logo - Orange on White.svg
  media/Logo - White on Orange.png
  media/Logo - White on Orange.svg
  media/Mark - Orange on Transparant.png
  media/Mark - Orange on Transparant.svg
  media/Mark - Orange on White.png
  media/Mark - Orange on White.svg
  media/Mark - White on Orange.png
  media/Mark - White on Orange.svg
Labels: kind/documentation

#3486 Updates to repo docs
  .github/ISSUE_TEMPLATE/end_game.md
  README.md
  SECURITY.md
  docs/ROADMAP.md
Labels: kind/documentation

#3477 Change `document_similarity` to return markdown, not JSON.
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
Labels: kind/enhancement, area/ai

#3498 Add support for creating embeddings for Utf8View type columns
  crates/runtime/src/embeddings/execution_plan.rs
Labels: kind/bug

#3500 Add vector search support for Utf8View type columns
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/bug

#3503 Update `datafusion-table-providers` version
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#3505 Update `text-embeddings-inference` and `mistral.rs` from downstream.
  Cargo.lock
  crates/llms/Cargo.toml
Labels: kind/enhancement

#3484 Fix snapshot update PR push in benchmark
  .github/workflows/benchmarks.yml
Labels: kind/bug

#3508 Run FederationAnalyzerRule before ResolveGroupingFunction rule
  Cargo.lock
  Cargo.toml
  crates/runtime/benches/bench_object_store/s3.rs
  crates/runtime/benches/bench_postgres/mod.rs
  crates/runtime/benches/bench_spark/mod.rs
  crates/runtime/benches/bench_spicecloud/mod.rs
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q2_explain.snap
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_avg_gas_used.snap
Labels: kind/enhancement

#3512 docs: Release DuckDB accelerator RC
  README.md
  docs/criteria/accelerators/rc.md
Labels: kind/documentation

#3511 Upgrade datafusion-functions-json to 0.43
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#3514 Update Datafusion Table Provider patch to fix MySQL refresh append mode
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#3521 Handle panics in HF API calls
  Cargo.lock
  crates/llms/Cargo.toml
Labels: kind/bug, area/ai

#3518 Update Runtime metrics according to metrics naming guidelines
  crates/runtime/src/accelerated_table/metrics.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/src/metrics.rs
  crates/telemetry/src/lib.rs
Labels: kind/optimization, breaking change

#3520 Update Results Cache metrics according to metrics naming guidelines
  crates/cache/src/lib.rs
  crates/cache/src/metrics.rs
Labels: kind/optimization, breaking change

#3531 Refactor runtime initialization into separate modules
  crates/runtime/src/init/catalog.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/init/embedding.rs
  crates/runtime/src/init/extension.rs
  crates/runtime/src/init/llm.rs
  crates/runtime/src/init/metrics.rs
  crates/runtime/src/init/mod.rs
  crates/runtime/src/init/model.rs
  crates/runtime/src/init/pods_watcher.rs
  crates/runtime/src/init/results_cache.rs
  crates/runtime/src/init/task_history.rs
  crates/runtime/src/init/tool.rs
  crates/runtime/src/init/view.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement, kind/refactor

#3529 Update Anonymous telemetry metrics according to metrics naming guidelines
  crates/runtime/src/metrics.rs
  crates/telemetry/src/lib.rs
Labels: kind/optimization, breaking change

#3516 Add Metrics naming principles and guidelines
  CONTRIBUTING.md
  docs/dev/metrics.md
Labels: kind/optimization

#3532 Improve localpod startup to register immediately after its parent is registered
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/secrets.rs
Labels: kind/bug

#3530 Update dashboards to match new metrics names
  crates/runtime/src/flight/metrics.rs
  monitoring/datadog-dashboard.json
  monitoring/grafana-dashboard.json
Labels: kind/optimization

#3541 Clarify source of prefixes for data component parameters.
  crates/runtime/src/parameters.rs
Labels: kind/documentation

#3565 fix: Validate the endpoint for ABFS and S3
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/s3.rs
Labels: kind/bug

#3575 Vector Search: Default to datasets with embeddings only when none are specified
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/tests/models/openai.rs
Labels: kind/bug

#3577 Lowercase the ready handler response
  .github/workflows/e2e_test_ci.yml
  crates/runtime/src/http/v1/ready.rs
  test/scripts/run_queries_and_monitor.bash
Labels: kind/enhancement, breaking change

#3571 Improve `spice search` error handling
  bin/spice/cmd/search.go
Labels: kind/bug

#3566 Load components in parallel, not concurrently
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#3578 fix: Make S3 auth parameter validation more robust:
  crates/runtime/src/dataconnector/s3.rs
Labels: kind/bug

#3580 fix: Infer if the specified file format is correct in object store
  crates/runtime/src/dataconnector/listing/connector.rs
Labels: kind/bug

#3581 Add ability to configure CORS on the HTTP server
  Cargo.lock
  Cargo.toml
  crates/app/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/http.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/tests/cors/mod.rs
  crates/runtime/tests/integration.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#3582 fix: Handle invalid S3 auth and region better
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/s3.rs
Labels: kind/bug

#3586 allow setting of replicaCount to a falsy-value
  deploy/chart/Chart.yaml
  deploy/chart/templates/deployment.yaml
Labels: kind/bug

#3588 `spice search` to default to only datasets with embeddings
  bin/spice/cmd/search.go
Labels: kind/bug

#3572 Run AI integration tests as part of CI
  .github/workflows/integration_models.yml
  crates/runtime/tests/models/openai.rs
Labels: kind/optimization

#3585 Load datasets in parallel
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/lib.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/bug

#3583 Run integration test on smaller runners
  .github/workflows/integration.yml
Labels: kind/enhancement

#3584 Use folders for model component
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/runtime/src/model/chat.rs
  crates/spicepod/src/component/model.rs
Labels: kind/bug, area/ai

#3592 Improve models integration tests
  .github/workflows/integration_models.yml
  crates/runtime/tests/models/snapshots/integration_models__models__openai__search_2.snap
Labels: kind/optimization

#3598 Change default task_history captured_output to `none`
  bin/spiced/src/tracing.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#3601 Add timeout to `/v1/datasets` APIs when app is locked
  crates/runtime/src/http/v1/datasets.rs
Labels: kind/bug

#3604 Make integration tests more robust on fewer cores
  crates/runtime/tests/cors/mod.rs
  crates/runtime/tests/endpoint_auth/flight.rs
  crates/runtime/tests/endpoint_auth/http.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/github/mod.rs
  crates/runtime/tests/mysql/mod.rs
  crates/runtime/tests/postgres/mod.rs
  crates/runtime/tests/refresh_retry/mysql.rs
  crates/runtime/tests/rehydration/mod.rs
  crates/runtime/tests/tls/mod.rs
Labels: kind/bug

#3602 refactor: First pass data connector error messages update
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/github/commits.rs
  crates/runtime/src/dataconnector/github/issues.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/github/pull_requests.rs
  crates/runtime/src/dataconnector/github/stargazers.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/localpod.rs
  crates/runtime/src/dataconnector/memory.rs
  crates/runtime/src/dataconnector/mssql.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/sharepoint.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/dataconnector/unity_catalog.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/init/catalog.rs
  crates/runtime/src/init/dataset.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement, kind/refactor

#3605 Add log if no datasets are configured
  crates/runtime/src/init/dataset.rs
Labels: kind/bug

#3599 Add E2E test for spice search and chat functionality (OpenAI)
  .github/workflows/e2e_test_ci_models.yml
  test/models/chat_01.exp
  test/models/search_01.exp
  test/models/spicepod.yml
Labels: kind/optimization

#3507 Use spiceai-runners for TPCH / TPCDS benchmark
  .github/workflows/benchmarks.yml
  crates/runtime/benches/setup/mod.rs
Labels: kind/optimization

#3611 docs: Update error handling guide
  docs/dev/error_handling.md
Labels: kind/documentation

#3612 Improve default description for sql tool
  crates/runtime/src/tools/builtin/sql.rs
Labels: kind/enhancement, area/ai

#3613 Update metric name from `query_invocations` to `query_executions`
  crates/runtime/src/metrics.rs
  crates/telemetry/src/lib.rs
Labels: kind/optimization

#3615 Don't provide runtime tools to health check.
  crates/llms/src/chat/mod.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement, area/ai

#3620 Sort vector search results based on similarity score
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/search.rs
Labels: kind/bug

#3619 Allow overriding runtime configuration with `--set-runtime` CLI flags
  Cargo.lock
  bin/spiced/Cargo.toml
  bin/spiced/src/lib.rs
  bin/spiced/src/main.rs
  crates/flightrepl/src/lib.rs
Labels: kind/enhancement

#3621 Some bugs
  crates/runtime/src/model/chat.rs
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_ai_completion_input.snap
Labels: kind/bug, area/ai

#3640 Improve S3 errors
  crates/runtime/src/dataconnector/s3.rs
Labels: kind/optimization, kind/task

#3642 Update Databricks, Delta Lake, DuckDB error messages
  crates/data_components/src/delta_lake.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/duckdb.rs
Labels: kind/optimization

#3639 docs: Add error message UX to beta connector criteria
  docs/criteria/connectors/beta.md
Labels: kind/documentation

#3617 feat: Make REPL identify it's waiting on a new line
  crates/flightrepl/src/lib.rs
  test/repl/show_tables.exp
Labels: kind/enhancement

#3641 Wrap Server-Sent-Events chat errors as OpenAI error events
  bin/spice/cmd/chat.go
  crates/runtime/src/http/v1/chat.rs
Labels: kind/bug

#3614 refactor: Update accelerated table errors, dataset health monitor errors
  crates/flight_client/src/lib.rs
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/dataconnector/unity_catalog.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/cosine_distance.rs
  crates/runtime/src/embeddings/execution_plan.rs
  docs/dev/error_handling.md
Labels: kind/bug, kind/documentation

#3644 Extend `v1/datasets` api to indicate if dataset can be used in vector search
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/tools/builtin/list_datasets.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/optimization

#3646 feat: Unnest DataFusion errors
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/accelerated_table/refresh_task/streaming_append.rs
  crates/runtime/src/accelerated_table/sink/multi.rs
  crates/runtime/src/accelerated_table/sink/table.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/github/commits.rs
  crates/runtime/src/dataconnector/github/issues.rs
  crates/runtime/src/dataconnector/github/pull_requests.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/error.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/udf.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/src/dataupdate.rs
  crates/runtime/tests/acceleration/on_conflict.rs
Labels: kind/enhancement

#3648 feat: Add RateLimited DataConnectorError
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/github/mod.rs
Labels: kind/enhancement

#3649 Setup nightly docker release workflow
  .github/workflows/spiced_docker_nightly.yml
Labels: kind/enhancement

#3576 Make LLM integration tests more extensible.
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_1_response_choices.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_completion.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__embeddings_1.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__embeddings_2.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__embeddings_3.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__nsql_sample_data_task.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__nsql_sample_data_task_sql_query.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__nsql_table_schema_task.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_ai_completion_input.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_response_choices.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_sql_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_2_document_similarity_input.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_2_document_similarity_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_2_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_2_response_choices.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_completion.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__embeddings__base64_format.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__embeddings__basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__embeddings__multiple_inputs.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__nsql__basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__nsql__basic_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__nsql__with_model_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__nsql__with_model_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__nsql__with_sample_data_enabled_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__nsql__with_sample_data_enabled_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__nsql_sample_data_task.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__nsql_sample_data_task_sql_query.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__nsql_table_schema_task.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__search_2.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__search__all_datasets_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__search__basic_response.snap
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement, area/ai

#3651 feat: Update ODBC error messages
  crates/runtime/src/dataconnector/odbc.rs
Labels: kind/enhancement

#3652 Nightly release workflow fixes
  .github/workflows/spiced_docker_nightly.yml
Labels: kind/bug

#3610 Use GitHub GraphQL rate limiting responses to rate limit requests
  crates/data_components/src/graphql/builder.rs
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/graphql/mod.rs
  crates/data_components/src/graphql/rate_limit.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/github/rate_limit.rs
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/enhancement, area/data-connectors, data-connector/graphql, data-connector/github

#3654 Fix typo in nightly release publish step
  .github/workflows/spiced_docker_nightly.yml
Labels: kind/bug

#3656 Handle GitHub rate-limiting for the Rest API
  crates/data_components/src/github.rs
  crates/data_components/src/graphql/builder.rs
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/rate_limit/mod.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/github/rate_limit.rs
Labels: kind/enhancement

#3609 Adding custom User-Agent parameters to chat, nsql and flightrepl
  bin/spice/cmd/chat.go
  bin/spice/cmd/nsql.go
  bin/spice/cmd/sql.go
  bin/spice/pkg/context/context.go
  bin/spice/pkg/util/os_release_unix.go
  bin/spice/pkg/util/os_release_windows.go
  bin/spice/pkg/util/platform.go
  crates/flightrepl/src/config.rs
  crates/flightrepl/src/lib.rs
  crates/runtime/tests/endpoint_auth/flight.rs
Labels: kind/enhancement

#3671 Remove "nightly-" prefix from tag
  .github/workflows/spiced_docker_nightly.yml
Labels: kind/bug

#3590 `spice search` to warn if dataset is not ready and won't be included in search
  bin/spice/cmd/search.go
  bin/spice/pkg/api/dataset.go
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/optimization

#3600 Handle empty embeds by allowing for nulls
  crates/runtime/src/embeddings/execution_plan.rs
  crates/runtime/src/embeddings/table.rs
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/bug

#3676 Update FlightSQL error messages
  crates/data_components/src/flightsql.rs
  crates/runtime/src/dataconnector/flightsql.rs
Labels: kind/enhancement

#3678 Update Datafusion Table Provider Patch to include error message improvements
  Cargo.lock
  Cargo.toml
Labels: kind/optimization

#3647 Integration tests for `llms` crate, with basic Anthropic test.
  .github/workflows/integration_llms.yml
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/anthropic/chat.rs
  crates/llms/src/anthropic/mod.rs
  crates/llms/src/anthropic/types_stream.rs
  crates/llms/tests/integration.rs
  crates/llms/tests/llms/create.rs
  crates/llms/tests/llms/mod.rs
  crates/llms/tests/llms/snapshots/integration__llms__basic_anthropic_message_keys.snap
  crates/llms/tests/llms/snapshots/integration__llms__basic_anthropic_replied_appropriately.snap
  crates/llms/tests/llms/snapshots/integration__llms__system_prompt_anthropic_assistant_response.snap
  crates/llms/tests/llms/snapshots/integration__llms__system_prompt_anthropic_replied_appropriately.snap
  crates/llms/tests/llms/snapshots/integration__llms__tool_use_anthropic_finish_reason.snap
  crates/llms/tests/llms/snapshots/integration__llms__tool_use_anthropic_tool_choice.snap
  crates/llms/tests/llms/snapshots/integration__llms__tool_use_anthropic_valid_function_args.snap
  crates/runtime/src/model/chat.rs
  crates/runtime/tests/models/openai.rs
Labels: kind/enhancement, area/ai
