Repository spiceai/spiceai, pull requests merged in 2024-02, with the labels that each got.

#641 Incremental SpiceAI datasource
  crates/flight_client/src/lib.rs
  crates/runtime/src/datasource.rs
  crates/runtime/src/datasource/spiceai.rs
  crates/spicepod/src/component/dataset.rs
Labels: enhancement

#642 Error out if the dataset to subscribe to doesn't exist
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datasource/spiceai.rs
  crates/runtime/src/flight.rs
Labels: bug

#645 Always use bare table references
  crates/runtime/src/databackend/memtable.rs
Labels: bug

#646 Fix `spice add` to work with new spicepod format
  bin/spice/pkg/cli/cmd/add.go
  bin/spice/pkg/cli/cmd/version.go
  bin/spice/pkg/context/context.go
  bin/spice/pkg/registry/spicerack.go
Labels: enhancement

#648 Basic DuckDB TableProvider implementation
  Cargo.lock
  Cargo.toml
  crates/duckdb_datafusion/Cargo.toml
  crates/duckdb_datafusion/README.md
  crates/duckdb_datafusion/src/lib.rs
Labels: enhancement

#649 Support DuckDB push down filters
  Cargo.lock
  crates/duckdb_datafusion/Cargo.toml
  crates/duckdb_datafusion/src/expr.rs
  crates/duckdb_datafusion/src/lib.rs
Labels: enhancement

#652 Integrate device auth with SpiceAI datasource
  Cargo.lock
  Makefile
  bin/spice/Makefile
  bin/spice/pkg/api/spice_api_client.go
  bin/spice/pkg/cli/cmd/version.go
  bin/spice/pkg/registry/spicerack.go
  bin/spice/pkg/version/version.go
  bin/spiced/Cargo.toml
  bin/spiced/Makefile
  crates/flight_client/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/datasource/dremio.rs
  crates/runtime/src/datasource/flight.rs
  crates/runtime/src/datasource/spiceai.rs
Labels: enhancement

#653 SQL view datasets
  bin/spiced/src/lib.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/http/v1.rs
  crates/spicepod/src/component/dataset.rs
Labels: enhancement

#656 DuckDB DataBackend
  Cargo.lock
  Dockerfile
  bin/spiced/src/lib.rs
  clippy.toml
  crates/duckdb_datafusion/Cargo.toml
  crates/duckdb_datafusion/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/databackend.rs
  crates/runtime/src/databackend/duckdb.rs
  crates/runtime/src/databackend/memtable.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/opentelemetry.rs
  crates/spicepod/Cargo.toml
  crates/spicepod/src/component/dataset.rs
Labels: enhancement

#658 Flight REPL
  Cargo.lock
  Cargo.toml
  bin/flightrepl/Cargo.toml
  bin/flightrepl/src/main.rs
  crates/runtime/src/datafusion.rs
Labels: enhancement

#669 Use the PostgreSqlDialect instead of Ansi
  crates/runtime/src/databackend/memtable.rs
  crates/runtime/src/datafusion.rs
Labels: enhancement

#670 Rename DataSource -> DataConnector, Update principles, add extensibility doc
  bin/spiced/src/lib.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/debug.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/flight.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/lib.rs
  docs/EXTENSIBILITY.md
  docs/PRINCIPLES.md
Labels: documentation

#675 Implement `sql_ref` and improve view CTE detection
  bin/spiced/src/lib.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/http/v1.rs
  crates/spicepod/src/component/dataset.rs
Labels: bug

#677 Only warn once if a metric isn't supported
  crates/runtime/src/datafusion.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/opentelemetry.rs
  crates/runtime/src/tracers.rs
Labels: enhancement

#692 `spice query` -> `spice sql`
  bin/spice/pkg/cli/cmd/sql.go
Labels: bug

#693 Support pushing data to Spice.ai
  Cargo.lock
  bin/spiced/src/lib.rs
  crates/flight_client/Cargo.toml
  crates/flight_client/src/lib.rs
  crates/runtime/src/databackend.rs
  crates/runtime/src/databackend/duckdb.rs
  crates/runtime/src/databackend/memtable.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/debug.rs
  crates/runtime/src/dataconnector/flight.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datapublisher.rs
  crates/runtime/src/dataupdate.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/opentelemetry.rs
  crates/runtime/src/tracers.rs
  crates/spicepod/src/component/dataset.rs
  docs/EXTENSIBILITY.md
Labels: enhancement

#705 Add `replication` configuration to Dataset to control data pushing
  crates/runtime/src/datafusion.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/opentelemetry.rs
  crates/runtime/src/tracers.rs
  crates/spicepod/src/component/dataset.rs
Labels: enhancement

#714 Remove unix-specific code
  crates/runtime/src/lib.rs
Labels: enhancement

#710 Add build & release workflow
  .github/actions/setup-rust/action.yml
  .github/workflows/build_and_release.yml
  .github/workflows/license_check.yml
  .github/workflows/pr.yml
  bin/spice/Makefile
  install/install.sh
Labels: enhancement

#723 Show query time in REPL
  crates/flightrepl/src/lib.rs
Labels: enhancement

#736 Updated README for OSS v2
  README.md
  docs/ROADMAP.md
Labels: documentation

#740 Deleted "sql>" from lines 120 and 219.
  README.md
Labels: documentation

#738 Improvements to README.md for v0.7-alpha release
  README.md
Labels: documentation

#743 Add Quickstart video to README.md
  README.md
Labels: documentation
