Repository spiceai/spiceai, pull requests merged in 2024-04, with the labels that each got.

#1002 Add basic Helm chart for spiceai
  deploy/chart/Chart.yaml
  deploy/chart/templates/spiceai-config.yaml
  deploy/chart/templates/spiceai.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#1001 Improvement to README
  README.md
Labels: kind/documentation

#1014 Remove dependency on `duckdb-rs` fork
  Cargo.lock
  Cargo.toml
Labels: kind/dependencies

#1018 Update ROADMAP Apr 2, 2024
  docs/ROADMAP.md
Labels: kind/documentation, area/cli

#1021 Add additional links to quickstarts and samples
  README.md
Labels: kind/documentation

#1030 Update Helm chart + Grafana dashboard
  .github/ISSUE_TEMPLATE/end_game.md
  bin/spice/cmd/spice.go
  bin/spice/pkg/context/context.go
  deploy/chart/templates/podmonitor.yaml
  deploy/chart/values.yaml
  monitoring/grafana-dashboard.json
Labels: area/dashboard

#1029 Fix optional connector features: duckdb, postgres, sqlite
  bin/spiced/Cargo.toml
  crates/app/Cargo.toml
  crates/arrow_sql_gen/Cargo.toml
  crates/arrow_sql_gen/src/lib.rs
  crates/db_connection_pool/Cargo.toml
  crates/db_connection_pool/src/dbconnection.rs
  crates/db_connection_pool/src/lib.rs
  crates/flight_client/Cargo.toml
  crates/flight_datafusion/Cargo.toml
  crates/flightrepl/Cargo.toml
  crates/ns_lookup/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/databackend.rs
  crates/runtime/src/dataconnector.rs
  crates/secrets/Cargo.toml
  crates/spicepod/Cargo.toml
  crates/spicepod/src/component/dataset.rs
  crates/sql_provider_datafusion/Cargo.toml
Labels: kind/bug

#1046 Add "How is Spice Different"
  README.md
Labels: kind/documentation

#1049 Update Roadmap for v0.11
  docs/ROADMAP.md
Labels: kind/documentation

#1052 Consistently use Go 1.22.0 everywhere
  .github/workflows/build_and_release.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/license_check.yml
  .github/workflows/pr.yml
  .github/workflows/tpch_benchmark.yml
  go.mod
  go.sum
Labels: kind/dependencies

#1072 Create enhancement.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: kind/documentation

#1077 Explicitly pass the schema to data accelerator SqlTable
  crates/arrow_sql_gen/src/statement.rs
  crates/data_components/src/duckdb.rs
  crates/data_components/src/postgres.rs
  crates/data_components/src/sqlite.rs
  crates/sql_provider_datafusion/src/lib.rs
Labels: kind/bug

#1064 Support for secrets defined in AWS Secrets Manager
  Cargo.lock
  bin/spiced/src/main.rs
  crates/runtime/src/lib.rs
  crates/secrets/Cargo.toml
  crates/secrets/src/aws_secrets_manager.rs
  crates/secrets/src/lib.rs
Labels: kind/enhancement

#1073 Add `refresh_sql` to dataset `acceleration`
  bin/spice/pkg/spec/dataset.go
  crates/data_components/Cargo.toml
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/refresh_sql.rs
  crates/runtime/src/lib.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#1097 Upgrade Arrow, DataFusion, Tonic
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/databricks/write.rs
  crates/data_components/src/flight.rs
  crates/data_components/src/flight/stream.rs
  crates/data_components/src/flightsql.rs
  crates/data_components/src/lib.rs
  crates/flightrepl/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataupdate.rs
  crates/runtime/src/execution_plan/slice.rs
  crates/runtime/src/execution_plan/tee.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/do_get.rs
  crates/runtime/src/flight/flightsql/get_tables.rs
  crates/runtime/src/flight/flightsql/prepared_statement_query.rs
  crates/runtime/src/flight/flightsql/statement_query.rs
  crates/sql_provider_datafusion/src/lib.rs
  tools/flightpublisher/Cargo.toml
  tools/flightsubscriber/Cargo.toml
Labels: dependencies

#1113 Remove extraneous login parameters for databricks
  bin/spice/cmd/login.go
Labels: area/cli

#1110 Databricks connector based on spark-connect-rs
  .github/workflows/e2e_test_ci.yml
  .github/workflows/pr.yml
  Cargo.lock
  Dockerfile
  crates/data_components/Cargo.toml
  crates/data_components/src/databricks.rs
  crates/data_components/src/databricks/write.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/spark_connect.rs
  crates/runtime/src/dataconnector/databricks.rs
Labels: area/data-connectors

#1115 Choose between databricks implementations via `format` & `mode` parameters
  .github/workflows/build_and_release.yml
  bin/spice/cmd/login.go
  crates/data_components/Cargo.toml
  crates/data_components/src/databricks_delta.rs
  crates/data_components/src/databricks_spark.rs
  crates/data_components/src/deltatable/mod.rs
  crates/data_components/src/deltatable/write.rs
  crates/data_components/src/lib.rs
  crates/runtime/src/dataconnector/databricks.rs
Labels: area/data-connectors

#1186 Properly support Spark Connect filter pushdown
  crates/data_components/src/spark_connect.rs
  crates/sql_provider_datafusion/src/expr.rs
Labels: kind/bug

#1189 Avoid rate-limiting on arduino/setup-protoc@v3
  .github/workflows/e2e_test_ci.yml
  .github/workflows/pr.yml
Labels: kind/bug

#1200 Upgrade DataFusion to 37.1 & DuckDB to 10.2
  Cargo.lock
  Cargo.toml
Labels: dependencies

#1219 Add BI dashboard acceleration video to README.md
  README.md
Labels: kind/documentation

#1214 Improve clarity and consistency of output messages
  .github/actions/verify-dataset/action.yml
  README.md
  crates/flightrepl/src/lib.rs
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/lib.rs
Labels: kind/documentation

#1220 Update ROADMAP Apr 29, 2024
  docs/ROADMAP.md
Labels: kind/documentation

#1213 Stand-alone Spark Connect: Isolate Spark Connect from Databricks Connect to make it reusable
  bin/spiced/Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/databricks_spark.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/spark_connect.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/spark.rs
Labels: area/data-connectors
