Repository spiceai/spiceai, pull requests merged in 2024-06, with the labels that each got.

#1595 Support BinaryArray in DuckDB accelerations
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#1568 Add v0.13.2-alpha release notes
  README.md
  docs/release_notes/v0.13.2-alpha.md
Labels: kind/documentation

#1615 Upgrade duckdb-rs to DuckDB 1.0.0
  Cargo.lock
  Cargo.toml
Labels: data-connector/duckdb

#1620 Add branching policy & updated endgame instructions
  .github/ISSUE_TEMPLATE/end_game.md
  docs/RELEASE.md
Labels: kind/documentation

#1636 [append] Refresher::get_latest_timestamp / get_df to add refresh_sql predicates to scan
  crates/runtime/src/accelerated_table/refresh.rs
Labels: kind/bug

#1644 Support indexes in accelerated tables
  crates/arrow_sql_gen/src/statement.rs
  crates/data_components/src/duckdb.rs
  crates/data_components/src/postgres.rs
  crates/data_components/src/sqlite.rs
  crates/data_components/src/util.rs
  crates/data_components/src/util/indexes.rs
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/mysql.rs
  crates/runtime/tests/odbc/mod.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#1669 Add missing dependency on arrow_sql_gen from duckdb data_component
  crates/data_components/Cargo.toml
Labels: kind/bug

#1682 Atomic updates for DuckDB tables with constraints
  Cargo.lock
  crates/arrow_sql_gen/src/statement.rs
  crates/data_components/Cargo.toml
  crates/data_components/src/duckdb.rs
  crates/data_components/src/duckdb/creator.rs
  crates/data_components/src/duckdb/write.rs
  crates/data_components/src/util/constraints.rs
  crates/db_connection_pool/src/dbconnection/duckdbconn.rs
Labels: kind/enhancement

#1687 Support `primary_key` in Spicepod and create in accelerated table.
  crates/data_components/src/duckdb/creator.rs
  crates/data_components/src/postgres.rs
  crates/data_components/src/sqlite.rs
  crates/data_components/src/util/constraints.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/lib.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#1697 Improve `ArrayDistance` scalar UDF
  crates/runtime/src/embeddings/array_distance.rs
  crates/runtime/src/embeddings/mod.rs
  crates/runtime/src/lib.rs
Labels: rust

#1688 Implement `on_conflict` behavior for accelerated tables with constraints
  Cargo.lock
  Cargo.toml
  crates/arrow_sql_gen/src/lib.rs
  crates/arrow_sql_gen/src/statement.rs
  crates/data_components/Cargo.toml
  crates/data_components/src/duckdb.rs
  crates/data_components/src/duckdb/creator.rs
  crates/data_components/src/duckdb/write.rs
  crates/data_components/src/postgres.rs
  crates/data_components/src/postgres/write.rs
  crates/data_components/src/sqlite.rs
  crates/data_components/src/sqlite/write.rs
  crates/data_components/src/util.rs
  crates/data_components/src/util/column_reference.rs
  crates/data_components/src/util/constraints.rs
  crates/data_components/src/util/indexes.rs
  crates/data_components/src/util/on_conflict.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/component/dataset/acceleration/constraints.rs
  crates/runtime/src/component/dataset/acceleration/on_conflict.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/tests/federation/mysql.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#1709 Fix error message on DuckDB constraint violation
  crates/data_components/src/duckdb/creator.rs
  crates/data_components/src/duckdb/write.rs
Labels: kind/bug

#1713 Improve README clarity and add comparison table
  README.md
Labels: kind/documentation

#1723 Move secret crate to runtime module
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/databricks_delta.rs
  crates/data_components/src/postgres.rs
  crates/data_components/src/util.rs
  crates/data_components/src/util/secrets.rs
  crates/db_connection_pool/Cargo.toml
  crates/db_connection_pool/src/clickhousepool.rs
  crates/db_connection_pool/src/dbconnection/odbcconn.rs
  crates/db_connection_pool/src/mysqlpool.rs
  crates/db_connection_pool/src/odbcpool.rs
  crates/db_connection_pool/src/postgrespool.rs
  crates/db_connection_pool/src/snowflakepool.rs
  crates/model_components/Cargo.toml
  crates/model_components/src/model.rs
  crates/model_components/src/modelsource/huggingface.rs
  crates/model_components/src/modelsource/local.rs
  crates/model_components/src/modelsource/mod.rs
  crates/model_components/src/modelsource/spiceai.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/localhost.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/secrets.rs
  crates/runtime/src/secrets/aws_secrets_manager.rs
  crates/runtime/src/secrets/env.rs
  crates/runtime/src/secrets/file.rs
  crates/runtime/src/secrets/keyring.rs
  crates/runtime/src/secrets/kubernetes.rs
  crates/secrets/Cargo.toml
  crates/spice_cloud/Cargo.toml
  crates/spice_cloud/src/lib.rs
  crates/sql_provider_datafusion/Cargo.toml
  crates/sql_provider_datafusion/tests/postgres_integration_test.rs
Labels: kind/enhancement

#1733 Support Struct in PostgreSQL accelerator
  Cargo.lock
  Cargo.toml
  crates/arrow_sql_gen/Cargo.toml
  crates/arrow_sql_gen/src/arrow.rs
  crates/arrow_sql_gen/src/postgres.rs
  crates/arrow_sql_gen/src/postgres/builder.rs
  crates/arrow_sql_gen/src/postgres/composite.rs
  crates/arrow_sql_gen/src/statement.rs
  crates/data_components/src/postgres.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/datafusion/filter_converter.rs
  crates/runtime/src/http/v1/nsql.rs
Labels: kind/enhancement

#1750 Fix error when GraphQL error locations is missing
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/bug

#1767 Show UUID types as String instead of base64 binary.
  Cargo.lock
  Makefile
  crates/arrow_sql_gen/src/clickhouse.rs
  crates/arrow_sql_gen/src/postgres.rs
  crates/db_connection_pool/src/postgrespool.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/postgres/common.rs
  crates/runtime/tests/postgres/mod.rs
  crates/sql_provider_datafusion/Cargo.toml
  crates/sql_provider_datafusion/tests/postgres_integration_test.rs
Labels: kind/bug

#1769 docs: Add linux contributor guide for setup
  CONTRIBUTING.md
Labels: kind/documentation

#1787 fix(bin/spice): Implement custom Unmarshaller for DatasetOrReference
  Cargo.lock
  bin/spice/cmd/add.go
  bin/spice/cmd/dataset.go
  bin/spice/cmd/login.go
  bin/spice/pkg/spec/component.go
  bin/spice/pkg/spec/dataset.go
  bin/spice/pkg/spec/spicepod.go
  bin/spice/pkg/spec/spicepod_test.go
  bin/spice/pkg/spicepod/spicepod.go
Labels: kind/bug

#1794 docs: Add PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation

#1798 fix: Stream PostgreSQL data in
  Cargo.lock
  crates/db_connection_pool/Cargo.toml
  crates/db_connection_pool/src/dbconnection/postgresconn.rs
  crates/runtime/Cargo.toml
  crates/runtime/tests/postgres/common.rs
  crates/runtime/tests/postgres/mod.rs
Labels: kind/enhancement

#1808 refactor: Format TOML with Taplo
  .taplo.toml
  Cargo.toml
  Makefile
  bin/spiced/.cargo/config.toml
  bin/spiced/Cargo.toml
  clippy.toml
  crates/app/Cargo.toml
  crates/arrow_sql_gen/Cargo.toml
  crates/arrow_tools/Cargo.toml
  crates/cache/Cargo.toml
  crates/data_components/Cargo.toml
  crates/db_connection_pool/Cargo.toml
  crates/flight_client/Cargo.toml
  crates/flightrepl/Cargo.toml
  crates/llms/Cargo.toml
  crates/model_components/Cargo.toml
  crates/ns_lookup/Cargo.toml
  crates/runtime/Cargo.toml
  crates/spice_cloud/Cargo.toml
  crates/spicepod/Cargo.toml
  crates/sql_provider_datafusion/Cargo.toml
  crates/util/Cargo.toml
  tools/flightpublisher/Cargo.toml
  tools/flightsubscriber/Cargo.toml
Labels: kind/refactor

#1815 feat: Update PR template, add label enforcement in PR
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/enforce-labels.yml
Labels: kind/enhancement

#1817 fix bug that append may miss updates when the incremental changes are not able to be contained in one record batch
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
Labels: kind/bug

#1811 add integration test for inner join across federated table and accelerated table
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/mysql/common.rs
  crates/runtime/tests/refresh_retry/mysql.rs
Labels: kind/bug

#1818 Unify spicepod.llms into spicepod.models and refactor UX of spicepod.models
  bin/spiced/src/lib.rs
  crates/app/src/lib.rs
  crates/model_components/src/model.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model.rs
  crates/spicepod/src/component.rs
  crates/spicepod/src/component/embeddings.rs
  crates/spicepod/src/component/llms.rs
  crates/spicepod/src/component/model.rs
  crates/spicepod/src/lib.rs
  crates/spicepod/src/spec.rs
Labels: rust, kind/refactor

#1823 Fix issue with querying accelerated tables where the dataset name has a schema
  crates/sql_provider_datafusion/src/lib.rs
Labels: kind/bug

#1826 Fix schema support for refresh_sql and improve e2e tests
  .github/actions/verify-dataset/action.yml
  .github/workflows/e2e_test_ci.yml
  crates/runtime/src/datafusion/refresh_sql.rs
Labels: kind/bug
