Repository spiceai/spiceai, pull requests merged in 2024-03, with the labels that each got.

#771 Add a better error message when publishing fails to SpiceAI due to a PermissionDenied error
  crates/flight_client/Cargo.toml
  crates/flight_client/src/lib.rs
  crates/flightrepl/Cargo.toml
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/opentelemetry.rs
  tools/flightpublisher/Cargo.toml
  tools/flightsubscriber/Cargo.toml
Labels: bug

#789 Actually use the config
  crates/runtime/src/datafusion.rs
Labels: bug

#809 Add v0.9-v0.12 and v1.0+ roadmap items
  docs/ROADMAP.md
Labels: documentation

#795 Implement Flight SQL server
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/actions.rs
  crates/runtime/src/flight/do_exchange.rs
  crates/runtime/src/flight/do_get.rs
  crates/runtime/src/flight/do_put.rs
  crates/runtime/src/flight/flightsql.rs
  crates/runtime/src/flight/flightsql/get_catalogs.rs
  crates/runtime/src/flight/flightsql/get_schemas.rs
  crates/runtime/src/flight/flightsql/get_sql_info.rs
  crates/runtime/src/flight/flightsql/get_tables.rs
  crates/runtime/src/flight/flightsql/prepared_statement_query.rs
  crates/runtime/src/flight/flightsql/statement_query.rs
  crates/runtime/src/flight/get_flight_info.rs
  crates/runtime/src/flight/handshake.rs
Labels: kind/enhancement

#810 Tweaks to Endgame template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/end_game.md
  docs/RELEASE.md
  docs/ROADMAP.md
Labels: kind/documentation

#811 Create SECURITY.md
  SECURITY.md
Labels: kind/documentation

#825 Consistent spice and spiced versions - with better pre-release versioning
  bin/spice/Makefile
  bin/spiced/build.rs
  bin/spiced/src/main.rs
Labels: kind/bug

#828 Add spiced Docker build & release
  .github/workflows/license_check.yml
  .github/workflows/pr.yml
  .github/workflows/spiced_docker.yml
Labels: kind/bug

#827 Fix version check upgrade logic
  bin/spice/pkg/cli/cmd/version.go
  bin/spice/pkg/context/context.go
Labels: kind/bug

#834 Fix do_get.CommandStatementQuery
  crates/runtime/src/flight/do_get.rs
  crates/runtime/src/flight/flightsql/statement_query.rs
Labels: kind/bug

#835 Make `spice init` work like other tools
  README.md
  bin/spice/pkg/cli/cmd/init.go
Labels: kind/enhancement

#843 Don't downgrade the runtime if the CLI version is lower
  bin/spice/pkg/context/context.go
Labels: kind/enhancement

#845 `spice add` automatically creates spicepod.yaml if it does not exist
  bin/spice/cmd/add.go
  bin/spice/cmd/init.go
  bin/spice/pkg/spicepod/spicepod.go
Labels: kind/enhancement

#842 Add supported data connectors and data stores
  README.md
Labels: kind/documentation

#848 Add `spice status` command
  bin/spice/cmd/status.go
  bin/spice/pkg/api/service.go
  bin/spice/pkg/context/context.go
  bin/spice/pkg/util/out.go
  crates/runtime/src/http/v1.rs
Labels: kind/enhancement

#850 Friendlier DataFusion errors
  Cargo.lock
  crates/flightrepl/Cargo.toml
  crates/flightrepl/src/lib.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/flightsql/statement_query.rs
Labels: kind/bug

#852 Add user facing errors guidelines + don't use debug to display errors
  bin/spiced/src/main.rs
  crates/runtime/src/databackend/duckdb.rs
  crates/runtime/src/databackend/memtable.rs
  crates/runtime/src/dataconnector/flight.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/do_exchange.rs
  crates/runtime/src/flight/do_get.rs
  crates/runtime/src/flight/do_put.rs
  crates/runtime/src/flight/flightsql/get_sql_info.rs
  crates/runtime/src/flight/flightsql/prepared_statement_query.rs
  crates/runtime/src/http/v1.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/podswatcher.rs
  crates/sql_provider_datafusion/src/expr.rs
  docs/dev/user_facing_errors.md
  tools/flightsubscriber/src/main.rs
Labels: kind/bug

#801 Basic FlightSQL data connector
  Cargo.lock
  Cargo.toml
  bin/spiced/src/main.rs
  crates/flight_client/src/lib.rs
  crates/flight_client/src/tls.rs
  crates/flightsql_datafusion/Cargo.toml
  crates/flightsql_datafusion/README.md
  crates/flightsql_datafusion/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/flightsql/prepared_statement_query.rs
  crates/runtime/src/flight/flightsql/statement_query.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#860 Fix `make install-dev`
  bin/spice/pkg/api/client.go
  bin/spice/pkg/registry/spicerack.go
Labels: kind/bug

#862 Fix spice init logic
  bin/spice/cmd/init.go
Labels: kind/bug

#857 use absolute stat path in install script
  install/install.sh
Labels: kind/bug

#858 Add `spice pods` CLI command
  bin/spice/cmd/add.go
  bin/spice/cmd/dataset.go
  bin/spice/cmd/login.go
  bin/spice/cmd/pods.go
  bin/spice/pkg/api/pod.go
  bin/spice/pkg/api/spicepod.go
  bin/spice/pkg/spec/spicepod.go
  bin/spice/pkg/spicepod/spicepod.go
Labels: kind/enhancement

#894 Fix --access-secret
  bin/spice/cmd/login.go
Labels: kind/bug

#903 Update v0.9.1 and v0.10 roadmap
  docs/ROADMAP.md
Labels: kind/documentation

#915 Handle NULL values in Postgres rows
  crates/arrow_sql_gen/src/postgres.rs
Labels: kind/bug

#922 Improvements to end_game.md
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#927 Add additional release step to remove from ROADMAP
  .github/ISSUE_TEMPLATE/end_game.md
  docs/ROADMAP.md
Labels: kind/bug

#972 Gracefully handle connection resets
  crates/runtime/src/dataconnector/spiceai.rs
Labels: kind/bug

#973 Add images to README
  README.md
Labels: kind/documentation

#980 Add v0.10-alpha release notes
  docs/release_notes/v0.10-alpha.md
  docs/release_notes/v0.9.1-alpha.md
Labels: kind/documentation
