Repository spiceai/spiceai, pull requests merged in 2024-07, with the labels that each got.

#1822 feat: Add GraphQL unnesting
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/enhancement

#1830 fix: Allow kind/optimization labels, increase Postgres test timeout
  .github/workflows/enforce-labels.yml
  crates/runtime/tests/postgres/mod.rs
Labels: kind/optimization

#1824 Plumb through the `read_provider` instead of recreating it
  crates/runtime/src/datafusion.rs
  crates/runtime/src/dataupdate.rs
  crates/runtime/src/lib.rs
Labels: kind/bug

#1825 Automatically apply constraints to accelerated table if federated table defines them.
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/internal_table.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement

#1827 Persist metadata for Debezium connector to gracefully survive restarts (DuckDB/Sqlite)
  Cargo.lock
  crates/data_components/src/debezium/change_event.rs
  crates/data_components/src/duckdb.rs
  crates/data_components/src/kafka.rs
  crates/data_components/src/sqlite.rs
  crates/db_connection_pool/src/sqlitepool.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/metadata.rs
  crates/runtime/src/dataaccelerator/metadata/duckdb.rs
  crates/runtime/src/dataaccelerator/metadata/sqlite.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/dataconnector/debezium.rs
Labels: kind/enhancement

#1828 Persist metadata for Debezium connector to gracefully survive restarts (PostgreSQL)
  crates/data_components/src/kafka.rs
  crates/runtime/src/dataaccelerator/metadata.rs
  crates/runtime/src/dataaccelerator/metadata/postgres.rs
Labels: kind/enhancement

#1832 Implement Real-time acceleration updates via Debezium CDC
  .github/workflows/features.yml
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  crates/arrow_sql_gen/Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/README.md
  crates/data_components/src/arrow.rs
  crates/data_components/src/arrow/struct_builder.rs
  crates/data_components/src/cdc.rs
  crates/data_components/src/debezium.rs
  crates/data_components/src/debezium/arrow.rs
  crates/data_components/src/debezium/arrow/changes.rs
  crates/data_components/src/debezium/change_event.rs
  crates/data_components/src/debezium/tests/all_types.json
  crates/data_components/src/debezium/tests/mod.rs
  crates/data_components/src/debezium_kafka.rs
  crates/data_components/src/duckdb.rs
  crates/data_components/src/kafka.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/sqlite.rs
  crates/db_connection_pool/src/sqlitepool.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/metadata.rs
  crates/runtime/src/dataaccelerator/metadata/duckdb.rs
  crates/runtime/src/dataaccelerator/metadata/postgres.rs
  crates/runtime/src/dataaccelerator/metadata/sqlite.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/dataupdate.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/tracing_util.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/odbc/mod.rs
  crates/spice_cloud/src/lib.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#1835 Remove println statement from PG Connector
  crates/db_connection_pool/src/dbconnection/postgresconn.rs
Labels: kind/optimization

#1837 Don't try to "hot reload" Debezium accelerated datasets
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/lib.rs
Labels: kind/bug

#1836 Create `v1/search` that performs vector search.
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/assist.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/search.rs
Labels: kind/enhancement, area/ai

#1829 Align spicepod UX of `embeddings` with `models`
  crates/runtime/src/lib.rs
  crates/runtime/src/model.rs
  crates/spicepod/src/component/embeddings.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement, rust, area/ai

#1840 Add `"cmake-build"` feature to `rdkafka` for windows
  crates/data_components/Cargo.toml
Labels: kind/bug, area/quality

#1839 Add a better error message when trying to configure refresh_mode=changes on a data connector that doesn't support it.
  crates/runtime/src/lib.rs
Labels: kind/bug

#1816 v0.15.0-alpha Release Notes
  docs/release_notes/v0.15.0-alpha.md
Labels: kind/documentation

#1843 Update ROADMAP.md - Remove v0.15.0-alpha roadmap items.
  docs/ROADMAP.md
Labels: kind/documentation

#1845 update helm chart for v0.15.0-alpha
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/documentation

#1844 update cargo.toml and version.txt to 0.15.1-alpha (for next release)
  Cargo.toml
  version.txt
Labels: kind/documentation, endgame

#1846 Fix check for outdated Cargo.lock & update Cargo.lock
  .github/workflows/pr.yml
  Cargo.lock
Labels: kind/bug

#1847 Add Debezium to README
  README.md
Labels: kind/documentation

#1833 Streaming approach to write refresh data to accelerated table
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/dataupdate.rs
  crates/runtime/tests/refresh_retry/mysql.rs
Labels: kind/enhancement

#1850 Streaming refresh: logic to retry on data retrieval errors
  crates/data_components/src/arrow/write.rs
  crates/data_components/src/deltatable/write.rs
  crates/data_components/src/duckdb/write.rs
  crates/data_components/src/flight/write.rs
  crates/data_components/src/postgres/write.rs
  crates/data_components/src/sqlite/write.rs
  crates/data_components/src/util.rs
  crates/data_components/src/util/retriable_error.rs
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
Labels: kind/refactor

#1851 Remove DataUpdateExecutionPlan in favor of StreamingDataUpdateExecutionPlan
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/dataupdate.rs
Labels: kind/refactor

#1831 Various improvements for mistral.rs
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/chat/mistral.rs
Labels: kind/bug, area/ai

#1863 Enable streaming for accelerated tables refresh (common logic)
  crates/data_components/src/arrow/write.rs
  crates/data_components/src/deltatable/write.rs
  crates/data_components/src/duckdb/write.rs
  crates/data_components/src/flight/write.rs
  crates/data_components/src/postgres/write.rs
  crates/data_components/src/sqlite/write.rs
  crates/data_components/src/util.rs
  crates/data_components/src/util/retriable_error.rs
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/dataupdate.rs
  crates/runtime/tests/refresh_retry/mysql.rs
  crates/runtime/tests/refresh_sql/mod.rs
Labels: kind/enhancement

#1849 Use in-memory DB pool for DuckDB functions
  crates/runtime/src/dataconnector/duckdb.rs
Labels: area/data-connectors, kind/refactor

#1865 Generate Spicepod JSON Schema
  .github/workflows/generate_json_schema.yml
  .schema/spicepod.schema.json
  Cargo.lock
  Cargo.toml
  crates/spicepod/Cargo.toml
  crates/spicepod/src/component.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/embeddings.rs
  crates/spicepod/src/component/extension.rs
  crates/spicepod/src/component/model.rs
  crates/spicepod/src/component/params.rs
  crates/spicepod/src/component/runtime.rs
  crates/spicepod/src/component/secrets.rs
  crates/spicepod/src/component/view.rs
  crates/spicepod/src/lib.rs
  crates/spicepod/src/spec.rs
  tools/spicepodschema/Cargo.toml
  tools/spicepodschema/src/main.rs
Labels: kind/enhancement

#1872 Update http param names
  crates/runtime/src/dataconnector/https.rs
Labels: kind/bug, area/data-connectors

#1874 Remove more dead code moved to datafusion-table-providers
  Cargo.lock
  crates/arrow_sql_gen/Cargo.toml
  crates/arrow_sql_gen/src/arrow.rs
  crates/arrow_sql_gen/src/clickhouse.rs
  crates/arrow_sql_gen/src/lib.rs
  crates/arrow_sql_gen/src/mysql.rs
  crates/arrow_sql_gen/src/postgres.rs
  crates/arrow_sql_gen/src/postgres/builder.rs
  crates/arrow_sql_gen/src/postgres/composite.rs
  crates/arrow_sql_gen/src/sqlite.rs
  crates/arrow_sql_gen/src/statement.rs
  crates/data_components/Cargo.toml
  crates/db_connection_pool/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/refresh_retry/mysql.rs
Labels: kind/refactor

#1862 feat: Optimize ODBC for streaming results
  Cargo.lock
  crates/db_connection_pool/Cargo.toml
  crates/db_connection_pool/src/dbconnection/odbcconn.rs
Labels: kind/optimization

#1875 Fix how models uses secrets
  crates/runtime/src/lib.rs
Labels: kind/bug, area/data-connectors

#1876 fix: Add support for varying duplicate columns behavior in GraphQL unnesting
  CONTRIBUTING.md
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/enhancement

#1877 fix: Remove GraphQL duplicate rename support
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/bug

#1882 fix: Remove Overwrite GraphQL duplicates behavior
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/enhancement

#1883 fix: Use tokio mpsc channels for ODBC streaming
  Cargo.lock
  crates/db_connection_pool/Cargo.toml
  crates/db_connection_pool/src/dbconnection/odbcconn.rs
Labels: kind/refactor

#1884 Upgrade table providers to enable DuckDB streaming write
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#1880 Update ROADMAP.md - Add debezium (alpha) to connector list.
  docs/ROADMAP.md
Labels: kind/documentation

#1886 Allow defining user for mysql data connector via secrets
  crates/runtime/src/dataconnector/mysql.rs
Labels: kind/bug

#1890 Update README images
  README.md
Labels: kind/documentation

#1891 Handle deletion vectors for `delta` tables
  Cargo.lock
  Cargo.toml
  crates/data_components/src/delta.rs
Labels: kind/enhancement, area/data-connectors

#1892 Rename `delta` to `delta_lake`
  .github/workflows/features.yml
  bin/spiced/Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/databricks_delta.rs
  crates/data_components/src/delta_lake.rs
  crates/data_components/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/delta_lake.rs
Labels: kind/enhancement, area/data-connectors

#1885 Add where is the AI to the FAQ.
  README.md
Labels: kind/documentation

#1889 update df table providers rev version
  Cargo.lock
  Cargo.toml
  crates/runtime/tests/federation/mysql.rs
Labels: kind/enhancement, area/data-connectors

#1893 Enable other cloud providers for delta_lake integration
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
Labels: kind/enhancement, area/data-connectors

#1894 Add CLI parameters for logging into Databricks with Azure/GCP cloud storage
  bin/spice/cmd/login.go
  bin/spice/pkg/api/auth.go
Labels: kind/enhancement

#1897 Add 'Content-Type' to metrics exporter to be prometheus exposition format compliant
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  crates/runtime/Cargo.toml
Labels: kind/bug

#1898 Update enforce-labels.yml so it accepts depdenabot updates with kind/…
  .github/workflows/enforce-labels.yml
Labels: kind/bug

#1899 List 'delta_lake' as supported data connector
  README.md
Labels: kind/documentation

#1879 Create v0.15.1-alpha.md Release notes.
  docs/release_notes/v0.15.1-alpha.md
Labels: kind/documentation

#1902 release: Update helm 0.15.1-alpha
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#1905 fix: Detect and error on duplicate component names on spiced (re)load
  crates/runtime/src/lib.rs
  crates/spicepod/src/component.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/embeddings.rs
  crates/spicepod/src/component/model.rs
  crates/spicepod/src/component/view.rs
  crates/spicepod/src/lib.rs
Labels: kind/bug

#1908 fix: flaky test - test_refresh_status_change_to_ready
  crates/runtime/src/accelerated_table/refresh.rs
Labels: kind/bug

#1903 Add support for parsing `catalog` from Spicepod.
  crates/spicepod/src/component.rs
  crates/spicepod/src/component/catalog.rs
  crates/spicepod/src/lib.rs
  crates/spicepod/src/spec.rs
Labels: kind/enhancement

#1906 Add catalog component to `Runtime`
  crates/app/src/lib.rs
  crates/runtime/src/component/catalog.rs
  crates/runtime/src/component/mod.rs
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#1913 Adds a RuntimeBuilder and make most items on Runtime private
  bin/spiced/src/lib.rs
  crates/runtime/benches/bench.rs
  crates/runtime/benches/setup/mod.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/src/lib.rs
  crates/runtime/tests/federation/mod.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/graphql/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/odbc/mod.rs
  crates/runtime/tests/refresh_retry/mysql.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/results_cache/mod.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement

#1909 Add separate tagged image with enabled models feature
  .github/workflows/spiced_docker.yml
Labels: kind/enhancement, area/ai

#1932 Add MySQL support for TPC-H test data generation script
  test/tpch/Makefile
  test/tpch/Readme.md
Labels: kind/enhancement

#1924 fix: Expose ODBC task errors if error is before data stream begins
  crates/db_connection_pool/src/dbconnection/odbcconn.rs
Labels: kind/bug

#1934 Use public.ecr.aws/docker/library/{postgres/mysql}:latest for integration test images
  crates/runtime/tests/mysql/common.rs
  crates/runtime/tests/postgres/common.rs
Labels: kind/bug

#1925 Implement `spice.ai` `CatalogProvider`
  Cargo.lock
  bin/spiced/Cargo.toml
  bin/spiced/src/lib.rs
  crates/data_components/src/clickhouse.rs
  crates/data_components/src/databricks_delta.rs
  crates/data_components/src/databricks_spark.rs
  crates/data_components/src/duckdb.rs
  crates/data_components/src/flight.rs
  crates/data_components/src/flightsql.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/mysql.rs
  crates/data_components/src/odbc.rs
  crates/data_components/src/postgres.rs
  crates/data_components/src/snowflake.rs
  crates/data_components/src/spark_connect.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/component/catalog.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/extension.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/status.rs
  crates/spice_cloud/Cargo.toml
  crates/spice_cloud/src/catalog.rs
  crates/spice_cloud/src/lib.rs
  crates/spice_cloud/src/schema.rs
Labels: kind/enhancement

#1926 fix: validate time column and time format when constructing accelerated table refresh
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/datafusion.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#1933 Add support for filtering tables included by a catalog
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/component/catalog.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/extension.rs
  crates/runtime/src/lib.rs
  crates/spice_cloud/Cargo.toml
  crates/spice_cloud/src/catalog.rs
  crates/spice_cloud/src/lib.rs
  crates/spicepod/src/component/catalog.rs
Labels: kind/enhancement

#1940 Add `UnityCatalog` catalog provider
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/databricks_delta.rs
  crates/data_components/src/delta_lake.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/unity_catalog.rs
  crates/data_components/src/unity_catalog/provider.rs
  crates/runtime/src/component/catalog.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/dataconnector/unity_catalog.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/lib.rs
  crates/spicepod/src/component/catalog.rs
Labels: kind/enhancement

#1941 Implement `Databricks` catalog provider
  crates/data_components/src/delta_lake.rs
  crates/data_components/src/unity_catalog.rs
  crates/data_components/src/unity_catalog/provider.rs
  crates/runtime/src/dataconnector/databricks.rs
Labels: kind/enhancement

#1947 Copy `params` into `dataset_params`
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/unity_catalog.rs
Labels: kind/enhancement

#1955 Make integration tests more stable by using logged-in registry during CI
  .github/workflows/integration.yml
  crates/runtime/tests/docker/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/mysql/common.rs
  crates/runtime/tests/postgres/common.rs
Labels: kind/bug

#1956 Add integration test for Spice.ai catalog provider
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/component/catalog.rs
  crates/runtime/tests/catalog/mod.rs
  crates/runtime/tests/integration.rs
Labels: kind/enhancement

#1957 Add GET /v1/catalogs API and catalogs CMD
  Cargo.lock
  bin/spice/cmd/catalogs.go
  bin/spice/pkg/api/catalog.go
  crates/runtime/Cargo.toml
  crates/runtime/src/component/catalog.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/catalogs.rs
  crates/runtime/src/http/v1/mod.rs
Labels: kind/enhancement

#1954 feat: Enable ODBC JoinPushDown with hashed connection string
  Cargo.lock
  crates/db_connection_pool/Cargo.toml
  crates/db_connection_pool/src/odbcpool.rs
Labels: kind/optimization

#1962 Fix bug: arrow acceleration reports zero results during refresh
  crates/data_components/src/arrow/write.rs
Labels: kind/bug

#1964 Revert "fix: validate time column and time format when constructing accelerated table refresh"
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/datafusion.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#1965 fix: Update arrow-odbc to use our fork for pending fixes
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
Labels: kind/bug

#1963 Upgrade to DataFusion 40
  Cargo.lock
  Cargo.toml
  crates/data_components/src/debezium/arrow.rs
  crates/data_components/src/delete.rs
  crates/data_components/src/spark_connect.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/execution_plan/schema_cast.rs
  crates/runtime/tests/federation/mod.rs
Labels: kind/enhancement, kind/dependencies

#1946 Use custom dialect rule for flight federated request
  Cargo.lock
  Cargo.toml
  crates/data_components/src/flight.rs
  crates/data_components/src/flight/federation.rs
  crates/runtime/benches/bench_spicecloud/mod.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/spiceai.rs
Labels: kind/enhancement

#1970 upgrade datafusion federation to have the table rewrite fix for tpch-q9
  Cargo.lock
  Cargo.toml
  crates/runtime/benches/bench_spicecloud/mod.rs
Labels: kind/bug

#1969 Create v0.15.2-alpha.md Release notes
  docs/release_notes/v0.15.2-alpha.md
Labels: kind/documentation

#1973 Fix Unity Catalog API response for Azure Databricks
  crates/data_components/src/unity_catalog.rs
Labels: kind/bug

#1977 Update v0.15.2-alpha.md - update changelist.
  docs/release_notes/v0.15.2-alpha.md
Labels: kind/documentation

#1975 bump helm chart versions to 0.15.2-alpha
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/documentation

#1981 Remove unused Cargo.toml fields
  Cargo.toml
Labels: kind/bug

#1983 Update version to 0.16.0-beta
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/enhancement

#1980 Enable sqlite acceleration testing in E2E
  .github/workflows/e2e_test_ci.yml
Labels: kind/bug

#1982 Revert "Revert "fix: validate time column and time format when constructing accelerated table refresh""
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/datafusion.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#1971 Add DataDog dashboard skeleton
  monitoring/datadog-dashboard.json
Labels: kind/enhancement, area/dashboard

#1988 Format Cargo.toml with taplo
  Cargo.toml
  bin/spiced/Cargo.toml
  crates/data_components/Cargo.toml
  crates/db_connection_pool/Cargo.toml
  crates/llms/Cargo.toml
  crates/runtime/Cargo.toml
  crates/spice_cloud/Cargo.toml
  crates/spicepod/Cargo.toml
  tools/spicepodschema/Cargo.toml
Labels: kind/enhancement, area/quality, kind/optimization

#1990 Spice cli `spice chat` command, to interact with deployed spiced instance in spice.ai cloud
  Makefile
  bin/spice/Makefile
  bin/spice/cmd/cloud.go
  bin/spice/pkg/api/client.go
Labels: kind/enhancement, go

#1992 Remove `Secret` abstraction, remove `file` secret store
  bin/spice/pkg/spec/dataset.go
  crates/data_components/src/databricks_delta.rs
  crates/data_components/src/delta_lake.rs
  crates/data_components/src/unity_catalog.rs
  crates/db_connection_pool/src/clickhousepool.rs
  crates/db_connection_pool/src/dbconnection/odbcconn.rs
  crates/db_connection_pool/src/odbcpool.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/localhost.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/dataconnector/unity_catalog.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/secrets.rs
  crates/runtime/src/secrets/aws_secrets_manager.rs
  crates/runtime/src/secrets/env.rs
  crates/runtime/src/secrets/file.rs
  crates/runtime/src/secrets/keyring.rs
  crates/runtime/src/secrets/kubernetes.rs
  crates/spice_cloud/src/lib.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/secrets.rs
Labels: kind/enhancement

#1994 Remove SecretMap abstraction, use IndexMap for secret stores
  crates/runtime/Cargo.toml
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/unity_catalog.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/secrets.rs
  crates/runtime/src/secrets/aws_secrets_manager.rs
  crates/runtime/src/secrets/env.rs
  crates/runtime/src/secrets/keyring.rs
  crates/runtime/src/secrets/kubernetes.rs
Labels: kind/enhancement

#1996 Support loading multiple secrets in the Spicepod
  crates/app/src/lib.rs
  crates/runtime/benches/setup/mod.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/secrets.rs
  crates/runtime/tests/catalog/mod.rs
  crates/runtime/tests/federation/mod.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/results_cache/mod.rs
  crates/spicepod/src/component.rs
  crates/spicepod/src/component/secret.rs
  crates/spicepod/src/lib.rs
  crates/spicepod/src/spec.rs
Labels: kind/enhancement

#1998 Use platform api `/v1/chat/completions` with streaming in `spice chat` cli command
  bin/spice/cmd/cloud.go
Labels: kind/enhancement, area/cli

#2001 update spiceai datafusion version to fix tpch queries
  Cargo.lock
  Cargo.toml
  crates/runtime/benches/bench_spicecloud/mod.rs
Labels: kind/bug

#2003 Install a rustls default CryptoProvider
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  bin/spiced/src/main.rs
Labels: kind/bug

#2002 Roadmap update July, 2024
  docs/ROADMAP.md
Labels: kind/documentation

#2005 Support loading from `.env` files
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/secrets.rs
  crates/runtime/src/secrets/stores/aws_secrets_manager.rs
  crates/runtime/src/secrets/stores/env.rs
  crates/runtime/src/secrets/stores/keyring.rs
  crates/runtime/src/secrets/stores/kubernetes.rs
Labels: kind/enhancement

#2007 Add local spice runtime support for `spice chat` command, add `--model` flag
  bin/spice/cmd/cloud.go
Labels: kind/enhancement, area/cli

#2010 Switch order to look for `SPICE_` prefixed keys first
  crates/runtime/src/secrets/stores/aws_secrets_manager.rs
  crates/runtime/src/secrets/stores/env.rs
  crates/runtime/src/secrets/stores/keyring.rs
  crates/runtime/src/secrets/stores/kubernetes.rs
Labels: kind/enhancement

#2008 feat: Add sql_dialect parameter for overriding ODBC dialect
  crates/runtime/src/dataconnector/odbc.rs
Labels: kind/enhancement

#2013 Autoload secrets that Data Connectors have indicated are needed
  Cargo.lock
  Cargo.toml
  crates/db_connection_pool/src/odbcpool.rs
  crates/db_connection_pool/src/snowflakepool.rs
  crates/runtime/src/dataaccelerator/metadata/postgres.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/localhost.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/dataconnector/unity_catalog.rs
  crates/runtime/src/lib.rs
  crates/runtime/tests/postgres/common.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement, breaking change

#1930 fix: GraphQL Data Connector - Change json path to json pointer
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/tests/graphql/mod.rs
Labels: kind/bug

#2017 Inject secrets into acceleration params
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/query/query_history.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/spice_metrics.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement

#2016 Update ROADMAP.md to include MySQL data connector in Beta
  docs/ROADMAP.md
Labels: kind/documentation

#2021 upgrade spiceai datafusion to fix tpch simple query 3
  Cargo.lock
  Cargo.toml
  crates/runtime/benches/bench_spicecloud/mod.rs
Labels: kind/bug

#1997 feat: Autodetect ODBC dialect
  crates/data_components/src/odbc.rs
  crates/runtime/src/dataconnector/odbc.rs
Labels: kind/enhancement

#2020 feat: Use CustomDialectBuilder for Databricks ODBC dialect
  crates/runtime/src/dataconnector/odbc.rs
Labels: kind/enhancement

#2026 Switch the secret replacement syntax to `${ <secret>:<key> }`
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/secrets.rs
  crates/runtime/src/secrets/lexer.rs
Labels: kind/enhancement

#2024 fix spiceai connector lengthy error
  crates/data_components/src/flight.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/spiceai.rs
Labels: kind/bug

#2031 Log parameter key instead of value when injecting secret
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/secrets.rs
Labels: kind/bug

#2032 Update benchmark yml to support postgres benchmark test
  .github/workflows/benchmarks.yml
Labels: kind/enhancement

#2028 Separate data connector parameters into `connector` and `runtime` categories
  crates/data_components/src/databricks_delta.rs
  crates/data_components/src/unity_catalog.rs
  crates/db_connection_pool/src/clickhousepool.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/localhost.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/dataconnector/unity_catalog.rs
Labels: kind/enhancement

#2029 Fix spice chat prompt and spinner
  bin/spice/cmd/cloud.go
Labels: kind/enhancement, area/cli

#2036 Build spiced with odbc for release binaries
  .github/workflows/build_and_release.yml
Labels: kind/enhancement, area/data-connectors

#2035 MySQL timestamp, int64 casting, date part extraction and intervals support
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2034 updating default http and metrics ports
  .github/actions/verify-dataset/action.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_release_install.yml
  Dockerfile
  Makefile
  README.md
  bin/spice/cmd/cloud.go
  bin/spice/cmd/spice.go
  bin/spice/pkg/context/context.go
  crates/flightrepl/src/lib.rs
  crates/runtime/src/config.rs
  deploy/chart/templates/podmonitor.yaml
  deploy/chart/templates/spiceai.yaml
Labels: kind/enhancement

#2041 enable spark connect federated query
  crates/data_components/src/spark_connect.rs
  crates/data_components/src/spark_connect/federation.rs
Labels: kind/enhancement

#2037 fix: Use MySQL Interval for Databricks ODBC
  crates/runtime/src/dataconnector/odbc.rs
Labels: kind/bug

#2045 Re-enable test_quickstart_dremio E2E test
  .github/workflows/e2e_test_ci.yml
Labels: kind/enhancement

#2046 Fix ODBC build for release binaries
  .github/workflows/build_and_release.yml
  bin/spiced/Makefile
Labels: kind/bug

#2044 chore: Remove unused dependencies
  Cargo.lock
  bin/spiced/Cargo.toml
  crates/app/Cargo.toml
  crates/arrow_sql_gen/Cargo.toml
  crates/data_components/Cargo.toml
  crates/db_connection_pool/Cargo.toml
  crates/flight_client/Cargo.toml
  crates/flightrepl/Cargo.toml
  crates/llms/Cargo.toml
  crates/runtime/Cargo.toml
  crates/spice_cloud/Cargo.toml
Labels: kind/optimization

#2051 fix: Change version to alpha breaking
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/bug

#2052 Add connector prefix for `dataset configure` endpoint param
  bin/spice/cmd/dataset.go
Labels: kind/bug

#2050 Fix unprefixed runtime parameters
  .github/workflows/e2e_test_ci.yml
  crates/data_components/src/databricks_spark.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/tests/graphql/mod.rs
  crates/runtime/tests/results_cache/mod.rs
Labels: kind/bug

#2054 Fix make install-with-models
  bin/spiced/Makefile
Labels: kind/bug

#2055 ignore empty constraints when creating accelerated table
  crates/runtime/src/dataaccelerator.rs
Labels: kind/bug

#2027 release notes for v0.16.0-alpha
  docs/release_notes/v0.15.2-alpha.md
  docs/release_notes/v0.16.0-alpha.md
Labels: kind/documentation

#2057 update helm chart versions for v0.16.0-alpha
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/documentation

#2063 fix: Install `unixodbc` for E2E test release installation
  .github/workflows/e2e_test_release_install.yml
Labels: kind/bug

#2065 update next release to 0.16.1-beta
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/enhancement

#2068 update version to 0.17.0-beta
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/documentation

#2066 Update ROADMAP.md - removing delivered features and updating Beta timeline.
  docs/ROADMAP.md
Labels: kind/documentation

#2042 make bench works for more connectors
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_spark/mod.rs
  crates/runtime/benches/bench_spicecloud/mod.rs
  crates/runtime/benches/queries/tpch_q1.sql
  crates/runtime/benches/queries/tpch_q10.sql
  crates/runtime/benches/queries/tpch_q11.sql
  crates/runtime/benches/queries/tpch_q12.sql
  crates/runtime/benches/queries/tpch_q13.sql
  crates/runtime/benches/queries/tpch_q14.sql
  crates/runtime/benches/queries/tpch_q16.sql
  crates/runtime/benches/queries/tpch_q17.sql
  crates/runtime/benches/queries/tpch_q18.sql
  crates/runtime/benches/queries/tpch_q19.sql
  crates/runtime/benches/queries/tpch_q2.sql
  crates/runtime/benches/queries/tpch_q20.sql
  crates/runtime/benches/queries/tpch_q21.sql
  crates/runtime/benches/queries/tpch_q22.sql
  crates/runtime/benches/queries/tpch_q3.sql
  crates/runtime/benches/queries/tpch_q4.sql
  crates/runtime/benches/queries/tpch_q5.sql
  crates/runtime/benches/queries/tpch_q6.sql
  crates/runtime/benches/queries/tpch_q7.sql
  crates/runtime/benches/queries/tpch_q8.sql
  crates/runtime/benches/queries/tpch_q9.sql
  crates/runtime/benches/queries/tpch_simple_q1.sql
  crates/runtime/benches/queries/tpch_simple_q2.sql
  crates/runtime/benches/queries/tpch_simple_q3.sql
  crates/runtime/benches/queries/tpch_simple_q4.sql
  crates/runtime/benches/queries/tpch_simple_q5.sql
  crates/runtime/benches/results/mod.rs
  crates/runtime/benches/setup/mod.rs
Labels: kind/enhancement

#2069 enable spark benchmark
  .github/workflows/benchmarks.yml
Labels: kind/enhancement

#2072 Make the `json_pointer` param optional for the GraphQL connector
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/bug

#2073 Fix secrets init to not bail if a secret store can't load
  crates/runtime/src/secrets.rs
Labels: kind/bug

#2059 Update end_game.md
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#2058 Fix time predicate with timezone info casting for Dremio
  crates/runtime/src/dataconnector/dremio.rs
Labels: kind/bug

#2048 Add benchmark tests for MySQL data connector
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_mysql/mod.rs
  crates/runtime/benches/setup/mod.rs
Labels: kind/enhancement

#2084 fix: Add Athena dialect for ODBC
  crates/runtime/src/dataconnector/odbc.rs
Labels: kind/enhancement

#2070 Workflow to build MySQL image with TPCH benchmark data
  .github/workflows/spice_mysql_bench_docker.yml
  test/tpch/Makefile
  test/tpch/mysql-bench/Dockerfile
Labels: kind/enhancement

#2086 Fix secrets replacement within connection strings
  crates/runtime/src/secrets/lexer.rs
Labels: kind/bug

#2088 fix: Correctly prefix missing required parameters
  crates/runtime/src/dataconnector.rs
Labels: kind/bug

#2009 Add Postgres Data Connector TPCH Benchmark Tests
  Makefile
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_postgres/mod.rs
  crates/runtime/benches/bench_spicecloud/mod.rs
  crates/runtime/benches/results/mod.rs
  crates/runtime/benches/setup/mod.rs
Labels: kind/enhancement

#2095 Add cfg flag to properly support build w / wo feature in benchmark tests
  crates/runtime/benches/setup/mod.rs
Labels: kind/bug

#2093 Move Prometheus metrics server to runtime
  Cargo.lock
  bin/spiced/src/lib.rs
  bin/spiced/src/main.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/builder.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/metrics_server/mod.rs
  crates/runtime/src/spice_metrics.rs
Labels: kind/enhancement

#2103 fix: Remove unixodbc from test release install
  .github/workflows/e2e_test_release_install.yml
Labels: kind/refactor

#2102 Upgrade `delta_kernel` to 0.2.0
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/delta_lake.rs
Labels: kind/dependencies

#2104 Allow DuckDB to load extensions in Docker
  Dockerfile
Labels: kind/bug

#2105 Spawn the metrics server in the background.
  crates/runtime/src/lib.rs
  crates/runtime/src/metrics_server/mod.rs
Labels: kind/bug

#2107 fix: suffix delta kernel table location with slash if none
  crates/data_components/src/delta_lake.rs
Labels: kind/bug

#2091 Decision Record: Default HTTP and GRPC ports for Spice.ai OSS
  docs/decisions/002-default-ports.md
Labels: kind/documentation

#2108 Enable TLS for metrics endpoint
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  bin/spiced/src/lib.rs
  crates/llms/src/embeddings/candle/mod.rs
  crates/model_components/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/builder.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/embeddings/array_distance.rs
  crates/runtime/src/flight/flightsql/get_sql_info.rs
  crates/runtime/src/http/v1/assist.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/metrics_server/mod.rs
Labels: kind/enhancement

#2112 Use Postgres container for tpch bench
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench_postgres/mod.rs
Labels: kind/enhancement
