Repository spiceai/spiceai, pull requests merged in 2024-08, with the labels that each got.

#2158 Improve MySql schema extraction and add InList and ScalarFunction expr support
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2165 Fix issue with use of `EmbeddingConnector`
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/lib.rs
Labels: kind/bug, area/ai

#2168 add client timeout for all object store providers
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/object_store_registry.rs
  crates/runtime/src/objectstore/ftp.rs
  crates/runtime/src/objectstore/sftp.rs
Labels: kind/bug

#2172 Benchmark: include sqlite acceleration and enable more tests
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_s3/mod.rs
Labels: kind/bug

#2171 feat: Use datafusion SQLite streaming updates
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#2173 Benchmark: include arrow acceleration and enable more tests (tpch_q22)
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_s3/mod.rs
Labels: kind/bug

#2167 Localhost -> Sink; Fix Sink connector to not require schema via `CREATE TABLE...` and infer on first write
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/sink.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/tracing_util.rs
Labels: kind/enhancement

#2175 Fix misspelled acceleration engine name in benchmark tests
  crates/runtime/benches/bench.rs
Labels: kind/bug

#2178 update spark bench catalog
  crates/runtime/benches/setup/mod.rs
Labels: kind/bug

#2179 Benchmark: Discard first measurement of sql query, disable result caching
  crates/runtime/benches/bench.rs
Labels: kind/optimization

#2177 clear message when invalid params configured for accelerator
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/arrow.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/postgres.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/parameters.rs
Labels: kind/bug

#2169 Implement the Flight `GetSchema` API
  crates/data_components/src/flight.rs
  crates/flight_client/src/lib.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/get_schema.rs
Labels: kind/enhancement

#2181 Support AppendStream for SpiceAI data connector
  crates/data_components/src/cdc.rs
  crates/data_components/src/flight.rs
  crates/flight_client/src/lib.rs
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/flight/do_exchange.rs
  crates/runtime/src/flight/get_schema.rs
Labels: kind/enhancement

#2184 Support MySQL BINARY, VARBINARY, Postgres BYTEA and improve MySQL auth error message
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2183 Benchmark: use SF1 for MySQL TPC-H tests
  .github/workflows/benchmarks.yml
  .github/workflows/spice_mysql_bench_docker.yml
  test/tpch/Makefile
  test/tpch/mysql-bench/Dockerfile
  test/tpch/mysql-bench/conf.d/my.cnf
  test/tpch/tpch_index.sql
Labels: kind/enhancement

#2193 fix windows build broken by adding tokio unix signal
  crates/util/src/lib.rs
Labels: kind/bug

#2194 Adds TLS support for `flightsubscriber`/`flightpublisher` tools
  tools/flightpublisher/src/main.rs
  tools/flightsubscriber/src/main.rs
Labels: kind/enhancement

#2195 Update README output samples
  README.md
Labels: kind/documentation

#2192 Release Notes: `v0.17.1-beta`
  docs/release_notes/v0.17.1-beta.md
Labels: kind/documentation

#2200 Pin actions/upload-artifact to v4.3.4
  .github/workflows/build_and_release.yml
Labels: kind/bug

#2203 Update to next release version, `v0.17.2-beta`
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/enhancement

#2201 add accelerator beta criteria
  docs/criteria/accelerator-stages.md
Labels: kind/documentation

#2205 update helm chart to 0.17.1-beta
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#2206 add dockerignore to avoid copy target and test folder
  .dockerignore
Labels: kind/optimization

#2208 add client timeout for deltalake connector
  crates/data_components/src/delta_lake.rs
  crates/runtime/src/dataconnector/delta_lake.rs
Labels: kind/optimization

#2223 Upgrade tonic and opentelemetry-proto
  Cargo.lock
  Cargo.toml
  crates/flightrepl/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/component/dataset/acceleration/constraints.rs
  crates/runtime/src/embeddings/execution_plan.rs
  crates/runtime/src/http/v1/status.rs
  crates/runtime/src/opentelemetry.rs
  crates/runtime/tests/tls/mod.rs
  tools/flightpublisher/Cargo.toml
Labels: kind/enhancement

#2196 Add index and resource tuning for postgres ghcr image to support postgres benchmark in sf1
  .github/workflows/benchmarks.yml
  .github/workflows/spice_postgres_bench_docker.yml
  test/tpch/Makefile
  test/tpch/postgres-bench/postgres-entrypoint.sh
Labels: kind/enhancement

#2176 Remove embedding columns from `retrieved_primary_keys` in v1/search
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/assist.rs
  crates/runtime/src/http/v1/search.rs
Labels: kind/bug

#2230 use file as db_path_param as the param prefix is trimmed
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
Labels: kind/bug

#2231 use file for sqlite db path param
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
Labels: kind/bug

#2228 docs: Clarify the global requirement for local_infile when loading TPCH
  test/tpch/Readme.md
Labels: kind/documentation

#2232 Revert pinning actions/upload-artifact@v4
  .github/workflows/build_and_release.yml
Labels: kind/bug

#2207 Runtime tools to chat models
  crates/llms/src/chat/mod.rs
  crates/llms/src/embeddings/candle/mod.rs
  crates/llms/src/lib.rs
  crates/llms/src/openai/mod.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model.rs
  crates/runtime/src/tool_use.rs
Labels: kind/enhancement, area/ai

#2191 Create `runtime.task_history` table for queries, and embeddings
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/query_history.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/execution_plan.rs
  crates/runtime/src/embeddings/mod.rs
  crates/runtime/src/embeddings/table.rs
  crates/runtime/src/embeddings/task.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/assist.rs
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/http/v1/embeddings.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/embed.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/task_history.rs
Labels: kind/enhancement, area/ai

#2238 chore: Update Databricks ODBC Bench to use TPCH SF1
  crates/runtime/benches/bench_odbc_databricks/mod.rs
Labels: kind/refactor

#2240 Replace `metrics-rs` with OpenTelemetry Metrics
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  bin/spiced/src/lib.rs
  bin/spiced/src/main.rs
  crates/cache/Cargo.toml
  crates/cache/src/lib.rs
  crates/cache/src/metrics.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/metrics.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/metrics.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/src/execution_plan/fallback_on_zero_results.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/actions.rs
  crates/runtime/src/flight/do_exchange.rs
  crates/runtime/src/flight/do_get.rs
  crates/runtime/src/flight/do_put.rs
  crates/runtime/src/flight/flightsql/get_catalogs.rs
  crates/runtime/src/flight/flightsql/get_primary_keys.rs
  crates/runtime/src/flight/flightsql/get_schemas.rs
  crates/runtime/src/flight/flightsql/get_sql_info.rs
  crates/runtime/src/flight/flightsql/get_table_types.rs
  crates/runtime/src/flight/flightsql/get_tables.rs
  crates/runtime/src/flight/flightsql/prepared_statement_query.rs
  crates/runtime/src/flight/flightsql/statement_query.rs
  crates/runtime/src/flight/handshake.rs
  crates/runtime/src/flight/metrics.rs
  crates/runtime/src/http.rs
  crates/runtime/src/http/metrics.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/metrics.rs
  crates/runtime/src/metrics_server/mod.rs
  crates/runtime/src/spice_metrics.rs
  crates/runtime/src/status.rs
  crates/runtime/src/timing.rs
  crates/runtime/tests/tls/mod.rs
  monitoring/grafana-dashboard.json
Labels: kind/enhancement, area/observability

#2249 fix: Remove dead code
  crates/runtime/src/dataconnector/sink.rs
Labels: kind/refactor

#2250 Improve tool quality and add vector search tool
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/tool_use.rs
Labels: kind/enhancement

#2253 fix missing partition cols in delta lake
  Makefile
  crates/data_components/src/delta_lake.rs
  crates/runtime/tests/delta_lake/mod.rs
  crates/runtime/tests/integration.rs
  test/assets/delta-lake-nation-with-partitionkey.zip
Labels: kind/bug

#2254 download file from remote for delta testing
  crates/data_components/src/delta_lake.rs
  crates/runtime/tests/delta_lake/mod.rs
  test/assets/delta-lake-nation-with-partitionkey.zip
Labels: kind/bug

#2242 feat: Set SQLite DB path to .spice/data
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#2256 Jack/tools quality
  crates/llms/src/chat/mistral.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/tool_use.rs
Labels: kind/optimization

#2255 Support tools for chat completions in streaming mode
  bin/spice/cmd/cloud.go
  crates/llms/src/chat/candle.rs
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/llms/src/openai/mod.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement

#2261 Load component `description` field from spicepod.yaml and include in LLM context
  .schema/spicepod.schema.json
  crates/runtime/src/model/tool_use.rs
  crates/spicepod/src/component/catalog.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/model.rs
  crates/spicepod/src/component/secret.rs
  crates/spicepod/src/component/view.rs
Labels: kind/enhancement

#2251 Add parameter for `connection_pool_size` in the Postgres Data Connector
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataconnector/postgres.rs
Labels: kind/bug

#2257 Track nested spans into Zipkin
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  bin/spiced/src/lib.rs
  bin/spiced/src/main.rs
  bin/spiced/src/tls.rs
  bin/spiced/src/tracing.rs
  crates/data_components/Cargo.toml
  crates/flightrepl/Cargo.toml
  crates/llms/Cargo.toml
  crates/llms/src/chat/mod.rs
  crates/llms/src/openai/mod.rs
  crates/model_components/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/query_history.rs
  crates/runtime/src/embeddings/task.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/assist.rs
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/http/v1/embeddings.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/task_history.rs
  crates/spice_cloud/Cargo.toml
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#2263 Add primary keys to response of `DocumentSimilarityTool`
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement

#2265 Emit `task_history` traces from tracing OTel exporter
  bin/spiced/src/lib.rs
  bin/spiced/src/tracing.rs
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/task_history.rs
  crates/runtime/src/task_history/otel_exporter.rs
Labels: kind/enhancement

#2267 Add OTel multiplexer to enable zipkin
  Cargo.lock
  bin/spiced/Cargo.toml
  bin/spiced/src/tracing.rs
Labels: kind/enhancement

#2268 Enable SQL tracking properly
  crates/runtime/src/datafusion/query.rs
Labels: kind/enhancement

#2262 run queries bash script
  test/scripts/run-queries.bash
  test/scripts/setup-semi-structure-spicepod.bash
  test/scripts/setup-tpc-spicepod.bash
Labels: kind/enhancement

#2274 Filter out sql_query tasks related to the runtime tables
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/task_history/otel_exporter.rs
Labels: kind/enhancement

#2275 Add output for `ai_chat`, `ai_completion` and `vector_search`
  crates/runtime/src/embeddings/task.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement

#2276 Remove the ListTablesTool
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement

#2278 Return full vector search response
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/enhancement

#2282 Load components metadata into models scope
  .schema/spicepod.schema.json
  crates/runtime/src/model/tool_use.rs
  crates/spicepod/src/component/catalog.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/model.rs
  crates/spicepod/src/component/view.rs
Labels: kind/enhancement

#2284 Keep `has_metadata_table: boolean` dataset field without rename
  .schema/spicepod.schema.json
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#2277 Run benchmark test on schedule
  .github/workflows/benchmarks.yml
Labels: kind/enhancement

#2283 feat: Add a reference to originating App for a Dataset
  bin/spiced/src/lib.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/catalogs.rs
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/http/v1/inference.rs
  crates/runtime/src/http/v1/models.rs
  crates/runtime/src/http/v1/spicepods.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#2286 Tool use & telemetry productionisation.
  .schema/spicepod.schema.json
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  bin/spiced/src/lib.rs
  bin/spiced/src/main.rs
  bin/spiced/src/tls.rs
  bin/spiced/src/tracing.rs
  crates/data_components/Cargo.toml
  crates/flightrepl/Cargo.toml
  crates/llms/Cargo.toml
  crates/llms/src/chat/mod.rs
  crates/llms/src/openai/mod.rs
  crates/model_components/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/query_history.rs
  crates/runtime/src/embeddings/task.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/assist.rs
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/http/v1/embeddings.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/task_history.rs
  crates/runtime/src/task_history/otel_exporter.rs
  crates/spice_cloud/Cargo.toml
  crates/spicepod/src/component/catalog.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/model.rs
  crates/spicepod/src/component/runtime.rs
  crates/spicepod/src/component/view.rs
Labels: kind/enhancement, area/ai

#2288 Fix cron in benchmarks.yml
  .github/workflows/benchmarks.yml
Labels: kind/bug

#2290 Upgrade to DataFusion v41
  Cargo.lock
  Cargo.toml
  crates/data_components/src/arrow.rs
  crates/data_components/src/arrow/write.rs
  crates/data_components/src/debezium_kafka.rs
  crates/data_components/src/delete.rs
  crates/data_components/src/delta_lake.rs
  crates/data_components/src/duckdb.rs
  crates/data_components/src/flight.rs
  crates/data_components/src/flight/stream.rs
  crates/data_components/src/flight/write.rs
  crates/data_components/src/flightsql.rs
  crates/data_components/src/object/metadata.rs
  crates/data_components/src/object/text.rs
  crates/data_components/src/postgres.rs
  crates/data_components/src/spark_connect.rs
  crates/data_components/src/sqlite.rs
  crates/data_components/src/unity_catalog/provider.rs
  crates/db_connection_pool/src/dbconnection/clickhouseconn.rs
  crates/model_components/Cargo.toml
  crates/model_components/src/modelruntime/tract.rs
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/dataaccelerator/arrow.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/postgres.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/sink.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/refresh_sql.rs
  crates/runtime/src/datafusion/schema.rs
  crates/runtime/src/datafusion/udf.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/src/embeddings/table.rs
  crates/runtime/src/execution_plan/mod.rs
  crates/runtime/src/execution_plan/schema_cast.rs
  crates/runtime/src/lib.rs
  crates/runtime/tests/federation/mod.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/graphql/mod.rs
  crates/runtime/tests/integration.rs
  crates/spice_cloud/src/catalog.rs
  crates/spice_cloud/src/schema.rs
  crates/util/Cargo.toml
  tools/spicepodschema/Cargo.toml
Labels: kind/enhancement

#2292 Chat completions adjustments and fixes
  Cargo.lock
  Cargo.toml
  bin/spice/pkg/github/asset.go
  crates/runtime/src/model/tool_use.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement

#2295 Define the new metrics Arrow schema based on Open Telemetry
  Cargo.lock
  Cargo.toml
  crates/otel-arrow/Cargo.toml
  crates/otel-arrow/src/lib.rs
  crates/otel-arrow/src/schema.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/builder.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/spice_metrics.rs
Labels: kind/enhancement

#2302 Calculate summary metrics from histograms for Prometheus endpoint
  crates/runtime/src/metrics_server/mod.rs
  monitoring/datadog-dashboard.json
  monitoring/grafana-dashboard.json
Labels: kind/enhancement

#2304 Add back Spice DF runtime_env during SessionContext construction
  crates/runtime/src/datafusion.rs
Labels: kind/bug

#2305 Add integration test for S3 data connector
  crates/runtime/tests/integration.rs
  crates/runtime/tests/s3/mod.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/bug

#2306 Fix `secrets.inject_secrets` when secret not found.
  crates/runtime/src/secrets.rs
Labels: kind/bug

#2299 Intra-table federation query on duckdb accelerated table
  Cargo.lock
  Cargo.toml
  crates/data_components/src/delete.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/poly.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/federation.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/tests/refresh_retry/mysql.rs
  crates/runtime/tests/refresh_sql/mod.rs
Labels: kind/enhancement

#2309 Postgres federation on acceleration
  crates/runtime/src/accelerated_table/federation.rs
  crates/runtime/src/dataaccelerator/postgres.rs
Labels: kind/enhancement

#2308 sqlite intra table federation on acceleration
  crates/runtime/src/dataaccelerator/sqlite.rs
Labels: kind/enhancement

#2293 feat: Add `DataAccelerator::init()` for SQLite acceleration federation
  .github/workflows/e2e_test_ci.yml
  Cargo.lock
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/arrow.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/postgres.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/lib.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement

#2310 Initial framework for collecting anonymous usage telemetry
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  bin/spiced/src/lib.rs
  crates/data_components/src/flight.rs
  crates/flight_client/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/http/v1/status.rs
  crates/spicepod/src/component/runtime.rs
  crates/telemetry/Cargo.toml
  crates/telemetry/src/anonymous.rs
  crates/telemetry/src/exporter.rs
  crates/telemetry/src/lib.rs
  crates/telemetry/src/meter.rs
Labels: kind/enhancement

#2316 Add gRPC action to trigger accelerated dataset refresh
  crates/runtime/src/flight/actions.rs
  crates/runtime/src/flight/actions/datasets.rs
Labels: kind/enhancement

#2312 Remove `v1/assist`
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/assist.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/search.rs
Labels: kind/enhancement

#2329 bump table provider version to set the correct dialect for postgres writer
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2331 Send telemetry on startup
  crates/otel-arrow/src/converter.rs
  crates/otel-arrow/src/exporter.rs
  crates/otel-arrow/src/lib.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/telemetry/src/anonymous.rs
  crates/telemetry/src/exporter.rs
  crates/telemetry/src/meter.rs
Labels: kind/enhancement, area/observability

#2332 Calculate resource IDs for telemetry
  Cargo.lock
  bin/spiced/src/lib.rs
  crates/telemetry/Cargo.toml
  crates/telemetry/src/anonymous.rs
Labels: kind/enhancement

#2328 Refactor `v1/search`: include WHERE condition, allow extra columns in projection.
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement

#2330 Add integration test for gRPC dataset refresh action
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/actions.rs
  crates/runtime/src/lib.rs
  crates/runtime/tests/grpc_api/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/tls/mod.rs
Labels: kind/enhancement

#2337 Propagate errors through all `task_history` nested spans
  crates/llms/src/chat/mod.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/bug

#2338 Improve tools
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement, area/ai

#2336 update duckdb rs version to support more types: interval/duration/etc
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#2335 feat: Add DuckDB accelerator init, attach databases for federation
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
Labels: kind/enhancement

#2333 Add query telemetry metrics
  crates/llms/src/openai/mod.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/builder.rs
  crates/runtime/src/datafusion/query/query_history.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/embeddings/task.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/do_get.rs
  crates/runtime/src/flight/flightsql/prepared_statement_query.rs
  crates/runtime/src/flight/flightsql/statement_query.rs
  crates/runtime/src/flight/get_flight_info.rs
  crates/runtime/src/flight/get_schema.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/task_history/otel_exporter.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/catalog/mod.rs
  crates/runtime/tests/s3/mod.rs
  crates/telemetry/src/lib.rs
Labels: kind/enhancement

#2342 Add system prompts for LLMs; system prompts for tool using models.
  crates/llms/src/openai/mod.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement, area/ai

#2347 Fix benchmark test to keep running when there's failed queries
  crates/runtime/benches/bench_delta/mod.rs
  crates/runtime/benches/bench_mysql/mod.rs
  crates/runtime/benches/bench_odbc_athena/mod.rs
  crates/runtime/benches/bench_odbc_databricks/mod.rs
  crates/runtime/benches/bench_postgres/mod.rs
  crates/runtime/benches/bench_s3/mod.rs
  crates/runtime/benches/bench_spark/mod.rs
  crates/runtime/benches/bench_spicecloud/mod.rs
Labels: kind/bug

#2344 Tools as a spicepod first class citizen.
  crates/app/src/lib.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/metrics.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/status.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
  crates/runtime/src/tools/builtin/list_datasets.rs
  crates/runtime/src/tools/builtin/mod.rs
  crates/runtime/src/tools/builtin/sql.rs
  crates/runtime/src/tools/builtin/table_schema.rs
  crates/runtime/src/tools/factory/builtin.rs
  crates/runtime/src/tools/factory/mod.rs
  crates/runtime/src/tools/mod.rs
  crates/runtime/src/tools/options.rs
  crates/spicepod/src/component.rs
  crates/spicepod/src/component/tool.rs
  crates/spicepod/src/lib.rs
  crates/spicepod/src/spec.rs
Labels: kind/enhancement, area/ai

#2343 Add `bytes_processed` telemetry metric
  Cargo.lock
  Cargo.toml
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/extension/bytes_processed.rs
  crates/runtime/src/datafusion/extension/mod.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/delta_lake/mod.rs
  crates/runtime/tests/federation/mod.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/graphql/mod.rs
  crates/runtime/tests/postgres/mod.rs
  crates/telemetry/src/lib.rs
Labels: kind/enhancement

#2356 fix misaligned columns from delta lake
  crates/data_components/src/delta_lake.rs
  crates/runtime/tests/delta_lake/mod.rs
Labels: kind/bug

#2352 Emit telemetry metrics to `runtime.metrics`/Prometheus as well
  crates/runtime/src/datafusion/extension/bytes_processed.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/metrics.rs
Labels: kind/enhancement

#2354 Use UTC timezone for telemetry timestamps
  crates/otel-arrow/src/converter.rs
  crates/otel-arrow/src/schema.rs
Labels: kind/enhancement

#2353 Add dataset details to tool using LLMs; early check tables in vector search
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/tools/builtin/list_datasets.rs
Labels: kind/enhancement, area/ai

#2360 Bump datafusion-federation/datafusion-table-providers dependencies
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#2371 fix: Disable DuckDB and SQLite federation
  .github/workflows/benchmarks.yml
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2367 Fix system prompt in ToolUsingChat, fix builtin registration
  crates/runtime/src/lib.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
  crates/runtime/src/tools/builtin/list_datasets.rs
  crates/runtime/src/tools/builtin/mod.rs
  crates/runtime/src/tools/builtin/sql.rs
  crates/runtime/src/tools/builtin/table_schema.rs
Labels: kind/bug, area/ai

#2372 fix: Use --profile release for benchmarks
  .github/workflows/benchmarks.yml
Labels: kind/bug

#2366 nql parameter 'use' -> 'model'
  crates/flightrepl/src/lib.rs
  crates/runtime/src/http/v1/nsql.rs
Labels: kind/enhancement, area/ai

#2375 Bump datafusion-federation/datafusion-table-providers dependencies
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2373 Release notes for v0.17.2-beta
  docs/release_notes/v0.17.2-beta.md
Labels: kind/documentation

#2378 Make E2E tests pass and add trace msg when runtime installation is required
  .github/actions/install-spice/action.yml
  .github/workflows/e2e_test_ci.yml
  bin/spice/pkg/runtime/runtime.go
Labels: kind/bug

#2382 Add datafusion-functions-json UDFs
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/datafusion.rs
Labels: kind/enhancement

#2386 Bump `datafusion-table-providers` to fix DuckDB acceleration
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2387 Enabled DuckDB file acceleration e2e test
  .github/workflows/e2e_test_ci.yml
Labels: kind/enhancement

#2365 Add a basic Github Connector
  crates/data_components/Cargo.toml
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/graphql/mod.rs
  crates/data_components/src/graphql/provider.rs
  crates/data_components/src/lib.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/github.rs
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/enhancement, area/data-accelerators

#2389 task: Re-enable federation
  crates/data_components/Cargo.toml
  crates/db_connection_pool/Cargo.toml
Labels: kind/enhancement

#2393 GitHub Data Connector `files` support (basic fields)
  crates/data_components/src/github.rs
  crates/data_components/src/lib.rs
  crates/runtime/src/dataconnector/github.rs
Labels: kind/enhancement

#2395 Add a `--force` flag to `spice install` to force it to install the latest released version
  bin/spice/cmd/install.go
  bin/spice/pkg/github/runtime_release.go
  bin/spice/pkg/runtime/runtime.go
Labels: kind/enhancement, area/cli

#2396 Improve experience of using `spice chat`
  bin/spice/cmd/chat.go
  bin/spice/pkg/api/dataset.go
  bin/spice/pkg/api/model.go
  bin/spice/pkg/api/status.go
  go.mod
  go.sum
Labels: kind/enhancement, area/cli

#2398 Fix view loading on startup
  crates/runtime/src/datafusion.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/view.rs
Labels: kind/bug

#2397 Add `include` param support to GitHub Data Connector
  crates/data_components/src/github.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/github.rs
Labels: kind/enhancement

#2359 Postgres integration test to cover on-conflict behavior
  crates/runtime/tests/acceleration/mod.rs
  crates/runtime/tests/acceleration/on_conflict.rs
Labels: kind/enhancement

#2399 Create dependabot.yml
  .github/dependabot.yml
Labels: kind/enhancement, area/ci

#2400 Add `content` column to GitHub Connector when dataset is accelerated
  crates/data_components/src/github.rs
  crates/runtime/src/dataconnector/github.rs
Labels: kind/enhancement

#2418 Add correct labels to dependabot.yml
  .github/dependabot.yml
Labels: kind/enhancement

#2430 Fix build break
  Cargo.lock
  crates/arrow_sql_gen/Cargo.toml
  crates/llms/Cargo.toml
  crates/model_components/Cargo.toml
Labels: kind/bug

#2431 Dependabot updates
  .github/workflows/generate_json_schema.yml
  .github/workflows/license_check.yml
  .github/workflows/pr.yml
  .github/workflows/spiced_docker.yml
  .github/workflows/types_check.yml
  Cargo.lock
  Cargo.toml
  crates/flight_client/Cargo.toml
  crates/flight_client/src/tls.rs
Labels: kind/dependencies

#2392 Preserve timezone information in constructing expr
  Cargo.lock
  Cargo.toml
  crates/runtime/src/datafusion/filter_converter.rs
  crates/runtime/tests/postgres/mod.rs
Labels: kind/bug

#2401 Fix repeated base table data in acceleration with embeddings
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/datafusion/schema.rs
  crates/runtime/src/embeddings/table.rs
Labels: kind/bug

#2435 Fix tool calling with Groq (and potentially other tool-enabled models)
  .vscode/tasks.json
  crates/runtime/src/model/tool_use.rs
Labels: kind/bug

#2439 Remove candle from `crates/llms/src/chat/`
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/chat/candle.rs
  crates/llms/src/chat/mod.rs
  crates/llms/src/chat/template.json
  crates/llms/src/embeddings/candle/mod.rs
  crates/llms/src/embeddings/mod.rs
  crates/runtime/Cargo.toml
Labels: kind/bug, area/ai

#2433 fix: Only attach successfully initialized accelerators
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/lib.rs
Labels: kind/bug

#2434 Support overriding OpenAI default values in a model param; add token usage telemetry to task_history.
  Cargo.lock
  crates/runtime/src/lib.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/tool_use.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement, area/ai

#2180 Enable message chains and tool calls for local LLMs
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement, area/ai

#2437 DuckDB on-conflict integration test
  Cargo.lock
  Cargo.toml
  Makefile
  crates/runtime/tests/acceleration/on_conflict.rs
Labels: kind/enhancement

#2441 Fix MySQL E2E tests and include MySQL acceleration testing
  .github/workflows/e2e_test_ci.yml
Labels: kind/enhancement

#2442 Use rtcontext for proper cloud/local context in `spice chat`
  bin/spice/cmd/chat.go
  bin/spice/pkg/context/context.go
Labels: kind/bug
