Repository spiceai/spiceai, pull requests merged in 2024-09, with the labels that each got.

#2443 Fix MySQL connector to respect the source column's decimal precision
  .github/workflows/e2e_test_ci.yml
  Cargo.lock
  Cargo.toml
  crates/db_connection_pool/src/dbconnection/clickhouseconn.rs
  crates/db_connection_pool/src/dbconnection/odbcconn.rs
  crates/db_connection_pool/src/dbconnection/snowflakeconn.rs
Labels: kind/bug

#2448 Improve Github Data Connector tables schema
  crates/data_components/src/github.rs
  crates/runtime/src/dataconnector/github.rs
Labels: kind/enhancement

#2449 Improve GitHub Connector error msg when invalid token or permissions
  crates/data_components/src/github.rs
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/graphql/mod.rs
Labels: kind/enhancement

#2454 Proper error tracking across tracing spans
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/bug

#2457 task: Disable and update federation
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/db_connection_pool/Cargo.toml
Labels: kind/enhancement

#2452 GitHub connector: convert `labels` and `hashes` to primitive arrays
  crates/arrow_tools/src/record_batch.rs
  crates/data_components/src/graphql/mod.rs
  crates/data_components/src/graphql/provider.rs
  crates/runtime/src/dataconnector/github.rs
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/bug

#2456 Bump `datafusion` version to the latest
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#2459 Add `accelerated_refresh` to `task_history` table
  crates/runtime/src/accelerated_table/refresh_task.rs
Labels: kind/enhancement

#2467 Add `assignees` and `labels` fields to github issues and github pulls datasets
  crates/runtime/src/dataconnector/github.rs
Labels: kind/enhancement

#2466 Native clickhouse schema inference
  crates/db_connection_pool/src/dbconnection/clickhouseconn.rs
Labels: kind/enhancement

#2468 List GitHub connector in readme
  README.md
Labels: kind/documentation, kind/task

#2474 Fix LLMs health check; Add `updatedAt` field to GitHub connector
  crates/llms/src/chat/mod.rs
  crates/runtime/src/dataconnector/github.rs
Labels: kind/enhancement

#2475 Remove non existing updated_at from github.pulls dataset
  crates/runtime/src/dataconnector/github.rs
Labels: kind/bug

#2477 GitHub connector: add pulls labels and rm duplicate milestoneId and milestoneTitle for issues
  crates/runtime/src/dataconnector/github.rs
Labels: kind/bug

#2479 Add back GitHub connector Pull Request `updated_at`
  crates/runtime/src/dataconnector/github.rs
Labels: kind/bug, area/data-connectors

#2478 Update ROADMAP Sep 2, 2024.
  docs/ROADMAP.md
Labels: kind/bug

#2480 Disable dataset refresh via gRPC
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/actions.rs
  crates/runtime/src/flight/actions/datasets.rs
  crates/runtime/src/lib.rs
  crates/runtime/tests/grpc_api/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/tls/mod.rs
Labels: kind/refactor

#2486 GitHub connector: rename `github_access_token` to `github_token` param
  crates/runtime/src/dataconnector/github.rs
Labels: kind/bug

#2482 Release notes for v0.17.3-beta
  docs/release_notes/v0.17.3-beta.md
Labels: kind/documentation

#2484 Change to sql lang
  README.md
Labels: kind/documentation

#2493 Native schema inference for snowflake (and support timezone_tz, better numeric support)
  Cargo.lock
  crates/db_connection_pool/Cargo.toml
  crates/db_connection_pool/src/dbconnection/snowflakeconn.rs
Labels: kind/enhancement

#2488 Prepare for v0.18.0-beta
  Cargo.toml
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
  version.txt
Labels: kind/enhancement

#2497 Add logo to README.md
  Cargo.lock
  README.md
Labels: kind/documentation

#2511 Enable federation for accelerated queries (sqlite and duckdb)
  crates/data_components/Cargo.toml
  crates/db_connection_pool/Cargo.toml
Labels: kind/optimization

#2498 Load SQLite decimal extension
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/dataaccelerator/sqlite.rs
Labels: kind/enhancement

#2513 fix: Support INTERVAL in SQLite
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2510 Add refresh jitter to refreshing dataset acceleration
  crates/runtime/Cargo.toml
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/tracing_util.rs
  crates/spice_cloud/src/lib.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement, area/data-connectors

#2514 Update to use DuckDB streaming
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#2512 Add more MySQL types in E2E testing
  test/scripts/setup-data-mysql.sql
Labels: kind/enhancement

#2509 Update tpc loading script to support automatic loading into postgres
  test/scripts/setup-tpc-spicepod.bash
Labels: kind/enhancement

#2516 docs: update README.md
  README.md
Labels: kind/bug

#2500 Script for loading clickbench data into arrow / postgres and run clickbench queries
  test/scripts/clickbench/create.sql
  test/scripts/clickbench/queries.sql
  test/scripts/clickbench/run.sh
  test/scripts/clickbench/setup-clickbench-spicepod.bash
Labels: kind/enhancement

#2529 Fix run query script to correctly record all errors
  test/scripts/run-queries.bash
Labels: kind/bug

#2530 Add support for DuckDB engine to setup-tpc-spicepod.bash
  test/scripts/setup-tpc-spicepod.bash
Labels: kind/enhancement

#2532 Upgrade `datafusion` (fixes subquery alias table unparsing for SQLite)
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2534 Make dataset acceleration delay `period +- jitter`
  crates/runtime/src/accelerated_table/refresh.rs
Labels: kind/bug

#2515 Add refresh options to `POST /v1/datasets/:name/acceleration/refresh`
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/accelerated_table/refresh_task_runner.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/tests/refresh_retry/mysql.rs
  crates/runtime/tests/refresh_sql/mod.rs
Labels: kind/enhancement

#2505 Add E2E for GitHub Connector
  .github/actions/run-query/action.yml
  .github/workflows/e2e_test_ci.yml
Labels: kind/enhancement

#2533 Add on-conflict integration test for file based and memory based sqlite
  Makefile
  crates/runtime/tests/acceleration/on_conflict.rs
Labels: kind/enhancement

#2539 Upgrade to Rust v.1.81.0 and fix resulting compile error
  .github/actions/setup-rust/action.yml
  Cargo.lock
  Cargo.toml
  Dockerfile
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/tests/acceleration/on_conflict.rs
  crates/runtime/tests/postgres/common.rs
Labels: kind/bug

#2541 Remove unneeded `RwLock` from `EmbeddingModelStore`
  crates/llms/src/embeddings/candle/mod.rs
  crates/llms/src/embeddings/mod.rs
  crates/llms/src/openai/mod.rs
  crates/runtime/src/embeddings/execution_plan.rs
  crates/runtime/src/embeddings/table.rs
  crates/runtime/src/embeddings/task.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/embeddings.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/embed.rs
Labels: kind/bug

#2537 Remove unneeded RwLock from LlmModelStore
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/chat.rs
Labels: kind/bug

#2540 Add sqlite to the setup tpc benchmark script
  test/scripts/setup-tpc-spicepod.bash
Labels: kind/enhancement, kind/task

#2548 Add sqlite to setup clickbench script
  test/scripts/clickbench/setup-clickbench-spicepod.bash
Labels: kind/enhancement

#2563 Update version for v0.17.4-beta release
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/enhancement

#2294 Sharepoint data connector
  Cargo.lock
  Cargo.toml
  bin/spice/cmd/login.go
  bin/spice/pkg/api/auth.go
  bin/spice/pkg/msal/msal.go
  bin/spiced/Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/lib.rs
  crates/data_components/src/sharepoint/client.rs
  crates/data_components/src/sharepoint/drive_items.rs
  crates/data_components/src/sharepoint/error.rs
  crates/data_components/src/sharepoint/mod.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/sharepoint.rs
  go.mod
  go.sum
Labels: kind/enhancement, area/data-connectors

#2564 Fix predicate/projection push-down for BytesProcessedNode
  crates/runtime/src/datafusion/extension/bytes_processed.rs
  crates/runtime/src/datafusion/extension/mod.rs
  crates/runtime/tests/acceleration/mod.rs
  crates/runtime/tests/acceleration/on_conflict.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/graphql/mod.rs
Labels: kind/bug

#2569 fix out of order projections in sharepoint scans
  crates/data_components/src/sharepoint/client.rs
Labels: kind/bug

#2570 Add snapshot tests for EXPLAIN plans in integration tests
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/tests/federation/mod.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/graphql/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/snapshots/integration__mysql_federation_inner_join_with_acc_inner_join_0.snap
  crates/runtime/tests/snapshots/integration__mysql_federation_inner_join_with_acc_inner_join_1.snap
  crates/runtime/tests/snapshots/integration__mysql_federation_push_down_select_limit_10.snap
  crates/runtime/tests/snapshots/integration__mysql_federation_push_down_select_order_by_limit_10.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_avg_gas_used.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_eth_logs.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_max_blocks_number.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_max_num.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_number_filter.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_number_subquery.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_sum_tx_receipt_gas_used.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_union_all.snap
  crates/runtime/tests/snapshots/integration__test_graphql_pagination_select_all.snap
  crates/runtime/tests/snapshots/integration__test_graphql_pagination_select_limit_1_id_4.snap
  crates/runtime/tests/snapshots/integration__test_graphql_select_all.snap
  crates/runtime/tests/snapshots/integration__test_graphql_select_posts_title.snap
  crates/runtime/tests/snapshots/integration__test_sqlite_decimal_memory_non_federated.snap
  crates/runtime/tests/sqlite/mod.rs
Labels: kind/enhancement

#2578 Set refresh.period from `refresh_data_window`
  crates/runtime/src/datafusion.rs
Labels: kind/bug

#2581 Disable federation for accelerated queries
  crates/data_components/Cargo.toml
  crates/db_connection_pool/Cargo.toml
  crates/runtime/tests/snapshots/integration__test_sqlite_decimal_file_non_federated.snap
  crates/runtime/tests/sqlite/mod.rs
Labels: kind/optimization

#2565 Add manual refresh payload to 'spice refresh...'
  bin/spice/cmd/refresh.go
  bin/spice/pkg/api/util.go
Labels: kind/enhancement, area/cli

#2579 v0.17.4-beta release notes draft
  README.md
  docs/release_notes/v0.17.4-beta.md
Labels: kind/documentation

#2595 Set helm to v0.17.4-beta
  deploy/chart/values.yaml
Labels: kind/enhancement

#2596 Bump to next v0.18.0-beta version
  Cargo.lock
  Cargo.toml
  deploy/chart/values.yaml
  version.txt
Labels: kind/enhancement

#2594 Add snapshot test docs / Update beta criteria for data accelerators
  docs/criteria/accelerator-stages.md
  docs/dev/snapshot_tests.md
Labels: kind/documentation

#2598 Enable federation for accelerated queries (sqlite, duckdb, postgres)
  crates/data_components/Cargo.toml
  crates/db_connection_pool/Cargo.toml
  crates/runtime/tests/sqlite/mod.rs
Labels: kind/optimization

#2601 spelling updates on v0.17.4 release notes
  docs/release_notes/v0.17.4-beta.md
Labels: kind/documentation

#2591 Update endgame template
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#2602 fix: Re-attach DuckDB attachments on each query
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2597 Speed up sqlite accelerator benchmark test with indexes
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_s3/mod.rs
  crates/runtime/benches/setup/mod.rs
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q10_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q12_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q13_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q14_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q16_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q17_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q18_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q19_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q1_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q20_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q21_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q22_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q2_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q3.snap_explain.new
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q3_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q4_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q5_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q6_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q7_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q8_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q9_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q1_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q2_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q3_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q4_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q5_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q6_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q7_explain.snap
Labels: kind/enhancement

#2609 Fix refresh API using `refresh_mode: append`
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/refresh_sql/snapshots/integration__refresh_sql__spiceai_integration_test_refresh_sql_override_append.snap
Labels: kind/bug

#2600 Tweak `/ready` to only report ready when components have all reported Ready
  crates/runtime/benches/setup/mod.rs
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/accelerated_table/refresh_task_runner.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/initial_load.rs
  crates/runtime/src/datafusion/query/query_history.rs
  crates/runtime/src/http/v1/ready.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/spice_metrics.rs
  crates/runtime/src/status.rs
  crates/runtime/src/task_history.rs
  crates/runtime/tests/acceleration/on_conflict.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/catalog/mod.rs
  crates/runtime/tests/federation/mod.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/graphql/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/refresh_retry/mysql.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/sqlite/mod.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement

#2627 fix: Remove comments from SQL files
  test/scripts/run-queries.bash
Labels: kind/bug

#2614 Utilize runtime.status().is_ready() to check acceleration dataset readiness in benchmark test
  crates/runtime/benches/setup/mod.rs
Labels: kind/enhancement

#2603 Allow for prefix to be kept in internal Parameters
  crates/runtime/src/parameters.rs
Labels: kind/bug, area/data-connectors

#2599 Add initial threat model using OWASP Threat Dragon
  docs/threat_models/v0.17.4-beta.json
Labels: kind/documentation

#2628 fix: Explicitly error for duplicate duckdb file accelerators
  crates/runtime/src/dataaccelerator/duckdb.rs
Labels: kind/bug

#2626 Benchmark test binary can parse command line option
  crates/runtime/benches/bench.rs
Labels: kind/enhancement

#2613 Snapshot tests shouldn't crash the Spice benchmark test
  crates/runtime/benches/bench.rs
Labels: kind/bug

#2634 Upgrade datafusion to improve SQLite subquery tables aliasing support
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2631 Run benchmark separately using workflow
  .github/workflows/benchmarks.yml
  crates/runtime/benches/setup/mod.rs
Labels: kind/enhancement

#2630 Improve `/ready` to only mark a dataset ready iff the initial refresh completed
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/metadata.rs
  crates/runtime/src/dataaccelerator/metadata/duckdb.rs
  crates/runtime/src/dataaccelerator/metadata/postgres.rs
  crates/runtime/src/dataaccelerator/metadata/sqlite.rs
  crates/runtime/src/dataaccelerator/spice_sys.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/mod.rs
  crates/runtime/src/dataaccelerator/spice_sys/debezium_kafka/mod.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/lib.rs
  crates/runtime/tests/acceleration/checkpoint_duckdb.rs
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
  crates/runtime/tests/acceleration/checkpoint_sqlite.rs
  crates/runtime/tests/acceleration/mod.rs
  crates/runtime/tests/acceleration/on_conflict.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/acceleration/snapshots/integration__acceleration__checkpoint_duckdb__acceleration_duckdb_checkpoint.snap
  crates/runtime/tests/acceleration/snapshots/integration__acceleration__checkpoint_postgres__acceleration_postgres_checkpoint.snap
  crates/runtime/tests/acceleration/snapshots/integration__acceleration__checkpoint_sqlite__acceleration_sqlite_checkpoint.snap
  crates/runtime/tests/s3/mod.rs
Labels: kind/enhancement, breaking change, area/data-accelerators

#2637 Support relative paths for file connector
  crates/runtime/src/dataconnector/file.rs
Labels: kind/bug, area/data-connectors, area/quality

#2645 Fix `error decoding response body` GitHub file connector bug
  crates/data_components/src/github.rs
Labels: kind/bug

#2632 GraphQL pagination and robustness.
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/graphql/client.rs
  crates/runtime/src/dataconnector/github.rs
Labels: kind/enhancement, area/data-connectors, data-connector/graphql

#2629 docs: Update bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: kind/documentation

#2646 Define GitHub `issues` data connector schema upfront
  crates/data_components/src/graphql/client.rs
  crates/runtime/src/dataconnector/github.rs
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/bug

#2642 Add support for loading from Sharepoint Group's default drive.
  Cargo.lock
  Cargo.toml
  crates/data_components/src/sharepoint/client.rs
Labels: kind/bug, area/data-connectors

#2654 Fix typo in workflow, fix the postgres connector container readiness check
  .github/workflows/benchmarks.yml
  test/tpch/postgres-bench/postgres-entrypoint.sh
Labels: kind/bug

#2653 Fix check all features
  crates/runtime/src/dataaccelerator/spice_sys.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/duckdb.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/mod.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/postgres.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/sqlite.rs
  crates/runtime/src/dataaccelerator/spice_sys/debezium_kafka/duckdb.rs
  crates/runtime/src/dataaccelerator/spice_sys/debezium_kafka/mod.rs
  crates/runtime/src/dataaccelerator/spice_sys/debezium_kafka/postgres.rs
  crates/runtime/src/dataaccelerator/spice_sys/debezium_kafka/sqlite.rs
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
Labels: kind/bug

#2655 Enable Warn/Error traces from dependency components
  bin/spiced/src/tracing.rs
Labels: kind/bug

#2551 Use lower case iso8601 for time_column
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#2643 Add basic integration test for Spice spill-to-disk and re-hydration scenario
  crates/runtime/src/lib.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/rehydration/mod.rs
Labels: kind/enhancement

#2641 Add 'RefreshOverrides::max_jitter' to 'POST /v1/datasets/:name/acceleration/refresh'
  bin/spice/cmd/refresh.go
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task_runner.rs
  crates/runtime/tests/refresh_sql/mod.rs
Labels: kind/enhancement

#2657 Update dependencies to support querying postgres enum types
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#2659 Upgrade table-providers
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#2658 Improve `spill_to_disk_and_rehydration` integration test
  crates/runtime/tests/docker/mod.rs
  crates/runtime/tests/rehydration/mod.rs
Labels: kind/enhancement

#2661 Enhance GitHub connector robustness with explicit table schema definitions
  crates/runtime/src/dataconnector/github.rs
  crates/runtime/src/dataconnector/github/commits.rs
  crates/runtime/src/dataconnector/github/issues.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/github/pull_requests.rs
  crates/runtime/src/dataconnector/github/stargazers.rs
Labels: kind/optimization

#2668 Rename sharepoint fields
  crates/data_components/src/sharepoint/drive_items.rs
Labels: kind/enhancement, area/data-connectors

#2676 Disable dataset checkpoint for DuckDB acceleration
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/duckdb.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/mod.rs
  crates/runtime/tests/acceleration/checkpoint_duckdb.rs
  crates/runtime/tests/acceleration/checkpoint_sqlite.rs
Labels: kind/bug

#2683 Revert "Enable federation for accelerated queries (sqlite, duckdb, postgres) (#2598)
  crates/data_components/Cargo.toml
  crates/db_connection_pool/Cargo.toml
  crates/runtime/tests/sqlite/mod.rs
Labels: kind/optimization

#2686 Revert "Use lower case iso8601 for time_column (#2551)"
  crates/spicepod/src/component/dataset.rs
Labels: kind/bug

#2681 v0.18.0-beta release notes
  docs/release_notes/v0.18.0-beta.md
Labels: kind/documentation

#2711 Update Helm Chart for 0.18.0-beta release
  deploy/chart/Chart.yaml
Labels: kind/optimization

#2715 Dependabot upgrades
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/flight_client/Cargo.toml
  crates/flight_client/src/tls.rs
  crates/model_components/Cargo.toml
Labels: kind/dependencies

#2720 Use a single instance for all SQLite accelerated datasets
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator/spice_sys.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/sqlite.rs
  crates/runtime/src/dataaccelerator/spice_sys/debezium_kafka/sqlite.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/tests/rehydration/mod.rs
Labels: kind/enhancement

#2692 Prepare for v0.18.1-beta release
  Cargo.lock
  Cargo.toml
  docs/ROADMAP.md
  version.txt
Labels: kind/optimization

#2713 For GraphQL, remove necessity of `json_pointer` and improve error messaging.
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/graphql/mod.rs
  crates/runtime/src/dataconnector/github/commits.rs
  crates/runtime/src/dataconnector/github/issues.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/github/pull_requests.rs
  crates/runtime/src/dataconnector/github/stargazers.rs
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/enhancement, data-connector/graphql

#2652 Postgres accelerator benchmark test
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_postgres/mod.rs
  crates/runtime/benches/setup/mod.rs
Labels: kind/enhancement

#2684 Trace query result while running benchmark tests
  crates/runtime/benches/bench.rs
Labels: kind/optimization

#2717 Early check EmbeddingConnector if embedding models do not exist
  crates/runtime/src/embeddings/connector.rs
Labels: kind/enhancement

#2732 Move table creation for spice_sys_dataset_checkpoint to DatasetCheckpoint::try_new
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/duckdb.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/mod.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/postgres.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/sqlite.rs
  crates/runtime/tests/acceleration/checkpoint_duckdb.rs
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
  crates/runtime/tests/acceleration/checkpoint_sqlite.rs
Labels: kind/bug

#2731 Don't load tools immediately
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#2725 Renable accelerator federation on trunk
  crates/data_components/Cargo.toml
  crates/db_connection_pool/Cargo.toml
  crates/runtime/tests/acceleration/on_conflict.rs
  crates/runtime/tests/sqlite/mod.rs
Labels: kind/enhancement

#2724 Fixing Data Connectors link in README.md
  README.md
Labels: kind/documentation

#2729 Enable rehydration tests for DuckDB
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/tests/rehydration/duckdb.rs
  crates/runtime/tests/rehydration/mod.rs
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-2.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-3.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-4.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-5.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-6.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-7.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-8.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration.snap
  crates/runtime/tests/rehydration/sqlite.rs
Labels: kind/enhancement

#2733 refactor: Replace query_history with task_history
  .github/workflows/integration.yml
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/builder.rs
  crates/runtime/src/datafusion/query/query_history.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/lib.rs
Labels: kind/bug

#2730 Check pageInfo is correct at initialisation of GraphQL connector
  crates/data_components/src/graphql/client.rs
  crates/runtime/tests/acceleration/single_instance_duckdb.rs
Labels: kind/enhancement

#2741 Microsoft SQL Server data connector initial support
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/lib.rs
  crates/data_components/src/mssql.rs
  crates/db_connection_pool/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/mssql.rs
Labels: kind/enhancement

#2739 Add `spice search` CLI command
  bin/spice/cmd/chat.go
  bin/spice/cmd/datasets.go
  bin/spice/cmd/search.go
  bin/spice/pkg/api/status.go
  bin/spice/pkg/context/context.go
  bin/spice/pkg/util/out.go
  bin/spice/pkg/util/util.go
Labels: kind/enhancement, area/cli

#2735 feat: use task history for dataset availability checks
  crates/runtime/src/datasets_health_monitor.rs
Labels: kind/enhancement

#2738 Update threat model
  docs/threat_models/v0.17.4-beta.json
Labels: kind/documentation

#2744 Upgrade to Arrow 53, DataFusion 42 and DuckDB 1.1
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/delete.rs
  crates/data_components/src/poly.rs
  crates/flight_client/src/tls.rs
  crates/flightrepl/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/src/execution_plan/fallback_on_zero_results.rs
  crates/runtime/src/flight/actions.rs
  crates/runtime/src/flight/do_get.rs
  crates/runtime/src/flight/do_put.rs
  crates/runtime/src/flight/flightsql/get_catalogs.rs
  crates/runtime/src/flight/flightsql/get_table_types.rs
  crates/runtime/src/flight/get_flight_info.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/status.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/catalog/mod.rs
  crates/runtime/tests/federation/mod.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/snapshots/integration__test_graphql_pagination_select_limit_1_id_4.snap
  crates/runtime/tests/tls/mod.rs
Labels: kind/dependencies

#2747 Update datafusion table provider patch
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2758 feat: Add enabled config option for task_history
  bin/spiced/src/lib.rs
  bin/spiced/src/tracing.rs
  crates/runtime/src/lib.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#2748 Remove v0.18.0-beta from the Roadmap
  docs/ROADMAP.md
Labels: kind/documentation

#2766 Fix spark-connect to use native roots for TLS again
  Cargo.lock
  crates/data_components/Cargo.toml
Labels: kind/bug

#2752 Fix benchmark test - Install default crypto provider
  crates/runtime/benches/bench.rs
  crates/runtime/benches/setup/mod.rs
Labels: kind/bug

#2749 Resolve primary keys for datasets with catalog or schema
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/bug, area/ai

#2746 MSSQL: include table name in schema retrieval error
  crates/data_components/src/mssql.rs
Labels: kind/bug

#2740 File Format parsing for Document tables, support for docx + pdf
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/object/text.rs
  crates/document_parse/Cargo.toml
  crates/document_parse/src/docx.rs
  crates/document_parse/src/lib.rs
  crates/document_parse/src/pdf.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/builder.rs
  crates/runtime/src/dataconnector.rs
Labels: kind/enhancement

#2760 Add Document parsing to Sharepoint connector.
  crates/data_components/src/sharepoint/client.rs
  crates/data_components/src/sharepoint/error.rs
  crates/data_components/src/sharepoint/mod.rs
  crates/data_components/src/sharepoint/table.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/sharepoint.rs
Labels: kind/refactor

#2768 Execution plan with BinaryExpr predicates pushdown support for MS SQL
  crates/data_components/src/mssql/connection_manager.rs
  crates/data_components/src/mssql/convert.rs
  crates/data_components/src/mssql/execution_plan.rs
  crates/data_components/src/mssql/mod.rs
  crates/runtime/src/dataconnector/mssql.rs
Labels: kind/enhancement

#2772 Update datafusion patch
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#2773 Support for standalone config parameters for MS SQL
  crates/data_components/src/mssql/connection_manager.rs
  crates/data_components/src/mssql/execution_plan.rs
  crates/data_components/src/mssql/mod.rs
  crates/runtime/src/dataconnector/mssql.rs
Labels: kind/enhancement

#2759 Utilize DataConnectorError for MySQL Data Connector Errors
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataconnector/mysql.rs
Labels: kind/enhancement, kind/task

#2774 Add Score to search results
  bin/spice/cmd/search.go
Labels: kind/enhancement, area/cli

#2779 Don't call GetComponentStatuses when --metrics not enabled
  bin/spice/cmd/search.go
  bin/spice/pkg/api/status.go
Labels: kind/bug

#2767 Implement better error handling for spicepods
  Cargo.lock
  bin/spiced/src/lib.rs
  crates/spicepod/Cargo.toml
  crates/spicepod/src/component.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/params.rs
Labels: kind/enhancement

#2782 Make integration tests more robust
  crates/runtime/tests/acceleration/mod.rs
  crates/runtime/tests/rehydration/mod.rs
Labels: kind/bug

#2781 Query results streaming support for MS SQL
  crates/data_components/src/mssql/execution_plan.rs
Labels: kind/optimization

#2778 Update benchmark snapshots
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q16_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q18_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q20_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q21_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q22_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q2_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_q4_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q3_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q4_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q6_explain.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_tpch_simple_q7_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q16_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q18_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q20_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q21_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q22_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q2_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_q4_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_simple_q3_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_simple_q4_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_simple_q6_explain.snap
  crates/runtime/benches/snapshots/bench__s3_tpch_simple_q7_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q14_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q17_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q19_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q2_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q6_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q8_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q9_explain.snap
Labels: kind/enhancement

#2780 For Sharepoint connector, if client_secret and auth_code are both provided, default to auth_code
  crates/runtime/src/dataconnector/sharepoint.rs
Labels: kind/enhancement

#2743 Add modified pk/indexes scenario to rehydration tests
  crates/runtime/tests/rehydration/mod.rs
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-2.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-4.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-5.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-6.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-7.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration-8.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__execute_spill_to_disk_and_rehydration.snap
  crates/runtime/tests/rehydration/snapshots/integration__rehydration__records.snap
Labels: kind/optimization

#2786 Run benchmarks on Wed, Fri, Sat, and Sun.
  .github/workflows/benchmarks.yml
Labels: kind/performance

#2785 Update PULL_REQUEST_TEMPLATE.md to include a section for Documentation
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation

#2788 Add E2E test for MS SQL data connector
  .github/workflows/e2e_test_ci.yml
  test/scripts/setup-data-mssql.sql
Labels: kind/enhancement

#2789 More types support for MS SQL data connector
  crates/data_components/src/mssql/convert.rs
  crates/data_components/src/mssql/mod.rs
  test/scripts/setup-data-mssql.sql
Labels: kind/enhancement

#2783 feat: Add captured_output option for task_history
  bin/spiced/src/lib.rs
  bin/spiced/src/tracing.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/query_history.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/task_history.rs
  crates/runtime/src/task_history/otel_exporter.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#2787 Add ability to refresh when file data connector detects changes
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/dataaccelerator/arrow.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/postgres.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/tests/acceleration/data/names.csv
  crates/runtime/tests/acceleration/file_watcher.rs
  crates/runtime/tests/acceleration/mod.rs
  crates/runtime/tests/acceleration/snapshots/integration__acceleration__file_watcher__file_watcher-2.snap
  crates/runtime/tests/acceleration/snapshots/integration__acceleration__file_watcher__file_watcher.snap
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement

#2776 Propagate MySQL invalid table name error
  crates/runtime/src/dataconnector/mysql.rs
Labels: kind/enhancement

#2784 feat: Add retention options for task_history config
  Cargo.lock
  bin/spiced/src/lib.rs
  bin/spiced/src/tracing.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/task_history.rs
  crates/spicepod/Cargo.toml
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#2793 fix: Move task history check after query history creation
  crates/runtime/src/lib.rs
Labels: kind/bug

#2796 Queries that cannot be planned show up in task history
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#2791 Improve Sharepoint DX
  crates/data_components/src/sharepoint/client.rs
  crates/data_components/src/sharepoint/error.rs
  crates/data_components/src/sharepoint/table.rs
Labels: kind/refactor

#2798 Track internal queries to task_history table
  crates/runtime/src/builder.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/task_history/otel_exporter.rs
  crates/runtime/src/tools/builtin/sql.rs
Labels: kind/enhancement

#2799 Keep track of accelerated tables and mark queries as accelerated in task_history
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/builder.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement, area/observability

#2792 Replace query history with task history
  .github/workflows/integration.yml
  crates/runtime/src/builder.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/builder.rs
  crates/runtime/src/datafusion/query/query_history.rs
  crates/runtime/src/datafusion/query/tracker.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/task_history/otel_exporter.rs
  crates/runtime/src/tools/builtin/sql.rs
Labels: kind/enhancement

#2805 Fix datasets_health_monitor spice.runtime.task_history not found warning
  crates/runtime/src/builder.rs
  crates/runtime/src/datasets_health_monitor.rs
Labels: kind/bug
