Repository spiceai/spiceai, pull requests merged in 2024-05, with the labels that each got.

#1266 Implement the Localhost Data Connector & fix DoPut
  crates/runtime/src/arrow.rs
  crates/runtime/src/dataconnector/localhost.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/lib.rs
Labels: area/data-connectors

#1303 Add CLI cmd `spice login spark`
  bin/spice/cmd/login.go
  bin/spice/pkg/api/auth.go
Labels: area/cli

#1306 Fix the panic on bad clickhouse connection
  Cargo.lock
  Cargo.toml
Labels: kind/bug, area/data-connectors

#1336 Select columns from Spark Dataframe according to projected_schema
  crates/data_components/src/spark_connect.rs
Labels: kind/bug

#1368 Upgrade to DataFusion 38
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/arrow/write.rs
  crates/data_components/src/clickhouse.rs
  crates/data_components/src/databricks_delta.rs
  crates/data_components/src/databricks_spark.rs
  crates/data_components/src/deltatable/write.rs
  crates/data_components/src/duckdb.rs
  crates/data_components/src/duckdb/write.rs
  crates/data_components/src/flight.rs
  crates/data_components/src/flight/stream.rs
  crates/data_components/src/flight/write.rs
  crates/data_components/src/flightsql.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/mysql.rs
  crates/data_components/src/odbc.rs
  crates/data_components/src/postgres.rs
  crates/data_components/src/postgres/write.rs
  crates/data_components/src/snowflake.rs
  crates/data_components/src/spark_connect.rs
  crates/data_components/src/sqlite.rs
  crates/data_components/src/sqlite/write.rs
  crates/db_connection_pool/src/dbconnection.rs
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/localhost.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/datafusion.rs
  crates/sql_provider_datafusion/src/lib.rs
Labels: dependencies

#1380 Implement federation for DuckDB Data Connector (POC)
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/clickhouse.rs
  crates/data_components/src/duckdb.rs
  crates/data_components/src/mysql.rs
  crates/data_components/src/odbc.rs
  crates/data_components/src/postgres.rs
  crates/data_components/src/snowflake.rs
  crates/data_components/src/sqlite.rs
  crates/runtime/Cargo.toml
  crates/sql_provider_datafusion/Cargo.toml
  crates/sql_provider_datafusion/src/federation.rs
  crates/sql_provider_datafusion/src/lib.rs
  crates/sql_provider_datafusion/tests/postgres_integration_test.rs
Labels: area/data-connectors

#1394 Fully implement federation for all SqlTable-based Data Connectors
  .gitignore
  .vscode/settings.json
  Cargo.lock
  crates/data_components/src/clickhouse.rs
  crates/data_components/src/mysql.rs
  crates/data_components/src/odbc.rs
  crates/data_components/src/postgres.rs
  crates/data_components/src/snowflake.rs
  crates/db_connection_pool/Cargo.toml
  crates/db_connection_pool/src/clickhousepool.rs
  crates/db_connection_pool/src/duckdbpool.rs
  crates/db_connection_pool/src/lib.rs
  crates/db_connection_pool/src/mysqlpool.rs
  crates/db_connection_pool/src/odbcpool.rs
  crates/db_connection_pool/src/postgrespool.rs
  crates/db_connection_pool/src/snowflakepool.rs
  crates/db_connection_pool/src/sqlitepool.rs
  crates/sql_provider_datafusion/src/federation.rs
  crates/sql_provider_datafusion/src/lib.rs
Labels: kind/enhancement, area/data-connectors

#1401 Add federation to FlightTable based DataConnectors
  .vscode/settings.json.template
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/flight.rs
  crates/data_components/src/flight/federation.rs
  crates/flight_client/src/lib.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/spiceai.rs
Labels: kind/enhancement, area/data-connectors

#1438 Correctly map NullBuilder for Null arrow types
  crates/arrow_sql_gen/src/arrow.rs
Labels: kind/bug

#1460 Fix the table reference to use the full table reference, not just the table
  Cargo.lock
  crates/sql_provider_datafusion/src/federation.rs
Labels: kind/bug

#1477 Add basic integration test for MySQL federation
  Cargo.lock
  Makefile
  crates/runtime/Cargo.toml
  crates/runtime/tests/docker/mod.rs
  crates/runtime/tests/federation/mod.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/integration.rs
  crates/spicepod/src/component/params.rs
Labels: area/quality

#1461 Add DuckDB quickstart to E2E tests
  .github/workflows/e2e_test_ci.yml
Labels: area/quality

#1490 Pin Git dependencies to a specific commit hash
  Cargo.lock
  crates/llms/Cargo.toml
Labels: dependencies

#1503 Separate runtime Dataset from spicepod Dataset
  Cargo.lock
  bin/spiced/Cargo.toml
  crates/app/Cargo.toml
  crates/data_components/src/databricks_delta.rs
  crates/data_components/src/postgres.rs
  crates/db_connection_pool/Cargo.toml
  crates/db_connection_pool/src/clickhousepool.rs
  crates/db_connection_pool/src/dbconnection/odbcconn.rs
  crates/db_connection_pool/src/lib.rs
  crates/db_connection_pool/src/mysqlpool.rs
  crates/db_connection_pool/src/odbcpool.rs
  crates/db_connection_pool/src/postgrespool.rs
  crates/db_connection_pool/src/snowflakepool.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/mod.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/mysql.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/localhost.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/filter_converter.rs
  crates/runtime/src/http/v1.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/spice_metrics.rs
  crates/secrets/src/lib.rs
  crates/spicepod/Cargo.toml
  crates/spicepod/src/component/dataset.rs
  crates/sql_provider_datafusion/tests/postgres_integration_test.rs
Labels: area/quality

#1506 Use TableReference for dataset name
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/refresh_sql.rs
  crates/runtime/src/execution_plan/fallback_on_zero_results.rs
  crates/runtime/src/http/v1.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/spice_metrics.rs
  crates/runtime/src/status.rs
Labels: area/quality

#1510 Fix refresh_sql not properly passing down filters
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#1512 Improve clarity of README and add FAQ
  README.md
Labels: kind/documentation

#1532 Register runtime tables with runtime schema
  crates/runtime/src/datafusion.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/query_history.rs
  crates/runtime/src/spice_metrics.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/bug

#1535 Update ROADMAP.md May 27, 2024
  docs/ROADMAP.md
Labels: kind/documentation

#1550 Fix UNION ALL federated push down
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/runtime/tests/federation/mod.rs
Labels: kind/bug

#1555 Use proper MySQL dialect during federation push-down
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/flight/federation.rs
  crates/data_components/src/flightsql/federation.rs
  crates/data_components/src/mysql.rs
  crates/runtime/tests/federation/mysql.rs
  crates/sql_provider_datafusion/src/federation.rs
  crates/sql_provider_datafusion/src/lib.rs
Labels: kind/bug
