Repository spiceai/spiceai, pull requests merged in 2024-12, with the labels that each got.

#3725 Update `llms` dependencies: `mistralrs`, `async-openai`
  Cargo.lock
  Cargo.toml
  crates/llms/Cargo.toml
  crates/llms/src/anthropic/chat.rs
  crates/llms/src/anthropic/types_stream.rs
  crates/llms/src/chat/mistral.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement, area/ai

#3726 Support `jsonl` for object store
  crates/runtime/src/dataconnector/listing/connector.rs
Labels: kind/enhancement, area/data-connectors

#3727 Fix NSQL models integration tests for HF
  crates/llms/src/chat/nsql/mod.rs
  crates/llms/src/chat/nsql/snapshots/llms__chat__nsql__tests__sql_gen_default.snap
  crates/llms/src/chat/nsql/snapshots/llms__chat__nsql__tests__sql_gen_json.snap
  crates/llms/src/chat/nsql/snapshots/llms__chat__nsql__tests__sql_gen_structured.snap
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_1_response_choices.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_completion.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__embeddings_1.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__embeddings_2.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__embeddings_3.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__search_1.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__hf_invalid_dataset_name_error.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__hf_invalid_model_name_error.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__hf_with_model_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__hf_with_model_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__hf_with_sample_data_enabled_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__hf_with_sample_data_enabled_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__openai_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__openai_basic_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__openai_with_model_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__openai_with_model_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__openai_with_sample_data_enabled_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__openai_with_sample_data_enabled_tasks.snap
Labels: kind/optimization

#3732 standardise 'csv_schema_infer_max_records' -> 'schema_infer_max_records'; include deprecation messages for dataset params
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/listing/mod.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/parameters.rs
Labels: kind/bug

#3737 feat: Add script to generate TPC-H data for file connector
  test/tpc-bench/Makefile
  test/tpc-bench/tpch_file.py
Labels: kind/enhancement

#3735 feat: Add file connector integration test
  crates/runtime/tests/file/.gitignore
  crates/runtime/tests/file/datatypes.parquet
  crates/runtime/tests/file/generate_parquet.py
  crates/runtime/tests/file/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/snapshots/integration__file__file_integration_test_select.snap
Labels: kind/enhancement

#3736 fix: Add explicit message for ODBC connector when not installed
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/lib.rs
Labels: kind/bug

#3739 Remove Box::leak in `create_accelerated_table`
  crates/runtime/src/datafusion.rs
Labels: kind/optimization

#3740 docs: Update enhancement and PR template
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation

#3734 feat: add file connector benchmark
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_object_store/file.rs
  crates/runtime/benches/bench_object_store/mod.rs
  crates/runtime/benches/setup/mod.rs
  crates/runtime/benches/snapshots/bench__file_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__file_tpch_q9.snap
Labels: kind/enhancement

#3738 docs: Release file connector beta
  README.md
  docs/criteria/connectors/beta.md
Labels: kind/documentation

#3724 For embeddings, use `sentence_*_config.json`, download HF async, use TEI functions
  crates/llms/src/embeddings/candle/tei.rs
  crates/llms/src/embeddings/candle/util.rs
  crates/llms/src/embeddings/mod.rs
  crates/runtime/src/model/embed.rs
Labels: kind/refactor, area/ai

#3741 Optimize build & release workflow for trunk builds
  .github/workflows/build_and_release.yml
Labels: kind/enhancement, area/ci

#3755 Skip Spice cloud integration tests
  crates/runtime/tests/catalog/mod.rs
  crates/runtime/tests/federation/mod.rs
Labels: kind/enhancement

#3748 Add `http_requests` metric and deprecate `http_requests_total`
  crates/runtime/src/http/metrics.rs
  crates/runtime/src/http/routes.rs
Labels: kind/bug

#3762 fix: Parquet file generation script
  test/tpc-bench/tpch_file.py
Labels: kind/bug

#3763 fix: Use InvalidConfiguration error for GraphQL query errors
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/bug

#3750 Extend Spice Search integration and E2E tests to cover chunking
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_all_datasets_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_chunking_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_all_datasets_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_chunking_response.snap
  test/models/spicepod.yml
Labels: kind/bug, kind/optimization

#3756 test: Add GraphQL integration tests from external sources
  crates/runtime/tests/graphql/mod.rs
  crates/runtime/tests/snapshots/integration__test_graphql_select_swapi.snap
  crates/runtime/tests/snapshots/integration__test_graphql_select_tcgdex.snap
Labels: kind/enhancement

#3764 docs: Release GraphQL release candidate
  README.md
  docs/criteria/connectors/rc.md
Labels: kind/documentation

#3765 Accelerate a subset of columns from source dataset in Refresh SQL
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/refresh_sql.rs
  crates/runtime/src/dataupdate.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/tracers.rs
Labels: kind/enhancement

#3747 Update dependencies
  Cargo.lock
  Cargo.toml
  crates/llms/Cargo.toml
  crates/runtime/Cargo.toml
Labels: kind/dependencies

#3767 Implement InvalidTypeAction for PostgreSQL Data Connector
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/init/dataset.rs
Labels: kind/enhancement

#3777 fix: Check ODBC parameters are positive integers
  crates/runtime/src/dataconnector/odbc.rs
Labels: kind/bug

#3776 Fix Delta DataType `Map` type mapping to arrow type
  crates/data_components/src/delta_lake.rs
Labels: kind/bug

#3778 Update Databricks & Delta Lake Connector RC criteria
  docs/criteria/connectors/rc.md
Labels: kind/enhancement

#3782 Add a `/v1/packages/generate` API to generate a Spicepod package from a GitHub repo.
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/document_parse/Cargo.toml
  crates/flight_client/Cargo.toml
  crates/llms/Cargo.toml
  crates/package/Cargo.toml
  crates/package/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/packages.rs
  crates/runtime/src/objectstore/github.rs
  crates/runtime/src/objectstore/mod.rs
Labels: kind/enhancement

#3783 Set `Spice-Target-Source` header for `spice add`
  bin/spice/pkg/http/client.go
  bin/spice/pkg/registry/spicerack.go
Labels: kind/enhancement

#3784 Call v1 spicerack API
  bin/spice/pkg/registry/spicerack.go
Labels: kind/enhancement

#3785 Run models integration tests on self-hosted macOS runners
  .github/workflows/integration_models.yml
Labels: kind/enhancement

#3786 Fix OpenAI models integration tests
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_completion.snap
Labels: kind/bug

#3779 Integration test for Databricks delta_lake mode
  .github/workflows/integration.yml
  crates/runtime/tests/databricks_delta/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/snapshots/integration__databricks_delta__databricks_delta_lake_select.snap
  crates/runtime/tests/snapshots/integration__databricks_delta_lake_test_select.snap
Labels: kind/enhancement

#3792 Release RC for databricks delta_lake mode
  README.md
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
  docs/criteria/connectors/rc.md
Labels: kind/enhancement

#3788 Include Huggingface model to E2E models tests
  .github/workflows/e2e_test_ci_models.yml
  test/models/chat_01_simple.exp
  test/models/spicepod_hf.yml
  test/models/spicepod_openai.yml
Labels: kind/enhancement

#3791 Enable `trace_id` & `parent_span_id` overrides for `v1/chat/completion`
  crates/runtime/Cargo.toml
  crates/runtime/src/http.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/traceparent.rs
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/task_history.rs
  crates/runtime/src/task_history/otel_exporter.rs
Labels: kind/enhancement

#3793 Search benchmark: run search workload and measure result
  crates/runtime/benches/bench_search/datasets.rs
  crates/runtime/benches/bench_search/mod.rs
  crates/runtime/benches/bench_search/setup.rs
  crates/runtime/benches/setup/mod.rs
  crates/runtime/benches/utils/mod.rs
  crates/runtime/benches/vector_search.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#3804 Search benchmark: measure search precision
  crates/runtime/benches/bench_search/datasets.rs
  crates/runtime/benches/bench_search/evaluator.rs
  crates/runtime/benches/bench_search/mod.rs
  crates/runtime/benches/bench_search/setup.rs
  crates/runtime/benches/vector_search.rs
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/enhancement

#3816 Only verify TPCH / TPCDS official query results for DuckDB
  crates/runtime/benches/bench_duckdb/mod.rs
  crates/runtime/benches/snapshots/bench__duckdb_tpch_simple_q1.snap
  crates/runtime/benches/snapshots/bench__duckdb_tpch_simple_q2.snap
  crates/runtime/benches/snapshots/bench__duckdb_tpch_simple_q3.snap
  crates/runtime/benches/snapshots/bench__duckdb_tpch_simple_q4.snap
  crates/runtime/benches/snapshots/bench__duckdb_tpch_simple_q5.snap
Labels: kind/optimization

#3819 Fixes for the Debezium connector
  crates/data_components/src/debezium/arrow.rs
  crates/data_components/src/kafka.rs
  crates/runtime/src/dataconnector/debezium.rs
Labels: kind/enhancement

#3820 Fix insert statement when all columns are constraint columns
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#3823 docs: Move ODBC to Beta for current state of roadmap
  docs/ROADMAP.md
Labels: kind/documentation

#3821 Accept `:`, `/` or `://` as the delimiter for the data connector
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/tests/acceleration/file_watcher.rs
  crates/runtime/tests/snapshots/integration__test_graphql_select_tcgdex.snap
Labels: kind/enhancement, breaking change

#3826 Update dependencies
  Cargo.lock
  Cargo.toml
  crates/arrow_sql_gen/Cargo.toml
  crates/runtime/Cargo.toml
Labels: kind/enhancement

#3813 Enable `read_write` mode support for Postgres Data Connector
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/tests/federation/mysql.rs
  crates/runtime/tests/refresh_retry/mysql.rs
  crates/runtime/tests/rehydration/mod.rs
Labels: kind/enhancement

#3824 Azure AI support for both LLMs & embedding models
  Cargo.lock
  Cargo.toml
  crates/llms/src/chat/mod.rs
  crates/llms/src/chunking/mod.rs
  crates/llms/src/embeddings/candle/tei.rs
  crates/llms/src/embeddings/candle/util.rs
  crates/llms/src/openai/chat.rs
  crates/llms/src/openai/embed.rs
  crates/llms/src/openai/mod.rs
  crates/llms/tests/llms/create.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/embed.rs
  crates/runtime/tests/models/hf.rs
  crates/spicepod/src/component/embeddings.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement, area/ai

#3834 Add Github Workflow to run Search Benchmark
  .github/workflows/benchmarks.yml
  .github/workflows/benchmarks_search.yml
  crates/runtime/benches/vector_search.rs
Labels: kind/enhancement

#3836 Fetch access token with Microsoft OAuth, and use access token to initiate Sharepoint data connector graph client
  bin/spice/cmd/login.go
  bin/spice/pkg/api/auth.go
  bin/spice/pkg/msal/msal.go
  crates/runtime/src/dataconnector/sharepoint.rs
Labels: kind/enhancement, breaking change

#3714 Initialize accelerator for datasets dynamically included
  crates/runtime/src/init/dataset.rs
Labels: kind/bug

#3838 Update cargo.lock
  Cargo.lock
Labels: kind/bug

#3833 feat: add MS SQL TPCH benchmark
  .github/workflows/benchmarks.yml
  .github/workflows/spice_mssql_tpch_bench_docker.yml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_mssql/mod.rs
  crates/runtime/benches/bench_mssql/tpch_q12.sql
  crates/runtime/benches/bench_mssql/tpch_q19.sql
  crates/runtime/benches/setup/mod.rs
  crates/runtime/benches/snapshots/bench__mssql_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q9.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_simple_q1.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_simple_q2.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_simple_q3.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_simple_q4.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_simple_q5.snap
  test/tpc-bench/Makefile
  test/tpc-bench/mssql-tpch/Dockerfile
  test/tpc-bench/mssql-tpch/data/.gitignore
  test/tpc-bench/mssql-tpch/docker-compose.yml
  test/tpc-bench/mssql-tpch/entrypoint.sh
  test/tpc-bench/mssql-tpch/insert.sql
  test/tpc-bench/mssql-tpch/setup.sh
  test/tpc-bench/mssql-tpch/up.sql
Labels: kind/enhancement

#3835 Improve Azure AI models support
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/embed.rs
Labels: kind/bug

#3829 Primary key support for Arrow's `Memtable`
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/arrow.rs
  crates/data_components/src/arrow/write.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/dataconnector/sink.rs
Labels: kind/enhancement, area/data-connectors

#3839 Update Tokenizer to 0.21 and mistral.rs
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/chat/nsql/snapshots/llms__chat__nsql__tests__sql_gen_structured.snap
  crates/llms/src/embeddings/candle/tei.rs
Labels: kind/bug, area/ai

#3843 Fix models integration tests
  crates/runtime/Cargo.toml
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_completion.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_ai_completion_input.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_2_document_similarity_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__embeddings__base64_format.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__embeddings__basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__embeddings__multiple_inputs.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_all_datasets_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_basic_response.snap
Labels: kind/enhancement

#3844 Enable `spice login abfs`
  bin/spice/cmd/login.go
  bin/spice/pkg/api/auth.go
Labels: kind/enhancement

#3846 update `crates/llms` dependencies to 'spiceai' branch
  Cargo.lock
  crates/llms/Cargo.toml
Labels: kind/dependencies, area/ai

#3780 Make eval runs non-blocking; `spice.eval.{results, runs}` tables.
  crates/runtime/benches/setup/mod.rs
  crates/runtime/src/dataconnector/sink.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/flight/do_put.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/http/v1/eval.rs
  crates/runtime/src/init/eval.rs
  crates/runtime/src/init/eval_scorer.rs
  crates/runtime/src/init/mod.rs
  crates/runtime/src/init/task_history.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/eval/dataset.rs
  crates/runtime/src/model/eval/mod.rs
  crates/runtime/src/model/eval/result.rs
  crates/runtime/src/model/eval/runs.rs
  crates/runtime/src/model/eval/scorer.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/opentelemetry.rs
  crates/runtime/src/spice_metrics.rs
  crates/runtime/src/task_history.rs
  crates/runtime/src/task_history/otel_exporter.rs
  crates/runtime/src/tools/memory/store.rs
  crates/runtime/src/tracing_util.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement, area/ai

#3849 fix: Update GraphQL snapshots
  crates/runtime/tests/snapshots/integration__test_graphql_select_swapi.snap
  crates/runtime/tests/snapshots/integration__test_graphql_select_tcgdex.snap
Labels: kind/bug

#3847 Update to Rust 1.83
  .github/actions/setup-rust/action.yml
  Cargo.toml
  Dockerfile
  bin/spiced/src/lib.rs
  bin/spiced/src/tracing.rs
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/object/text.rs
  crates/data_components/src/sharepoint/table.rs
  crates/db_connection_pool/src/snowflakepool.rs
  crates/llms/src/anthropic/types_stream.rs
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_object_store/mod.rs
  crates/runtime/benches/bench_search/setup.rs
  crates/runtime/benches/setup/mod.rs
  crates/runtime/benches/vector_search.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/embeddings/cosine_distance.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/http/v1/eval.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/http/v1/query.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/opentelemetry.rs
  crates/runtime/src/request/baggage.rs
  crates/runtime/src/secrets/lexer.rs
  crates/runtime/src/tools/builtin/list_datasets.rs
  crates/runtime/tests/delta_lake/mod.rs
Labels: kind/dependencies

#3848 feat: add mssql integration test
  .github/workflows/spice_mssql_tpch_bench_docker.yml
  crates/data_components/src/mssql/convert.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/mssql/common.rs
  crates/runtime/tests/mssql/mod.rs
  crates/runtime/tests/snapshots/integration__mssql__mssql_integration_test_select.snap
  crates/runtime/tests/snapshots/integration__mssql_integration_test_select.snap
Labels: kind/enhancement

#3850 Prepend user-specified user agent in flight repl
  crates/flightrepl/src/lib.rs
Labels: kind/enhancement

#3852 fix: trim CHAR in mssql
  crates/data_components/src/mssql/convert.rs
  crates/runtime/benches/bench_mssql/mod.rs
  crates/runtime/benches/bench_mssql/tpch_q12.sql
  crates/runtime/benches/bench_mssql/tpch_q19.sql
  crates/runtime/benches/snapshots/bench__mssql_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__mssql_tpch_simple_q4.snap
Labels: kind/bug

#3857 Fix column quoting for SpiceCloudPlatform dialect
  crates/data_components/src/flight/federation.rs
  crates/data_components/src/flightsql/federation.rs
  crates/runtime/src/dataconnector/spiceai.rs
Labels: kind/bug

#3861 Optimize builds
  .github/workflows/integration_llms.yml
  .github/workflows/spiced_docker_nightly.yml
Labels: kind/enhancement

#3859 Endgame template: Add recently added AI/ML quickstarts and samples
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/optimization

#3853 docs: Release MS SQL Beta
  README.md
Labels: kind/documentation

#3860 Fix nsql sampling for tables with embeddings
  crates/runtime/src/datafusion.rs
  crates/runtime/src/tools/builtin/sample/distinct.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__hf_with_sample_data_enabled_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__openai_with_sample_data_enabled_tasks.snap
Labels: kind/bug

#3863 Make GH workflows with spiceai-macos runners more stable
  .github/workflows/e2e_test_ci_models.yml
  .github/workflows/integration_models.yml
Labels: kind/bug

#3869 handle `max_completion_tokens` vs `max_tokens` for openai vs azure
  crates/llms/src/openai/chat.rs
  crates/llms/src/openai/mod.rs
Labels: kind/bug, area/ai

#3871 Search benchmark: write results to dataset
  crates/runtime/benches/bench_search/mod.rs
  crates/runtime/benches/bench_search/setup.rs
  crates/runtime/benches/vector_search.rs
Labels: kind/enhancement

#3864 Create `evalconverter` that creates spice eval components.
  Cargo.lock
  Cargo.toml
  crates/spicepod/src/component.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/eval.rs
  crates/spicepod/src/component/runtime.rs
  crates/spicepod/src/spec.rs
  tools/evalconverter/.gitignore
  tools/evalconverter/Cargo.toml
  tools/evalconverter/data/3d_globe_movement/samples.jsonl
  tools/evalconverter/eval/3d_globe_movement.yaml
  tools/evalconverter/src/eval.rs
  tools/evalconverter/src/main.rs
Labels: kind/enhancement, area/ai

#3876 Update quickstart in README.md
  README.md
Labels: kind/enhancement

#3885 Remove reference to spiceai-smart-demo from the repo home
  README.md
Labels: kind/optimization

#3884 Trace `evals` accelerated tables updates in debug mode
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/datafusion.rs
Labels: kind/bug

#3862 Clarify confusing log message
  crates/runtime/src/init/dataset.rs
Labels: kind/enhancement

#3883 Azure OpenAI models: make `endpoint` parameter required
  crates/runtime/src/model/chat.rs
Labels: kind/bug

#3856 Use spiceai delta kernel fork, actionable message for delta checkpoint errors
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/delta_lake.rs
Labels: kind/optimization

#3875 Add support for GGUF files in HF
  Makefile
  crates/llms/src/chat/mod.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/objectstore/hf.rs
Labels: kind/enhancement, area/ai

#3868 docs: Add release notes for rc.2
  docs/criteria/connectors/beta.md
  docs/release_notes/beta/v0.17.0-beta.md
  docs/release_notes/beta/v0.17.1-beta.md
  docs/release_notes/beta/v0.17.2-beta.md
  docs/release_notes/beta/v0.17.3-beta.md
  docs/release_notes/beta/v0.17.4-beta.md
  docs/release_notes/beta/v0.18.0-beta.md
  docs/release_notes/beta/v0.18.1-beta.md
  docs/release_notes/beta/v0.18.2-beta.md
  docs/release_notes/beta/v0.18.3-beta.md
  docs/release_notes/beta/v0.19.0-beta.md
  docs/release_notes/beta/v0.19.1-beta.md
  docs/release_notes/beta/v0.19.2-beta.md
  docs/release_notes/beta/v0.19.3-beta.md
  docs/release_notes/beta/v0.19.4-beta.md
  docs/release_notes/beta/v0.20.0-beta.md
  docs/release_notes/v1.0.0-rc.2.md
Labels: kind/documentation

#3894 Disable read_write mode support for Postgres Data Connector
  crates/runtime/src/dataconnector/postgres.rs
Labels: kind/enhancement

#3888 Add CI configuration for search benchmark dataset access
  .github/workflows/benchmarks_search.yml
Labels: kind/optimization

#3896 Upgrade dependencies
  Cargo.lock
  Cargo.toml
  tools/evalconverter/Cargo.toml
Labels: kind/dependencies

#3899 chore: Update helm chart for RC.2
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#3901 chore: Update MacOS test release install to macos-13
  .github/workflows/e2e_test_release_install.yml
Labels: kind/bug

#3898 Add usage to `spice chat` and fix `v1/models?status=true`.
  bin/spice/cmd/chat.go
  crates/runtime/src/http/v1/models.rs
  crates/runtime/src/status.rs
Labels: kind/enhancement, area/ai

#3902 chore: Bump versions for rc3
  .github/ISSUE_TEMPLATE/end_game.md
  Cargo.lock
  Cargo.toml
  SECURITY.md
  docs/ROADMAP.md
  version.txt
Labels: kind/enhancement

#3897 docs: Update endgame with a step to verify dependencies in release notes
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#3900 Ensure eval dataset input and ouput of correct length
  crates/runtime/src/http/v1/eval.rs
  crates/runtime/src/model/eval/mod.rs
Labels: kind/enhancement, area/ai

#3905 `spice add/connect/dataset configure` should update spicepod, not overwrite it & upgrade to Go 1.23
  .github/workflows/build_and_release.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_ci_models.yml
  .github/workflows/license_check.yml
  .github/workflows/makefile_targets.yml
  .github/workflows/pr.yml
  .github/workflows/types_check.yml
  CONTRIBUTING.md
  bin/spice/cmd/dataset.go
  bin/spice/pkg/spec/component.go
  bin/spice/pkg/spec/dataset.go
  bin/spice/pkg/spec/spicepod.go
  bin/spice/pkg/spec/spicepod_test.go
  bin/spice/pkg/spicepod/spicepod.go
  go.mod
Labels: kind/enhancement

#3906 Ensure trace_id is overridden for prior written spans
  crates/runtime/src/task_history.rs
  crates/runtime/src/task_history/otel_exporter.rs
Labels: kind/bug, area/ai

#3910 add 'role': 'assistant' for local models
  crates/llms/src/chat/mod.rs
Labels: kind/bug, area/ai

#3928 Update to reference cookbook instead of quickstarts/samples
  .github/ISSUE_TEMPLATE/end_game.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/criteria/accelerators/alpha.md
  docs/criteria/accelerators/beta.md
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
  docs/criteria/connectors/rc.md
Labels: kind/documentation

#3930 Fix/remove flaky integration tests
  crates/runtime/tests/graphql/mod.rs
  crates/runtime/tests/snapshots/integration__test_graphql_select_tcgdex.snap
Labels: kind/bug

#3923 Implement `/v1/iceberg/namespaces` & `/v1/iceberg/config` APIs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/iceberg/error.rs
  crates/runtime/src/http/v1/iceberg/mod.rs
  crates/runtime/src/http/v1/iceberg/namespace.rs
  crates/runtime/src/http/v1/mod.rs
Labels: kind/enhancement

#3931 Add script for creating tpcds parquet files and spicepod for file connector
  test/tpc-bench/Makefile
Labels: kind/enhancement, kind/task

#3927 Use `utoipa` to generate openapi.json and swagger for dev
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/catalogs.rs
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/http/v1/embeddings.rs
  crates/runtime/src/http/v1/eval.rs
  crates/runtime/src/http/v1/iceberg/error.rs
  crates/runtime/src/http/v1/iceberg/mod.rs
  crates/runtime/src/http/v1/iceberg/namespace.rs
  crates/runtime/src/http/v1/inference.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/models.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/http/v1/packages.rs
  crates/runtime/src/http/v1/query.rs
  crates/runtime/src/http/v1/ready.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/http/v1/spicepods.rs
  crates/runtime/src/http/v1/status.rs
  crates/runtime/src/http/v1/tools.rs
  crates/runtime/src/model/eval/runs.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/status.rs
  crates/runtime/src/tools/builtin/sample/distinct.rs
  crates/runtime/src/tools/builtin/sample/mod.rs
  crates/runtime/src/tools/builtin/sample/random.rs
  crates/runtime/src/tools/builtin/sample/top_samples.rs
  crates/spicepod/Cargo.toml
Labels: kind/enhancement

#3926 `fuzzy_match`, `json_match`, `includes` scorer
  Cargo.lock
  Cargo.toml
  crates/llms/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/model/eval/scorer/fuzzy_match.rs
  crates/runtime/src/model/eval/scorer/includes.rs
  crates/runtime/src/model/eval/scorer/json_match.rs
  crates/runtime/src/model/eval/scorer/match_.rs
  crates/runtime/src/model/eval/scorer/mod.rs
Labels: kind/enhancement, area/ai

#3933 Implement `/v1/iceberg/namespaces/:namespace`
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/iceberg/mod.rs
  crates/runtime/src/http/v1/iceberg/namespace.rs
Labels: kind/enhancement

#3934 Implement `GET /v1/iceberg/namespaces/:namespace/tables` API
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/iceberg/mod.rs
  crates/runtime/src/http/v1/iceberg/namespace.rs
Labels: kind/enhancement

#3938 Add custom Spice DuckDB dialect with cosine_distance support
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/dialect/duckdb.rs
  crates/runtime/src/datafusion/dialect/mod.rs
Labels: kind/bug

#3947 Fix NSQL error: `all columns in a record batch must have the same length`
  crates/runtime/src/tools/builtin/sample/distinct.rs
Labels: kind/bug

#3955 Don't include tools use in hf test model
  test/models/spicepod_hf.yml
Labels: kind/bug, area/ai

#3940 Implement `GET /v1/namespaces/{namespace}/tables/{table}` API
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/iceberg/error.rs
  crates/runtime/src/http/v1/iceberg/mod.rs
  crates/runtime/src/http/v1/iceberg/namespace.rs
  crates/runtime/src/http/v1/iceberg/tables.rs
Labels: kind/enhancement

#3967 Update dependencies
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
Labels: kind/dependencies

#3961 DuckDB: add support for nested types in Lists
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#3945 Add script to set up clickbench for file connector
  test/scripts/clickbench/setup-file.bash
Labels: kind/enhancement, kind/task

#3908 docs: Add connector stable criteria
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
  docs/criteria/connectors/rc.md
  docs/criteria/connectors/stable.md
  docs/criteria/definitions.md
Labels: kind/documentation

#3978 Update Roadmp Dec 23, 2024
  docs/ROADMAP.md
Labels: kind/documentation

#3948 Improve CI testing for OpenAPI, new tool `spiceschema`, fix broken OpenAPI stuff.
  .github/workflows/features.yml
  .github/workflows/generate-openapi.yml
  Cargo.lock
  Cargo.toml
  crates/runtime/.gitignore
  crates/runtime/Cargo.toml
  crates/runtime/src/http.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/catalogs.rs
  crates/runtime/src/http/v1/chat.rs
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/http/v1/embeddings.rs
  crates/runtime/src/http/v1/eval.rs
  crates/runtime/src/http/v1/iceberg/mod.rs
  crates/runtime/src/http/v1/iceberg/tables.rs
  crates/runtime/src/http/v1/inference.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/models.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/http/v1/packages.rs
  crates/runtime/src/http/v1/query.rs
  crates/runtime/src/http/v1/ready.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/http/v1/spicepods.rs
  crates/runtime/src/http/v1/status.rs
  crates/runtime/src/http/v1/tools.rs
  crates/runtime/src/lib.rs
  tools/spiceschema/Cargo.toml
  tools/spiceschema/src/main.rs
Labels: kind/bug, area/ci

#3981 remove `v1/datasets/sample`
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/datasets.rs
Labels: kind/bug, area/data-connectors, area/quality, breaking change

#3975 feat: add SQLite ClickBench benchmark
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench_object_store/mod.rs
  crates/runtime/benches/bench_search/setup.rs
  crates/runtime/benches/setup/mod.rs
  crates/runtime/benches/utils/mod.rs
Labels: kind/enhancement

#3984 Remove feature 'llms/mistralrs'
  crates/llms/Cargo.toml
  crates/llms/src/chat/mod.rs
  crates/runtime/Cargo.toml
Labels: kind/bug, area/ai, kind/task

#3985 Add support for 'params.spiced_tools: nsql'
  Cargo.lock
  crates/runtime/src/tools/builtin/catalog.rs
  crates/runtime/src/tools/builtin/mod.rs
  crates/runtime/src/tools/options.rs
  crates/runtime/src/tools/utils.rs
Labels: kind/enhancement, area/ai

#3989 Fix integration tests - add missing `format` query parameter in /v1/status requests
  crates/runtime/tests/endpoint_auth/http.rs
Labels: kind/bug

#3959 Enhance AI tools sampling logic for robust handling of large fields
  crates/arrow_tools/src/record_batch.rs
  crates/runtime/src/tools/builtin/sample/tool.rs
Labels: kind/bug

#3991 Fix subquery federation
  Cargo.lock
  Cargo.toml
Labels: kind/optimization

#3995 Fix unnest and add DuckDB support for `array_element`
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#3996 Add score value snapshotting to vector similarity search tests
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_all_datasets_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_chunking_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_all_datasets_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_chunking_response.snap
Labels: kind/enhancement

#3992 Use Llama-3.2-3B-Instruct for Hugging Face integration testing
  .github/workflows/integration_models.yml
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__hf_with_model_tasks.snap
Labels: kind/enhancement

#3988 Simplify `construct_chunk_query_sql` for DuckDB compatibility
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/enhancement

#3997 Correctly pass Hugging Face token in models integration tests
  crates/runtime/tests/models/hf.rs
Labels: kind/bug

#3998 Fix: `on_zero_results` causes `TransactionContext Error: Catalog write-write conflict on create with "attachment_0"`
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#4000 Add DuckDB acceleration to search benchmarks
  .github/workflows/benchmarks_search.yml
  crates/runtime/benches/bench_search/datasets.rs
  crates/runtime/benches/bench_search/setup.rs
  crates/runtime/benches/vector_search.rs
Labels: kind/enhancement

#4004 Enable Postgres write via non-default `postgres-write` feature flag
  bin/spiced/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector/postgres.rs
Labels: kind/enhancement

#4008 Allow search benchmark to write test results
  .github/workflows/benchmarks_search.yml
Labels: kind/optimization

#4002 Make Flight DoPut atomic and commit write only on successful stream completion
  crates/runtime/src/datafusion.rs
  crates/runtime/src/flight/do_put.rs
  crates/runtime/tests/flight/do_put.rs
  crates/runtime/tests/flight/mod.rs
  crates/runtime/tests/flight/snapshots/integration__flight__do_put__do_put_basic_reponse.snap
  crates/runtime/tests/flight/snapshots/integration__flight__do_put__do_put_basic_table_content.snap
  crates/runtime/tests/flight/snapshots/integration__flight__do_put__stream_error_table_content.snap
  crates/runtime/tests/integration.rs
Labels: kind/enhancement

#4003 Create a `CatalogConnector` abstraction
  Cargo.lock
  crates/data_components/src/lib.rs
  crates/data_components/src/unity_catalog.rs
  crates/data_components/src/unity_catalog/provider.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/catalogconnector/databricks.rs
  crates/runtime/src/catalogconnector/mod.rs
  crates/runtime/src/catalogconnector/unity_catalog.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/localpod.rs
  crates/runtime/src/dataconnector/memory.rs
  crates/runtime/src/dataconnector/mssql.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/sharepoint.rs
  crates/runtime/src/dataconnector/sink.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/init/catalog.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/init/model.rs
  crates/runtime/src/init/tool.rs
  crates/runtime/src/lib.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement

#3983 Fix `generate-openapi.yml` and add `.schema/openapi.json`.
  .github/workflows/generate-openapi.yml
  .schema/openapi.json
Labels: kind/bug, area/ci

#4001 Enable spice.ai tpcds bench workflow. Comment failing tpch queries.
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench_spicecloud/mod.rs
Labels: kind/bug

#4016 feat: Add SQLite ClickBench overrides
  crates/runtime/benches/bench_object_store/mod.rs
  crates/runtime/benches/queries/clickbench/sqlite/q19.sql
  crates/runtime/benches/queries/clickbench/sqlite/q24.sql
  crates/runtime/benches/queries/clickbench/sqlite/q25.sql
  crates/runtime/benches/queries/clickbench/sqlite/q27.sql
  crates/runtime/benches/queries/clickbench/sqlite/q37.sql
  crates/runtime/benches/queries/clickbench/sqlite/q38.sql
  crates/runtime/benches/queries/clickbench/sqlite/q39.sql
  crates/runtime/benches/queries/clickbench/sqlite/q40.sql
  crates/runtime/benches/queries/clickbench/sqlite/q41.sql
  crates/runtime/benches/queries/clickbench/sqlite/q42.sql
  crates/runtime/benches/queries/clickbench/sqlite/q43.sql
  crates/runtime/benches/queries/clickbench/sqlite/q7.sql
Labels: kind/enhancement

#4053 Implement Iceberg Catalog Connector
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/iceberg/catalog.rs
  crates/data_components/src/iceberg/mod.rs
  crates/data_components/src/iceberg/provider.rs
  crates/data_components/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/runtime/src/catalogconnector/mod.rs
  crates/runtime/src/http.rs
  crates/runtime/src/http/v1/iceberg/mod.rs
  crates/runtime/src/parameters.rs
Labels: kind/enhancement

#4054 feat: Datafusion updates for SQLite fixes and release
  Cargo.lock
  Cargo.toml
  README.md
  crates/runtime/benches/bench_object_store/mod.rs
  crates/runtime/benches/queries/clickbench/sqlite/q19.sql
  crates/runtime/benches/queries/clickbench/sqlite/q24.sql
  crates/runtime/benches/queries/clickbench/sqlite/q25.sql
  crates/runtime/benches/queries/clickbench/sqlite/q27.sql
  crates/runtime/benches/queries/clickbench/sqlite/q37.sql
  crates/runtime/benches/queries/clickbench/sqlite/q38.sql
  crates/runtime/benches/queries/clickbench/sqlite/q39.sql
  crates/runtime/benches/queries/clickbench/sqlite/q40.sql
  crates/runtime/benches/queries/clickbench/sqlite/q41.sql
  crates/runtime/benches/queries/clickbench/sqlite/q42.sql
  crates/runtime/benches/queries/clickbench/sqlite/q43.sql
  crates/runtime/benches/queries/clickbench/sqlite/q7.sql
  docs/criteria/accelerators/rc.md
Labels: kind/enhancement

#4017 docs: Add accelerator stable release criteria
  docs/criteria/accelerators/rc.md
  docs/criteria/accelerators/stable.md
Labels: kind/documentation

#4019 Update docs, and make PR to `spiceai/docs` for new `openapi.json`.
  .github/workflows/generate-openapi.yml
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/http/v1/tools.rs
Labels: kind/documentation, area/ci

#4064 Fix dremio subquery rewrite
  Cargo.lock
  Cargo.toml
  crates/data_components/src/flight.rs
  crates/data_components/src/flight/federation.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/spiceai.rs
Labels: kind/bug, kind/enhancement

#4073 Update generate-openapi.yml
  .github/workflows/generate-openapi.yml
Labels: kind/enhancement

#4052 docs: Add catalog criteria
  docs/criteria/catalogs/alpha.md
  docs/criteria/catalogs/beta.md
  docs/criteria/catalogs/rc.md
  docs/criteria/catalogs/stable.md
Labels: kind/documentation

#4074 fix `distinct_columns` in auto/nsql tool groups
  crates/runtime/src/tools/options.rs
Labels: kind/bug

#4012 Implement window_func_support_window_frame from DremioDialect
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataconnector/dremio.rs
Labels: kind/bug, kind/enhancement

#4080 Promote file connector to rc
  README.md
  docs/criteria/connectors/rc.md
Labels: kind/enhancement

#4085 Add Iceberg to README
  README.md
Labels: kind/enhancement

#4081 Fix '/v1/status' default format
  crates/runtime/src/http/v1/status.rs
Labels: kind/bug

#4068 Add v1.0.0.0-rc.3 release notes
  docs/ROADMAP.md
  docs/release_notes/v1.0.0-rc.3.md
Labels: kind/documentation

#4088 Update Helm chart for v1.0.0-rc.3 (v0.2.2)
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/documentation, area/deployment

#4090 Rev version to v1.0.0-rc.4
  Cargo.lock
  Cargo.toml
  SECURITY.md
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
  version.txt
Labels: kind/documentation

#4084 Fix OpenAI Models Integration tests
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__openai_basic_tasks.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_ai_completion_input.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_sql_tasks.snap
Labels: kind/bug

#4092 fix: Update Postgres TPCDS and ClickBench queries
  crates/runtime/benches/bench_object_store/mod.rs
  crates/runtime/benches/bench_postgres/mod.rs
  crates/runtime/benches/queries/README.md
  crates/runtime/benches/queries/clickbench/postgres/q43.sql
  crates/runtime/benches/queries/tpcds/postgres/q36.sql
  crates/runtime/benches/queries/tpcds/postgres/q70.sql
  crates/runtime/benches/queries/tpcds/postgres/q86.sql
  crates/runtime/benches/queries/tpcds/sqlite/q49.sql
  crates/runtime/benches/queries/tpcds/sqlite/q75.sql
  crates/runtime/benches/queries/tpcds/sqlite/q90.sql
  test/scripts/run-queries.bash
Labels: kind/bug

#4094 fix: Check Postgres acceleration schema on insert
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#4096 Update v1.0.0-rc.3.md
  docs/release_notes/v1.0.0-rc.3.md
Labels: kind/documentation
