Repository spiceai/spiceai, pull requests merged in 2025-10, with the labels that each got.

#7381 Robust search test
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_column_with_where_response.snap
Labels: kind/bug, area/ai

#7383 [bug] Fix ai UDF bug of mismatched column length
  crates/runtime-datafusion-udfs/src/ai.rs
Labels: kind/bug, area/ai

#7379 Add OpenOption to spice_sys acceleration tables
  crates/runtime/src/dataaccelerator/spice_sys.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/mod.rs
  crates/runtime/src/dataaccelerator/spice_sys/debezium_kafka/mod.rs
  crates/runtime/src/dataaccelerator/spice_sys/kafka/duckdb.rs
  crates/runtime/src/dataaccelerator/spice_sys/kafka/mod.rs
  crates/runtime/src/dataaccelerator/spice_sys/kafka/sqlite.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/kafka.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/federated_table/mod.rs
  crates/runtime/tests/acceleration/mod.rs
  crates/runtime/tests/view/mod.rs
Labels: kind/enhancement

#7395 Fix minor lint warnings
  crates/db_connection_pool/src/dbconnection/odbcconn.rs
  crates/scheduler/src/channel/cron.rs
  crates/test-framework/src/metrics/mod.rs
  crates/test-framework/src/utils/mod.rs
Labels: kind/task

#7397 Enable metadata columns in document-based object store datasets
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/object/text.rs
  crates/runtime/src/dataconnector/listing/connector.rs
Labels: kind/enhancement, area/ai

#7400 Core dependencies of financebench
  test/spicepods/financebench/core/evals/spicepod.yaml
  test/spicepods/financebench/core/models/spicepod.yaml
Labels: kind/bug, kind/refactor

#7398 Set PostgreSQL unsupported_spice_action=string by default
  crates/runtime/src/dataconnector/postgres.rs
Labels: kind/enhancement, breaking change

#7401 Use non-blocking connection check for verify_ns_lookup_and_tcp_connect
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#7402 Forbid `INSERT OVERWRITE` DML operations
  crates/runtime/src/datafusion/sql_validator.rs
Labels: kind/optimization

#7405 Disable vector index only scans
  crates/runtime/src/embeddings/index/scan_table.rs
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_basic.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_basic_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_basic_multiple_pk.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_filter.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_filter_multiple_pk.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_projection.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_projection_multiple_pk.snap
Labels: kind/enhancement, area/ai

#7313 Read and write partitioned S3 indexes
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/s3_vectors/list_provider.rs
  crates/data_components/src/s3_vectors/mod.rs
  crates/data_components/src/s3_vectors/partition.rs
  crates/data_components/src/s3_vectors/query_provider.rs
  crates/data_components/src/s3_vectors/vector_table.rs
  crates/runtime-table-partition/src/expression.rs
  crates/runtime-table-partition/src/insert.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/index/s3/index.rs
  crates/runtime/src/embeddings/index/s3/mod.rs
  crates/runtime/src/embeddings/index/s3/write.rs
  crates/runtime/tests/models/s3_vectors.rs
  crates/s3_vectors/src/lib.rs
  crates/s3_vectors/src/mock.rs
  crates/spicepod/src/vector.rs
Labels: kind/enhancement

#7411 Fix partial data writes in Iceberg data connector
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#7416 Use DataFusion JoinSetTracer for async context propagation
  crates/runtime/src/builder.rs
  crates/runtime/src/tracers.rs
Labels: kind/enhancement

#7408 Use LogicalPlan builder API for LogicalPlans
  crates/runtime/src/embeddings/index/scan_table.rs
  crates/runtime/src/embeddings/udtf.rs
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__filters_pushdown_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_chunking_vector_search_sql_match_and_underlying_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_chunking_vector_search_sql_match_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_chunking_vector_search_sql_offset_explain.snap
  crates/search/src/generation/text_search/index.rs
  crates/search/src/index/s3_vectors/mod.rs
  crates/search/src/provider.rs
Labels: kind/refactor, area/ai

#7421 Limit results from `SearchIndex::query_table_provider`
  crates/search/src/provider.rs
Labels: kind/optimization, area/ai

#7425 Delay initial readiness if snapshots are enabled with an append-mode refresh
  crates/runtime/src/datafusion/mod.rs
Labels: kind/enhancement

#7426 Disable snapshots by default
  bin/spiced/Cargo.toml
  crates/runtime-acceleration/Cargo.toml
  crates/runtime/Cargo.toml
Labels: kind/enhancement

#7413 Rewrite `ChunkedNonIndexVectorGeneration` to use LogicalPlanBuilder (instead of string formatting).
  crates/runtime/src/search/candidate/vector.rs
  crates/search/src/generation.rs
Labels: kind/refactor, area/ai

#7429 Fix for search field as metadata for chunked search indexes
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/index/s3/mod.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_chunking_vector_search_sql_match_and_underlying_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_chunking_vector_search_sql_match_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_chunking_vector_search_sql_offset_explain.snap
  crates/search/src/index/chunking.rs
  crates/search/src/index/s3_vectors/mod.rs
Labels: kind/bug, area/ai

#7440 Add preview warning for write access mode
  crates/runtime/src/datafusion/mod.rs
Labels: kind/enhancement

#7437 Add recent improvements into 1.8
  bin/spiced/Cargo.toml
  crates/app/src/lib.rs
  crates/runtime-acceleration/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/index/s3/mod.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_chunking_vector_search_sql_match_and_underlying_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_chunking_vector_search_sql_match_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_chunking_vector_search_sql_offset_explain.snap
  crates/search/src/index/chunking.rs
  crates/search/src/index/s3_vectors/mod.rs
Labels: kind/endgame

#7415 Fix tracing so that ai_completions are parented under sql_query
  .github/workflows/integration_models.yml
  Cargo.lock
  crates/data_components/src/unity_catalog.rs
  crates/llms/src/chat/mod.rs
  crates/runtime-datafusion-udfs/Cargo.toml
  crates/runtime-datafusion-udfs/src/ai.rs
  crates/runtime/src/tracers.rs
  crates/runtime/tests/models/AI_UDF_TESTS.md
  crates/runtime/tests/models/ai_udf.rs
  crates/runtime/tests/models/mod.rs
Labels: kind/bug, area/ai

#7450 Disable acceleration refresh metrics
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/timestamp_metrics_utils.rs
Labels: kind/enhancement

#7430 Add v1.8 release notes
  docs/release_notes/v1.7/v1.7.0.md
  docs/release_notes/v1.7/v1.7.1.md
  docs/release_notes/v1.8.0.md
Labels: kind/documentation

#7454 Fix lint error due to ignore without reasons
  crates/runtime/src/accelerated_table/timestamp_metrics_utils.rs
Labels: kind/bug

#7455 Post-release 1.8 updates
  .github/workflows/testoperator_dispatch.yml
  Cargo.lock
  Cargo.toml
  SECURITY.md
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
  docs/ROADMAP.md
  version.txt
Labels: kind/documentation

#7463 Remove italics from snapshot logging
  crates/runtime-acceleration/src/snapshot/mod.rs
Labels: kind/enhancement
