Repository spiceai/spiceai, pull requests merged in 2025-07, with the labels that each got.

#6317 Surface table not found errors immediately
  crates/runtime/src/flight/mod.rs
Labels: kind/bug, kind/dependencies

#6359 Ensure views load even if they're the only components defined
  crates/runtime/src/init/dataset.rs
Labels: kind/bug

#6327 Improve type conversion and add integration tests for the Oracle connector
  .github/workflows/integration.yml
  crates/data_components/src/oracle/convert.rs
  crates/data_components/src/oracle/mod.rs
  crates/runtime/tests/abfs/mod.rs
  crates/runtime/tests/docker/mod.rs
  crates/runtime/tests/dynamodb/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/mssql/common.rs
  crates/runtime/tests/mysql/common.rs
  crates/runtime/tests/oracle/common.rs
  crates/runtime/tests/oracle/mod.rs
  crates/runtime/tests/oracle/snapshots/integration__oracle__data.snap
  crates/runtime/tests/oracle/snapshots/integration__oracle__filters_pushdown_query_plan.snap
  crates/runtime/tests/oracle/snapshots/integration__oracle__filters_pushdown_query_result.snap
  crates/runtime/tests/oracle/snapshots/integration__oracle__schema.snap
  crates/runtime/tests/postgres/common.rs
Labels: kind/enhancement

#6368 Partitioning TableProvider::scan and streaming ExecutionPlan
  Cargo.lock
  crates/runtime-table-partition/Cargo.toml
  crates/runtime-table-partition/src/creator.rs
  crates/runtime-table-partition/src/insert.rs
  crates/runtime-table-partition/src/lib.rs
  crates/runtime-table-partition/src/provider.rs
  crates/runtime/src/dataaccelerator/partitioned_duckdb.rs
  crates/runtime/src/dataaccelerator/spice_sys.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/mod.rs
  crates/runtime/src/dataaccelerator/spice_sys/debezium_kafka/mod.rs
Labels: kind/enhancement

#6375 Upgrade dependabot dependencies
  Cargo.lock
  crates/scheduler/Cargo.toml
  crates/test-framework/Cargo.toml
  go.mod
  go.sum
Labels: kind/dependencies

#6379 Don't run tests that require a Databricks cluster on every PR
  .github/ISSUE_TEMPLATE/end_game.md
  .github/workflows/integration.yml
  crates/runtime/tests/databricks_delta_catalog_m2m/mod.rs
  crates/runtime/tests/databricks_delta_m2m/mod.rs
  crates/runtime/tests/databricks_spark/mod.rs
  crates/runtime/tests/databricks_spark_catalog/mod.rs
  crates/runtime/tests/databricks_spark_catalog_m2m/mod.rs
  crates/runtime/tests/databricks_spark_m2m/mod.rs
  crates/runtime/tests/odbc/mod.rs
  crates/runtime/tests/spark/mod.rs
Labels: kind/bug

#6364 Properly handle duplicate flags to `spice run`
  bin/spice/pkg/context/context.go
Labels: kind/bug

#6360 Enable configuring otel endpoint from `spice run`
  bin/spice/cmd/run.go
  bin/spice/pkg/context/context.go
Labels: kind/bug

#6395 Enable Oracle connector in default build configuration
  bin/spiced/Cargo.toml
Labels: kind/bug

#6396 Change version to 1.5.0-rc.1 and include recent fixes
  Cargo.lock
  Cargo.toml
  bin/spice/cmd/run.go
  bin/spice/pkg/context/context.go
  bin/spiced/Cargo.toml
  crates/runtime/src/model/params/openai.rs
  version.txt
Labels: kind/enhancement

#6398 Fix perplexity model parameters in llm integration tests
  crates/llms/tests/llms/create.rs
Labels: kind/bug

#6407 Update v1.5.0-rc.1.md
  docs/release_notes/v1.5.0-rc.1.md
Labels: kind/bug

#6405 Improve error messages
  crates/llms/src/embeddings/mod.rs
  crates/runtime/src/init/dataset.rs
Labels: kind/bug

#6369 docs: update the SpiceQA workflow verification instruction
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#6338 Add a PartitionedDuckDB Accelerator
  Cargo.lock
  Makefile
  crates/runtime-table-partition/Cargo.toml
  crates/runtime-table-partition/src/creator.rs
  crates/runtime-table-partition/src/insert.rs
  crates/runtime-table-partition/src/lib.rs
  crates/runtime-table-partition/src/provider.rs
  crates/runtime-table-partition/src/provider/pruning.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/component/dataset/mod.rs
  crates/runtime/src/component/view.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/mod.rs
  crates/runtime/src/dataaccelerator/partitioned_duckdb.rs
  crates/runtime/src/dataaccelerator/spice_sys.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/init/view.rs
Labels: kind/enhancement

#6419 Update endgame template - include json schema update into the release branch
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#6409 Add supported types for partitioning expressions
  crates/runtime-table-partition/src/creator/filename.rs
Labels: kind/enhancement

#6426 Enable session time zone override for MySQL
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/tests/mysql/mod.rs
  crates/runtime/tests/mysql/snapshots/integration__mysql__custom_time_zone.snap
  crates/runtime/tests/mysql/snapshots/integration__mysql__system_time_zone.snap
Labels: kind/enhancement

#6382 Acceleration-like indexing for full text search indexes.
  crates/runtime-datafusion-index/src/lib.rs
  crates/runtime-datafusion-index/src/provider.rs
  crates/runtime/src/search/full_text/index.rs
  crates/runtime/src/search/full_text/mod.rs
  crates/runtime/src/search/full_text/util.rs
Labels: kind/enhancement, area/ai

#6421 Add support for Oracle Autonomous Database connections (Oracle Cloud)
  .github/workflows/integration.yml
  crates/data_components/src/oracle/connection.rs
  crates/data_components/src/oracle/mod.rs
  crates/runtime/src/dataconnector/oracle.rs
  crates/runtime/tests/oracle/common.rs
  crates/runtime/tests/oracle/mod.rs
  crates/runtime/tests/oracle/snapshots/integration__oracle__oracle_cloud_query_result.snap
Labels: kind/enhancement

#6423 prune partitions for exact and in list with and without UDFs
  Cargo.lock
  crates/runtime-table-partition/Cargo.toml
  crates/runtime-table-partition/src/provider.rs
  crates/runtime-table-partition/src/provider/pruning.rs
Labels: kind/enhancement

#6434 Upgrade DuckDB to 1.3.2
  Cargo.lock
  Cargo.toml
Labels: kind/dependencies

#6443 Fix issue in limit clause for the Github Data connector
  crates/data_components/src/graphql/client.rs
  crates/runtime/tests/graphql/mod.rs
  crates/runtime/tests/snapshots/integration__graphql__graphql_pagination_with_limit.snap
Labels: kind/bug

#6462 Update qa_analytics.csv
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#6466 Add option to preinstall Oracle ODPI-C library in Docker image
  Dockerfile
Labels: kind/enhancement

#6474 v1.5.0-rc.3 release notes
  docs/release_notes/v1.5.0-rc.3.md
Labels: kind/documentation

#6469 Add integration tests for S3 Vectors filters pushdown
  .github/workflows/integration_models.yml
  crates/runtime/tests/integration_models.rs
  crates/runtime/tests/models/bedrock.rs
  crates/runtime/tests/models/s3_vectors.rs
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__basic_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__filters_pushdown.snap
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__filters_pushdown_explain.snap
  crates/spicepod/src/semantic.rs
Labels: kind/enhancement

#6478 Check for `IndexedTableProvider` when finding tables to vector search upon.
  crates/runtime/src/search/util.rs
Labels: kind/bug, area/ai

#6480 Add integration test for S3 Vectors to cover data update (overwrite)
  crates/runtime/tests/models/s3_vectors.rs
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__data_v1.snap
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__data_v2.snap
Labels: kind/enhancement

#6481 Add 'Run all tests' option for models tests and enable Bedrock tests
  .github/workflows/integration_models.yml
  crates/runtime/tests/models/bedrock.rs
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__cohere-english_comparison_test.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__cohere-english_multiple_texts_float.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__cohere-english_single_text_float.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__cohere-multilingual_comparison_test.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__cohere-multilingual_french_text_float.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__cohere-multilingual_multilingual_texts_float.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__titan-1024_dim_1024.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__titan-256_dim_256.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__titan-512_dim_512.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__titan-v1_comparison_test.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__titan-v1_multiple_texts_float.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__titan-v1_single_text_base64.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__titan-v1_single_text_float.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__titan-v2_comparison_test.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__titan-v2_multiple_texts_float_512.snap
  crates/runtime/tests/models/snapshots/integration_models__models__embedding__titan-v2_single_text_float_512.snap
Labels: kind/optimization

#6487 Don't infer `FixedSizeList` size during indexing vectors.
  crates/runtime/src/embeddings/execution_plan.rs
Labels: kind/bug, area/ai

#6489 Make dataset refresh progress tracing less verbose
  crates/runtime/src/accelerated_table/refresh_task.rs
Labels: kind/bug

#6497 Upgade dependabot dependencies
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/runtime/Cargo.toml
  go.mod
  go.sum
Labels: kind/dependencies

#6499 Add periodic tracing of data loading progress during dataset refresh
  crates/runtime/src/accelerated_table/refresh_task.rs
Labels: kind/enhancement

#6503 Promote Oracle Data Connector to Alpha
  README.md
  docs/criteria/connectors/alpha.md
Labels: kind/optimization

#6498 Use AWS SDK to provide credentials for Iceberg connectors
  Cargo.lock
  Cargo.toml
  crates/data_components/src/iceberg/catalog.rs
  crates/iceberg-aws-sdk/Cargo.toml
  crates/iceberg-aws-sdk/src/credential_provider.rs
  crates/iceberg-aws-sdk/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/runtime/src/dataconnector/iceberg.rs
Labels: kind/enhancement

#6491 Use top-level table in full-text search `JOIN ON`
  crates/runtime/src/search/full_text/analyzer_rule.rs
  crates/runtime/src/search/full_text/udtf.rs
Labels: kind/bug, area/ai

#6516 Use accelerated table in vector_search JOIN operations when appropriate
  crates/runtime/src/embeddings/index/query_table.rs
  crates/runtime/src/embeddings/udtf.rs
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__basic_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__filters_pushdown_explain.snap
Labels: kind/performance, kind/refactor

#6512 Fix 'additional_column' for quoted columns (fix for qualified columns broke it)
  crates/runtime/src/search/request.rs
Labels: kind/bug, area/ai

#6504 Also use AWS SDK for inferring credentials for S3/Delta/Databricks Delta data connectors
  .github/workflows/integration_aws_sdk.yml
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/delta_lake.rs
  crates/object-store-aws-sdk/Cargo.toml
  crates/object-store-aws-sdk/src/credential_provider.rs
  crates/object-store-aws-sdk/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/object_store_registry/mod.rs
  crates/runtime/tests/aws_sdk/mod.rs
  crates/runtime/tests/aws_sdk/spicepods/aws_sdk_verify.yaml
  crates/runtime/tests/integration_aws_sdk.rs
  crates/runtime/tests/utils/mod.rs
  crates/spicepod/src/lib.rs
Labels: kind/enhancement

#6533 Suppress the warning from the AWS SDK if it can't load credentials
  bin/spiced/src/tracing.rs
Labels: kind/bug

#6539 README.md improvements for v1.5.0
  README.md
Labels: kind/documentation

#6537 Temporary disable plan verification in `s3_vectors_basic`
  crates/runtime/tests/models/s3_vectors.rs
Labels: kind/bug

#6374 Ensure binder errors show before query and other
  crates/runtime/src/flight/mod.rs
  crates/runtime/tests/flight/prepared_statements.rs
Labels: kind/bug

#6496 Update spiceai/duckdb-rs -> DuckDB 1.3.2 + index fix
  Cargo.lock
  Cargo.toml
Labels: kind/bug, area/data-accelerators

#6494 v1.5.0 release notes
  docs/release_notes/v1.5.0.md
Labels: kind/documentation

#6549 Fix refresh via Api when dataset is already accelerated and no refresh interval is set
  crates/runtime/src/accelerated_table/refresh.rs
Labels: kind/bug

#6562 Add reference to spice-rs v3.0.0 release in release notes
  docs/release_notes/v1.5.0.md
Labels: kind/documentation

#6563 Add reference to spice-rs v3.0.0 release in release notes
  docs/release_notes/v1.5.0.md
Labels: kind/documentation

#6540 Add support for custom GraphQL unnesting behavior
  crates/data_components/src/graphql/builder.rs
  crates/data_components/src/graphql/client.rs
  crates/runtime/src/dataconnector/github/commits.rs
  crates/runtime/src/dataconnector/github/issues.rs
  crates/runtime/src/dataconnector/github/members.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/github/pull_requests.rs
  crates/runtime/src/dataconnector/github/stargazers.rs
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/enhancement

#6568 v1.5.0 post-release updates
  .github/workflows/testoperator_dispatch.yml
  Cargo.lock
  Cargo.toml
  SECURITY.md
  docs/ROADMAP.md
  version.txt
Labels: kind/documentation

#6571 Update qa_analytics.csv as per 1.5.0 release
  docs/release_notes/qa_analytics.csv
Labels: kind/optimization

#6569 Initial support for PR comments
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/github/pull_requests.rs
Labels: kind/enhancement

#6547 chore: Update croner
  Cargo.lock
  crates/runtime/tests/acceleration/cron.rs
  crates/scheduler/Cargo.toml
  crates/scheduler/src/channel/cron.rs
  crates/scheduler/src/schedule.rs
  crates/scheduler/src/scheduler.rs
Labels: kind/dependencies

#6576 fix: Mismatched Spicecloud testoperator secrets
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_data_consistency.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
  test/spicepods/tpch/sf1/accelerated/spicecloud-arrow.yaml
Labels: kind/bug

#6583 Add `kind/documentation` to `.schema/openapi.json` auto-PRs
  .github/workflows/generate-openapi.yml
Labels: kind/documentation

#6585 Allow integration/e2e tests to run properly for PRs on forks
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_ci_models.yml
  .github/workflows/enforce-pulls-with-spice.yml
  .github/workflows/integration.yml
  .github/workflows/integration_aws_sdk.yml
  .github/workflows/integration_models.yml
  .github/workflows/integration_runtime_table_partition.yaml
Labels: kind/enhancement

#6586 Add `pull_request_target` to integration_models.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_ci_models.yml
  .github/workflows/integration.yml
  .github/workflows/integration_aws_sdk.yml
  .github/workflows/integration_models.yml
  .github/workflows/integration_runtime_table_partition.yaml
Labels: kind/enhancement

#6581 Add integration tests for GitHub PRs with comments
  .github/workflows/integration.yml
  crates/data_components/src/graphql/provider.rs
  crates/runtime/tests/github/mod.rs
  crates/runtime/tests/snapshots/integration__test_github_commits_auto.snap
  crates/runtime/tests/snapshots/integration__test_github_pull_requests_auto.snap
  crates/runtime/tests/snapshots/integration__test_github_stargazers_auto.snap
Labels: kind/enhancement

#6577 Initial snapshot tests for 'VectorQueryTableProvider'
  crates/runtime/src/embeddings/index/query_table.rs
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__query_table__tests__basic.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__query_table__tests__join_for_filter.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__query_table__tests__join_for_filter_use_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__query_table__tests__join_for_projection.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__query_table__tests__join_for_projection_use_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__query_table__tests__no_join_for_metadata_filter.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__query_table__tests__no_join_for_metadata_projection.snap
Labels: kind/enhancement, area/ai

#6592 Enable configurations of max invocations for Bedrock models
  crates/llms/src/bedrock/embed/mod.rs
  crates/runtime/src/model/embed.rs
Labels: kind/enhancement

#6579 Client-supplied cache keys (Spice-Cache-Key)
  .github/workflows/e2e_test_ci.yml
  crates/cache/src/key.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/builder.rs
  crates/runtime/src/datafusion/query/cache.rs
  crates/runtime/src/flight/mod.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/request/cache_control.rs
  crates/runtime/src/request/context.rs
  crates/runtime/src/search/vector_search.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
Labels: kind/enhancement

#6584 Update generate-openapi.yml
  .github/workflows/generate-openapi.yml
Labels: kind/documentation

#6582 Improved partition pruning
  Cargo.lock
  crates/runtime-table-partition/Cargo.toml
  crates/runtime-table-partition/src/provider.rs
  crates/runtime-table-partition/src/provider/pruning.rs
  crates/runtime-table-partition/tests/partition_table_provider.rs
Labels: kind/enhancement

#6595 Fix retention filter when both retention_sql and period are set
  crates/runtime/src/accelerated_table/retention.rs
  crates/runtime/tests/retention/mod.rs
  crates/runtime/tests/retention/snapshots/integration__retention__retention_sql.snap
  crates/runtime/tests/retention/snapshots/integration__retention__retention_sql_and_time_column.snap
Labels: kind/bug

#6610 Embedding column config to support client-specified vector sizes
  crates/runtime/benches/vector_search.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/table.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/s3_vectors.rs
  crates/runtime/tests/models/search.rs
  crates/spicepod/src/component/embeddings.rs
  crates/spicepod/src/semantic.rs
Labels: kind/enhancement, area/ai

#6573 Add Support for S3 Table Buckets
  crates/runtime/src/catalogconnector/glue/provider.rs
  crates/runtime/src/dataconnector/glue.rs
Labels: kind/enhancement

#6617 Non-accelerated views should report as ready only after all dependent datasets are ready
  crates/runtime/src/datafusion/mod.rs
Labels: kind/bug

#6620 Revert "Update generate-openapi.yml (#6584)"
  .github/workflows/generate-openapi.yml
Labels: kind/bug, area/ci

#6612 CDC: Compute embeddings on ingest
  crates/data_components/src/cdc.rs
  crates/data_components/src/debezium/arrow/changes.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/datafusion/dialect/duckdb.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/execution_plan.rs
  crates/runtime/src/embeddings/table.rs
Labels: kind/enhancement

#6622 Release notes for v1.5.1
  docs/release_notes/v1.5.1.md
Labels: kind/documentation

#6629 Fixes for Databricks OpenAI compatibility
  crates/llms/src/databricks.rs
Labels: kind/bug, area/ai

#6633 Add environment variable for org token
  .github/workflows/integration.yml
Labels: kind/bug

#6634 Fix typo in release notes
  docs/release_notes/v1.5.1.md
Labels: kind/documentation

#6642 Update SECURITY.md
  SECURITY.md
Labels: kind/documentation, area/ci

#6637 Remove 'stream_options' from databricks LLMs
  crates/llms/src/databricks.rs
Labels: kind/bug

#6626 Move retry and rate limiting logic for Amazon bedrock out of embeddings.
  crates/llms/src/bedrock/chat/mod.rs
  crates/llms/src/bedrock/embed/mod.rs
  crates/llms/src/bedrock/embed/titan.rs
  crates/llms/src/bedrock/mod.rs
  crates/llms/src/bedrock/rate_limit.rs
  crates/runtime/src/model/embed.rs
Labels: kind/enhancement, area/ai

#6649 Disable Metal precomplation in `integration_llms.yml`
  .github/workflows/integration_llms.yml
Labels: kind/bug, area/ci

#6635 Fix multiple query error being classified as an internal error
  crates/runtime/src/flight/mod.rs
Labels: kind/bug

#6640 Score and P95 latency calculation for MTEB Quora-based vector search tests in Test Operator
  .vscode/launch.json
  crates/test-framework/src/spicetest/vector_search/evaluate.rs
  crates/test-framework/src/spicetest/vector_search/mod.rs
  crates/test-framework/src/spicetest/vector_search/worker.rs
  test/spicepods/vector_search/README.md
  test/spicepods/vector_search/mteb/quora/openai[text-embedding-3-small[chunking]]-duckdb[file].yaml
  test/spicepods/vector_search/mteb/quora/openai[text-embedding-3-small]-arrow.yaml
  test/spicepods/vector_search/mteb/quora/openai[text-embedding-3-small]-s3_vectors.yaml
  tools/testoperator/src/commands/vector_search/mod.rs
  tools/testoperator/src/commands/vector_search/mteb_quora.rs
Labels: kind/enhancement

#6657 Make models E2E chat test more robust
  test/models/chat_01.exp
Labels: kind/bug
