Repository spiceai/spiceai, pull requests merged in 2025-05, with the labels that each got.

#5648 Provide ModelContextLayer for evals
  crates/runtime/src/http/routes.rs
Labels: kind/bug, area/ai

#5654 Databricks data_components refactor. Databricks Spark connect - add set_token method and writable spark session
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/databricks/delta.rs
  crates/data_components/src/databricks/mod.rs
  crates/data_components/src/databricks/spark_connect.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/spark_connect.rs
  crates/runtime/src/dataconnector/databricks.rs
Labels: kind/enhancement

#5656 Extract AWS Glue warehouse for cross-account Iceberg tables
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/runtime/src/dataconnector/iceberg.rs
Labels: kind/bug

#5660 Refactor Dataset component
  crates/runtime/src/catalogconnector/spice_cloud.rs
  crates/runtime/src/component/dataset/builder.rs
  crates/runtime/src/component/dataset/mod.rs
  crates/runtime/src/component/dataset/replication.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datasets_health_monitor.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/tracing_util.rs
  crates/runtime/tests/acceleration/checkpoint_duckdb.rs
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
  crates/runtime/tests/acceleration/checkpoint_sqlite.rs
  crates/runtime/tests/acceleration/single_instance_duckdb.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement

#5665 Fix Iceberg API returning 404 when schema contains a Dictionary
  Cargo.lock
  Cargo.toml
  crates/runtime/tests/iceberg_api/mod.rs
  crates/runtime/tests/iceberg_api/snapshots/integration__iceberg_api__iceberg_api_get_table_schema.snap
  crates/runtime/tests/integration.rs
Labels: kind/bug

#5664 Fix dependencies: downgrade swagger-ui to v8; force zip to 2.3.0
  .github/workflows/makefile_targets.yml
  Cargo.lock
  crates/runtime/Cargo.toml
Labels: kind/bug

#5673 docs(readme): update data federation link
  README.md
Labels: kind/bug, area/quality, kind/task

#5661 Support metadata columns for object-store based data connectors
  crates/runtime/src/component/dataset/builder.rs
  crates/runtime/src/component/dataset/metadata.rs
  crates/runtime/src/component/dataset/mod.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/metadata/mod.rs
  crates/runtime/tests/metadata/snapshots/integration__metadata__explain_met_all_location_filtered.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__explain_met_last_modified_filtered.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__explain_met_location_filtered.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__explain_met_location_last_modified_filtered.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__explain_met_location_size_filtered.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__explain_met_size_filtered.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__met_all.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__met_all_location_filtered.snap
Labels: kind/enhancement

#5655 Add `model` name to LLM judges, and add `model_graded_scoring` task.
  crates/runtime/src/init/eval.rs
  crates/runtime/src/model/eval/mod.rs
  crates/runtime/src/model/eval/scorer/mod.rs
  crates/runtime/src/model/eval/scorer/modelgraded.rs
Labels: kind/refactor, area/ai

#5606 Add SF1000 TPCH test spicepods for delta lake
  test/spicepods/tpch/sf1000/accelerated/delta_lake-duckdb[file].yaml
  test/spicepods/tpch/sf1000/federated/delta_lake.yaml
Labels: kind/optimization

#5674 Validate Github Connector resource existence before building the github connector graphql table
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/graphql/mod.rs
  crates/data_components/src/graphql/provider.rs
  crates/runtime/src/dataconnector/github/mod.rs
Labels: kind/bug

#5675 Remove hard-coded embedding performance tests in CI
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/optimization

#5677 Enable federated data refresh support for accelerated views
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/federation.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/refresh_task_runner.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/extension/bytes_processed.rs
  crates/runtime/src/datafusion/extension/mod.rs
  crates/runtime/tests/acceleration/query_push_down.rs
Labels: kind/bug

#5681 Add pods watcher integration test
  crates/runtime/tests/integration.rs
  crates/runtime/tests/podswatcher/mod.rs
  crates/runtime/tests/podswatcher/snapshots/integration__podswatcher__pods_watcher_assert_after.snap
  crates/runtime/tests/podswatcher/snapshots/integration__podswatcher__pods_watcher_assert_before.snap
Labels: kind/optimization, kind/task

#5684 Update end_game.md
  .github/ISSUE_TEMPLATE/end_game.md
Labels: endgame, kind/optimization

#5686 Update StaticTokenProvider to use SecretString instead of raw str value
  crates/data_components/src/token_provider.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/enhancement

#5687 Add M2M Auth support support for Databricks catalog connector
  crates/data_components/src/databricks/delta.rs
  crates/data_components/src/unity_catalog.rs
  crates/runtime/src/catalogconnector/databricks.rs
  crates/runtime/src/catalogconnector/unity_catalog.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/tests/databricks_delta_catalog_m2m/mod.rs
  crates/runtime/tests/databricks_spark_catalog_m2m/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/snapshots/integration__databricks_delta_catalog_m2m__test_select_tpcds.snap
  crates/runtime/tests/snapshots/integration__databricks_delta_catalog_m2m__test_select_tpch.snap
  crates/runtime/tests/snapshots/integration__databricks_spark_catalog_m2m__test_select_tpcds.snap
  crates/runtime/tests/snapshots/integration__databricks_spark_catalog_m2m__test_select_tpch.snap
Labels: kind/enhancement

#5682 Update UX to disable acceleration federation
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/lib.rs
  crates/runtime/tests/acceleration/query_push_down.rs
Labels: kind/bug

#5692 Improve placeholder inference (LIMIT & Expr::InSubquery)
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5693 Tweak default log to ignore aws_config::imds::region
  bin/spiced/src/tracing.rs
Labels: kind/bug

#5695 Make Spice properly Iceberg Catalog API compatible for load table API
  crates/runtime/src/http/v1/iceberg/tables.rs
Labels: kind/enhancement

#5704 Support retrieving the latest Iceberg table on table scan
  Cargo.lock
  Cargo.toml
  crates/data_components/src/iceberg/catalog.rs
  crates/data_components/src/iceberg/provider.rs
  crates/runtime/src/dataconnector/iceberg.rs
Labels: kind/bug

#5711 Support retrieving the latest Iceberg table on table scan (#5704)
  Cargo.lock
  Cargo.toml
  crates/data_components/src/iceberg/catalog.rs
  crates/data_components/src/iceberg/provider.rs
  crates/runtime/src/dataconnector/iceberg.rs
Labels: kind/bug

#5710 Add 1.2.1 release notes
  docs/release_notes/v1.2.1.md
Labels: kind/documentation, kind/enhancement

#5712 Fix databricks cookbook link in endgame issue template
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/optimization

#5714 add PR 'release/*' when 'release-*' exists
  .github/workflows/e2e_test_ci.yml
  .github/workflows/integration.yml
  .github/workflows/integration_llms.yml
  .github/workflows/integration_models.yml
  .github/workflows/license_check.yml
  .github/workflows/makefile_targets.yml
  .github/workflows/pr.yml
Labels: kind/bug

#5715 Databricks AI: Embedding models & LLM streaming.
  crates/llms/src/databricks.rs
  crates/llms/src/embeddings/mod.rs
  crates/llms/src/lib.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/embed.rs
  crates/spicepod/src/component/embeddings.rs
Labels: kind/enhancement, area/ai

#5716 Make 'token_providers' crate
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/databricks/delta.rs
  crates/data_components/src/databricks/mod.rs
  crates/data_components/src/databricks/spark_connect.rs
  crates/data_components/src/github.rs
  crates/data_components/src/graphql/builder.rs
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/unity_catalog.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/builder.rs
  crates/runtime/src/catalogconnector/databricks.rs
  crates/runtime/src/catalogconnector/unity_catalog.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/registry/mod.rs
  crates/token_providers/Cargo.toml
  crates/token_providers/src/databricks.rs
  crates/token_providers/src/github_app_token.rs
  crates/token_providers/src/lib.rs
  crates/token_providers/src/registry.rs
Labels: kind/refactor

#5717 Pass the default user agent string to the Databricks Spark, Delta, and Unity clients
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/databricks/mod.rs
  crates/data_components/src/databricks/spark_connect.rs
  crates/data_components/src/spark_connect.rs
  crates/data_components/src/unity_catalog.rs
Labels: kind/enhancement

#5718 Retrieve Github App tokens in background; make `TokenProvider` not async
  Cargo.lock
  crates/data_components/src/databricks/spark_connect.rs
  crates/data_components/src/github.rs
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/unity_catalog.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/token_providers/Cargo.toml
  crates/token_providers/src/databricks.rs
  crates/token_providers/src/github_app_token.rs
  crates/token_providers/src/lib.rs
Labels: kind/refactor

#5719 Add Databricks user_agent header to model provider
  crates/llms/src/openai/mod.rs
  crates/runtime/src/model/chat.rs
Labels: kind/enhancement

#5721 Infer partitions from schema_source_path if present
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/listing/infer.rs
  crates/runtime/tests/s3/mod.rs
  crates/runtime/tests/s3/snapshots/integration__s3__s3_schema_source_path_authenticated_parts.snap
Labels: kind/bug

#5728 Include `Infer partitions from schema_source_path if present` into v1.2.1 release
  .github/workflows/e2e_test_ci.yml
  .github/workflows/integration.yml
  .github/workflows/integration_llms.yml
  .github/workflows/integration_models.yml
  .github/workflows/license_check.yml
  .github/workflows/makefile_targets.yml
  .github/workflows/pr.yml
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/listing/infer.rs
  crates/runtime/tests/s3/mod.rs
  crates/runtime/tests/s3/snapshots/integration__s3__s3_schema_source_path_authenticated_parts.snap
  docs/release_notes/v1.2.1.md
Labels: kind/bug

#5729 Update v1.2.1 release notes (include Infer partitions from schema_source_path if present fix)
  docs/release_notes/v1.2.1.md
Labels: kind/documentation

#5734 Update Spice version to 1.3.0-unstable
  .github/ISSUE_TEMPLATE/end_game.md
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/optimization

#5732 Fix the workflow when github.event.inputs.build_cli == 'false'
  .github/workflows/e2e_test_spice_cli.yml
Labels: kind/bug

#5735 indentation update v1.2.1
  docs/release_notes/v1.2.1.md
Labels: kind/documentation, endgame

#5720 Support Databricks M2M auth in LLMs + Embeddings
  Cargo.lock
  Cargo.toml
  crates/llms/Cargo.toml
  crates/llms/src/anthropic/mod.rs
  crates/llms/src/config.rs
  crates/llms/src/databricks.rs
  crates/llms/src/perplexity/mod.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/embed.rs
Labels: kind/enhancement, area/ai

#5741 Clear plan cache when dataset updates
  crates/runtime/src/datafusion.rs
  crates/runtime/src/init/dataset.rs
Labels: kind/bug

#5746 Use Github action for SpiceQA
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#5742 Remove HTTP auth from LLM config and simplify Databricks models logic by using static headers
  Cargo.lock
  crates/data_components/src/databricks/mod.rs
  crates/data_components/src/unity_catalog.rs
  crates/llms/Cargo.toml
  crates/llms/src/anthropic/mod.rs
  crates/llms/src/config.rs
  crates/llms/src/databricks.rs
  crates/llms/src/perplexity/mod.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/embed.rs
Labels: kind/refactor

#5745 Update qa_analytics.csv for 1.2.1
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#5749 Support for overriding the product name in the Databricks user agent string
  crates/data_components/src/databricks/mod.rs
Labels: kind/enhancement

#5753 Endgame instructions on running SpiceQA
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/optimization

#5760 fix: Use decimal_cmp for numerical BETWEEN in SQLite
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-sqlite[file]_tpch_q19_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-sqlite[file]_tpch_q6_explain.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__file[parquet]-sqlite[file]_tpch_q6.snap
  tools/testoperator/dispatch/tpch/sf1/accelerated/file[parquet]-sqlite[file].yaml
  tools/testoperator/dispatch/tpch/sf1/accelerated/file[parquet]-sqlite[memory].yaml
Labels: kind/bug

#5752 Refactor runtime crate to move top-level modules to <module>/mod.rs
  crates/runtime/src/accelerated_table/mod.rs
  crates/runtime/src/dataaccelerator/mod.rs
  crates/runtime/src/dataconnector/mod.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/flight/mod.rs
  crates/runtime/src/http/mod.rs
  crates/runtime/src/secrets/mod.rs
  crates/runtime/src/task_history/mod.rs
Labels: kind/refactor

#5748 show available tables from catalogs in list_datasets tool
  crates/runtime/src/tools/builtin/list_datasets.rs
Labels: kind/bug, area/ai

#5761 Fix Iceberg predicates not matching the Arrow type of columns read from parquet files
  Cargo.lock
  Cargo.toml
  crates/app/src/lib.rs
  crates/runtime/tests/iceberg/connector/audit_log.rs
  crates/runtime/tests/iceberg/connector/audit_log.yaml
  crates/runtime/tests/iceberg/connector/mod.rs
  crates/runtime/tests/iceberg/connector/snapshots/integration__iceberg__connector__audit_log__audit_log_query.snap
  crates/spicepod/src/component.rs
  crates/spicepod/src/lib.rs
  crates/spicepod/src/reader.rs
  crates/test-framework/src/app_utils/mod.rs
  crates/test-framework/src/lib.rs
Labels: kind/bug

#5764 Respect `runtime.dataset_load_parallelism` for accelerated views
  crates/runtime/src/datafusion/mod.rs
Labels: kind/enhancement

#5768 Add `--http-endpoint` to `spice trace`
  bin/spice/cmd/trace.go
Labels: kind/bug, area/ai

#5763 Control the parallelism of acceleration refresh datasets with `runtime.dataset_load_parallelism`
  crates/runtime/src/accelerated_table/mod.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/refresh_task_runner.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/tests/refresh_retry/mysql.rs
Labels: kind/bug

#5774 Helm chart: enable service ports customization
  deploy/chart/templates/service.yaml
Labels: kind/bug

#5772 Lru cache: limit single cached record size to u32::MAX (4GB)
  crates/cache/src/utils.rs
Labels: kind/bug

#5773 Set application_name when connecting to Postgres
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator/arrow.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/mod.rs
  crates/runtime/src/dataaccelerator/postgres.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/dataconnector/postgres.rs
Labels: kind/enhancement

#5770 MySQL: Set the character_set_results/character_set_client/character_set_connection session variables on connection setup
  Cargo.lock
  Cargo.toml
  crates/runtime/tests/integration.rs
  crates/runtime/tests/mysql/mod.rs
  crates/runtime/tests/snapshots/integration__mysql__character_set_results_default.snap
Labels: kind/bug

#5779 Fix bug where setting `Cache-Control: no-cache` doesn't compute the cache key.
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/cache.rs
  crates/runtime/tests/cache/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/snapshots/integration__cache__cache_integration_test_select.snap
Labels: kind/bug

#5778 Don't display bb8 Postgres pool errors by default
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5788 Update spice cli login command with client-id and client-secret flags for Databricks
  bin/spice/cmd/login.go
  bin/spice/pkg/api/auth.go
Labels: kind/enhancement

#5798 Update spark-connect-rs to override user agent string
  Cargo.lock
  crates/data_components/Cargo.toml
Labels: kind/enhancement

#5799 Update release/1.2
  Cargo.lock
  crates/data_components/Cargo.toml
Labels: kind/enhancement

#5800 Initial release notes for v1.2.2
  docs/release_notes/v1.2.2.md
Labels: kind/documentation

#5802 Initial release notes for v1.2.2 (#5800)
  docs/release_notes/v1.2.2.md
Labels: kind/documentation

#5808 Move sandboxing logic to Dockerfile
  Dockerfile
  deploy/chart/templates/deployment.yaml
  scripts/setup_sandbox.sh
Labels: kind/bug

#5797 Add note to run installation health workflow after release is marked as official
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#5809 ROADMAP updates May 13, 2025
  docs/ROADMAP.md
Labels: kind/documentation

#5810 Update qa_analytics.csv
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#5811 Post-release housekeeping
  .github/ISSUE_TEMPLATE/end_game.md
  SECURITY.md
Labels: kind/documentation

#5818 Fix flaky DataBricks M2M integration tests
  crates/runtime/tests/databricks_spark_catalog_m2m/mod.rs
  crates/runtime/tests/databricks_spark_m2m/mod.rs
Labels: kind/bug

#5807 Add DataFusion request context extension to http routes
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/datafusion/request_context_extension.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/http/v1/eval.rs
  crates/runtime/src/http/v1/iceberg/mod.rs
  crates/runtime/src/http/v1/iceberg/tables.rs
  crates/runtime/src/http/v1/inference.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/http/v1/query.rs
Labels: kind/enhancement

#5819 Use full path for location metadata column
  Cargo.lock
  Cargo.toml
  crates/runtime/src/component/dataset/metadata.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/tests/metadata/mod.rs
  crates/runtime/tests/metadata/snapshots/integration__metadata__explain_met_all_location_filtered.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__explain_met_location_filtered.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__explain_met_location_last_modified_filtered.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__explain_met_location_size_filtered.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__met_all.snap
  crates/runtime/tests/metadata/snapshots/integration__metadata__met_all_location_filtered.snap
Labels: kind/bug

#5821 Remove the DataFusion reference from the flight service and use the reference from the request context instead
  crates/runtime/src/flight/actions.rs
  crates/runtime/src/flight/do_exchange.rs
  crates/runtime/src/flight/do_get.rs
  crates/runtime/src/flight/do_put.rs
  crates/runtime/src/flight/flightsql/get_catalogs.rs
  crates/runtime/src/flight/flightsql/get_primary_keys.rs
  crates/runtime/src/flight/flightsql/get_schemas.rs
  crates/runtime/src/flight/flightsql/get_tables.rs
  crates/runtime/src/flight/flightsql/prepared_statement_query.rs
  crates/runtime/src/flight/flightsql/statement_query.rs
  crates/runtime/src/flight/get_flight_info.rs
  crates/runtime/src/flight/get_schema.rs
  crates/runtime/src/flight/middleware/request_context.rs
  crates/runtime/src/flight/mod.rs
Labels: kind/enhancement

#5823 Upgrade delta_kernel to 0.10
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/delta_lake.rs
Labels: kind/dependencies

#5824 Update qa_analytics.csv
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#5837 Fix dispatch spicepod reference for `file[parquet]-duckdb[file]-indexes` and `file[parquet]-duckdb[memory]-indexes`
  tools/testoperator/dispatch/tpch/sf1/accelerated/indexes/file[parquet]-duckdb[file]-indexes.yaml
  tools/testoperator/dispatch/tpch/sf1/accelerated/indexes/file[parquet]-duckdb[memory]-indexes.yaml
Labels: kind/bug

#5812 Fix `spice run --http-endpoint` in CLI
  bin/spice/pkg/context/context.go
Labels: kind/bug

#5838 fix: Prevent excessively copying RawCacheKey
  crates/cache/src/lib.rs
  crates/cache/src/lru_cache.rs
  crates/cache/src/utils.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/cache.rs
  docs/dev/style_guide.md
Labels: kind/enhancement

#5839 Make DuckDB database attachments logic more robust
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator/duckdb.rs
  test/spicepods/tpch/sf1/accelerated/file[parquet]-duckdb[file-many].yaml
  test/spicepods/tpch/sf1/accelerated/s3[parquet]-duckdb[file-many].yaml
Labels: kind/bug

#5758 Update to new MCP crate
  Cargo.lock
  Cargo.toml
  bin/spice/pkg/api/util.go
  crates/data_components/src/debezium/arrow.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/mcp.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/tools/mcp/catalog.rs
  crates/runtime/src/tools/mcp/mod.rs
  crates/runtime/src/tools/mcp/server.rs
  crates/runtime/src/tools/mcp/tool.rs
  crates/tools/Cargo.toml
  crates/tools/src/mcp.rs
Labels: kind/refactor, area/ai, breaking change

#5852 fix: Disable the query tracker when task history is disabled
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/builder.rs
  crates/runtime/src/datafusion/query/cache.rs
Labels: kind/bug

#5854 Set fsGroup on PodSpec to force volumes to be mounted with permission to docker image
  deploy/chart/templates/deployment.yaml
Labels: kind/bug

#5855 Clarify Helm release steps
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#5853 fix: Avoid cloning cached results
  crates/cache/src/lib.rs
  crates/runtime/src/datafusion/query/cache.rs
  crates/test-framework/src/queries/mod.rs
  crates/test-framework/src/spicetest/datasets/worker.rs
Labels: kind/bug

#5866 Adapt to Arrow 54 changes in Dict IDs preserving (Arrow IPC)
  crates/runtime/src/flight/mod.rs
  crates/runtime/tests/flight/do_get.rs
  crates/runtime/tests/flight/do_put.rs
  crates/runtime/tests/flight/mod.rs
  crates/runtime/tests/flight/prepared_statements.rs
  crates/runtime/tests/flight/snapshots/integration__flight__do_get__dict_types.snap
Labels: kind/bug

#5868 Fix s3[parquet]-duckdb[file-many] benchmark Spicepod configuration
  test/spicepods/tpch/sf1/accelerated/s3[parquet]-duckdb[file-many].yaml
Labels: kind/bug

#5858 Overried health checks for Databricks models in U2M auth mode
  crates/llms/src/databricks.rs
  crates/llms/src/lib.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/embed.rs
Labels: kind/enhancement

#5878 Update trunk to 1.4.0-unstable
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/documentation

#5883 fix: Pass parameters to testoperator explain plan
  crates/test-framework/src/flight/mod.rs
  crates/test-framework/src/snapshot/mod.rs
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q10_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q11_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q12_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q13_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q14_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q16_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q18_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q19_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q21_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q8_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q9_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q10_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q11_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q12_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q13_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q14_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q16_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q18_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q19_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q21_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q8_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q9_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q10_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q11_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q12_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q13_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q14_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q16_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q18_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q19_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q21_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q8_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q9_explain.snap
  crates/test-framework/src/spicetest/datasets/worker.rs
  tools/testoperator/dispatch/tpch/sf1/accelerated/indexes/file[parquet]-duckdb[file]-indexes.yaml
  tools/testoperator/dispatch/tpch/sf1/accelerated/indexes/file[parquet]-duckdb[memory]-indexes.yaml
Labels: kind/bug

#5886 fix: Pass parameters to testoperator explain plan (#5883)
  crates/test-framework/src/flight/mod.rs
  crates/test-framework/src/snapshot/mod.rs
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q10_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q11_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q12_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q13_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q14_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q16_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q18_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q19_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q21_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q8_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q9_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q10_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q11_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q12_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q13_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q14_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q16_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q18_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q19_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q21_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q8_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-federated_tpch[parameterized]_q9_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q10_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q11_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q12_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q13_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q14_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q16_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q18_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q19_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q21_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q8_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-federated_tpch[parameterized]_q9_explain.snap
  crates/test-framework/src/spicetest/datasets/worker.rs
  tools/testoperator/dispatch/tpch/sf1/accelerated/indexes/file[parquet]-duckdb[file]-indexes.yaml
  tools/testoperator/dispatch/tpch/sf1/accelerated/indexes/file[parquet]-duckdb[memory]-indexes.yaml
Labels: kind/bug

#5879 docs: Update testoperator readme
  tools/testoperator/README.md
Labels: kind/documentation

#5884 feat: Add testoperator disable cache flag for tests
  crates/test-framework/src/spiced/mod.rs
  crates/test-framework/src/spicetest/datasets/mod.rs
  tools/testoperator/README.md
  tools/testoperator/src/args/dataset.rs
  tools/testoperator/src/commands/bench/mod.rs
  tools/testoperator/src/commands/evals/mod.rs
  tools/testoperator/src/commands/load/mod.rs
  tools/testoperator/src/commands/throughput/mod.rs
Labels: kind/enhancement

#5889 feat: Testoperator reports benchmark failure summary
  Cargo.lock
  crates/test-framework/Cargo.toml
  crates/test-framework/src/metrics/mod.rs
  crates/test-framework/src/spicetest/datasets/mod.rs
  crates/test-framework/src/spicetest/datasets/worker.rs
  crates/test-framework/src/spicetest/http/consistency.rs
  crates/test-framework/src/spicetest/http/overhead.rs
  crates/test-framework/src/spicetest/vector_search/mod.rs
  tools/testoperator/src/commands/bench/mod.rs
  tools/testoperator/src/commands/http/overhead.rs
  tools/testoperator/src/commands/load/mod.rs
  tools/testoperator/src/commands/mod.rs
Labels: kind/enhancement

#5887 Disallow schema updates for existing accelerated tables.
  crates/arrow_tools/src/schema.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/dataconnector/mod.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/execution_plan/fallback_on_zero_results.rs
  crates/runtime/src/federated_table/mod.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/tracers.rs
  crates/runtime/tests/iceberg/catalog/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/podswatcher/mod.rs
  crates/runtime/tests/schema_evolution/mod.rs
  crates/runtime/tests/schema_evolution/snapshots/integration__schema_evolution__test_schema_evolution_add_column.snap
  crates/runtime/tests/schema_evolution/snapshots/integration__schema_evolution__test_schema_evolution_change_column_type.snap
  crates/runtime/tests/schema_evolution/snapshots/integration__schema_evolution__test_schema_evolution_drop_column.snap
  crates/runtime/tests/schema_evolution/snapshots/integration__schema_evolution__test_schema_evolution_drop_table.snap
  crates/runtime/tests/schema_evolution/snapshots/integration__schema_evolution__test_schema_evolution_initial.snap
  crates/runtime/tests/schema_evolution/snapshots/integration__schema_evolution__test_schema_evolution_rename_column.snap
  crates/runtime/tests/utils/mod.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement

#5873 Full federation support for accelerated views and datasets
  crates/runtime/src/component/view.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/init/view.rs
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q10_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q11_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q12_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q13_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q14_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q16_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q17_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q18_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q19_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q1_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q20_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q21_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q22_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q4_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q6_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q8_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q9_explain.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q1.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q10.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q11.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q12.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q13.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q14.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q16.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q17.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q18.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q19.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q2.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q20.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q21.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q22.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q3.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q4.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q5.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q6.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q7.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q8.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_q9.snap
  test/spicepods/tpch/sf1/accelerated/s3[parquet]-mixed[duckdb[ds]+duckdb[view]].yaml
Labels: kind/bug

#5860 Deferrable registration for Databricks U2M datasets
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/deferred.rs
  crates/runtime/src/dataconnector/mod.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/request/context.rs
  crates/runtime/src/request/databricks.rs
Labels: kind/enhancement

#5830 Add support for Databricks SQL Statement Execution API
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
  crates/data_components/src/databricks/mod.rs
  crates/data_components/src/databricks/sql_warehouse.rs
  crates/runtime/src/catalogconnector/databricks.rs
  crates/runtime/src/dataconnector/databricks.rs
  test/spicepods/tpch/sf1/federated/databricks[sql_warehouse].yaml
  tools/testoperator/dispatch/tpch/sf1/federated/databricks[sql_warehouse].yaml
Labels: kind/enhancement, area/data-connectors

#5905 fix: Publish binaries to dev when platform option is all
  .github/workflows/build_and_release.yml
Labels: kind/bug

#5900 v1.3.0 release notes
  docs/release_notes/v1.2/v1.2.0.md
  docs/release_notes/v1.2/v1.2.1.md
  docs/release_notes/v1.2/v1.2.2.md
  docs/release_notes/v1.3.0.md
  scripts/generate_changelog.sh
Labels: kind/documentation

#5906 feat: Print dispatch current test count of total
  tools/testoperator/src/commands/dispatch/mod.rs
Labels: kind/enhancement

#5913 Include multiple duckdb files acceleration scenarios into testoperator dispatch
  tools/testoperator/dispatch/tpch/sf1/accelerated/file[parquet]-duckdb[file-many].yaml
  tools/testoperator/dispatch/tpch/sf1/accelerated/s3[parquet]-mixed[duckdb[ds]+duckdb[view]].yaml
Labels: kind/optimization

#5915 feat: Support building testoperator on dev
  .github/actions/setup-testoperator-data/action.yml
  .github/workflows/testoperator_run_bench.yml
Labels: kind/enhancement

#5925 Bump Helm chart to 1.3.0
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#5926 Update ROADMAP & SECURITY for 1.3.0
  SECURITY.md
  docs/ROADMAP.md
Labels: kind/documentation

#5876 Define `SearchGeneration` paradigm & use in Vector Search .
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/benches/vector_search.rs
  crates/runtime/src/embeddings/cosine_distance.rs
  crates/runtime/src/embeddings/mod.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/mod.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/search/candidate.rs
  crates/runtime/src/search/candidate/vector.rs
  crates/runtime/src/search/mod.rs
  crates/runtime/src/search/request.rs
  crates/runtime/src/search/types.rs
  crates/runtime/src/search/util.rs
  crates/runtime/src/search/vector_search.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
  crates/search/Cargo.toml
  crates/search/src/lib.rs
Labels: kind/enhancement, area/ai

#5928 docs: Update qa_analytics.csv
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#5929 Make `spill_to_disk_and_rehydration` test more robust
  crates/runtime/tests/docker/mod.rs
  crates/runtime/tests/mysql/common.rs
  crates/runtime/tests/mysql/federation.rs
  crates/runtime/tests/mysql/mod.rs
  crates/runtime/tests/refresh_retry/mysql.rs
  crates/runtime/tests/rehydration/mod.rs
Labels: kind/bug

#5931 fix: Properly publish binaries to dev on push
  .github/workflows/build_and_release.yml
Labels: kind/bug

#5916 Load request context extensions on every flight incoming call
  crates/runtime/src/flight/middleware/request_context.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/request/context.rs
Labels: kind/enhancement

#5939 fix: Avoid mistaken ILike to string equality optimization (DataFusion / Arrow)
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5932 Fix deferred loading for datasets with embeddings
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/init/dataset.rs
Labels: kind/enhancement

#5940 Schedule AI benchmarks to run every Mon and Thu evening PST
  .github/workflows/ai_benchmark_nsql.yml
  .github/workflows/financebench.yml
Labels: kind/optimization

#5942 Fix explain plan snapshots for TPCDS queries Q36, Q70 & Q86 not being deterministic after DF 46 upgrade
  crates/test-framework/src/snapshot/mod.rs
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__dremio-federated_tpcds_q36_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__dremio-federated_tpcds_q70_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__dremio-federated_tpcds_q86_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpcds_q36_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpcds_q70_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpcds_q86_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[file-many]_tpch_simple_q1_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[file-many]_tpch_simple_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[file-many]_tpch_simple_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[file-many]_tpch_simple_q4_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[file-many]_tpch_simple_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[file-many]_tpch_simple_q6_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[file-many]_tpch_simple_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[file]_tpcds_q36_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[file]_tpcds_q70_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[file]_tpcds_q86_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[memory]_tpcds_q36_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[memory]_tpcds_q70_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-duckdb[memory]_tpcds_q86_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-postgres_tpcds_q36_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-postgres_tpcds_q70_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__file[parquet]-postgres_tpcds_q86_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__mysql-federated_tpcds_q36_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__mysql-federated_tpcds_q70_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__mysql-federated_tpcds_q86_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__postgres-federated_tpcds_q36_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__postgres-federated_tpcds_q70_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__postgres-federated_tpcds_q86_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_simple_q1_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_simple_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_simple_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_simple_q4_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_simple_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_simple_q6_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__s3[parquet]-mixed[duckdb[ds]+duckdb[view]]_tpch_simple_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__spicecloud-federated_tpcds_q36_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__spicecloud-federated_tpcds_q70_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__spicecloud-federated_tpcds_q86_explain.snap
Labels: kind/bug

#5945 chore: Upgrade to Rust 1.86
  .github/actions/setup-rust/action.yml
  Cargo.toml
  Dockerfile
  Dockerfile-cuda
  bin/spiced/src/lib.rs
  crates/data_components/src/databricks/delta.rs
  crates/data_components/src/delta_lake.rs
  crates/data_components/src/flight/stream.rs
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/graphql/provider.rs
  crates/data_components/src/unity_catalog.rs
  crates/data_components/src/unity_catalog/provider.rs
  crates/db_connection_pool/src/odbcpool.rs
  crates/db_connection_pool/src/snowflakepool.rs
  crates/flightrepl/src/lib.rs
  crates/llms/src/chat/nsql/mod.rs
  crates/llms/src/databricks.rs
  crates/model_components/src/modelsource/spiceai.rs
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/flight/do_put.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/init/view.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/search/request.rs
  crates/runtime/src/secrets/mod.rs
  crates/runtime/src/tools/mod.rs
  crates/runtime/src/tracing_util.rs
  crates/runtime/tests/flight/mod.rs
  crates/test-framework/src/spicetest/http/consistency.rs
  crates/test-framework/src/spicetest/http/overhead.rs
  crates/util/src/lib.rs
  crates/workers/src/router.rs
  rust-toolchain.toml
Labels: kind/dependencies

#5946 add projection to logical plan to force federation and correct dialect
  crates/runtime/src/dataconnector/mod.rs
Labels: kind/enhancement

#5769 Standardise HTTP settings across CLI
  bin/spice/cmd/add.go
  bin/spice/cmd/catalogs.go
  bin/spice/cmd/chat.go
  bin/spice/cmd/datasets.go
  bin/spice/cmd/eval.go
  bin/spice/cmd/install.go
  bin/spice/cmd/models.go
  bin/spice/cmd/nsql.go
  bin/spice/cmd/pods.go
  bin/spice/cmd/refresh.go
  bin/spice/cmd/run.go
  bin/spice/cmd/search.go
  bin/spice/cmd/spice.go
  bin/spice/cmd/sql.go
  bin/spice/cmd/status.go
  bin/spice/cmd/trace.go
  bin/spice/cmd/upgrade.go
  bin/spice/cmd/version.go
  bin/spice/cmd/workers.go
  bin/spice/pkg/api/status.go
  bin/spice/pkg/api/util.go
  bin/spice/pkg/constants/http.go
  bin/spice/pkg/context/context.go
Labels: area/cli, kind/refactor

#5947 allow join push down for same sql warehouse
  crates/data_components/src/databricks/sql_warehouse.rs
Labels: kind/optimization

#5936 Add support for STRUCT type in Databricks SQL Warehouse
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/databricks/sql_warehouse.rs
  crates/data_components/src/databricks/sql_warehouse/datatypes.rs
  crates/runtime/Cargo.toml
Labels: kind/enhancement

#5924 Fix Databricks SQL Warehouse benchmark test
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_data_consistency.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
  crates/data_components/src/databricks/sql_warehouse.rs
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q10_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q11_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q12_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q13_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q14_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q16_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q18_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q19_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q1_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q20_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q21_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q22_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q4_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q6_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q8_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_q9_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_simple_q1_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_simple_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_simple_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_simple_q4_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_simple_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_simple_q6_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__databricks[sql_warehouse]-federated_tpch_simple_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q1.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q10.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q11.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q12.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q13.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q14.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q16.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q18.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q19.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q20.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q21.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q22.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q3.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q4.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q5.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q6.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q7.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q8.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__databricks[sql_warehouse]-federated_tpch_q9.snap
  test/spicepods/tpch/sf1/federated/databricks[sql_warehouse].yaml
Labels: kind/bug

#5958 Fix deferred flag for Databricks SQL warehouse mode
  crates/runtime/src/dataconnector/databricks.rs
Labels: kind/bug

#5961 Refactor deferred_load using ComponentInitialization enum for better clarity
  crates/runtime/src/catalogconnector/databricks.rs
  crates/runtime/src/catalogconnector/mod.rs
  crates/runtime/src/component/mod.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/deferred.rs
  crates/runtime/src/dataconnector/mod.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/init/dataset.rs
Labels: kind/enhancement

#5962 Fix parameter schema ordering with > 10 parameters for parameterized queries
  crates/runtime/src/datafusion/query.rs
  crates/runtime/tests/flight/prepared_statements.rs
  crates/runtime/tests/flight/snapshots/integration__flight__prepared_statements__more_than_ten_parameters_table_content.snap
  crates/runtime/tests/flight/snapshots/integration__flight__prepared_statements__more_than_ten_question_mark_parameters_table_content.snap
Labels: kind/bug

#5964 Post-release housekeeping
  .github/ISSUE_TEMPLATE/end_game.md
  .github/workflows/testoperator_dispatch.yml
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/documentation

#5967 Alias the `random()` function to `rand()`
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/udf.rs
  crates/runtime/src/datafusion/udf/alias.rs
Labels: kind/enhancement

#5709 add LTO for release builds
  .github/actions/spiced-cuda-build/action.yaml
  .github/workflow_templates/spiced_docker_nightly.yml
  .github/workflows/build_and_release.yml
  .github/workflows/build_and_release_cuda.yml
  .github/workflows/pr.yml
  Cargo.toml
  Dockerfile
  bin/spiced/Makefile
Labels: kind/optimization

#5968 Fix placeholder inference in CASE expressions
  Cargo.lock
  Cargo.toml
  crates/runtime/tests/flight/prepared_statements.rs
  crates/runtime/tests/flight/snapshots/integration__flight__prepared_statements__case_simple_parameter_table_content.snap
  crates/runtime/tests/flight/snapshots/integration__flight__prepared_statements__case_when_parameter_false_table_content.snap
  crates/runtime/tests/flight/snapshots/integration__flight__prepared_statements__case_when_parameter_table_content.snap
Labels: kind/bug

#5977 Fix Test-to-SQL benchmark scheduled run
  .github/workflows/ai_benchmark_nsql.yml
Labels: kind/bug

#5979 Update JSON to ScalarValue type conversion to match DataFusion behavior
  crates/runtime/src/datafusion/param_utils.rs
Labels: kind/bug

#5978 Add v1.3.1 release notes
  docs/ROADMAP.md
  docs/release_notes/v1.3.1.md
Labels: kind/documentation

#5981 Bump to 1.3.1 in version.txt
  version.txt
Labels: kind/enhancement

#5983 Upgrade DataFusion to include expanded type inference
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5984 Fix placeholder inference to not fail
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5995 Regenerate nightly build workflow
  .github/workflow_templates/spiced_docker_nightly.yml
  .github/workflows/spiced_docker_nightly.yml
Labels: kind/bug, area/ci

#5987 Fix DataFusion dependency loading in Databricks request context extension
  crates/runtime/src/flight/middleware/request_context.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/request/context.rs
  crates/runtime/src/request/databricks.rs
Labels: kind/bug

#6001 fix: Remove caching RwLock
  crates/cache/src/lib.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/cache.rs
  crates/runtime/src/init/caching.rs
  crates/runtime/src/init/mod.rs
  crates/runtime/src/lib.rs
Labels: kind/refactor

#6002 1.3.1 Post-release housekeeping
  .github/ISSUE_TEMPLATE/end_game.md
  SECURITY.md
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#6011 fix: Allow dev runners in dispatch files
  tools/testoperator/src/args/dispatch.rs
Labels: kind/bug

#6008 refactor: Deprecate results_cache for caching.sql_results
  bin/spiced/src/lib.rs
  bin/spiced/src/main.rs
  crates/app/src/lib.rs
  crates/cache/src/lib.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/cache.rs
  crates/runtime/src/init/caching.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/request/cache_control.rs
  crates/spicepod/src/component.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/refactor

#6013 Fix models benchmark results reporting
  tools/testoperator/src/commands/evals/mod.rs
Labels: kind/bug

#6014 fix: Run PR checks for tools/ changes
  .github/workflows/pr.yml
Labels: kind/bug

#6005 feat: Add a CronRequestChannel for `scheduler`
  Cargo.lock
  crates/scheduler/Cargo.toml
  crates/scheduler/README.md
  crates/scheduler/src/channel/cron.rs
  crates/scheduler/src/channel/mod.rs
  crates/scheduler/src/lib.rs
Labels: kind/enhancement

#6021 Update license check to allow dual license crates
  .github/workflows/license_check.yml
  deny.toml
  tools/evalconverter/Cargo.toml
Labels: kind/bug

#6023 Don't fail if cargo-deny is already installed (license check)
  .github/workflows/license_check.yml
Labels: kind/bug

#5965 Read Iceberg tables from Glue Catalog Connector
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/catalogconnector/glue.rs
  crates/runtime/src/catalogconnector/mod.rs
Labels: kind/enhancement, area/data-connectors

#6034 fix: Use HTTPS ubuntu sources
  .github/actions/update-http-sources/action.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_ci_models.yml
  .github/workflows/integration.yml
  .github/workflows/makefile_targets.yml
  .github/workflows/pr.yml
Labels: kind/bug

#6039 refactor: Remove worker type
  crates/runtime/src/http/v1/workers.rs
  crates/runtime/src/init/scheduler.rs
  crates/runtime/src/init/worker.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/worker.rs
  crates/spicepod/src/component/worker.rs
Labels: kind/refactor

#6044 Define SearchPipeline and use in `runtime/vector_search.rs`.
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/search/mod.rs
  crates/runtime/src/search/request.rs
  crates/runtime/src/search/types.rs
  crates/runtime/src/search/vector_search.rs
  crates/search/src/lib.rs
  crates/search/src/pipeline.rs
Labels: kind/enhancement, area/ai

#6051 fix: Scheduler test when scheduler is running
  crates/scheduler/src/scheduler.rs
Labels: kind/bug

#6035 doc: Spice Cloud Connector Limitation
  crates/test-framework/src/queries/README.md
Labels: kind/documentation
