Repository spiceai/spiceai, pull requests merged in 2025-03, with the labels that each got.

#4912 Fix Datafusion resources deallocation during shutdown
  bin/spiced/src/lib.rs
  bin/spiced/src/main.rs
  crates/runtime/src/spice_metrics.rs
  crates/telemetry/src/lib.rs
  crates/telemetry/src/noop.rs
Labels: kind/bug

#4911 Update to latest async-openai fork. Update secrecy
  Cargo.lock
  Cargo.toml
  crates/data_components/src/delta_lake.rs
  crates/db_connection_pool/src/dbconnection/odbcconn.rs
  crates/db_connection_pool/src/dbconnection/snowflakeconn.rs
  crates/db_connection_pool/src/odbcpool.rs
  crates/db_connection_pool/src/snowflakepool.rs
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/llms/src/config.rs
  crates/llms/src/perplexity/mod.rs
  crates/llms/tests/llms/create.rs
  crates/model_components/src/modelsource/huggingface.rs
  crates/model_components/src/modelsource/local.rs
  crates/model_components/src/modelsource/spiceai.rs
  crates/runtime/src/auth/mod.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/embed.rs
  crates/runtime/src/parameters.rs
  crates/runtime/src/secrets.rs
  crates/runtime/src/secrets/stores/aws_secrets_manager.rs
  crates/runtime/src/secrets/stores/env.rs
  crates/runtime/src/secrets/stores/keyring.rs
  crates/runtime/src/secrets/stores/kubernetes.rs
  crates/runtime/src/tls.rs
  crates/runtime/src/tools/builtin/web_search/mod.rs
  crates/runtime/src/tools/mcp/mod.rs
Labels: kind/enhancement

#4913 Add support for Flight and HTTP endpoints configuration to Spice CLI (run and sql)
  bin/spice/cmd/run.go
  bin/spice/cmd/sql.go
Labels: kind/enhancement

#4916 Fix mcp tools build
  crates/runtime/src/tools/mcp/mod.rs
Labels: kind/bug

#4917 Introduce runtime shutdown state
  bin/spiced/src/lib.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/status.rs
Labels: kind/enhancement

#4922 DuckDB acceleration: fix Decimal with zero scale support
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#4921 fix: Improve row collection loop
  crates/test-framework/src/spicetest/datasets/worker.rs
Labels: kind/bug

#4933 task: Add more dispatch files
  tools/testoperator/dispatch/clickbench/accelerated/on_zero_results/file_duckdb_file.yaml
  tools/testoperator/dispatch/clickbench/accelerated/on_zero_results/file_duckdb_memory.yaml
  tools/testoperator/dispatch/clickbench/accelerated/s3_arrow.yaml
  tools/testoperator/dispatch/clickbench/accelerated/s3_duckdb_file.yaml
  tools/testoperator/dispatch/clickbench/accelerated/s3_duckdb_memory.yaml
  tools/testoperator/dispatch/clickbench/accelerated/s3_sqlite_file.yaml
  tools/testoperator/dispatch/clickbench/accelerated/s3_sqlite_memory.yaml
  tools/testoperator/dispatch/tpcds/abfs.yaml
  tools/testoperator/dispatch/tpcds/accelerated/on_zero_results/file_duckdb_file.yaml
  tools/testoperator/dispatch/tpcds/accelerated/on_zero_results/file_duckdb_memory.yaml
  tools/testoperator/dispatch/tpcds/odbc-databricks.yaml
  tools/testoperator/dispatch/tpcds/spark.yaml
  tools/testoperator/dispatch/tpch/abfs.yaml
  tools/testoperator/dispatch/tpch/accelerated/on_zero_results/file_duckdb_file.yaml
  tools/testoperator/dispatch/tpch/accelerated/on_zero_results/file_duckdb_memory.yaml
  tools/testoperator/dispatch/tpch/iceberg_catalog.yaml
  tools/testoperator/dispatch/tpch/mssql.yaml
  tools/testoperator/dispatch/tpch/odbc_athena.yaml
  tools/testoperator/dispatch/tpch/odbc_databricks.yaml
  tools/testoperator/dispatch/tpch/snowflake_sf1.yaml
  tools/testoperator/dispatch/tpch/spark.yaml
  tools/testoperator/dispatch/tpch/spicecloud_catalog.yaml
Labels: kind/enhancement

#4936 Convert sequential search code block to parallel async
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/enhancement

#4939 fix: Allow metrics endpoint setting in CLI
  bin/spice/cmd/run.go
  bin/spice/pkg/context/context.go
Labels: kind/enhancement

#4938 fix: Throughput metric calculation
  crates/test-framework/src/spicetest/datasets/mod.rs
Labels: kind/bug

#4872 Update dependabot dependencies & `cargo update`
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/llms/Cargo.toml
  crates/llms/src/chat/mod.rs
  crates/model_components/Cargo.toml
  crates/package/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/tracing_util.rs
  crates/runtime/tests/acceleration/on_conflict.rs
  crates/runtime/tests/cors/mod.rs
  crates/runtime/tests/endpoint_auth/flight.rs
  crates/runtime/tests/endpoint_auth/http.rs
  crates/runtime/tests/flight/do_put.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/postgres/common.rs
  crates/runtime/tests/tls/mod.rs
  crates/test-framework/Cargo.toml
  crates/test-framework/src/utils/mod.rs
  crates/util/Cargo.toml
  go.mod
  go.sum
  tools/evalconverter/Cargo.toml
  tools/otelpublisher/Cargo.toml
Labels: kind/dependencies

#4941 Implement an Iceberg Data Connector
  Cargo.lock
  crates/data_components/src/graphql/client.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/iceberg.rs
  crates/runtime/tests/acceleration/single_instance_duckdb.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/postgres/mod.rs
Labels: kind/enhancement, area/data-connectors

#4942 Improve servers shutdown sequence during runtime termination
  crates/runtime/Cargo.toml
  crates/runtime/src/builder.rs
  crates/runtime/src/cancellable_task.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/opentelemetry.rs
Labels: kind/enhancement

#4946 Semantic model for views. Views visible in `table_schema` & `list_datasets` tools.
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/view.rs
  crates/runtime/src/tools/builtin/list_datasets.rs
  crates/runtime/src/tools/builtin/table_schema.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/view.rs
  crates/spicepod/src/lib.rs
  crates/spicepod/src/semantic.rs
Labels: kind/enhancement, area/ai

#4948 update openai-async
  Cargo.lock
  Cargo.toml
  crates/model_components/Cargo.toml
Labels: kind/bug

#4958 Don't trace canceled dataset refresh during runtime termination
  crates/runtime/src/accelerated_table/refresh_task.rs
Labels: kind/bug

#4956 fix: Redundant results snapshotting
  crates/test-framework/src/spicetest/datasets/worker.rs
  test/spicepods/tpch/accelerated/s3_sf5_arrow.yaml
  test/spicepods/tpch/accelerated/s3_sf5_duckdb_file.yaml
  test/spicepods/tpch/accelerated/s3_sf5_duckdb_memory.yaml
  test/spicepods/tpch/cache/mysql_1gb.yaml
  test/spicepods/tpch/cache/mysql_4gb.yaml
  test/spicepods/tpch/cache/mysql_ttl.yaml
  test/spicepods/tpch/cache/s3_arrow_1gb.yaml
  test/spicepods/tpch/cache/s3_arrow_4gb.yaml
  test/spicepods/tpch/cache/s3_arrow_ttl.yaml
  test/spicepods/tpch/cache/s3_cache_1gb.yaml
  test/spicepods/tpch/cache/s3_cache_4gb.yaml
  test/spicepods/tpch/cache/s3_cache_ttl.yaml
  test/spicepods/tpch/cache/s3_duckdb_file_1gb.yaml
  test/spicepods/tpch/cache/s3_duckdb_file_4gb.yaml
  test/spicepods/tpch/cache/s3_duckdb_file_ttl.yaml
  test/spicepods/tpch/cache/s3_duckdb_memory_1gb.yaml
  test/spicepods/tpch/cache/s3_duckdb_memory_4gb.yaml
  test/spicepods/tpch/cache/s3_duckdb_memory_ttl.yaml
  test/spicepods/tpch/s3_sf5.yaml
Labels: kind/bug

#4957 Create schema for views if not exist
  crates/runtime/src/datafusion.rs
Labels: kind/bug

#4970 Use metadata column `last_modified` when specified as a `time_column` / `time_partition_column` for object store based connectors
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataconnector/listing/connector.rs
Labels: kind/enhancement

#4953 List available operations in 'spice trace <operation>'
  bin/spice/cmd/trace.go
Labels: kind/bug

#4971 Add `duckdb_memory_limit` param support for DuckDB acceleration
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator/duckdb.rs
Labels: kind/enhancement

#4975 Initial commit of release analytics
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#4984 Fix Spice pods watcher
  crates/runtime/src/lib.rs
Labels: kind/bug

#4985 Fix Spice pods watcher
  crates/runtime/src/lib.rs
Labels: kind/bug

#4950 Add Iceberg dataset integration test
  .github/workflows/integration.yml
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/tests/flight/do_put.rs
  crates/runtime/tests/iceberg/mod.rs
  crates/runtime/tests/integration.rs
Labels: kind/enhancement

#4986 Add Iceberg dataset integration test (#4950)
  .github/workflows/integration.yml
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/tests/flight/do_put.rs
  crates/runtime/tests/iceberg/mod.rs
  crates/runtime/tests/integration.rs
  docs/release_notes/v1.0.5.md
Labels: kind/enhancement

#4987 Omit timestamp when warning regarding datasets with hyphens
  bin/spice/cmd/dataset.go
Labels: kind/bug

#4989 docs: Update qa_analytics.csv
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#4991 Update end_game template
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/optimization

#4994 Add v1.0.5 release notes
  docs/release_notes/v1.0.5.md
Labels: kind/optimization

#4995 Supported Versions: include v1.0.5
  SECURITY.md
Labels: kind/documentation, kind/enhancement

#4992 Dependabot updates
  Cargo.lock
  Cargo.toml
  go.mod
  go.sum
Labels: kind/dependencies

#4934 Switch to basic markdown formatting for vector search
  Cargo.lock
  crates/arrow_tools/Cargo.toml
  crates/arrow_tools/src/format.rs
  crates/arrow_tools/src/snapshots/arrow_tools__format__tests__pretty_format_markdown.snap
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/bug

#5001 docs: Update qa_analytics.csv
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#5002 feat: Add TPCDS FileAppendableSource for testoperator
  crates/test-framework/src/spicetest/append/sources/file.rs
Labels: kind/enhancement

#5003 Update `ring`
  Cargo.lock
Labels: kind/dependencies

#5006 docs: Update qa_analytics.csv
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#5004 feat: Add ClickBench FileAppendableSource for testoperator
  crates/test-framework/src/spicetest/append/sources/file.rs
Labels: kind/enhancement

#5008 feat: Validate append test table counts
  crates/test-framework/src/queries/mod.rs
  crates/test-framework/src/spicetest/append/mod.rs
  crates/test-framework/src/spicetest/append/sources/file.rs
  crates/test-framework/src/spicetest/append/worker.rs
  crates/test-framework/src/spicetest/datasets/mod.rs
  tools/testoperator/src/commands/append/mod.rs
Labels: kind/enhancement

#5010 Improve Vector Search performance for large content w/o primary key defined
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_chunking_no_pk_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_chunking_with_extra_column_no_pk_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_chunking_with_extra_columns_and_where_no_pk_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_chunking_with_extra_columns_and_where_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_chunking_with_extra_columns_response.snap
Labels: kind/bug

#5014 Don't try to downgrade Arc in test_acceleration_duckdb_single_instance
  crates/runtime/tests/acceleration/single_instance_duckdb.rs
Labels: kind/bug

#5011 feat: Add an initial testoperator vector search command
  crates/test-framework/src/lib.rs
  crates/test-framework/src/spicetest/mod.rs
  crates/test-framework/src/spicetest/vector_search/mod.rs
  crates/test-framework/src/spicetest/vector_search/worker.rs
  test/spicepods/vector_search/spicecloud_docs.yaml
  tools/testoperator/src/args/mod.rs
  tools/testoperator/src/commands/mod.rs
  tools/testoperator/src/commands/vector_search/mod.rs
  tools/testoperator/src/main.rs
Labels: kind/enhancement

#5018 feat: Update testoperator workflows for automatic snapshot updates
  .github/workflows/testoperator_dispatch.yml
  .github/workflows/testoperator_run_bench.yml
  crates/test-framework/Cargo.toml
  crates/test-framework/src/spicetest/append/sources/mod.rs
  crates/test-framework/src/spicetest/mod.rs
  tools/testoperator/Cargo.toml
  tools/testoperator/src/args/dispatch.rs
  tools/testoperator/src/args/mod.rs
  tools/testoperator/src/commands/dispatch/mod.rs
  tools/testoperator/src/commands/mod.rs
  tools/testoperator/src/main.rs
Labels: kind/enhancement

#5022 Fix Vector Search when additional columns include embedding column
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_chunking_with_extra_column_no_pk2_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_chunking_with_extra_columns2_response.snap
Labels: kind/bug

#5019 Implement proper `ready_state: on_registration` for federation enabled accelerators
  .vscode/launch.json
  Cargo.lock
  Cargo.toml
  crates/runtime/src/accelerated_table/federation.rs
  crates/runtime/src/accelerated_table/federation/provider.rs
  crates/runtime/src/accelerated_table/federation/source.rs
  crates/runtime/src/datafusion.rs
Labels: kind/bug

#5024 Include test for primary key passed as additional column in Vector Search
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_chunking_with_extra_column_no_pk2_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hf_chunking_with_extra_columns2_response.snap
Labels: kind/optimization

#4952 upgrade mistral.rs
  Cargo.lock
  crates/llms/Cargo.toml
Labels: kind/bug, kind/dependencies

#5038 fix: Indexes for TPCDS SQLite Spicepod
  test/spicepods/tpcds/accelerated/file_sqlite_file.yaml
  test/spicepods/tpcds/accelerated/file_sqlite_memory.yaml
Labels: kind/bug

#5042 Add comprehensive integration tests for the `ready_state` behavior
  crates/cache/src/lib.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/parameters.rs
  crates/runtime/src/request/protocol.rs
  crates/runtime/src/tools/mcp/mod.rs
  crates/runtime/src/tools/mcp/tool.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/ready_state/mod.rs
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_load_federated_arrow_acceleration.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_load_federated_arrow_acceleration_after_loading.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_load_federated_duckdb_acceleration.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_load_federated_duckdb_acceleration_after_loading.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_load_native_arrow_acceleration.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_load_native_arrow_acceleration_after_loading.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_load_native_duckdb_acceleration.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_load_native_duckdb_acceleration_after_loading.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_registration_federated_arrow_acceleration.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_registration_federated_arrow_acceleration_after_loading.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_registration_federated_duckdb_acceleration.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_registration_federated_duckdb_acceleration_after_loading.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_registration_native_arrow_acceleration.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_registration_native_arrow_acceleration_after_loading.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_registration_native_duckdb_acceleration.snap
  crates/runtime/tests/ready_state/snapshots/integration__ready_state__test_ready_state_on_registration_native_duckdb_acceleration_after_loading.snap
Labels: kind/enhancement

#5041 Include local files in generated Spicepod package
  Cargo.lock
  Makefile
  crates/package/Cargo.toml
  crates/package/src/lib.rs
  crates/runtime/src/objectstore/github.rs
  crates/runtime/src/tools/mcp/tool.rs
Labels: kind/enhancement

#5029 update mistral.rs to 'spiceai' branch rev
  Cargo.lock
  crates/llms/Cargo.toml
Labels: kind/enhancement, area/ai

#5047 Add DuckDB graceful shutdown test to E2E CI tests
  .github/workflows/e2e_test_ci.yml
  test/spicepods/tpch/accelerated/constraints/simulate_append_data.sh
Labels: kind/optimization

#5045 Add indexes and primary keys mismatch detection for DuckDB Acceleration
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5039 Configure spiced as an MCP SSE server
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/http.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/mcp.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/tools.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/tools/mcp/catalog.rs
  crates/runtime/src/tools/mcp/mod.rs
  crates/runtime/src/tools/mcp/server.rs
  crates/runtime/src/tools/mcp/tool.rs
  crates/runtime/src/tools/mod.rs
Labels: kind/enhancement, area/ai

#5058 fix: Disable benchmarks schedule, enable testoperator schedule
  .github/workflows/benchmarks.yml
  .github/workflows/testoperator_dispatch.yml
  .github/workflows/testoperator_run_bench.yml
  tools/testoperator/dispatch/clickbench/accelerated/on_zero_results/file_duckdb_file.yaml
  tools/testoperator/dispatch/clickbench/accelerated/on_zero_results/file_duckdb_memory.yaml
  tools/testoperator/dispatch/clickbench/accelerated/s3_arrow.yaml
  tools/testoperator/dispatch/clickbench/accelerated/s3_duckdb_file.yaml
  tools/testoperator/dispatch/clickbench/accelerated/s3_duckdb_memory.yaml
  tools/testoperator/dispatch/clickbench/accelerated/s3_sqlite_file.yaml
  tools/testoperator/dispatch/clickbench/accelerated/s3_sqlite_memory.yaml
Labels: kind/bug

#5061 Update ROADMAP.md March 2025
  docs/ROADMAP.md
Labels: kind/documentation

#5067 Update duckdb_append_with_pk_and_indexes.yaml (work for duckdb 1.1.x)
  test/spicepods/tpch/accelerated/constraints/duckdb_append_with_pk_and_indexes.yaml
Labels: kind/optimization

#5070 fix: Acceleration federation integration test
  crates/runtime/tests/acceleration/query_push_down.rs
Labels: kind/bug

#5055 fix: Downgrade to DuckDB 1.1.3
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5069 Run Iceberg Data Connector - DuckDB File mode integration test
  crates/runtime/tests/iceberg/mod.rs
  crates/runtime/tests/iceberg/snapshots/integration__iceberg__iceberg_integration_test_dataset.snap
  crates/runtime/tests/iceberg/snapshots/integration__iceberg__iceberg_integration_test_duckdb_acceleration.snap
Labels: kind/enhancement, kind/task

#5050 fix: All HTTP endpoints to hang when adding an invalid dataset with --pods-watcher-enabled
  crates/runtime/src/init/pods_watcher.rs
Labels: kind/bug

#5071 Improvements to Iceberg Catalog/Data Connector
  Cargo.lock
  Cargo.toml
  crates/data_components/src/iceberg/provider.rs
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/runtime/src/dataconnector/dynamodb.rs
  crates/runtime/src/dataconnector/iceberg.rs
  crates/runtime/src/objectstore/github.rs
  crates/runtime/src/secrets/stores/aws_secrets_manager.rs
Labels: kind/enhancement

#5053 Integration tests for MCP tooling
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/snapshots/integration_models__models__tools__mcp__mcp_fetch_list.snap
  crates/runtime/tests/models/snapshots/integration_models__models__tools__mcp__mcp_spiced_list.snap
  crates/runtime/tests/models/tools.rs
Labels: kind/enhancement, area/ai

#5075 Test restart behavior of DuckDB file acceleration against glue iceberg table
  crates/runtime/tests/iceberg/mod.rs
  crates/runtime/tests/iceberg/snapshots/integration__iceberg__iceberg_integration_test_duckdb_acceleration_restart.snap
Labels: kind/enhancement

#5057 OpenAPI docs for MCP
  crates/runtime/Cargo.toml
  crates/runtime/src/http.rs
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/mcp.rs
  crates/runtime/src/lib.rs
  tools/spiceschema/Cargo.toml
  tools/spiceschema/src/main.rs
Labels: kind/documentation, kind/enhancement, area/ai

#5086 Add `refresh_on_startup` Spicepod configuration param
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/mod.rs
  crates/runtime/src/datafusion.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#5090 fix: Acceleration federation test
  crates/runtime/tests/acceleration/query_push_down.rs
Labels: kind/bug

#5098 fix: Allow spiced commit in testoperator dispatch
  .github/workflows/testoperator_dispatch.yml
Labels: kind/bug

#5085 Add v1.0.6 release notes
  docs/release_notes/v1.0.6.md
Labels: kind/enhancement

#5095 fix: Use RefreshOverrides for the refresh API definition
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/http/v1/datasets.rs
Labels: kind/bug

#5099 fix: Increase tries for refresh_status_change_to_ready test
  crates/runtime/src/accelerated_table/refresh.rs
Labels: kind/bug

#5101 feat: Testoperator reports on max and median memory usage
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
  Cargo.lock
  crates/test-framework/Cargo.toml
  crates/test-framework/src/lib.rs
  crates/test-framework/src/process/mod.rs
  crates/test-framework/src/spiced/mod.rs
  crates/test-framework/src/utils/mod.rs
  tools/testoperator/Cargo.toml
  tools/testoperator/src/commands/append/mod.rs
  tools/testoperator/src/commands/bench/mod.rs
  tools/testoperator/src/commands/load/mod.rs
  tools/testoperator/src/commands/mod.rs
  tools/testoperator/src/commands/throughput/mod.rs
  tools/testoperator/src/commands/vector_search/mod.rs
Labels: kind/enhancement

#5106 fix: Fail testoperator on failed queries
  crates/test-framework/src/spicetest/datasets/mod.rs
  tools/testoperator/src/commands/bench/mod.rs
Labels: kind/bug

#5107 Update Helm chart to 1.0.6
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#5110 Add QA analytics for 1.0.6
  docs/release_notes/qa_analytics.csv
Labels: kind/enhancement

#5097 add env variables to tools, usable in MCP stdio
  crates/runtime/src/init/tool.rs
  crates/runtime/src/tools/factory/mod.rs
  crates/runtime/src/tools/mcp/catalog.rs
  crates/runtime/src/tools/mcp/factory.rs
  crates/runtime/src/tools/mcp/mod.rs
  crates/spicepod/src/component/tool.rs
Labels: kind/enhancement, area/ai

#5044 HF downloads obey SIGTERM
  Cargo.lock
  crates/llms/Cargo.toml
Labels: kind/bug, area/ai

#5112 Remove redundant mod name for iceberg integration tests
  crates/runtime/tests/iceberg/catalog/mod.rs
  crates/runtime/tests/iceberg/catalog/snapshots/integration__iceberg__catalog__glue_iceberg_integration_test_catalog.snap
  crates/runtime/tests/iceberg/connector/mod.rs
  crates/runtime/tests/iceberg/connector/snapshots/integration__iceberg__connector__iceberg_integration_test_dataset.snap
  crates/runtime/tests/iceberg/connector/snapshots/integration__iceberg__connector__iceberg_integration_test_duckdb_acceleration.snap
  crates/runtime/tests/iceberg/connector/snapshots/integration__iceberg__connector__iceberg_integration_test_duckdb_acceleration_restart.snap
  crates/runtime/tests/iceberg/mod.rs
Labels: kind/bug

#5103 Use fixed data directory for test operator
  crates/test-framework/src/snapshot/mod.rs
Labels: kind/bug

#5040 Improvements for evals
  Cargo.lock
  bin/spice/pkg/api/util.go
  crates/runtime/Cargo.toml
  crates/runtime/src/init/eval.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/eval/mod.rs
  crates/runtime/src/model/eval/scorer/levenshtein.rs
  crates/runtime/src/model/eval/scorer/mod.rs
Labels: kind/enhancement, area/ai

#5115 Make McpProxy trait for MCP passthrough
  crates/runtime/src/tools/mcp/mod.rs
  crates/runtime/src/tools/mcp/server.rs
  crates/runtime/src/tools/mcp/tool.rs
  crates/runtime/src/tools/mod.rs
Labels: kind/bug, area/ai

#5116 Properly handle '/' for tool names.
  crates/runtime/src/model/tool_use.rs
Labels: kind/bug, area/ai

#5120 Use retry logic when loading tools
  crates/runtime/src/init/tool.rs
  crates/util/src/fibonacci_backoff.rs
Labels: kind/enhancement, area/ai

#5119 Exclude slow tests from regular pr runs
  .github/workflows/integration.yml
  crates/runtime/Cargo.toml
  crates/runtime/tests/iceberg/catalog/mod.rs
Labels: kind/optimization

#5130 Fix test operator snapshot update
  .github/workflows/testoperator_run_bench.yml
Labels: kind/bug

#5126 spice init: Fixes windows bug where full path is used for spicepod name
  bin/spice/cmd/init.go
Labels: kind/bug

#5124 Improve performance of schema inference for object-store data connectors
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/tests/s3/mod.rs
  crates/runtime/tests/s3/snapshots/integration__s3__s3_bulk_bucket_schema.snap
  crates/runtime/tests/s3/snapshots/integration__s3__s3_schema_evolution.snap
Labels: kind/bug

#5102 Implement graceful shutdown for HTTP server
  crates/runtime/src/http.rs
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#5142 Update enhancement.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: kind/enhancement

#5147 Fix go lint errors
  bin/spice/cmd/chat.go
  bin/spice/cmd/nsql.go
  bin/spice/cmd/search.go
  bin/spice/cmd/upgrade.go
  bin/spice/pkg/api/client.go
  bin/spice/pkg/api/status.go
  bin/spice/pkg/api/util.go
  bin/spice/pkg/github/github.go
  bin/spice/pkg/github/release.go
  bin/spice/pkg/registry/spicerack.go
  bin/spice/pkg/spicepod/spicepod.go
  bin/spice/pkg/util/file.go
  bin/spice/pkg/util/hash.go
  bin/spice/pkg/util/string.go
  bin/spice/pkg/util/untar.go
  bin/spice/pkg/util/zip.go
Labels: kind/bug

#5114 Fix Dremio schema inference
  crates/data_components/src/flight.rs
Labels: kind/bug

#5145 Add GitHub Workflow and PoC Spicepod configuration to run FinanceBench tests
  .github/workflows/financebench.yml
  test/financebench/README.md
  test/financebench/spicepod_gpt-4o.yaml
  tools/testoperator/src/commands/evals/mod.rs
Labels: kind/enhancement

#5149 Enable Spice to load larger than memory datasets into DuckDB accelerations
  Cargo.lock
  Cargo.toml
  crates/data_components/src/duckdb.rs
Labels: kind/bug

#5152 Add `temp_directory` runtime parameter and insert it for DuckDB accelerations
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#5156 De-duplicate attachments in DuckDBAttachments
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5153 v1.0.7 release note
  docs/release_notes/v1.0.7.md
Labels: kind/documentation

#5159 Update Helm chart to 1.0.7
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#5161 Add github token to macos test release download tasks
  .github/workflows/e2e_test_release_install_ai.yml
Labels: kind/bug

#5164 Add a performance comparison section for 1.0.7
  docs/release_notes/v1.0.7.md
Labels: kind/documentation

#5167 docs: Add snafu error variant point to style guide
  docs/dev/style_guide.md
Labels: kind/documentation

#5117 Adjust DuckDB connection pool size based on DuckDB accelerator instances usage
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator/duckdb.rs
Labels: kind/bug

#5169 Add automatic retry for NSQL queries
  crates/llms/src/chat/nsql/default.rs
  crates/llms/src/chat/nsql/json.rs
  crates/llms/src/chat/nsql/mod.rs
  crates/llms/src/chat/nsql/snapshots/llms__chat__nsql__tests__sql_gen_default_with_failed_attempt.snap
  crates/llms/src/chat/nsql/structured_output.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/nsql.rs
Labels: kind/enhancement

#5170 Include chat completion id to task history
  crates/runtime/src/model/wrapper.rs
Labels: kind/enhancement

#5171 Trace when all runtime components are ready
  crates/runtime/src/lib.rs
Labels: kind/enhancement

#5165 Update qa_analytics.csv for 1.0.7
  docs/release_notes/qa_analytics.csv
Labels: kind/enhancement

#5173 Set default tool recursion limit to 10 to prevent infinite loops
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/model/chat.rs
Labels: kind/bug

#5178 Add support for `schema_source_path` param for object-store data connectors
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/listing/mod.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/tests/s3/mod.rs
  crates/runtime/tests/s3/snapshots/integration__s3__s3_schema_source_path_ds1_customer.snap
  crates/runtime/tests/s3/snapshots/integration__s3__s3_schema_source_path_ds2_customer.snap
  crates/runtime/tests/s3/snapshots/integration__s3__s3_schema_source_path_ds3_lineitem.snap
Labels: kind/enhancement

#5179 Run license check and check changes on self-hosted macOS runners
  .github/actions/setup-make/action.yml
  .github/actions/setup-rust/action.yml
  .github/workflows/enforce-labels.yml
  .github/workflows/license_check.yml
  .github/workflows/pr.yml
Labels: kind/dependencies

#5183 Add MCP
  README.md
Labels: kind/documentation

#5185 Set version v1.1.0
  .schema/openapi.json
  Cargo.lock
  Cargo.toml
Labels: kind/documentation

#5123 Enable 'parameterized_prompt' in LLMs
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/wrapper/ast.rs
  crates/runtime/src/model/wrapper/mod.rs
Labels: kind/enhancement, area/ai
