Repository spiceai/spiceai, pull requests merged in 2025-09, with the labels that each got.

#6985 Update `datafusion` and `datafusion-table-providers` crates
  Cargo.lock
  Cargo.toml
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__filters_pushdown.snap
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__filters_pushdown_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__non_filters_pushdown_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_multiple_column_sql_text_search.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_sql_text_search.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_sql_vector_search.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_embeddings_sql_vector_search.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_text_column_sql_text_search_basic_answer.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_text_column_sql_text_search_basic_question.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_vector_search_sql_composite_key.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_vector_search_sql_composite_key_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_vector_search_sql_filters_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_vector_search_sql_single_column.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_vector_search_sql_single_column_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_basic_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_filters_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_filters_metadata_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_projection_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_projection_metadata_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_basic_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_filters_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_no_score_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_projection_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_random_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_vectors.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_vectors_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__test_text_search_sql_where_rowid_is_search_column_basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__test_text_search_sql_where_rowid_is_search_column_composite_pk_basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__text_search_sql_text_search_basic.snap
Labels: kind/bug, area/ai

#6998 Update build_and_release macOS pipeline to skip updating cmake if installed
  .github/workflows/build_and_release.yml
Labels: kind/bug, area/ci

#6991 Mark Kafka Data Connector Alpha quality
  README.md
  docs/criteria/connectors/alpha.md
Labels: kind/optimization

#6996 Spice CLI trace: make error friendlier when task_history is disabled
  bin/spice/cmd/trace.go
  bin/spice/pkg/taskhistory/taskhistory.go
Labels: kind/bug

#6953 Warn when runtime or management is added in spicepod dependency
  Cargo.lock
  bin/spiced/Cargo.toml
  bin/spiced/src/lib.rs
  bin/spiced/src/main.rs
  bin/spiced/src/tracing.rs
  crates/app/Cargo.toml
  crates/app/src/lib.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/init/caching.rs
  crates/runtime/src/lib.rs
  crates/util/Cargo.toml
  crates/util/src/lib.rs
  crates/util/src/tracing_util.rs
Labels: kind/bug, area/quality

#6982 Enable `.datasets[].vectors.params.s3_vectors_distance_metric` for S3 Vectors
  crates/data_components/src/s3_vectors/mod.rs
  crates/data_components/src/s3_vectors/vector_table.rs
  crates/runtime/src/embeddings/index/s3/mod.rs
Labels: kind/bug, area/ai

#6986 Add s3_vectors index support for CDC and Append streams
  crates/data_components/src/cdc.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/index/s3/write.rs
Labels: kind/enhancement

#7006 Fix release notes merge conflict
  docs/release_notes/v1.6.0.md
  docs/release_notes/v1.6.1.md
  docs/release_notes/v1.6/v1.6.1.md
Labels: kind/bug, kind/documentation

#7004 Find all vector indexes in v1/search
  crates/runtime/src/search/util.rs
  crates/runtime/src/search/vector_search.rs
Labels: kind/bug, area/ai

#7007 Fix RRF; reorder by score
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_multiple_column_additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_multiple_column_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_multiple_column_with_where_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_text_column_additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_text_column_basic_response.snap
  crates/search/src/aggregation/reciprocal_rank.rs
  crates/search/src/aggregation/snapshots/search__aggregation__reciprocal_rank__tests__multiple_keys_and_tables.snap
  crates/search/src/aggregation/snapshots/search__aggregation__reciprocal_rank__tests__single_table_single_key.snap
  crates/search/src/aggregation/snapshots/search__aggregation__reciprocal_rank__tests__three_tables_composite_key.snap
  crates/search/src/aggregation/snapshots/search__aggregation__reciprocal_rank__tests__two_tables_additional_columns.snap
  crates/search/src/aggregation/snapshots/search__aggregation__reciprocal_rank__tests__two_tables_single_key.snap
Labels: kind/bug, area/ai

#7002 feat(trace): add --sql flag to output SQL query for spice trace
  bin/spice/cmd/trace.go
Labels: kind/bug, area/ai

#7021 Speed up full text indexing/embeddings computation on change streams
  crates/runtime/src/changes/mod.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/search/full_text/connector.rs
Labels: kind/enhancement

#6895 Improve error messaging in tools
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/search/vector_search.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
  crates/runtime/src/tools/builtin/list_datasets.rs
  crates/runtime/src/tools/builtin/sample/tool.rs
  crates/runtime/src/tools/builtin/sql.rs
  crates/runtime/src/tools/builtin/table_schema.rs
  crates/runtime/src/tools/builtin/web_search/tool.rs
  crates/search/src/aggregation.rs
Labels: kind/bug, area/ai

#6968 Write and query partitioned S3 Vector indexes
  crates/data_components/src/s3_vectors/index_query_provider.rs
  crates/data_components/src/s3_vectors/list_provider.rs
  crates/data_components/src/s3_vectors/mod.rs
  crates/data_components/src/s3_vectors/partitioned_index_query_provider.rs
  crates/data_components/src/s3_vectors/vector_table.rs
  crates/runtime/src/embeddings/index/s3/index.rs
  crates/runtime/src/embeddings/index/s3/mod.rs
  crates/runtime/src/embeddings/udtf.rs
Labels: kind/enhancement

#7037 De-duplicate the changes stream
  crates/data_components/src/cdc/stream.rs
  crates/data_components/src/debezium_kafka.rs
  crates/data_components/src/kafka.rs
  crates/data_components/src/s3_vectors/vector_table.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/accelerated_table/refresh_task/constraints.rs
  crates/runtime/src/dataconnector/mod.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/index/s3/write.rs
  crates/runtime/src/search/full_text/connector.rs
Labels: kind/enhancement

#7044 Truncate text_embed task_history trace
  crates/runtime/src/embeddings/task.rs
Labels: kind/bug

#7047 fix redundant text embeds in vector search
  crates/runtime/src/search/candidate/vector.rs
Labels: kind/bug

#7048 Don't warn on task history export errors
  crates/runtime/src/management/mod.rs
Labels: kind/optimization

#7053 fix: Avoid redundant search embedding
  crates/runtime/src/search/candidate/vector.rs
Labels: kind/bug

#7056 Use the UTC offset for the `start_time` and `end_time` fields in the task history
  crates/runtime/src/task_history/mod.rs
Labels: kind/bug

#7060 Update supported versions in SECURITY.md
  SECURITY.md
Labels: kind/documentation

#6984 Enable parameters to enforce the value is one of several options
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/kafka.rs
  crates/runtime/src/dataconnector/listing/mod.rs
  crates/runtime/src/dataconnector/mongodb.rs
  crates/runtime/src/embeddings/index/s3/mod.rs
  crates/runtime/src/model/params/bedrock.rs
  crates/runtime/src/model/params/openai.rs
  crates/runtime/src/parameters.rs
Labels: area/data-connectors, area/quality, kind/optimization

#7025 feat: Add HTTP query concurrency support to testoperator
  Cargo.lock
  crates/test-framework/Cargo.toml
  crates/test-framework/src/spicetest/datasets/mod.rs
  crates/test-framework/src/spicetest/datasets/worker.rs
  tools/testoperator/src/args/dataset.rs
  tools/testoperator/src/args/mod.rs
  tools/testoperator/src/commands/bench/mod.rs
  tools/testoperator/src/commands/load/mod.rs
  tools/testoperator/src/commands/throughput/mod.rs
  tools/testoperator/src/commands/vector_search/mod.rs
  tools/testoperator/src/commands/vector_search/mteb_quora.rs
  tools/testoperator/src/main.rs
Labels: kind/enhancement, area/quality

#7033 Ensure no data does not throw error in v1/search
  crates/runtime/src/search/vector_search.rs
  crates/search/src/aggregation.rs
  crates/search/src/pipeline.rs
Labels: kind/bug, area/ai

#7075 No join predicate pushdown on empty results
  crates/runtime/src/embeddings/index/query_table.rs
Labels: kind/bug, area/ai

#7036 Bedrock: Tool use without inputs must empty Document
  crates/llms/src/bedrock/chat/mod.rs
Labels: kind/bug, area/ai

#7039 Only call 'list_datasets' once, after initial system/user messages
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/model/snapshots/runtime__model__tool_use__tests__insert_initial_tools_empty_messages.snap
  crates/runtime/src/model/snapshots/runtime__model__tool_use__tests__insert_initial_tools_insertion_point_end_of_messages.snap
  crates/runtime/src/model/snapshots/runtime__model__tool_use__tests__insert_initial_tools_skips_if_tool_already_exists.snap
  crates/runtime/src/model/snapshots/runtime__model__tool_use__tests__insert_initial_tools_with_different_tool_name.snap
  crates/runtime/src/model/snapshots/runtime__model__tool_use__tests__insert_initial_tools_with_existing_assistant_message.snap
  crates/runtime/src/model/snapshots/runtime__model__tool_use__tests__insert_initial_tools_with_system_and_user_messages.snap
  crates/runtime/src/model/tool_use.rs
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_ai_completion_input.snap
Labels: kind/bug, area/ai

#7088 Add friendly message for Kafka operation timeout error, improve code
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
Labels: kind/refactor

#6967 `embed` UDF
  Cargo.lock
  crates/llms/src/embeddings/mod.rs
  crates/runtime-datafusion-udfs/Cargo.toml
  crates/runtime-datafusion-udfs/src/embed.rs
  crates/runtime-datafusion-udfs/src/lib.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/udf.rs
Labels: kind/enhancement, ux-change

#6978 Add xxhash support for search/sql results
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  crates/cache/Cargo.toml
  crates/cache/src/lib.rs
  crates/cache/src/lru_cache.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/init/caching.rs
  crates/spicepod/src/component/caching.rs
Labels: kind/enhancement, ux-change, area/sql, area/caching

#7124 Add tests for xxhash hashers
  .github/workflows/pr.yml
  Makefile
  crates/cache/src/lru_cache.rs
Labels: kind/enhancement

#7128 Fix formatting to improve merges
  .github/ISSUE_TEMPLATE/datafusion_upgrade.md
  .github/ISSUE_TEMPLATE/end_game.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/actions/build-testoperator/action.yml
  .github/actions/install-postgres/action.yml
  .github/actions/run-query/action.yml
  .github/actions/setup-cc/action.yml
  .github/actions/setup-minio/action.yml
  .github/actions/setup-odbc/action.yml
  .github/actions/setup-sccache/action.yml
  .github/actions/setup-spiced/action.yml
  .github/actions/setup-testoperator-data/action.yml
  .github/actions/verify-accelerated-query/action.yml
  .github/actions/verify-dataset/action.yml
  .github/dependabot.yml
  .github/workflows/ai_benchmark_nsql.yml
  .github/workflows/e2e_test_spice_cli.yml
  .github/workflows/financebench.yml
  .github/workflows/generate-openapi.yml
  .github/workflows/generate_json_schema.yml
  .github/workflows/integration.yml
  .github/workflows/integration_data_components.yaml
  .github/workflows/pr.yml
  .github/workflows/release_only.yml
  .github/workflows/release_only_cuda.yml
  .github/workflows/testoperator_run_http_consistency.yml
  .github/workflows/testoperator_run_http_overhead.yml
  .github/workflows/testoperator_run_search.yml
  .schema/openapi.json
  .vscode/launch.json
  .vscode/tasks.json
  CONTRIBUTING.md
  SECURITY.md
  monitoring/datadog-dashboard.json
Labels: kind/bug

#7113 Add tests to nulling logic.
  crates/runtime/src/embeddings/index/s3/write.rs
  crates/util/src/lib.rs
Labels: kind/bug, area/ai

#7090 Search: RRF UDTF
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/udf.rs
  crates/runtime/src/embeddings/udtf.rs
  crates/runtime/src/search/full_text/udtf.rs
  crates/runtime/src/search/mod.rs
  crates/runtime/src/search/rrf.rs
Labels: kind/enhancement

#7156 Revert "Use proper federation in `max_timestamp_df` during acceleration refresh (#7055)"
  crates/data_components/src/poly.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/refresh_sql/refresh_max_timestamp_df.rs
  crates/runtime/tests/refresh_sql/snapshots/integration__refresh_sql__refresh_max_timestamp_df__refresh_max_timestamp_df_explain_plan.snap
Labels: kind/bug

#7052 fix: Remove keywords from AI document search (#7043)
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/search/request.rs
  crates/runtime/src/search/vector_search.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_ai_completion_input.snap
  crates/runtime/tests/models/snapshots/integration_models__models__tools__mcp__mcp_spiced_list.snap
Labels: kind/bug, area/search

#7171 Update TEI
  Cargo.lock
  crates/llms/Cargo.toml
Labels: kind/dependencies, area/ai

#7155 fix: Ensure vector search UDTF respects the supplied projection
  .github/actions/push-snap-changes/action.yml
  .github/workflows/integration_models.yml
  crates/runtime/src/embeddings/udtf.rs
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_sql_vector_search_no_score.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_column_additional_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_column_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_column_where_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_embedding_parent_child_additional_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_embedding_parent_child_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__multi_embedding_parent_child_where_response.snap
Labels: kind/bug

#7146 Add Kafka-specific metrics for consumer lag and consumed records
  crates/data_components/src/kafka.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/kafka.rs
Labels: kind/enhancement

#7173 Fix timestamp parsing for spice trace
  bin/spice/pkg/taskhistory/taskhistory.go
Labels: kind/bug

#7180 Support full-text indexing on CDC/append streams
  crates/runtime/src/changes/mod.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/search/full_text/connector.rs
  crates/runtime/tests/kafka/full_text.rs
  crates/runtime/tests/kafka/mod.rs
  crates/runtime/tests/kafka/snapshots/integration__kafka__stack_qa_data.snap
  crates/runtime/tests/kafka/test_data/stack_qa.json
  crates/spicepod/src/semantic.rs
Labels: kind/enhancement

#7191 Bump iceberg-rust version to include limit push down
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement, kind/task

#7193 Make full text stream connector more robust
  crates/runtime/src/search/full_text/connector.rs
Labels: kind/enhancement

#7103 Initial changes for SearchIndex
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/index/mod.rs
  crates/runtime/src/embeddings/index/query_table.rs
  crates/runtime/src/embeddings/index/s3/index.rs
  crates/runtime/src/embeddings/index/s3/mod.rs
  crates/runtime/src/embeddings/index/s3/write.rs
  crates/runtime/src/embeddings/index/scan_table.rs
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_basic.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_basic_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_basic_multiple_pk.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_filter.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_filter_use_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_filter_use_metadata_multiple_pk.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_projection.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_projection_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_projection_metadata_multiple_pk.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_projection_use_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_projection_use_metadata_multiple_pk.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_embedding_no_join.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_filter.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_filter_multiple_pk.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_projection.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_projection_multiple_pk.snap
  crates/runtime/src/embeddings/udtf.rs
  crates/runtime/src/search/full_text/mod.rs
  crates/runtime/src/search/full_text/udtf.rs
  crates/search/src/generation/text_search/index.rs
  crates/search/src/generation/text_search/mod.rs
  crates/search/src/generation/text_search/udtf.rs
  crates/search/src/index.rs
  crates/search/src/lib.rs
  crates/search/src/metadata.rs
  crates/search/src/provider.rs
Labels: kind/enhancement, area/ai

#7197 Robustly handle indexing FTS for CDC streams
  crates/runtime-datafusion-index/src/provider.rs
  crates/runtime/src/changes/mod.rs
  crates/runtime/src/embeddings/connector.rs
  crates/runtime/src/embeddings/udtf.rs
  crates/runtime/src/search/full_text/connector.rs
  crates/runtime/src/search/full_text/udtf.rs
  crates/runtime/src/search/util.rs
  crates/runtime/src/search/vector_search.rs
Labels: kind/bug

#7202 Add spicepod.yml
  spicepod.yml
Labels: kind/enhancement

#7203 Delta Lake: Support read pruning on timestamp columns using maxValues stats
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#7194 feat: Add initial embeddings cache
  Cargo.lock
  Cargo.toml
  crates/app/src/lib.rs
  crates/cache/Cargo.toml
  crates/cache/src/key.rs
  crates/cache/src/lib.rs
  crates/cache/src/lru_cache.rs
  crates/cache/src/metrics.rs
  crates/cache/src/result/embeddings.rs
  crates/cache/src/result/mod.rs
  crates/cache/src/simple_cache.rs
  crates/llms/Cargo.toml
  crates/llms/src/embeddings/mod.rs
  crates/llms/src/openai/embed.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/init/caching.rs
  crates/runtime/src/init/embedding.rs
  crates/runtime/src/model/embed.rs
  crates/runtime/src/search/vector_search.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/search.rs
  crates/spicepod/src/component/caching.rs
Labels: kind/enhancement

#7201 Make S3vector a FixedSizeListArray
  Cargo.lock
  crates/arrow_tools/src/record_batch.rs
  crates/data_components/Cargo.toml
  crates/data_components/src/s3_vectors/list_provider.rs
  crates/data_components/src/s3_vectors/query_provider.rs
  crates/data_components/src/s3_vectors/vector_table.rs
  crates/runtime/src/embeddings/index/s3/write.rs
Labels: kind/bug, area/ai

#7204 feat: Add embeddings cache to all embeddings
  crates/llms/src/bedrock/embed/mod.rs
  crates/llms/src/databricks.rs
  crates/llms/src/embeddings/candle/tei.rs
  crates/llms/src/model2vec.rs
  crates/runtime/src/init/caching.rs
  crates/runtime/src/model/embed.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/local.rs
  crates/runtime/tests/models/openai.rs
Labels: kind/enhancement

#7215 Update duckdb version to make ICU statically linked by default
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#7212 Use `Instant` + `saturating_sub` to handle time drift
  crates/cache/src/lib.rs
  crates/cache/src/lru_cache.rs
  crates/cache/src/metrics.rs
Labels: kind/bug

#7219 Flatten 'IndexedTableProvider' when adding full-text support
  crates/runtime/src/search/full_text/connector.rs
Labels: kind/bug, area/ai

#7230 Make S3vector a FixedSizeListArray
  Cargo.lock
  crates/arrow_tools/src/record_batch.rs
  crates/data_components/Cargo.toml
  crates/data_components/src/s3_vectors/list_provider.rs
  crates/data_components/src/s3_vectors/query_provider.rs
  crates/data_components/src/s3_vectors/vector_table.rs
  crates/runtime/src/embeddings/index/mod.rs
  crates/runtime/src/embeddings/index/s3/index.rs
  crates/runtime/src/embeddings/index/s3/write.rs
  crates/runtime/src/embeddings/index/scan_table.rs
Labels: kind/enhancement, area/ai

#7228 Proper federation during acceleration refresh + datafusion version bump + integration tests
  Cargo.lock
  Cargo.toml
  Makefile
  crates/data_components/src/poly.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/tests/acceleration/mod.rs
  crates/runtime/tests/acceleration/refresh/common.rs
  crates/runtime/tests/acceleration/refresh/mod.rs
  crates/runtime/tests/acceleration/refresh/refresh_duckdb.rs
  crates/runtime/tests/acceleration/refresh/refresh_postgres.rs
  crates/runtime/tests/acceleration/refresh/refresh_sqlite.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/refresh_sql/refresh_max_timestamp_df.rs
  crates/runtime/tests/refresh_sql/snapshots/integration__refresh_sql__refresh_max_timestamp_df__refresh_max_timestamp_df_explain_plan.snap
Labels: kind/bug

#7232 Use DuckDBDialect for DuckDB non-federated queries
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#7233 Remove duplicate pg_port configuration in test
  crates/runtime/tests/acceleration/refresh/refresh_postgres.rs
Labels: kind/bug

#7240 Catalog connection error: fix connector name from 'iceberg' to 'spice.ai'
  crates/runtime/src/catalogconnector/spice_cloud.rs
Labels: kind/bug

#7199 Create PutVectorsSink
  crates/data_components/Cargo.toml
  crates/data_components/src/s3_vectors/mod.rs
  crates/data_components/src/s3_vectors/put_vectors_sink.rs
Labels: kind/enhancement

#7239 Benchmark tests: fix API key reference in spicecloud catalog
  .github/workflows/testoperator_run_bench.yml
Labels: kind/bug

#7255 Postgres: Improve Decimals read performance and add Name type support
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#7220 Add tests for hybrid search on a vector engine.
  crates/runtime/tests/models/s3_vectors.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_additional_columns2_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_vector_search_sql_basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_vector_search_sql_basic_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_vector_search_sql_w_question.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_vector_search_sql_w_question_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_vector_search_text_search.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_vector_search_text_search_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_vector_search_text_search_w_answer.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_vector_search_text_search_w_answer_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_vector_search_text_search_w_embedding.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_vector_search_text_search_w_embedding_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_hybrid_with_where_response.snap
Labels: kind/bug, area/ai

#7258 update DF commit
  Cargo.toml
Labels: kind/bug

#7261 Update cargo.lock after Datafusion version update
  Cargo.lock
Labels: kind/documentation

#7282 Ensure FTS metadata columns can be used in projection
  crates/runtime/tests/models/search.rs
  crates/search/src/generation/text_search/index.rs
Labels: kind/bug, area/ai

#7284 Use 8-core runners for Winsows CUDA builds
  .github/workflows/build_and_release_cuda.yml
Labels: kind/enhancement

#7283 Make search test more robust
  crates/runtime/tests/models/search.rs
Labels: kind/optimization

#7272 Post-release housekeeping
  .github/workflows/testoperator_dispatch.yml
  Cargo.lock
  Cargo.toml
  SECURITY.md
  deploy/chart/Chart.yaml
  docs/release_notes/v1.7.0.md
  version.txt
Labels: kind/optimization

#7291 use SessionContext::new_empty in RRF
  crates/runtime/src/search/rrf.rs
Labels: kind/enhancement

#7294 RRF: Rank and recency boosting
  Cargo.lock
  Cargo.toml
  crates/runtime/src/search/rrf.rs
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_multiple_column_sql_rrf_explicit_join.snap
Labels: kind/enhancement, area/sql

#7297 Update ROADMAP.md by removing v1.7 milestone
  docs/ROADMAP.md
Labels: kind/optimization

#7302 fix removing embedding column
  crates/search/src/provider.rs
Labels: kind/bug, area/ai

#7304 Enable DML `Update` SQL operations for datasets configured as `access: read_write`
  crates/runtime/src/component/dataset/builder.rs
  crates/runtime/src/component/dataset/mod.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/sql_validator.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/management/mod.rs
  crates/spice_cloud/src/lib.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#7198 Create and parse partitioned S3 vector index names
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/s3_vectors/mod.rs
  crates/data_components/src/s3_vectors/partition.rs
  crates/data_components/src/s3_vectors/snapshots/data_components__s3_vectors__partition__tests__partition_by_stability-2.snap
  crates/data_components/src/s3_vectors/snapshots/data_components__s3_vectors__partition__tests__partition_by_stability-3.snap
  crates/data_components/src/s3_vectors/snapshots/data_components__s3_vectors__partition__tests__partition_by_stability-4.snap
  crates/data_components/src/s3_vectors/snapshots/data_components__s3_vectors__partition__tests__partition_by_stability-5.snap
  crates/data_components/src/s3_vectors/snapshots/data_components__s3_vectors__partition__tests__partition_by_stability.snap
Labels: kind/enhancement

#7306 RRF: Project top scores, do not yield duplicate results
  crates/runtime/src/search/rrf.rs
Labels: kind/bug

#7316 Don’t cache modification queries (DDL, DML, COPY)
  crates/cache/src/lib.rs
Labels: kind/bug

#7310 Enhancement: Implement before/after/lag metrics for acceleration refresh
  crates/runtime/src/accelerated_table/metrics.rs
  crates/runtime/src/accelerated_table/mod.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/timestamp_metrics_utils.rs
  crates/runtime/src/timing.rs
Labels: kind/enhancement

#7315 Add support for writing into Iceberg tables
  .github/workflows/integration.yml
  bin/spiced/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector/iceberg.rs
  crates/runtime/tests/iceberg/mod.rs
  crates/runtime/tests/iceberg/write/mod.rs
  crates/runtime/tests/iceberg/write/snapshots/integration__iceberg__write__iceberg_insert_into_table_appended_rows.snap
  crates/runtime/tests/iceberg/write/snapshots/integration__iceberg__write__iceberg_insert_into_table_result.snap
Labels: kind/enhancement

#7327 Fix lint warnings
  .github/workflows/enforce-pulls-with-spice.yml
  crates/data_components/src/clickhouse.rs
  crates/data_components/src/databricks/sql_warehouse.rs
  crates/data_components/src/snowflake.rs
  crates/db_connection_pool/src/clickhousepool.rs
  crates/db_connection_pool/src/dbconnection/clickhouseconn.rs
  crates/db_connection_pool/src/dbconnection/snowflakeconn.rs
  crates/db_connection_pool/src/snowflakepool.rs
  crates/llms/src/anthropic/types.rs
  crates/runtime/src/dataconnector/snowflake.rs
Labels: kind/refactor, kind/task

#7331 FTS max search results 100 -> 1000
  crates/search/src/generation/text_search/mod.rs
  crates/search/src/generation/text_search/query.rs
Labels: kind/bug, area/ai

#7333 Use spicepod embedding model name for 'model_name()'
  crates/runtime/src/embeddings/task.rs
Labels: kind/refactor, area/ai

#7335 Handle async queries for Databricks SQL Warehouse API
  crates/data_components/src/databricks/sql_warehouse.rs
  crates/util/src/fibonacci_backoff.rs
Labels: kind/bug

#7330 Enable DML (INSERT INTO) operations for catalogs configured as `access:read_write`
  crates/runtime/src/component/catalog.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/datafusion/sql_validator.rs
  crates/runtime/src/init/catalog.rs
  crates/runtime/src/request/databricks.rs
  crates/spicepod/src/component/catalog.rs
Labels: kind/enhancement

#7348 v1.7.1 release notes
  docs/release_notes/v1.7.1.md
Labels: kind/documentation

#7355 Add support for writing into Glue (Iceberg) tables and catalogs
  crates/runtime/src/component/access.rs
  crates/runtime/src/component/catalog.rs
  crates/runtime/src/component/dataset/builder.rs
  crates/runtime/src/component/dataset/mod.rs
  crates/runtime/src/component/mod.rs
  crates/runtime/src/dataconnector/glue.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/management/mod.rs
  crates/runtime/src/request/databricks.rs
  crates/runtime/tests/iceberg/write/mod.rs
  crates/runtime/tests/iceberg/write/snapshots/integration__iceberg__write__catalog_appended_rows.snap
  crates/runtime/tests/iceberg/write/snapshots/integration__iceberg__write__catalog_result.snap
  crates/runtime/tests/iceberg/write/snapshots/integration__iceberg__write__glue_catalog_appended_rows.snap
  crates/runtime/tests/iceberg/write/snapshots/integration__iceberg__write__glue_catalog_result.snap
  crates/runtime/tests/iceberg/write/snapshots/integration__iceberg__write__glue_table_appended_rows.snap
  crates/runtime/tests/iceberg/write/snapshots/integration__iceberg__write__glue_table_result.snap
  crates/runtime/tests/iceberg/write/snapshots/integration__iceberg__write__table_appended_rows.snap
  crates/runtime/tests/iceberg/write/snapshots/integration__iceberg__write__table_result.snap
  crates/spice_cloud/src/lib.rs
  crates/spicepod/src/component.rs
  crates/spicepod/src/component/access.rs
  crates/spicepod/src/component/catalog.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#7375 Update helm to v1.7.1
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/bug, endgame, kind/task

#7380 1.7.1 release analytics
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation
