Repository spiceai/spiceai, pull requests merged in 2025-08, with the labels that each got.

#6661 Redshift read support
  Cargo.lock
  Cargo.toml
Labels: kind/bug, kind/enhancement

#6667 ROADMAP updates Aug 1, 2025
  docs/ROADMAP.md
Labels: kind/documentation

#6672 Limit Concurrent Requests for GitHub
  crates/data_components/src/graphql/builder.rs
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/graphql/mod.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/graphql.rs
Labels: kind/bug

#6675 Make `FullTextSearchExec` robust to RecordBatch column ordering.
  crates/search/src/generation/text_search/exec.rs
Labels: kind/bug, area/ai

#6663 fix: Support include for Iceberg
  crates/data_components/src/iceberg/provider.rs
  crates/data_components/tests/hadoop_catalog_test.rs
  crates/runtime/src/catalogconnector/iceberg.rs
Labels: kind/bug

#6680 feat: Add Hadoop `metadata_path` parameter
  crates/data_components/src/iceberg/catalog/hadoop/catalog.rs
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/runtime/src/catalogconnector/mod.rs
  crates/runtime/src/dataconnector/iceberg.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/model/params/mod.rs
Labels: kind/enhancement

#6673 Amazon Bedrock, specifically Nova models
  .github/workflows/integration_llms.yml
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/bedrock/chat/mod.rs
  crates/llms/src/bedrock/chat/util.rs
  crates/llms/src/bedrock/embed/mod.rs
  crates/llms/src/bedrock/mod.rs
  crates/llms/tests/llms/create.rs
  crates/llms/tests/llms/mod.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/embed.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/model/params/bedrock.rs
  crates/runtime/src/model/params/mod.rs
  crates/runtime/src/model/util.rs
  crates/s3_vectors_metadata_filter/src/filter.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement, area/ai

#6693 Update bedrock keys for CI.
  .github/workflows/integration_llms.yml
  crates/llms/tests/llms/mod.rs
  crates/llms/tests/llms/snapshots/integration__llms__basic_bedrock_replied_appropriately.snap
  crates/llms/tests/llms/snapshots/integration__llms__tool_use_bedrock_finish_reason.snap
  crates/llms/tests/llms/snapshots/integration__llms__tool_use_bedrock_tool_choice.snap
  crates/llms/tests/llms/snapshots/integration__llms__tool_use_bedrock_valid_function_args.snap
  crates/llms/tests/llms/snapshots/integration__llms__usage_bedrock_has_completion_tokens.snap
  crates/llms/tests/llms/snapshots/integration__llms__usage_bedrock_has_prompt_tokens.snap
  crates/llms/tests/llms/snapshots/integration__llms__usage_bedrock_has_total_tokens.snap
  crates/llms/tests/llms/snapshots/integration__llms__usage_bedrock_total_tokens_gt_completion_tokens.snap
  crates/llms/tests/llms/snapshots/integration__llms__usage_bedrock_total_tokens_gt_prompt_tokens.snap
Labels: kind/bug, area/ci

#6699  Fix AWS Auth issue
  .github/workflows/pr.yml
  Cargo.lock
  crates/iceberg-aws-sdk/Cargo.toml
  crates/iceberg-aws-sdk/src/credential_provider.rs
  crates/iceberg-aws-sdk/src/lib.rs
  crates/object-store-aws-sdk/Cargo.toml
  crates/object-store-aws-sdk/src/credential_provider.rs
  crates/object-store-aws-sdk/src/lib.rs
  crates/runtime-object-store/src/registry/mod.rs
Labels: kind/bug

#6703 Use installation id to group connections
  crates/runtime/src/dataconnector/github/mod.rs
Labels: kind/bug

#6705 Move shared AWS crates used in bridges to workspace
  Cargo.toml
  crates/iceberg-aws-sdk/Cargo.toml
  crates/object-store-aws-sdk/Cargo.toml
Labels: kind/refactor

#6701 test: Add VectorScanTableProvider snapshot tests
  crates/runtime/src/embeddings/index/mod.rs
  crates/runtime/src/embeddings/index/query_table.rs
  crates/runtime/src/embeddings/index/scan_table.rs
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__query_table_basic.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__query_table_join_for_filter.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__query_table_join_for_filter_use_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__query_table_join_for_projection.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__query_table_join_for_projection_use_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__query_table_no_join_for_metadata_filter.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__query_table_no_join_for_metadata_projection.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_basic.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_filter.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_filter_use_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_projection.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_projection_use_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_filter.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_projection.snap
Labels: kind/enhancement

#6706 Fix testoperator append mode compilation error
  .github/workflows/pr.yml
  crates/test-framework/src/spicetest/append/mod.rs
  crates/test-framework/src/spicetest/append/sources/file.rs
  tools/testoperator/src/commands/append/mod.rs
Labels: kind/bug

#6708 docs: Add Hadoop cookbook to endgame template
  .github/ISSUE_TEMPLATE/end_game.md
  .github/workflows/pr.yml
Labels: kind/documentation

#6696 Improve Flight REPL error messages
  .github/actions/run-query/action.yml
  .github/actions/verify-dataset/action.yml
  crates/flightrepl/src/lib.rs
Labels: kind/enhancement

#6710 Fixes from search tests
  crates/runtime/src/search/candidate/vector.rs
  crates/runtime/src/search/request.rs
  crates/runtime/src/search/vector_search.rs
  crates/search/src/generation/post_apply.rs
Labels: kind/bug

#6729 Update changelog for 1.5.2
  docs/release_notes/v1.5.2.md
Labels: endgame

#6700 Cherry-pick new changes for v1.5.2
  .github/actions/run-query/action.yml
  .github/actions/verify-dataset/action.yml
  .github/workflows/pr.yml
  Cargo.lock
  Cargo.toml
  crates/data_components/src/graphql/builder.rs
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/graphql/mod.rs
  crates/flightrepl/src/lib.rs
  crates/iceberg-aws-sdk/Cargo.toml
  crates/iceberg-aws-sdk/src/credential_provider.rs
  crates/iceberg-aws-sdk/src/lib.rs
  crates/llms/Cargo.toml
  crates/llms/src/bedrock/chat/guardrail.rs
  crates/llms/src/bedrock/chat/mod.rs
  crates/object-store-aws-sdk/Cargo.toml
  crates/object-store-aws-sdk/src/credential_provider.rs
  crates/object-store-aws-sdk/src/lib.rs
  crates/runtime-object-store/src/registry/mod.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/glue.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/params/bedrock.rs
  crates/runtime/src/search/candidate/vector.rs
  crates/runtime/src/search/request.rs
  crates/runtime/src/search/vector_search.rs
  crates/search/src/generation/post_apply.rs
Labels: kind/enhancement, endgame

#6735 Update v1.5.2.md release date
  docs/release_notes/v1.5.2.md
Labels: kind/documentation

#6732 Update end game template - move glue catalog to catalogs section
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#6736 Updates to v1.5.2 release notes
  docs/release_notes/v1.5.2.md
Labels: kind/documentation

#6718 Combine the Iceberg and Object Store AWS SDK bridges into one crate
  Cargo.lock
  Cargo.toml
  crates/aws-sdk-credential-bridge/Cargo.toml
  crates/aws-sdk-credential-bridge/src/credential_provider.rs
  crates/aws-sdk-credential-bridge/src/lib.rs
  crates/data_components/Cargo.toml
  crates/data_components/src/delta_lake.rs
  crates/iceberg-aws-sdk/Cargo.toml
  crates/iceberg-aws-sdk/src/credential_provider.rs
  crates/iceberg-aws-sdk/src/lib.rs
  crates/object-store-aws-sdk/README.md
  crates/runtime-object-store/Cargo.toml
  crates/runtime-object-store/src/registry/mod.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/iceberg.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/spicepod/Cargo.toml
  crates/spicepod/src/lib.rs
Labels: kind/refactor

#6737 feat: Add Embedding and Search anonymous telemetry
  crates/runtime/src/embeddings/task.rs
  crates/runtime/src/embeddings/udtf.rs
  crates/runtime/src/search/full_text/udtf.rs
  crates/runtime/src/search/vector_search.rs
  crates/telemetry/src/lib.rs
Labels: kind/enhancement

#6740 Update QA analytics for release
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation, endgame

#6742 feat: Add more embedding traces, add MiniLM MTEB spicepod
  .github/workflows/testoperator_run_search.yml
  bin/spice/cmd/trace.go
  crates/llms/src/embeddings/candle/tei.rs
  crates/llms/src/openai/embed.rs
  crates/runtime/src/embeddings/execution_plan.rs
  test/spicepods/vector_search/mteb/quora/hf[all-minilm-l6-v2]-arrow.yaml
Labels: kind/enhancement

#6756 Set E2E Test CI models build to 90 minute timeout
  .github/workflows/e2e_test_ci_models.yml
Labels: kind/bug

#6762 Pin cargo-deny to 0.18.3
  .github/workflows/license_check.yml
Labels: area/ci

#6763 Use `.context` in Glue Catalog Provider
  crates/runtime/src/catalogconnector/glue/provider.rs
Labels: rust, kind/refactor

#6748 Use Spice specific errors instead of OpenAIError in embedding module
  crates/llms/src/bedrock/embed/cohere.rs
  crates/llms/src/bedrock/embed/mod.rs
  crates/llms/src/bedrock/embed/titan.rs
  crates/llms/src/databricks.rs
  crates/llms/src/embeddings/candle/tei.rs
  crates/llms/src/embeddings/mod.rs
  crates/llms/src/openai/embed.rs
  crates/runtime/src/embeddings/task.rs
Labels: kind/enhancement, area/ai

#6766 Move AWS SDK credential bridge integration test to the existing AWS SDK integration test run
  .github/workflows/integration_aws_sdk.yml
  crates/aws-sdk-credential-bridge/src/credential_provider.rs
  crates/aws-sdk-credential-bridge/tests/credential_provider.rs
Labels: kind/bug

#6769 Run the PR checks on the DEV runners
  .github/workflow_templates/README.md
  .github/workflow_templates/spiced_docker.yml
  .github/workflow_templates/spiced_docker_nightly.yml
  .github/workflows/build_and_release.yml
  .github/workflows/build_and_release_cuda.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_ci_models.yml
  .github/workflows/e2e_test_release_install.yml
  .github/workflows/e2e_test_spice_cli.yml
  .github/workflows/enforce-pulls-with-spice.yml
  .github/workflows/integration_llms.yml
  .github/workflows/license_check.yml
  .github/workflows/makefile_targets.yml
  .github/workflows/spiced_docker.yml
  .github/workflows/spiced_docker_nightly.yml
  .github/workflows/testoperator_run_data_consistency.yml
  .github/workflows/types_check.yml
Labels: kind/bug, area/ci

#6773 feat: Migrate bedrock rate limiter
  Cargo.lock
  crates/llms/src/bedrock/embed/mod.rs
  crates/llms/src/bedrock/mod.rs
  crates/llms/src/bedrock/rate_limit.rs
  crates/llms/src/openai/mod.rs
  crates/runtime-rate-control/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/model/util.rs
Labels: kind/enhancement

#6802 Respect default MAX_DECODING_MESSAGE_SIZE (100MB) in Flight API
  crates/runtime/src/flight/mod.rs
Labels: kind/bug

#6805 fix: Spice search CLI with FTS supports string or slice unmarshalling
  bin/spice/cmd/search.go
Labels: kind/bug

#6786 Add s3 vector test retrieving vectors
  crates/runtime/tests/models/s3_vectors.rs
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__basic_with_vectors.snap
Labels: kind/bug, area/ai, area/ci

#6829 Use latest commit in our fork of async-openai
  Cargo.lock
  Cargo.toml
Labels: kind/dependencies

#6832 Add streaming support
  crates/runtime/src/http/v1/responses.rs
Labels: kind/enhancement

#6836 fix: Include FTS search column if it is the PK
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__test_text_search_sql_where_rowid_is_search_column_basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__test_text_search_sql_where_rowid_is_search_column_composite_pk_basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__test_text_search_where_rowid_is_search_column_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__test_text_search_where_rowid_is_search_column_composite_pk_basic_response.snap
  crates/search/src/generation/text_search/index.rs
  crates/search/src/generation/text_search/udtf.rs
Labels: kind/bug

#6850 Improve management initialization message
  crates/runtime/src/management/mod.rs
Labels: kind/enhancement

#6853 Use latest version of OpenAI crate to resolve issues with deserialization
  Cargo.lock
  Cargo.toml
Labels: kind/bug, kind/dependencies

#6792 Pass embeddings calculated in `compute_index` to the acceleration
  crates/data_components/src/s3_vectors/vector_table.rs
  crates/runtime-datafusion-index/src/analyzer/index_table_scan.rs
  crates/runtime/src/embeddings/index/mod.rs
  crates/runtime/src/embeddings/index/s3.rs
  crates/runtime/src/embeddings/index/scan_table.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/s3_vectors.rs
  crates/runtime/tests/models/search.rs
  crates/search/src/generation/text_search/index.rs
Labels: kind/enhancement

#6788 Federated+Accelerated TPCH Benchmarks for MongoDB
  .github/workflows/testoperator_run_bench.yml
  test/spicepods/tpch/sf1/accelerated/mongodb-arrow.yaml
  test/spicepods/tpch/sf1/accelerated/mongodb-duckdb[file].yaml
  test/spicepods/tpch/sf1/federated/mongodb.yaml
  tools/testoperator/dispatch/tpch/sf1/accelerated/mongodb-arrow.yaml
  tools/testoperator/dispatch/tpch/sf1/accelerated/mongodb-duckdb[file].yaml
  tools/testoperator/dispatch/tpch/sf1/federated/mongodb.yaml
Labels: kind/enhancement

#6856 Kafka Data Connector: basic connector functionality
  bin/spiced/Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/cdc.rs
  crates/data_components/src/debezium_kafka.rs
  crates/data_components/src/kafka.rs
  crates/data_components/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/kafka.rs
  crates/runtime/src/dataconnector/mod.rs
Labels: kind/enhancement

#6868 Remove void acceleration engine + optional table behaviors
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/component/dataset/builder.rs
  crates/runtime/src/dataaccelerator/arrow.rs
  crates/runtime/src/dataaccelerator/behaviors/mod.rs
  crates/runtime/src/dataaccelerator/behaviors/wants_underlying_provider.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/mod.rs
  crates/runtime/src/dataaccelerator/partitioned_duckdb.rs
  crates/runtime/src/dataaccelerator/postgres.rs
  crates/runtime/src/dataaccelerator/spice_sys.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/dataaccelerator/void.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/internal_table.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement

#6854 Don't use metadata columns in `VectorScanTableProvider`
  crates/runtime/src/embeddings/index/scan_table.rs
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_filter_use_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_filter_use_metadata_multiple_pk.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_projection_use_metadata.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_join_for_projection_use_metadata_multiple_pk.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_embedding_no_join.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_filter.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_filter_multiple_pk.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_projection.snap
  crates/runtime/src/embeddings/index/snapshots/runtime__embeddings__index__tests__scan_table_no_join_for_metadata_projection_multiple_pk.snap
  crates/runtime/tests/models/s3_vectors.rs
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__data_v1.snap
Labels: kind/bug, area/ai

#6871 Add override parameter to force support for the Responses API
  crates/runtime/src/init/llm.rs
  crates/runtime/src/model/params/openai.rs
Labels: kind/enhancement

#6877 Fix newlines in errors added in recent PRs
  crates/runtime/src/dataconnector/kafka.rs
  crates/runtime/src/model/tool_use_responses.rs
Labels: kind/enhancement, rust

#6870 Kafka Data Connector: persist consumer between restarts
  crates/data_components/src/kafka.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataaccelerator/spice_sys.rs
  crates/runtime/src/dataaccelerator/spice_sys/kafka/duckdb.rs
  crates/runtime/src/dataaccelerator/spice_sys/kafka/mod.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/kafka.rs
Labels: kind/enhancement

#6775 Support multiple column primary keys for S3 vectors.
  crates/runtime/src/embeddings/index/mod.rs
  crates/runtime/src/embeddings/index/s3.rs
  crates/runtime/src/embeddings/index/s3/index.rs
  crates/runtime/src/embeddings/index/s3/mod.rs
  crates/runtime/src/embeddings/index/s3/write.rs
  crates/runtime/src/embeddings/udtf.rs
  crates/runtime/src/search/util.rs
  crates/runtime/src/search/vector_search.rs
  crates/search/src/generation/text_search/index.rs
Labels: kind/enhancement, area/ai

#6865 fix: Update search test case structure
  CONTRIBUTING.md
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_multiple_column_additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_multiple_column_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_multiple_column_with_where_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_sql_vector_search.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_with_where_response.snap
Labels: kind/refactor

#6879 Responses API support for Azure Open AI
  crates/runtime/src/init/llm.rs
  crates/runtime/src/model/responses.rs
Labels: kind/enhancement

#6852 Show correct limit for EXPLAIN plans in `S3VectorsQueryExec`
  crates/data_components/src/s3_vectors/query_provider.rs
  crates/runtime/tests/models/s3_vectors.rs
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__filters_pushdown.snap
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__filters_pushdown_explain.snap
Labels: kind/bug, area/ai

#6878 Enable embeddings for append streams
  crates/data_components/src/cdc.rs
  crates/data_components/src/debezium/arrow/changes.rs
  crates/runtime/src/embeddings/connector.rs
Labels: kind/bug

#6889 Update OpenAPI specification for `/v1/responses`
  Cargo.lock
  Cargo.toml
  crates/runtime/src/http/v1/responses.rs
Labels: kind/enhancement

#6896 Run E2E Test CI macOS build on bigger runners
  .github/workflows/e2e_test_ci.yml
Labels: kind/bug

#6884 In S3vector, do not pushdown on non-filterable columns
  crates/data_components/src/s3_vectors/query_provider.rs
  crates/data_components/src/s3_vectors/vector_table.rs
  crates/runtime/tests/models/s3_vectors.rs
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__non_filters_pushdown_explain.snap
Labels: kind/bug, area/ai

#6904 fix: Correctly project text search primary keys to underlying projection
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__text_search_sql_text_search_random.snap
  crates/search/src/generation/text_search/udtf.rs
Labels: kind/bug

#6897 Constraint violation check is improved to control behavior when violations occur within a batch
  Cargo.lock
  Cargo.toml
  crates/data_components/src/arrow/write.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/component/dataset/acceleration/on_conflict.rs
  crates/runtime/src/dataaccelerator/mod.rs
  crates/runtime/src/task_history/mod.rs
  crates/runtime/tests/acceleration/mod.rs
  crates/runtime/tests/acceleration/on_conflict_options.rs
  crates/runtime/tests/utils/mod.rs
  crates/spicepod/src/acceleration/mod.rs
Labels: kind/enhancement

#6907 Include GPT-5 into Text-To-SQL and Financebench benchmarks
  .github/workflows/ai_benchmark_nsql.yml
  .github/workflows/financebench.yml
  test/spicepods/financebench/embedding[openai].yaml
  test/spicepods/financebench/fts[openai].yaml
  test/spicepods/financebench/hybrid[openai].yaml
  test/spicepods/models/nsql_bench.yaml
Labels: kind/enhancement

#6912 Refactor how models supporting the Responses API are loaded
  crates/runtime/src/init/llm.rs
  crates/runtime/src/init/model.rs
  crates/runtime/src/model/params/azure.rs
  crates/runtime/src/model/params/openai.rs
Labels: kind/bug

#6915 Remove verbose tracing
  crates/search/src/generation/util.rs
Labels: kind/optimization, area/ai

#6919 remove `[...]` from queryset in spicepod path for CI
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
Labels: kind/bug, area/ci

#6920 Update snapshot for S3 vector search test
  crates/runtime/tests/models/snapshots/integration_models__models__s3_vectors__search__basic.snap
Labels: kind/bug, area/ci

#6914 Mark append-stream and CDC datasets as ready after first message
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
Labels: kind/bug

#6916 Add 1.6.0 release notes
  docs/release_notes/v1.5/v1.5.0-rc.1.md
  docs/release_notes/v1.5/v1.5.0-rc.2.md
  docs/release_notes/v1.5/v1.5.0-rc.3.md
  docs/release_notes/v1.5/v1.5.0.md
  docs/release_notes/v1.5/v1.5.1.md
  docs/release_notes/v1.5/v1.5.2.md
  docs/release_notes/v1.6.0.md
Labels: kind/optimization

#6934 [Debezium] Support for VariableScaleDecimal
  crates/data_components/src/debezium/arrow.rs
  crates/runtime/src/dataconnector/debezium.rs
Labels: kind/bug

#6942 Fix parameterised query planning in DataFusion
  Cargo.lock
  Cargo.toml
Labels: kind/bug, area/datafusion

#6941 Support Streaming with Tool Calls
  Cargo.lock
  Cargo.toml
  bin/spice/cmd/chat.go
  crates/runtime/src/model/tool_use_responses.rs
  crates/runtime/tests/models/openai.rs
Labels: kind/enhancement

#6948 Update acknowledgements and spicepod.schema.json
  .schema/spicepod.schema.json
  acknowledgements.md
  docs/release_notes/v1.6.0.md
Labels: kind/optimization

#6949 Add enabling the responses API
  docs/release_notes/v1.6.0.md
Labels: kind/documentation

#6950 Update helm chart for v1.6.0
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/optimization

#6951 Post-release housekeeping
  .github/workflows/testoperator_dispatch.yml
  Cargo.lock
  Cargo.toml
  SECURITY.md
  version.txt
Labels: kind/optimization

#6959 Add missing param in release notes
  docs/release_notes/v1.6.0.md
Labels: kind/documentation

#6903 Create comprehensive S3vectors test
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/tests/models/s3_vectors.rs
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__additional_columns_metadata_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_vector_search_sql_basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_vector_search_sql_basic_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_vector_search_sql_filters.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_vector_search_sql_filters_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_vector_search_sql_no_score.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_vector_search_sql_no_score_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_vector_search_sql_projection.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_vector_search_sql_projection_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_vector_search_sql_random.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_vector_search_sql_random_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__basic_with_where_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_vector_search_sql_composite_key.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_vector_search_sql_composite_key_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_vector_search_sql_filters.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_vector_search_sql_filters_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_vector_search_sql_single_column.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_vector_search_sql_single_column_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_composite_with_where_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_additional_columns_metadata_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_basic_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_filters.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_filters_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_filters_metadata.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_filters_metadata_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_projection.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_projection_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_projection_metadata.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_vector_search_sql_projection_metadata_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_with_where_metadata_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vector_metadata_with_where_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_basic.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_basic_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_filters.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_filters_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_no_score.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_no_score_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_projection.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_projection_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_random.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_random_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_vectors.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_vector_search_sql_vectors_explain.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__s3vectors_basic_with_where_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__with_where_metadata_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__with_where_response.snap
Labels: kind/enhancement, area/ai, area/ci

#6960 Add build step for new spiced images in end game template
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation, area/quality, area/ci

#6962 refactor: Use text search UDTF in v1/search
  crates/runtime/src/embeddings/udtf.rs
  crates/runtime/src/search/candidate.rs
  crates/runtime/src/search/candidate/text.rs
  crates/runtime/src/search/full_text/mod.rs
  crates/runtime/src/search/full_text/udtf.rs
  crates/runtime/src/search/util.rs
Labels: kind/refactor

#6969 Add `schema_inference_sample_count` param support for Kafka connector
  crates/runtime/src/dataconnector/kafka.rs
  crates/runtime/tests/kafka/bootstrap.rs
  crates/runtime/tests/kafka/mod.rs
  crates/runtime/tests/kafka/snapshots/integration__kafka__kafka_orders_data.snap
  crates/runtime/tests/kafka/snapshots/integration__kafka__kafka_orders_schema.snap
  crates/runtime/tests/kafka/snapshots/integration__kafka__kafka_schema_infer_test_data.snap
  crates/runtime/tests/kafka/snapshots/integration__kafka__kafka_schema_infer_test_schema.snap
  crates/runtime/tests/kafka/test_data/orders_schema_infer.json
Labels: kind/enhancement

#6971 Use model2vec for search integration tests for speed
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_multiple_column_additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_multiple_column_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_multiple_column_with_where_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_additional_columns_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_basic_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_sql_vector_search.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__hybrid_single_column_with_where_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__with_cache_bypass_post_cache_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__with_cache_bypass_pre_cache_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__with_cache_post_cache_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__with_cache_pre_cache_response.snap
Labels: kind/bug, area/ai, area/ci

#6966 feat: Add initial DuckDB regexp pushdown support
  crates/runtime/src/datafusion/dialect/duckdb.rs
  crates/runtime/src/datafusion/dialect/mod.rs
  crates/runtime/tests/duckdb/mod.rs
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_count_explain.snap
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_count_results.snap
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_like_is_case_sensitive_explain.snap
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_like_is_case_sensitive_results.snap
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_like_with_case_insensitive_flag_explain.snap
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_like_with_case_insensitive_flag_results.snap
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_replace_case_insensitive_explain.snap
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_replace_case_insensitive_results.snap
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_replace_explain.snap
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_replace_results.snap
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_results_match_explain.snap
  crates/runtime/tests/duckdb/snapshots/integration__duckdb__test_regexp_results_match_results.snap
  crates/runtime/tests/test_data/regions.csv
Labels: kind/enhancement

#6976 Add `flatten_json` param support for Kafka connector
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/kafka.rs
  crates/dataformat-json/src/unnest.rs
  crates/runtime/src/dataconnector/kafka.rs
  crates/runtime/tests/kafka/mod.rs
  crates/runtime/tests/kafka/snapshots/integration__kafka__kafka_flattent_json_test_data.snap
  crates/runtime/tests/kafka/snapshots/integration__kafka__kafka_flattent_json_test_schema.snap
  crates/runtime/tests/kafka/test_data/orders_nested.json
Labels: kind/enhancement

#6983 Fix mongo tests: ignore container_registry() when building image name
  crates/runtime/tests/mongo/common.rs
Labels: kind/bug

#6981 Implement support for s3 tables for glue DataConnector.
  crates/runtime/src/catalogconnector/glue/provider.rs
  crates/runtime/src/dataconnector/glue.rs
Labels: kind/enhancement

#6979 Add integration tests for models endpoint
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/models_http_endpoint.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__models_http_endpoint__models_response_no_status_no_metadata.snap
  crates/runtime/tests/models/snapshots/integration_models__models__models_http_endpoint__models_response_with_metadata.snap
  crates/runtime/tests/models/snapshots/integration_models__models__models_http_endpoint__models_response_with_status.snap
Labels: kind/bug
