Repository spiceai/spiceai, pull requests merged in 2025-04, with the labels that each got.

#5205 Add verification for `schema_source_path`
  crates/runtime/src/dataconnector/listing/connector.rs
Labels: kind/bug

#5208 Add verification for `schema_source_path` (#5205)
  crates/runtime/src/dataconnector/listing/connector.rs
Labels: kind/enhancement

#5182 Add v1.1.0 release notes
  docs/ROADMAP.md
  docs/release_notes/v1.0/v1.0.0.md
  docs/release_notes/v1.0/v1.0.1.md
  docs/release_notes/v1.0/v1.0.2.md
  docs/release_notes/v1.0/v1.0.3.md
  docs/release_notes/v1.0/v1.0.4.md
  docs/release_notes/v1.0/v1.0.5.md
  docs/release_notes/v1.0/v1.0.6.md
  docs/release_notes/v1.0/v1.0.7.md
  docs/release_notes/v1.1.0.md
Labels: kind/documentation

#5204 Improvement to Milestone Endgame template
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation, kind/enhancement

#5207 feat: Add testoperator search workflow
  .github/workflows/testoperator_run_search.yml
Labels: kind/enhancement

#5211 Update QA analytics for v1.1.0
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#5214 Add support for DuckDB `preserve_insertion_order` parameter
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator/duckdb.rs
Labels: kind/enhancement

#5223 Update Helm Chart and SECURITY.md to v1.1.0
  SECURITY.md
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/documentation, endgame, kind/task

#5225 Update Cargo.lock to v1.1.1-unstable
  .schema/openapi.json
  Cargo.lock
  Cargo.toml
Labels: kind/documentation

#5221 Add tests for `verify_schema_source_path` in `ListingTableConnector`
  crates/runtime/src/dataconnector/listing/connector.rs
Labels: kind/enhancement

#5227 Reduce noise from debug logging
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/datasets_health_monitor.rs
Labels: kind/enhancement

#5222 Improve `openai_test_chat_messages` integration test reliability
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_ai_completion_input.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_2_document_similarity_tasks.snap
Labels: kind/bug

#5232 Verify the checkpoints existence before shutting down runtime in integration tests directly querying checkpoint
  crates/runtime/tests/acceleration/checkpoint_duckdb.rs
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
  crates/runtime/tests/acceleration/checkpoint_sqlite.rs
  crates/runtime/tests/acceleration/mod.rs
  crates/runtime/tests/acceleration/single_instance_duckdb.rs
Labels: kind/bug, area/quality

#5241 Fix CORS support for json content-type api
  crates/runtime/src/http/routes.rs
  crates/runtime/tests/cors/mod.rs
Labels: kind/bug

#5238 fix: Use `pulls-with-spice-action` and switch to `spiceai-macos` runners
  .github/workflows/enforce-labels.yml
  .github/workflows/enforce-pulls-with-spice.yml
Labels: kind/bug

#5244 Use v1.0.3 pulls with spice action
  .github/workflows/enforce-pulls-with-spice.yml
Labels: kind/enhancement, area/ci

#5229 Bump timeout for several integration test runtime load_components & readiness check
  crates/runtime/tests/abfs/mod.rs
  crates/runtime/tests/acceleration/checkpoint_duckdb.rs
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
  crates/runtime/tests/acceleration/checkpoint_sqlite.rs
  crates/runtime/tests/acceleration/file_watcher.rs
  crates/runtime/tests/acceleration/on_conflict.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/acceleration/single_instance_duckdb.rs
  crates/runtime/tests/catalog/mod.rs
  crates/runtime/tests/databricks_delta/mod.rs
  crates/runtime/tests/databricks_delta_catalog/mod.rs
  crates/runtime/tests/databricks_spark/mod.rs
  crates/runtime/tests/databricks_spark_catalog/mod.rs
  crates/runtime/tests/delta_lake/mod.rs
  crates/runtime/tests/duckdb/mod.rs
  crates/runtime/tests/file/mod.rs
  crates/runtime/tests/github/mod.rs
  crates/runtime/tests/graphql/mod.rs
  crates/runtime/tests/iceberg/catalog/mod.rs
  crates/runtime/tests/iceberg/connector/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/mssql/mod.rs
  crates/runtime/tests/mysql/federation.rs
  crates/runtime/tests/mysql/mod.rs
  crates/runtime/tests/odbc/mod.rs
  crates/runtime/tests/ready_state/mod.rs
  crates/runtime/tests/refresh_retry/mysql.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/rehydration/mod.rs
  crates/runtime/tests/s3/mod.rs
  crates/runtime/tests/snowflake/mod.rs
  crates/runtime/tests/spark/mod.rs
  crates/runtime/tests/spiceai/mod.rs
  crates/runtime/tests/sqlite/mod.rs
  crates/runtime/tests/utils/mod.rs
Labels: kind/bug, area/quality

#5248 Validate port is available before binding port for docker container in integration tests
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
  crates/runtime/tests/postgres/common.rs
  crates/runtime/tests/postgres/mod.rs
Labels: kind/bug

#5259 Update datafusion-table-providers to fix the schema for PostgreSQL materialized views
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5240 Verify flight server is ready for flight integration tests
  crates/runtime/tests/flight/do_put.rs
Labels: kind/bug

#5258 fix: Publish to MinIO inside of matrix on build_and_release
  .github/workflows/build_and_release.yml
Labels: kind/bug

#5264 Use model as a judge scorer for Financebench
  test/financebench/README.md
  test/financebench/spicepod_gpt-4o.yaml
Labels: kind/enhancement

#5276 Fix FinanceBench llm scorer secret name
  test/financebench/spicepod_gpt-4o.yaml
Labels: kind/bug

#5265 Implements support for `runtime.results_cache.cache_key_type`
  Cargo.toml
  crates/cache/src/lib.rs
  crates/cache/src/lru_cache.rs
  crates/cache/src/utils.rs
  crates/runtime/benches/bench_search/setup.rs
  crates/runtime/benches/setup/mod.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/cache.rs
  crates/runtime/src/request/cache_control.rs
  crates/runtime/src/request/context.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#5268 Imporve embedding column parsing performance test
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/bug, area/quality

#5293 Add default descriptions to built-in MCP tools
  crates/runtime/src/tools/builtin/catalog.rs
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_ai_completion_input.snap
  crates/runtime/tests/models/snapshots/integration_models__models__tools__mcp__mcp_spiced_list.snap
Labels: kind/bug, area/ai, area/mcp

#5295 fix: Vector search with cased columns
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_casing_chunking_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_casing_no_chunking_response.snap
Labels: kind/bug

#5296 Run delta kernel scan in a blocking Tokio thread.
  crates/data_components/src/delta_lake.rs
Labels: kind/bug

#5297 Expose the `mysql_pool_min` and `mysql_pool_max` connection pool parameters
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataconnector/mysql.rs
Labels: kind/enhancement

#5298 Merge trunk to `release/1.1`
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataconnector/mysql.rs
Labels: kind/enhancement

#5270 use patched pdf-extract
  Cargo.lock
  crates/document_parse/Cargo.toml
Labels: kind/enhancement

#5305 Add v1.1.1 release notes
  docs/release_notes/v1.1.1.md
Labels: kind/documentation, endgame, kind/task

#5313 Add note on spice.js v2.0.1 to v1.1.1 release notes
  docs/release_notes/v1.1.1.md
Labels: kind/documentation

#5316 Merge `trunk` into `release/1.1` - Release Notes
  docs/release_notes/v1.1.1.md
Labels: kind/documentation

#5312 docs: Add throughput test parameters to endgame
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#5317 Update Helm + Prepare for next release
  Cargo.lock
  Cargo.toml
  SECURITY.md
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
  docs/ROADMAP.md
  version.txt
Labels: kind/documentation

#5308 add integration test for reading encrypted PDFs from S3
  crates/runtime/tests/s3/mod.rs
Labels: kind/enhancement

#5306 Stop `load_components` during runtime shutdown
  bin/spiced/src/lib.rs
  bin/spiced/src/main.rs
  crates/runtime/benches/bench_search/setup.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/cancellable_task.rs
  crates/runtime/src/lib.rs
  crates/runtime/tests/abfs/mod.rs
  crates/runtime/tests/acceleration/checkpoint_duckdb.rs
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
  crates/runtime/tests/acceleration/checkpoint_sqlite.rs
  crates/runtime/tests/acceleration/file_watcher.rs
  crates/runtime/tests/acceleration/on_conflict.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/acceleration/single_instance_duckdb.rs
  crates/runtime/tests/catalog/mod.rs
  crates/runtime/tests/databricks_delta/mod.rs
  crates/runtime/tests/databricks_delta_catalog/mod.rs
  crates/runtime/tests/databricks_spark/mod.rs
  crates/runtime/tests/databricks_spark_catalog/mod.rs
  crates/runtime/tests/delta_lake/mod.rs
  crates/runtime/tests/duckdb/mod.rs
  crates/runtime/tests/file/mod.rs
  crates/runtime/tests/github/mod.rs
  crates/runtime/tests/graphql/mod.rs
  crates/runtime/tests/iceberg/catalog/mod.rs
  crates/runtime/tests/iceberg/connector/mod.rs
  crates/runtime/tests/models/embedding.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/tools.rs
  crates/runtime/tests/mssql/mod.rs
  crates/runtime/tests/mysql/federation.rs
  crates/runtime/tests/mysql/mod.rs
  crates/runtime/tests/odbc/mod.rs
  crates/runtime/tests/ready_state/mod.rs
  crates/runtime/tests/refresh_retry/mysql.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/rehydration/mod.rs
  crates/runtime/tests/results_cache/mod.rs
  crates/runtime/tests/s3/mod.rs
  crates/runtime/tests/snowflake/mod.rs
  crates/runtime/tests/spark/mod.rs
  crates/runtime/tests/spiceai/mod.rs
  crates/runtime/tests/sqlite/mod.rs
Labels: kind/bug

#5331 feat: Implement record batch data validation
  Cargo.lock
  crates/test-framework/Cargo.toml
  crates/test-framework/src/queries/validation/mod.rs
  crates/test-framework/src/spicetest/datasets/worker.rs
Labels: kind/enhancement

#5320 Update QA analytics for v1.1.1
  docs/release_notes/qa_analytics.csv
Labels: kind/optimization

#5333 Add basic support for `application/vnd.spiceai.sql.v1+json` format
  crates/runtime/src/http/v1/eval.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/http/v1/query.rs
  crates/runtime/src/http/v1/snapshots/runtime__http__v1__tests__vnd_json_v1_with_sql.snap
  crates/runtime/src/http/v1/snapshots/runtime__http__v1__tests__vnd_json_v1_without_sql.snap
Labels: kind/enhancement

#5339 Enforce pulls with Spice v1.0.4
  .github/workflows/enforce-pulls-with-spice.yml
Labels: kind/enhancement, area/build

#5342 feat: Allow validating testoperator in benchmark workflow
  .github/workflows/testoperator_run_bench.yml
  crates/test-framework/src/queries/validation/mod.rs
  tools/testoperator/src/args/dataset.rs
Labels: kind/enhancement

#5343 Upgrade `delta_kernel` to 0.9
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/data_components/src/delta_lake.rs
Labels: kind/enhancement

#5344 deps: Update odbc-api
  Cargo.lock
  Cargo.toml
Labels: kind/dependencies

#5348 Fix schema inference for Snowflake tables with large number of columns
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5349 feat: Update testoperator dispatch for validation, version metric
  .github/workflows/testoperator_dispatch.yml
  crates/test-framework/src/metrics/mod.rs
  crates/test-framework/src/spiced/mod.rs
  crates/test-framework/src/spicetest/datasets/mod.rs
  crates/test-framework/src/spicetest/http/consistency.rs
  crates/test-framework/src/spicetest/http/overhead.rs
  crates/test-framework/src/spicetest/vector_search/mod.rs
  tools/testoperator/dispatch/tpch/accelerated/file_arrow.yaml
  tools/testoperator/dispatch/tpch/accelerated/file_duckdb_file.yaml
  tools/testoperator/dispatch/tpch/accelerated/file_duckdb_memory.yaml
  tools/testoperator/dispatch/tpch/duckdb.yaml
  tools/testoperator/dispatch/tpch/file.yaml
  tools/testoperator/src/args/dispatch.rs
  tools/testoperator/src/commands/dispatch/mod.rs
Labels: kind/enhancement

#5350 Backport - Fix schema inference for Snowflake tables with large number of columns #5348
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5352 fix: validate_results not validate
  tools/testoperator/dispatch/tpch/accelerated/file_arrow.yaml
  tools/testoperator/dispatch/tpch/accelerated/file_duckdb_file.yaml
  tools/testoperator/dispatch/tpch/accelerated/file_duckdb_memory.yaml
  tools/testoperator/dispatch/tpch/duckdb.yaml
  tools/testoperator/dispatch/tpch/file.yaml
  tools/testoperator/src/args/dispatch.rs
Labels: kind/bug

#5355 Revert lopdf patch
  Cargo.lock
  crates/document_parse/Cargo.toml
  crates/runtime/tests/s3/mod.rs
Labels: kind/bug

#5284 Stablize the test `verify_similarity_search_chat_completion`
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_2_document_similarity_tasks.snap
Labels: kind/bug, area/quality

#5362 Convert DataFusion filters to Delta Kernel predicates
  crates/data_components/src/delta_lake.rs
Labels: kind/enhancement

#5367 Turn off `delta_kernel::log_segment` logging and refactor log filtering
  bin/spiced/src/tracing.rs
Labels: kind/bug

#5365 Extend `application/vnd.spiceai.sql.v1+json` with `schema` and `row_count` fields
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/snapshots/runtime__http__v1__tests__vnd_json_v1_with_sql.snap
  crates/runtime/src/http/v1/snapshots/runtime__http__v1__tests__vnd_json_v1_without_sql.snap
Labels: kind/enhancement

#5380 Extend `application/vnd.spiceai.sql.v1+json` with `schema` and `row_count` fields (#5365)
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/snapshots/runtime__http__v1__tests__vnd_json_v1_with_sql.snap
  crates/runtime/src/http/v1/snapshots/runtime__http__v1__tests__vnd_json_v1_without_sql.snap
Labels: kind/enhancement

#5375 Upgrade to DuckDB 1.2.2
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#5376 Update Readme - fix broken and outdated links
  README.md
Labels: kind/documentation

#5382 Make separate `vnd.spiceai.sql.v1+json` and `vnd.spiceai.nsql.v1+json` MIME types
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/http/v1/query.rs
Labels: kind/bug

#5366 v1.1.2 release notes
  docs/release_notes/v1.1.2.md
Labels: kind/documentation

#5386 fix: Remove IMAP oauth
  crates/runtime/src/dataconnector/imap.rs
Labels: kind/bug

#5389 Bump Helm chart to 1.1.2
  .github/ISSUE_TEMPLATE/end_game.md
  SECURITY.md
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/documentation

#5388 Include `vnd.spiceai.sql/nsql.v1+json` response examples (openapi docs)
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/http/v1/query.rs
Labels: kind/enhancement

#5391 docs: Update endgame template with SpiceQA, update qa analytics
  .github/ISSUE_TEMPLATE/end_game.md
  .github/workflows/e2e_test_release_install_ai.yml
  docs/release_notes/qa_analytics.csv
Labels: kind/bug, kind/documentation

#5358 Make graceful shutdown timeout configurable
  crates/app/src/lib.rs
  crates/runtime/src/lib.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/shutdown/mod.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#5401 docs: Update release criteria with note on max columns
  docs/criteria/accelerators/beta.md
  docs/criteria/connectors/beta.md
Labels: kind/documentation

#5395 FinanceBench: update scorer instructions and switch scoring model to `gpt-4.1`
  test/financebench/spicepod_gpt-4o.yaml
  tools/testoperator/src/commands/evals/mod.rs
Labels: kind/enhancement

#5397 feat: Write OTel metrics for testoperator
  Cargo.lock
  crates/flight_client/Cargo.toml
  crates/flight_client/src/lib.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/telemetry/Cargo.toml
  crates/telemetry/src/anonymous.rs
  crates/telemetry/src/exporter.rs
  crates/telemetry/src/lib.rs
  crates/telemetry/src/meter.rs
  crates/telemetry/src/reader.rs
  crates/test-framework/Cargo.toml
  crates/test-framework/src/lib.rs
  crates/test-framework/src/metrics/mod.rs
  crates/test-framework/src/spiced/mod.rs
  crates/test-framework/src/spicepod_utils/mod.rs
  crates/test-framework/src/telemetry/mod.rs
  tools/testoperator/src/args/mod.rs
  tools/testoperator/src/commands/bench/mod.rs
  tools/testoperator/src/commands/http/consistency.rs
  tools/testoperator/src/commands/http/overhead.rs
  tools/testoperator/src/commands/mod.rs
  tools/testoperator/src/commands/vector_search/mod.rs
  tools/testoperator/src/main.rs
  tools/testoperator/src/metrics.rs
Labels: kind/enhancement

#5403 Update nsql openapi title
  crates/runtime/src/http/v1/nsql.rs
Labels: kind/documentation

#5393 Track `ai_inferences_count` with used tools flag. Extensible runtime request context.
  crates/runtime/src/http/routes.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/metrics/telemetry/mod.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/model/model_context.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/request/context.rs
  crates/telemetry/src/lib.rs
Labels: kind/enhancement

#5409 Track used_tools in ai_inferences_with_spice_count as number
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/model/model_context.rs
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement

#5407 Allow `flightsql` and `spiceai` connectors to override flight max message size
  Cargo.lock
  Cargo.toml
  crates/cache/Cargo.toml
  crates/flight_client/src/lib.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/spicepod/Cargo.toml
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#5405 Retry model graded scorer once on successful, empty response
  crates/runtime/src/model/eval/scorer/modelgraded.rs
Labels: kind/bug

#5421 fix: Update qa_analytics.csv
  docs/release_notes/qa_analytics.csv
Labels: kind/bug

#5417 Remove the filter for the `list_datasets` tool in the AI inferences metric count.
  crates/runtime/src/model/tool_use.rs
Labels: kind/enhancement

#5413 fix: Testoperator uses an exact API key for benchmark metric submission
  crates/flight_client/src/lib.rs
  crates/telemetry/src/exporter.rs
  crates/test-framework/src/metrics/mod.rs
  crates/test-framework/src/telemetry/mod.rs
  tools/testoperator/src/commands/bench/mod.rs
  tools/testoperator/src/metrics.rs
Labels: kind/bug

#5404 Upgrade mistral.rs
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/chat/mistral.rs
Labels: kind/dependencies, area/ai, kind/task

#5426 Include all FinanceBench documents in benchmark tests
  test/financebench/spicepod_gpt-4o.yaml
Labels: kind/enhancement

#5427 Handle second Ctrl-C to force runtime termination
  Cargo.lock
  bin/spiced/src/lib.rs
  crates/runtime/src/lib.rs
  crates/util/Cargo.toml
  crates/util/src/lib.rs
Labels: kind/enhancement

#5429 Add optional `--temperature` parameter for `spice chat` CLI command
  bin/spice/cmd/chat.go
Labels: kind/enhancement, kind/task

#5430 Remove `with_runtime_status` from the `RuntimeBuilder`
  crates/runtime/src/builder.rs
Labels: kind/bug

#5433 Fix spice chat error handling
  bin/spice/cmd/chat.go
  bin/spice/pkg/api/util.go
Labels: kind/enhancement, kind/task

#5431 Add more test models to FinanceBench benchmark
  .github/workflows/financebench.yml
  test/financebench/spicepod_openai.yaml
Labels: kind/enhancement

#5434 Support 'from: databricks:model_name'
  crates/llms/src/chat/mod.rs
  crates/runtime/src/model/chat.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement, area/ai

#5442 Upgrade Pulls with Spice to v1.0.6 and add concurrency control
  .github/workflows/enforce-pulls-with-spice.yml
Labels: kind/enhancement

#5443 Fix Postgres JSON type and add Dictionary type support for DuckDB
  Cargo.lock
  Cargo.toml
Labels: kind/bug, kind/enhancement

#5447 Test spice chat in e2e_test_spice_cli
  .github/workflows/e2e_test_spice_cli.yml
  test/cli/spice_chat_error.exp
  test/cli/spicepod_openai.yml
Labels: kind/enhancement, kind/task

#5444 Allow for one-shot chat request using `spice chat <message>`
  bin/spice/cmd/chat.go
Labels: kind/enhancement, kind/task

#5449 Enable parallel data sampling for NSQL
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/tools/builtin/sample/distinct.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/snapshots/integration_models__models__nsql__openai_with_sample_data_enabled_tasks.snap
Labels: kind/bug

#5462 Upgrade Go from v1.23.4 to v1.24.2
  .github/workflows/build_and_release.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_ci_models.yml
  .github/workflows/e2e_test_spice_cli.yml
  .github/workflows/license_check.yml
  .github/workflows/makefile_targets.yml
  .github/workflows/pr.yml
  .github/workflows/types_check.yml
  go.mod
Labels: kind/dependencies

#5465 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation

#5464 Enable captured outputs by default when spiced is started by the CLI (spice run)
  bin/spice/cmd/add.go
  bin/spice/cmd/catalogs.go
  bin/spice/cmd/chat.go
  bin/spice/cmd/datasets.go
  bin/spice/cmd/install.go
  bin/spice/cmd/models.go
  bin/spice/cmd/nsql.go
  bin/spice/cmd/pods.go
  bin/spice/cmd/refresh.go
  bin/spice/cmd/run.go
  bin/spice/cmd/search.go
  bin/spice/cmd/sql.go
  bin/spice/cmd/status.go
  bin/spice/cmd/trace.go
  bin/spice/cmd/upgrade.go
  bin/spice/cmd/version.go
  bin/spice/pkg/context/context.go
  bin/spice/pkg/runtime/runtime.go
Labels: kind/enhancement, area/cli

#5420 Parameterized queries via Flight SQL API
  Cargo.lock
  Cargo.toml
  crates/arrow_tools/src/record_batch.rs
  crates/arrow_tools/src/schema.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/param_utils.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/builder.rs
  crates/runtime/src/datafusion/query/cache.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/do_get.rs
  crates/runtime/src/flight/do_put.rs
  crates/runtime/src/flight/flightsql/prepared_statement_query.rs
  crates/runtime/src/flight/flightsql/statement_query.rs
  crates/runtime/src/flight/util.rs
Labels: kind/enhancement

#5466 fix: Update benchmarks readme badge
  README.md
Labels: kind/bug

#5475 Auth not required for parameterized queries via Flight SQL
  crates/runtime/src/flight/do_put.rs
Labels: kind/enhancement

#5463 Add support for `?` placeholder syntax in parameterized queries
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/flightsql/prepared_statement_query.rs
  crates/runtime/src/flight/flightsql/statement_query.rs
  crates/runtime/src/flight/get_flight_info.rs
  crates/runtime/src/flight/get_schema.rs
Labels: kind/enhancement

#5423 Enable task name override for non-static span names; add dynamic MCP tool task names
  crates/runtime/src/task_history/otel_exporter.rs
  crates/runtime/src/tools/mcp/catalog.rs
  crates/runtime/src/tools/mcp/tool.rs
Labels: kind/refactor

#5481 Allow parameter queries with no parameters
  crates/runtime/src/flight/flightsql/prepared_statement_query.rs
Labels: kind/enhancement

#5483 Support unparsing UNION for distinct results
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5485 Pin the version of the Rust toolchain
  rust-toolchain.toml
Labels: kind/enhancement, rust

#5484 Add parameterized query support to the HTTP API
  crates/runtime/src/http/v1/eval.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/nsql.rs
  crates/runtime/src/http/v1/query.rs
Labels: kind/enhancement

#5451 E2E test for spice chat <message> behavior
  .github/workflows/e2e_test_spice_cli.yml
  test/cli/spice_chat_error.exp
  test/cli/spice_chat_message.exp
  test/cli/spicepod_openai.yml
Labels: kind/enhancement, kind/task

#5478 Renable and fix huggingface models integration tests
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_1_response_choices.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_completion.snap
Labels: kind/bug

#5489 feat: Record memory usage as a metric
  crates/test-framework/src/process/mod.rs
  tools/testoperator/src/commands/bench/mod.rs
  tools/testoperator/src/metrics.rs
Labels: kind/enhancement

#5502 Fix ILIKE filters support
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5510 fix: working directory for duckdb e2e test spicepods
  .github/workflows/e2e_test_ci.yml
Labels: kind/bug

#5487 Cache logical plans of SQL statements
  Cargo.lock
  Cargo.toml
  crates/cache/Cargo.toml
  crates/cache/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/query/cache.rs
Labels: kind/enhancement

#5517 Fix `content-type: application/json` in NSQL testing
  crates/runtime/tests/models/mod.rs
Labels: kind/bug, area/ai

#5504 Validate postgres results in testoperator dispatch
  tools/testoperator/dispatch/tpch/sf1/federated/postgres.yaml
Labels: kind/optimization

#5520 Only generate the cache key once in the query path
  crates/cache/src/lib.rs
  crates/cache/src/lru_cache.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/cache.rs
Labels: kind/enhancement, kind/performance

#5518 Fix results cache by SQL with prepared statements
  crates/cache/src/lib.rs
  crates/cache/src/lru_cache.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/datafusion/query/cache.rs
Labels: kind/bug

#5509 Add initial support for views acceleration
  crates/runtime/benches/bench_search/datasets.rs
  crates/runtime/benches/bench_search/setup.rs
  crates/runtime/benches/vector_search.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/accelerated_table/refresh_task/streaming_append.rs
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/component/view.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/init/view.rs
  crates/runtime/src/status.rs
  crates/runtime/src/tracing_util.rs
  crates/runtime/src/view.rs
  crates/runtime/tests/acceleration/checkpoint_duckdb.rs
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
  crates/runtime/tests/acceleration/checkpoint_sqlite.rs
  crates/runtime/tests/acceleration/file_watcher.rs
  crates/runtime/tests/acceleration/mod.rs
  crates/runtime/tests/acceleration/on_conflict.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/acceleration/single_instance_duckdb.rs
  crates/runtime/tests/delta_lake/mod.rs
  crates/runtime/tests/iceberg/connector/mod.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/mysql/common.rs
  crates/runtime/tests/odbc/mod.rs
  crates/runtime/tests/ready_state/mod.rs
  crates/runtime/tests/refresh_retry/mysql.rs
  crates/runtime/tests/refresh_sql/mod.rs
  crates/runtime/tests/rehydration/mod.rs
  crates/runtime/tests/sqlite/mod.rs
  crates/spicepod/src/acceleration/mod.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/view.rs
  crates/spicepod/src/lib.rs
Labels: kind/enhancement

#5529 Fix nightly arm build - change tag `-default` to `-models`
  .github/workflow_templates/spiced_docker_nightly.yml
  .github/workflows/spiced_docker_nightly.yml
Labels: kind/bug

#5526 Apply Spice advanced acceleration logic and params support to accelerated views
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/view.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/arrow.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/postgres.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/init/view.rs
Labels: kind/enhancement

#5533 Enable DatasetCheckpoint logic for accelerated views
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/spice_sys.rs
  crates/runtime/src/dataaccelerator/spice_sys/dataset_checkpoint/mod.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/federated_table/mod.rs
  crates/runtime/src/init/dataset.rs
Labels: kind/enhancement

#5535 Fix public '.model' name for router workers
  Cargo.lock
  crates/workers/Cargo.toml
  crates/workers/src/router.rs
Labels: kind/bug, area/ai

#5536 feat: Add Runtime memory limit parameter
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion/builder.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement

#5537 For fallback worker, check first item in `chat/completion` stream.
  crates/workers/src/router.rs
Labels: kind/refactor, area/ai

#5540 Move rate limit check to after parameterized query binding
  crates/runtime/src/flight/do_put.rs
  crates/runtime/src/flight/middleware.rs
Labels: kind/enhancement

#5547 Accelerate views: `refresh_on_startup`, `ready_state`, `jitter` params support
  crates/runtime/src/component/view.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/lib.rs
  crates/spicepod/src/component/view.rs
Labels: kind/enhancement

#5550 Add integration test for accelerated views
  crates/runtime/tests/integration.rs
  crates/runtime/tests/view/mod.rs
  crates/runtime/tests/view/snapshots/integration__view__duckdb_persisted_records.snap
  crates/runtime/tests/view/snapshots/integration__view__duckdb_query_explain.snap
  crates/runtime/tests/view/snapshots/integration__view__duckdb_query_result.snap
  crates/runtime/tests/view/snapshots/integration__view__duckdb_spice_sys_dataset_checkpoint.snap
Labels: kind/enhancement

#5554 Don't install make or expect on spiceai-macos runners
  .github/actions/setup-make/action.yml
  .github/workflows/e2e_test_ci_models.yml
  .github/workflows/e2e_test_release_install.yml
  .github/workflows/e2e_test_release_install_ai.yml
Labels: kind/bug, area/ci

#5474 `event_stream` crate for emitting events from tracing::Span; used in v1/chat/completions streaming.
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  bin/spiced/src/tracing.rs
  crates/event_stream/Cargo.toml
  crates/event_stream/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/http/v1/chat.rs
Labels: kind/enhancement, area/ai

#5559 Fix typo in method `wait_until_dependent_tables_are_ready`
  crates/runtime/src/datafusion.rs
Labels: kind/bug

#5557 Run test operator every day and current and previous commits
  .github/workflows/testoperator_dispatch.yml
Labels: kind/enhancement, area/ci

#5541 Add aws_allow_http parameter for delta lake connector
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/delta_lake.rs
Labels: kind/optimization

#5563 feat: Add branch name to metric dimensions in testoperator
  tools/testoperator/src/commands/bench/mod.rs
Labels: kind/enhancement

#5567 fix: Split scheduled dispatch into a separate job
  .github/workflows/testoperator_dispatch.yml
Labels: kind/bug

#5568 fix: Use outputs.SPICED_COMMIT
  .github/workflows/testoperator_dispatch.yml
Labels: kind/bug

#5571 fix: Testoperator dispatch
  .github/actions/setup-spiced/action.yml
  .github/workflows/testoperator_dispatch.yml
Labels: kind/bug

#5572 fix: Testoperator dispatch
  .github/actions/setup-spiced/action.yml
  .github/workflows/testoperator_dispatch.yml
Labels: kind/bug

#5579 Use FETCH_HEAD instead of ${{ inputs.ref }} to list commits in setup_spiced
  .github/actions/setup-spiced/action.yml
Labels: kind/bug

#5582 Add additional test scenarios for benchmarks
  .github/workflows/testoperator_dispatch.yml
  test/spicepods/tpch/sf1/accelerated/databricks[delta_lake]-duckdb[file].yaml
  test/spicepods/tpch/sf1/accelerated/iceberg-duckdb[file].yaml
  tools/testoperator/dispatch/tpch/sf1/accelerated/databricks[delta_lake]-duckdb[file].yaml
  tools/testoperator/dispatch/tpch/sf1/accelerated/iceberg-duckdb[file].yaml
  tools/testoperator/dispatch/tpch/sf1/accelerated/mysql-duckdb[file].yaml
Labels: kind/enhancement

#5599 Fix Snowflake data connector rows ordering
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5476 Better user message for `spice chat --model`
  bin/spice/cmd/chat.go
  test/cli/spice_chat_error.exp
Labels: kind/bug

#5604 Add changelog script to generate changelog between two refs, with potentially cherry-picked changes.
  scripts/generate_changelog.sh
Labels: kind/enhancement

#5602 feat: testoperator parameterized queries
  .github/actions/setup-testoperator-data/action.yml
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
  Cargo.lock
  crates/flight_client/src/lib.rs
  crates/test-framework/Cargo.toml
  crates/test-framework/src/flight/mod.rs
  crates/test-framework/src/queries/mod.rs
  crates/test-framework/src/queries/parameterized/mod.rs
  crates/test-framework/src/queries/tpch/parameterized/q1.sql
  crates/test-framework/src/queries/tpch/parameterized/q10.sql
  crates/test-framework/src/queries/tpch/parameterized/q11.sql
  crates/test-framework/src/queries/tpch/parameterized/q12.sql
  crates/test-framework/src/queries/tpch/parameterized/q13.sql
  crates/test-framework/src/queries/tpch/parameterized/q14.sql
  crates/test-framework/src/queries/tpch/parameterized/q16.sql
  crates/test-framework/src/queries/tpch/parameterized/q17.sql
  crates/test-framework/src/queries/tpch/parameterized/q18.sql
  crates/test-framework/src/queries/tpch/parameterized/q19.sql
  crates/test-framework/src/queries/tpch/parameterized/q2.sql
  crates/test-framework/src/queries/tpch/parameterized/q20.sql
  crates/test-framework/src/queries/tpch/parameterized/q21.sql
  crates/test-framework/src/queries/tpch/parameterized/q22.sql
  crates/test-framework/src/queries/tpch/parameterized/q3.sql
  crates/test-framework/src/queries/tpch/parameterized/q4.sql
  crates/test-framework/src/queries/tpch/parameterized/q5.sql
  crates/test-framework/src/queries/tpch/parameterized/q6.sql
  crates/test-framework/src/queries/tpch/parameterized/q7.sql
  crates/test-framework/src/queries/tpch/parameterized/q8.sql
  crates/test-framework/src/queries/tpch/parameterized/q9.sql
  crates/test-framework/src/queries/validation/mod.rs
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q10_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q11_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q12_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q13_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q14_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q16_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q18_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q19_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q1_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q21_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q8_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__duckdb-federated_tpch[parameterized]_q9_explain.snap
  crates/test-framework/src/spicetest/datasets/worker.rs
  tools/testoperator/dispatch/tpch/sf1/federated/duckdb-tpch[parameterized].yaml
  tools/testoperator/src/args/dataset.rs
Labels: kind/enhancement

#5607 Downgrade DuckDB to 1.1.3
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#5598 Update Snowflake bench queries and add snapshots
  crates/test-framework/src/queries/tpch/snowflake/q10.sql
  crates/test-framework/src/queries/tpch/snowflake/q13.sql
  crates/test-framework/src/queries/tpch/snowflake/q16.sql
  crates/test-framework/src/queries/tpch/snowflake/q2.sql
  crates/test-framework/src/queries/tpch/snowflake/q21.sql
  crates/test-framework/src/queries/tpch/snowflake/q3.sql
  crates/test-framework/src/queries/tpch/snowflake/q8.sql
  crates/test-framework/src/queries/tpch/snowflake/q9.sql
  crates/test-framework/src/queries/validation/mod.rs
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q10_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q11_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q12_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q13_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q14_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q16_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q17_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q18_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q19_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q1_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q20_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q21_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q22_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q2_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q3_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q4_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q5_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q6_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q7_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q8_explain.snap
  crates/test-framework/src/snapshot/snapshots/explain/test_framework__snapshot__snowflake-federated_tpch_q9_explain.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q1.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q10.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q11.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q12.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q13.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q14.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q16.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q17.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q18.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q19.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q2.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q20.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q21.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q22.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q3.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q4.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q5.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q6.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q7.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q8.snap
  crates/test-framework/src/snapshot/snapshots/results/test_framework__spicetest__datasets__worker__snowflake-federated_tpch_q9.snap
  test/spicepods/tpch/sf1/federated/snowflake.yaml
Labels: kind/optimization

#5596 v1.2.0 release notes
  docs/release_notes/v1.1/v1.1.0.md
  docs/release_notes/v1.1/v1.1.1.md
  docs/release_notes/v1.1/v1.1.2.md
  docs/release_notes/v1.2.0.md
Labels: kind/documentation

#5613 Update query_overrides for all testoperator workflows
  .github/workflows/testoperator_run_data_consistency.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
Labels: kind/bug

#5616 Update 1.2.0 release notes
  docs/release_notes/v1.2.0.md
Labels: kind/documentation

#5621 Update helm chart to v1.2.0
  SECURITY.md
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#5625 spacing update
  docs/release_notes/v1.2.0.md
Labels: kind/documentation

#5609 Upgrade dependabot dependencies
  Cargo.lock
  crates/data_components/Cargo.toml
  crates/llms/Cargo.toml
  crates/runtime/Cargo.toml
  crates/telemetry/Cargo.toml
  crates/test-framework/Cargo.toml
  crates/util/Cargo.toml
Labels: kind/dependencies

#5622 Bump to v1.2.1-unstable
  Cargo.lock
  Cargo.toml
  docs/ROADMAP.md
  version.txt
Labels: kind/enhancement

#5630 fix: Specify metric type as a dimension for testoperator
  tools/testoperator/src/commands/bench/mod.rs
Labels: kind/refactor, area/observability

#5631 fix: Add option to run dispatch schedule
  .github/ISSUE_TEMPLATE/end_game.md
  .github/workflows/testoperator_dispatch.yml
Labels: kind/bug

#5626 update datafusion/spiceai-45
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement, area/datafusion

#5640 Add QA analytics for 1.2.0
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#5632 fix: Use SPICED_COMMIT for spiced_commit_sha
  .github/workflows/testoperator_run_bench.yml
  tools/testoperator/src/commands/bench/mod.rs
Labels: kind/bug
