Repository spiceai/spiceai, pull requests merged in 2025-06, with the labels that each got.

#6053 Enhance Arrow Flight DoPut operation tracing
  crates/runtime/src/flight/do_put.rs
Labels: kind/optimization

#6045 Upgrade to delta_kernel 0.11
  Cargo.lock
  Cargo.toml
  crates/data_components/src/delta_lake.rs
Labels: kind/dependencies

#6041 Implement full text search using Tantivy
  Cargo.lock
  crates/search/Cargo.toml
  crates/search/src/aggregation.rs
  crates/search/src/generation.rs
  crates/search/src/generation/snapshots/search__generation__text_search__tests__basic_index.snap
  crates/search/src/generation/text_search.rs
Labels: kind/enhancement, area/ai

#6050 refactor: Replace refresh oneshot with notify
  bin/spice/cmd/trace.go
  crates/runtime/src/accelerated_table/mod.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/accelerated_table/refresh_task/streaming_append.rs
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/http/v1/datasets.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/internal_table.rs
  crates/runtime/src/scheduling/mod.rs
  crates/scheduler/src/lib.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/refactor

#6068 Enable Upsert OnConflictBehavior for runtime.task_history table
  crates/runtime/src/component/dataset/acceleration.rs
  crates/runtime/src/task_history/mod.rs
Labels: kind/optimization

#6069 feat: Add a workers integration test
  crates/runtime/src/status.rs
  crates/runtime/tests/integration_models.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/workers/mod.rs
  crates/runtime/tests/workers/snapshots/integration_models__workers__worker_with_cron.snap
Labels: kind/bug, kind/enhancement

#6084 Handle Snowflake Timestamp NTZ with seconds precision
  crates/db_connection_pool/src/dbconnection/snowflakeconn.rs
Labels: kind/enhancement

#6082 Revert: fix: Use HTTPS ubuntu sources
  .github/actions/update-http-sources/action.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_ci_models.yml
  .github/workflows/features.yml
  .github/workflows/integration.yml
  .github/workflows/makefile_targets.yml
  .github/workflows/pr.yml
  .github/workflows/testoperator_dispatch.yml
  .github/workflows/testoperator_run_bench.yml
Labels: kind/bug

#6092 Add release notes for v1.3.2
  docs/release_notes/v1.3.2.md
Labels: kind/documentation

#6089 Add initial support for Spice Cloud Platform management
  crates/app/src/lib.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/management/mod.rs
  crates/spicepod/src/component.rs
  crates/spicepod/src/component/management.rs
  crates/spicepod/src/lib.rs
  crates/spicepod/src/spec.rs
  crates/test-framework/src/spicepod_utils/mod.rs
  tools/evalconverter/src/main.rs
Labels: kind/enhancement

#6049 Run spiceai cloud connector TPC tests using spice dev apps
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
  crates/flight_client/Cargo.toml
  test/spicepods/tpcds/sf1/federated/spicecloud.yaml
  test/spicepods/tpch/sf1/federated/spicecloud.yaml
Labels: kind/optimization, kind/task

#6093 feat: Add SQL worker action
  crates/runtime/src/init/scheduler.rs
  crates/runtime/src/init/worker.rs
  crates/runtime/src/scheduling/dataset/mod.rs
  crates/runtime/src/scheduling/mod.rs
  crates/runtime/src/scheduling/worker/mod.rs
  crates/runtime/src/worker.rs
  crates/runtime/tests/workers/mod.rs
  crates/runtime/tests/workers/snapshots/integration_models__workers__sql_worker_with_cron.snap
  crates/spicepod/src/component/worker.rs
Labels: kind/enhancement

#6054 Glue catalog connector for hive style parquet
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/catalogconnector/databricks.rs
  crates/runtime/src/catalogconnector/glue.rs
  crates/runtime/src/catalogconnector/glue/provider.rs
  crates/runtime/src/catalogconnector/glue/state.rs
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/runtime/src/catalogconnector/mod.rs
  crates/runtime/src/catalogconnector/spice_cloud.rs
  crates/runtime/src/catalogconnector/unity_catalog.rs
  crates/runtime/src/dataconnector/dynamodb.rs
  crates/runtime/src/dataconnector/mod.rs
  crates/runtime/src/dataconnector/parameters.rs
  crates/runtime/src/dataconnector/parameters/aws.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/init/catalog.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/management/mod.rs
  crates/runtime/src/parameters.rs
  crates/runtime/tests/ready_state/mod.rs
  crates/spice_cloud/src/lib.rs
Labels: kind/enhancement

#6105 Improve Flight Client DoPut / Publish error handling
  crates/flight_client/src/lib.rs
Labels: kind/bug

#6096 Define `PostApplyCandidateGeneration` to handle all filters & projections.
  crates/runtime/src/search/candidate/vector.rs
  crates/search/src/generation.rs
  crates/search/src/generation/post_apply.rs
  crates/search/src/generation/snapshots/search__generation__post_apply__tests__filter.snap
  crates/search/src/generation/snapshots/search__generation__post_apply__tests__projection.snap
  crates/search/src/generation/text_search.rs
Labels: kind/enhancement, area/ai

#6108 feat: Connect search caching for HTTP and tools
  crates/app/src/lib.rs
  crates/cache/src/lib.rs
  crates/cache/src/lru_cache.rs
  crates/cache/src/result/query.rs
  crates/cache/src/result/search.rs
  crates/cache/src/simple_cache.rs
  crates/runtime/src/datafusion/query/cache.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/search/request.rs
  crates/runtime/src/search/vector_search.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__post_cache_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__pre_cache_response.snap
Labels: kind/enhancement

#6110 Improve the ListingTableURL logging
  crates/runtime/src/dataconnector/listing/connector.rs
Labels: kind/bug

#6104 Avoid partial writes by FlightTableWriter
  crates/data_components/src/flight/write.rs
  crates/flight_client/src/lib.rs
Labels: kind/bug

#6111 fix: Update the TPCDS postgres acceleration indexes
  test/spicepods/tpcds/sf1/accelerated/file[parquet]-postgres.yaml
Labels: kind/bug

#6103 Make Glue Catalog refreshable
  crates/runtime/src/catalogconnector/glue.rs
  crates/runtime/src/catalogconnector/glue/provider.rs
  crates/runtime/src/catalogconnector/glue/state.rs
Labels: kind/enhancement

#6125 Refactor Glue catalog to use a new Glue data connector
  crates/runtime/src/catalogconnector/glue.rs
  crates/runtime/src/catalogconnector/glue/provider.rs
  crates/runtime/src/catalogconnector/glue/state.rs
  crates/runtime/src/dataconnector/dynamodb.rs
  crates/runtime/src/dataconnector/glue.rs
  crates/runtime/src/dataconnector/mod.rs
  crates/runtime/src/dataconnector/parameters/aws.rs
Labels: kind/enhancement

#6123 Emit retry error on flight transient connection failure
  crates/data_components/src/flight.rs
  crates/flight_client/src/lib.rs
Labels: kind/bug

#6130 update MCP crate
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/http/routes.rs
  crates/runtime/src/tools/mcp/catalog.rs
  crates/tools/Cargo.toml
Labels: kind/bug, area/ai

#6131 feat: Add search cache status header, respect cache control
  crates/cache/src/result/mod.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/search/vector_search.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/snapshots/integration_models__models__search__post_cache_response.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__pre_cache_response.snap
Labels: kind/enhancement

#6133 fix: Fix specifying individual caching blocks in spicepod
  crates/app/src/lib.rs
  crates/runtime/src/builder.rs
  crates/runtime/src/init/caching.rs
  crates/runtime/src/request/cache_control.rs
  crates/spicepod/src/component/caching.rs
  crates/spicepod/src/lib.rs
  crates/spicepod/tests/basic_spicepod.yaml
  crates/spicepod/tests/spicepod_with_caching.yaml
  crates/spicepod/tests/spicepod_with_only_search_results.yaml
  crates/spicepod/tests/spicepod_with_only_sql_results.yaml
  crates/spicepod/tests/spicepod_with_results_cache.yaml
Labels: kind/bug

#6138 Add CSV support to Glue data connector
  crates/runtime/src/catalogconnector/glue.rs
  crates/runtime/src/catalogconnector/glue/state.rs
  crates/runtime/src/dataconnector/glue.rs
  crates/runtime/src/dataconnector/listing/connector.rs
Labels: kind/enhancement, area/data-connectors

#6145 Update refresh to not block Caching cleanup
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task/changes.rs
  crates/runtime/src/accelerated_table/refresh_task/streaming_append.rs
Labels: kind/bug

#6147 Enable Spice Cloud Control Plane connect (management) for FinanceBench
  test/financebench/README.md
  test/financebench/spicepod_openai.yaml
Labels: kind/enhancement

#6141 Add full text search to vector search bench
  .github/workflows/benchmarks_search.yml
  crates/runtime/benches/bench_search/datasets.rs
  crates/runtime/benches/bench_search/setup.rs
  crates/runtime/benches/vector_search.rs
Labels: kind/enhancement, area/ai

#6150 Add integration test for Spice Cloud Platform management
  crates/runtime/tests/integration.rs
  crates/runtime/tests/integration_models.rs
  crates/runtime/tests/management/mod.rs
  crates/runtime/tests/management/snapshots/integration__management__periodic_export.snap
  crates/runtime/tests/management/snapshots/integration__management__shutdown_export.snap
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/openai.rs
  crates/runtime/tests/models/search.rs
  crates/runtime/tests/models/tools.rs
  crates/runtime/tests/utils/mod.rs
  crates/runtime/tests/workers/mod.rs
Labels: kind/optimization

#6152 fix: Prevent registering cron schedule with change stream accelerations
  crates/runtime/src/init/scheduler.rs
Labels: kind/bug

#6155 fix: Cache search results with no-cache directive
  crates/runtime/src/search/vector_search.rs
Labels: kind/bug

#6171 Update version to 1.4.0-rc.1 (1.4.x release branch)
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/optimization

#6174 Fix: Glue S3 location for directories and Iceberg credentials
  crates/runtime/src/dataconnector/glue.rs
Labels: kind/bug

#6158 fix: Add --cache-control flag for search CLI
  bin/spice/cmd/search.go
Labels: kind/bug

#6177 fix: Apply results cache deprecation correctly
  crates/runtime/src/builder.rs
Labels: kind/bug

#6181 Fix Linux CUDA build (use candle-core 0.8.4 and cudarc v0.12)
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#6192 fix: return empty stream when no results for Databricks SQL Warehouse
  crates/data_components/src/databricks/sql_warehouse.rs
Labels: kind/bug

#6191 Use arrow pretty print util instead of init dataframe / logical plan in `display_records`
  Cargo.lock
  crates/flightrepl/Cargo.toml
  crates/flightrepl/src/lib.rs
  crates/flightrepl/src/snapshots/flightrepl__tests__multiple_batches_exactly_500_rows.snap
  crates/flightrepl/src/snapshots/flightrepl__tests__multiple_batches_over_500_rows.snap
  crates/flightrepl/src/snapshots/flightrepl__tests__multiple_batches_under_500_rows.snap
  crates/flightrepl/src/snapshots/flightrepl__tests__single_batch_over_500_rows.snap
  crates/flightrepl/src/snapshots/flightrepl__tests__single_empty_batch.snap
Labels: kind/bug

#6196 chore: Update dependencies
  .github/workflows/e2e_test_release_install_ai.yml
  Cargo.lock
  Cargo.toml
  crates/llms/Cargo.toml
  crates/llms/src/chat/nsql/snapshots/llms__chat__nsql__tests__sql_gen_structured.snap
  crates/package/Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_ai_completion_input.snap
  crates/runtime/tests/shutdown/mod.rs
  crates/spicepod/Cargo.toml
  go.mod
  go.sum
  tools/spicepodschema/Cargo.toml
Labels: kind/dependencies

#6176 v1.4.0-rc.1 release notes
  docs/ROADMAP.md
  docs/release_notes/v1.3/v1.3.0.md
  docs/release_notes/v1.3/v1.3.1.md
  docs/release_notes/v1.3/v1.3.2.md
  docs/release_notes/v1.4.0-rc.1.md
Labels: kind/documentation

#6195 Move model-grading evals to testoperator
  .github/workflows/ai_benchmark_nsql.yml
  .github/workflows/financebench.yml
  test/financebench/README.md
  test/model_grading/README.md
  test/model_grading/structured_output.jsonl
  test/nsql_bench/README.md
  test/nsql_bench/spicepod_claude-3-5-sonnet.yaml
  test/nsql_bench/spicepod_gpt-4o-mini.yaml
  test/nsql_bench/spicepod_gpt-4o.yaml
  test/nsql_bench/spicepod_grok2.yaml
  test/nsql_bench/spicepod_llama3-3b.yaml
  test/nsql_bench/spicepod_o1.yaml
  test/nsql_bench/spicepod_o3_mini.yaml
  test/spicepods/financebench/embedding[openai].yaml
  test/spicepods/financebench/fts[openai].yaml
  test/spicepods/financebench/hybrid[openai].yaml
  test/spicepods/models/nsql_bench.yaml
  test/spicepods/models/structured_output.yaml
  tools/testoperator/src/commands/evals/mod.rs
Labels: kind/refactor, area/ai

#6208 Update openapi.json
  .github/workflows/integration.yml
  .schema/openapi.json
Labels: kind/enhancement, area/ai

#6219 Fix load status metric description
  crates/runtime/src/metrics/catalogs/mod.rs
  crates/runtime/src/metrics/datasets/mod.rs
  crates/runtime/src/metrics/embeddings/mod.rs
  crates/runtime/src/metrics/llms/mod.rs
  crates/runtime/src/metrics/models/mod.rs
  crates/runtime/src/metrics/tools/mod.rs
  crates/runtime/src/metrics/views/mod.rs
  crates/runtime/src/status.rs
Labels: kind/bug

#6215 Don't use base table for full text search post apply vector search
  crates/runtime/src/search/full_text/table.rs
  crates/runtime/src/search/util.rs
Labels: kind/bug, area/ai

#6217 Fix `content-type` header in `v1/sql` response
  crates/runtime/src/http/v1/mod.rs
Labels: kind/bug, area/datafusion

#6209 Add v1.4.0-rc.1 release into qa_analytics.csv
  docs/release_notes/qa_analytics.csv
Labels: kind/optimization

#6227 task: Add MySQL indexes
  test/tpc-bench/mysql-bench/indexes.sql
Labels: kind/bug

#6222 Paginate results from FullTextSearch
  crates/search/src/generation.rs
  crates/search/src/generation/post_apply.rs
  crates/search/src/generation/text_search.rs
Labels: kind/enhancement, area/ai

#6228 fix: use the query error message when queries fail
  crates/data_components/src/databricks/sql_warehouse.rs
Labels: kind/bug

#6252 cache table providers in Glue catalog
  crates/runtime/src/catalogconnector/glue.rs
  crates/runtime/src/catalogconnector/glue/provider.rs
  crates/runtime/src/catalogconnector/glue/state.rs
Labels: kind/bug

#6236 fix: Lower SF100 memory limit
  test/spicepods/tpch/sf100/accelerated/indexes/mysql-duckdb[file]-indexes.yaml
  test/spicepods/tpch/sf100/accelerated/mysql-duckdb[file].yaml
Labels: kind/bug

#6255 fix: databricks sql_warehouse schema contains duplicate fields
  crates/data_components/src/databricks/sql_warehouse.rs
Labels: kind/bug

#6248 Add glue integration test using hive and iceberg tables
  .github/workflows/integration.yml
  crates/runtime/tests/glue/mod.rs
  crates/runtime/tests/integration.rs
Labels: kind/enhancement

#6258 Read all databases and tables in Glue catalog when include is missing
  crates/runtime/src/catalogconnector/glue/provider.rs
Labels: kind/bug

#6179 add Glue catalog to README.md
  README.md
  docs/criteria/catalogs/alpha.md
  docs/criteria/connectors/alpha.md
Labels: kind/documentation

#6200 Add bucket UDF for partitioning
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/src/datafusion/udf.rs
  crates/runtime/src/datafusion/udf/bucket.rs
  crates/runtime/src/datafusion/udf/snapshots/runtime__datafusion__udf__bucket__tests__bucket_array.snap
  crates/runtime/src/datafusion/udf/snapshots/runtime__datafusion__udf__bucket__tests__bucket_scalar.snap
  crates/runtime/src/datafusion/udf/snapshots/runtime__datafusion__udf__bucket__tests__decimal_input.snap
  crates/runtime/src/datafusion/udf/snapshots/runtime__datafusion__udf__bucket__tests__empty_array.snap
  crates/runtime/src/datafusion/udf/snapshots/runtime__datafusion__udf__bucket__tests__null_array_input.snap
  crates/runtime/src/datafusion/udf/snapshots/runtime__datafusion__udf__bucket__tests__null_input.snap
Labels: kind/enhancement

#6232 New tool `parsley`
  Cargo.lock
  Cargo.toml
  crates/document_parse/src/docx.rs
  crates/document_parse/src/lib.rs
  crates/document_parse/src/pdf.rs
  crates/llms/Cargo.toml
  crates/llms/src/chunking/mod.rs
  crates/spicepod/src/component/model.rs
  tools/parsley/Cargo.toml
  tools/parsley/src/main.rs
  tools/parsley/src/output.rs
Labels: kind/optimization, area/ai

#6261 Upgrade dependabot dependencies
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  crates/flightrepl/Cargo.toml
Labels: kind/dependencies

#6263 Upgrade delta_kernel to 0.12.1
  Cargo.lock
  Cargo.toml
  crates/data_components/src/delta_lake.rs
Labels: kind/dependencies

#6260 docs: Add 1.4.0 stable release notes
  docs/release_notes/v1.4.0.md
Labels: kind/documentation

#6265 fix: Throughput test dispatching
  .github/workflows/testoperator_run_throughput.yml
Labels: kind/bug

#6259 Extend Flight CommandGetTables with source native data type info
  crates/runtime/src/flight/flightsql/get_tables.rs
Labels: kind/enhancement

#6269 cherry: Release notes for 1.4
  docs/release_notes/v1.4.0.md
Labels: kind/documentation

#6270 fix: Docker image build with profile
  .github/workflow_templates/spiced_docker.yml
  .github/workflows/spiced_docker.yml
Labels: kind/bug

#6277 Update QA analytics for v1.4.0
  docs/release_notes/qa_analytics.csv
Labels: kind/documentation

#6278 Add truncate UDF
  crates/runtime/src/datafusion/udf.rs
  crates/runtime/src/datafusion/udf/truncate.rs
Labels: kind/enhancement

#6284 Update qa_analytics.csv for 1.4.0
  docs/release_notes/qa_analytics.csv
Labels: kind/optimization

#6285 Default xAI to 'grok-3'
  crates/llms/src/xai.rs
  crates/llms/tests/llms/mod.rs
Labels: kind/bug, area/ai

#6254 For Spice.ai connectors, do not default to dev SCP for dev builds
  crates/runtime/src/dataconnector/spiceai.rs
Labels: area/quality, kind/refactor

#6288 fix: Deny extra caching parameters
  crates/cache/src/lib.rs
  crates/runtime/src/datafusion/query/cache.rs
  crates/runtime/src/init/caching.rs
  crates/spicepod/src/component/caching.rs
Labels: kind/bug

#6286 Create a table provider from full text search index + query
  crates/runtime/src/search/full_text/table.rs
  crates/search/src/generation/post_apply.rs
  crates/search/src/generation/text_search/exec.rs
  crates/search/src/generation/text_search/mod.rs
  crates/search/src/generation/text_search/snapshots/search__generation__text_search__tests__and_conjunction.snap
  crates/search/src/generation/text_search/snapshots/search__generation__text_search__tests__basic_index.snap
  crates/search/src/generation/text_search/snapshots/search__generation__text_search__tests__operators.snap
  crates/search/src/generation/text_search/snapshots/search__generation__text_search__tests__quotes_conjunction.snap
  crates/search/src/generation/text_search/snapshots/search__generation__text_search__tests__special_characters.snap
  crates/search/src/generation/text_search/table.rs
Labels: kind/enhancement, area/ai

#6297 Update Flight CommandGetTables to Return Native DataFusion SQL Data Types
  crates/runtime/src/flight/flightsql/get_tables.rs
Labels: kind/bug

#6300 Adds a synchronous `get_table` function on the DataFusion context
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/datafusion/schema.rs
  crates/runtime/src/http/v1/eval.rs
Labels: kind/enhancement

#6308 Support reserved word column names in DynamoDB
  crates/data_components/src/dynamodb/provider.rs
Labels: kind/bug

#6311 Add integration test for DynamoDB Data Connector
  .github/workflows/integration.yml
  crates/runtime/tests/dynamodb/mod.rs
  crates/runtime/tests/dynamodb/snapshots/integration__dynamodb__query_result.snap
  crates/runtime/tests/dynamodb/snapshots/integration__dynamodb__schema.snap
  crates/runtime/tests/integration.rs
Labels: kind/optimization

#6313 Add better error messages for cases when a port is already in use
  crates/runtime/src/flight/mod.rs
  crates/runtime/src/opentelemetry.rs
Labels: kind/bug

#6309 Disallow datasets with protected names
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/mod.rs
  crates/runtime/src/dataconnector/mssql.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/spicepod/src/keywords.rs
  crates/spicepod/src/lib.rs
Labels: kind/bug

#6318 Encode ScalarValues for use in filenames
  Cargo.lock
  crates/runtime-table-partition/Cargo.toml
  crates/runtime-table-partition/src/creator.rs
  crates/runtime-table-partition/src/creator/filename.rs
Labels: kind/enhancement

#6199 Standardize model parameter handling & prioritize `<model-prefix>_<param>` for model default overrides
  crates/llms/src/chat/mod.rs
  crates/llms/src/perplexity/mod.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/model/params/anthropic.rs
  crates/runtime/src/model/params/azure.rs
  crates/runtime/src/model/params/databricks.rs
  crates/runtime/src/model/params/file.rs
  crates/runtime/src/model/params/huggingface.rs
  crates/runtime/src/model/params/mod.rs
  crates/runtime/src/model/params/openai.rs
  crates/runtime/src/model/params/perplexity.rs
  crates/runtime/src/model/params/xai.rs
  crates/runtime/src/model/wrapper/mod.rs
  crates/runtime/src/parameters.rs
  crates/spicepod/src/component/model.rs
Labels: kind/bug, kind/optimization

#6321 Add initial support for Oracle Data Connector
  .github/workflows/features.yml
  Cargo.lock
  Cargo.toml
  bin/spiced/Cargo.toml
  crates/arrow_sql_gen/Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/lib.rs
  crates/data_components/src/mssql/connection_manager.rs
  crates/data_components/src/oracle/connection.rs
  crates/data_components/src/oracle/convert.rs
  crates/data_components/src/oracle/execution_plan.rs
  crates/data_components/src/oracle/mod.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector/mod.rs
  crates/runtime/src/dataconnector/oracle.rs
Labels: kind/enhancement

#6323 Oracle connector: Support all major Oracle data types
  crates/data_components/src/oracle/connection.rs
  crates/data_components/src/oracle/convert.rs
  crates/data_components/src/oracle/mod.rs
Labels: kind/enhancement

#6341 feat: Add support for cron-based view refresh
  crates/runtime/src/datafusion/mod.rs
  crates/runtime/src/init/dataset.rs
  crates/runtime/src/init/pods_watcher.rs
  crates/runtime/src/init/scheduler.rs
  crates/runtime/src/init/view.rs
  crates/runtime/src/scheduling/mod.rs
  crates/runtime/src/scheduling/view/mod.rs
  crates/runtime/tests/acceleration/cron.rs
  crates/runtime/tests/acceleration/snapshots/integration__acceleration__cron__test_cron_view.snap
  crates/runtime/tests/acceleration/snapshots/integration__acceleration__cron__test_cron_view_after.snap
  crates/runtime/tests/acceleration/spicepods/test_cron_view.yaml
  crates/scheduler/src/channel/cron.rs
Labels: kind/enhancement
