Repository spiceai/spiceai, pull requests merged in 2025-01, with the labels that each got.

#4098 First-class TSV for file data connector
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/listing/connector.rs
Labels: kind/enhancement, area/data-connectors

#4010 Allow Flight DoPut only for write api-keys
  crates/runtime-auth/src/api_key/mod.rs
  crates/runtime-auth/src/layer/flight.rs
  crates/runtime-auth/src/layer/grpc.rs
  crates/runtime-auth/src/layer/http.rs
  crates/runtime-auth/src/traits.rs
  crates/runtime/src/auth/mod.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/do_put.rs
  crates/runtime/src/flight/middleware.rs
  crates/runtime/src/request/context.rs
  crates/runtime/tests/endpoint_auth/flight.rs
  crates/runtime/tests/endpoint_auth/http.rs
  crates/runtime/tests/flight/do_put.rs
  crates/spicepod/src/component/runtime.rs
Labels: kind/enhancement, breaking change

#4099 Only create tables `eval.runs` and `eval.results` when an eval is defined
  crates/runtime/src/lib.rs
Labels: kind/refactor, area/ai

#4111 feat: add postgres clickbench accelerator, release postgres accelerator
  .github/workflows/benchmarks.yml
  README.md
  crates/runtime/benches/setup/mod.rs
  docs/criteria/accelerators/rc.md
Labels: kind/enhancement

#4097 Add spice binaries with metal to releases; detect metal device in `spice install/upgrade`.
  .github/workflows/build_and_release.yml
  bin/spice/pkg/github/asset.go
  bin/spice/pkg/github/runtime_release.go
  bin/spiced/src/main.rs
Labels: kind/enhancement, area/ai

#4112 docs: Clarify connector release criteria
  docs/criteria/connectors/rc.md
  docs/criteria/connectors/stable.md
Labels: kind/documentation

#4115 Update datafusion-federation to fix LIMIT with OFFSET handling in logical plan rewrite
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#4113 Support Grok AI.
  crates/llms/src/lib.rs
  crates/llms/src/xai.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/model/chat.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement, area/ai

#4119 Fix `spice chat` usage bar.
  bin/spice/cmd/chat.go
Labels: kind/bug

#4120 feat: Add the file connector as an appendable benchmark connector
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_duckdb/mod.rs
  crates/runtime/benches/bench_object_store/file.rs
  crates/runtime/benches/bench_object_store/mod.rs
  crates/runtime/benches/setup/mod.rs
Labels: kind/enhancement

#4118 Add `spice eval` command
  bin/spice/cmd/eval.go
Labels: kind/enhancement

#4129 Support multi-level table nesting for Dremio
  Cargo.lock
  Cargo.toml
  crates/data_components/src/flight.rs
  crates/data_components/src/flight/federation.rs
  crates/runtime/src/dataconnector/dremio.rs
Labels: kind/enhancement

#4141 feat: Run append TPCDS benchmarks in workflow (Arrow, DuckDB)
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_duckdb/mod.rs
  crates/runtime/benches/bench_object_store/file.rs
Labels: kind/enhancement

#4134 Setup spice.ai clickbench
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench_spicecloud/mod.rs
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q1.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q10.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q11.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q12.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q13.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q14.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q15.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q16.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q17.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q18.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q19.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q2.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q20.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q21.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q24.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q25.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q26.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q27.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q28.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q3.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q30.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q32.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q33.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q34.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q35.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q37.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q38.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q39.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q4.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q43.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q5.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q6.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q7.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q8.snap
  crates/runtime/benches/snapshots/bench__spice.ai_clickbench_q9.snap
Labels: area/data-connectors, kind/optimization, area/ci

#4142 Data is streamed when reading from the GitHub connector (GraphQL tables)
  crates/data_components/src/graphql/client.rs
  crates/data_components/src/graphql/mod.rs
  crates/data_components/src/graphql/provider.rs
  crates/runtime/src/dataconnector/github/commits.rs
  crates/runtime/src/dataconnector/github/issues.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/github/pull_requests.rs
  crates/runtime/tests/snapshots/integration__test_github_commits_auto.snap
  crates/runtime/tests/snapshots/integration__test_github_stargazers_auto.snap
  crates/runtime/tests/snapshots/integration__test_graphql_pagination_select_all.snap
  crates/runtime/tests/snapshots/integration__test_graphql_pagination_select_limit_1_id_4.snap
  crates/runtime/tests/snapshots/integration__test_graphql_select_all.snap
  crates/runtime/tests/snapshots/integration__test_graphql_select_posts_title.snap
Labels: kind/enhancement, area/data-connectors

#4143 Mark the GitHub Data Connector as Stable
  README.md
  docs/criteria/connectors/stable.md
Labels: kind/enhancement

#4140 Add target dataset schema validation for Flight DoPut
  crates/runtime/src/datafusion.rs
  crates/runtime/src/flight/do_put.rs
Labels: kind/enhancement

#4145 Fix table quoting for Databricks Spark connector
  .github/workflows/integration.yml
  crates/data_components/src/spark_connect/federation.rs
  crates/runtime/tests/databricks_spark/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/snapshots/integration__databricks_spark__databricks_spark_connect_select.snap
  crates/runtime/tests/snapshots/integration__databricks_spark_connect_test_select.snap
Labels: kind/bug

#4144 Extend flight compute context for spice.ai connector with org and app names, to fix federated queries from different spice.ai data sources
  crates/data_components/src/flight.rs
  crates/runtime/src/dataconnector/spiceai.rs
Labels: kind/bug, data-connector/spice.ai

#4117 Enforce Flight DoPut policies: Rate Limiting, Read Timeout, and Max Records per Batch
  Cargo.lock
  crates/runtime/Cargo.toml
  crates/runtime/src/builder.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/do_put.rs
  crates/runtime/src/flight/middleware.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/rate_limits.rs
  crates/runtime/tests/flight/do_put.rs
  crates/runtime/tests/flight/snapshots/integration__flight__do_put__max_rows_allowed_table_content.snap
  crates/runtime/tests/flight/snapshots/integration__flight__do_put__rate_limit_table_content.snap
  crates/runtime/tests/flight/snapshots/integration__flight__do_put__read_timeout_table_content.snap
Labels: kind/enhancement

#4147 Fix bug Changes in catalog.yaml would require saving in spicepod.yaml to apply
  crates/runtime/src/init/catalog.rs
  crates/runtime/src/podswatcher.rs
Labels: kind/bug

#4154 Fix `platform_option` variable in `build_and_release.yml`.
  .github/workflows/build_and_release.yml
Labels: kind/bug, area/ci, github_actions

#4160 feat: Add Clickbench append benchmark for DuckDB and Arrow
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_duckdb/mod.rs
  crates/runtime/benches/bench_object_store/file.rs
Labels: kind/enhancement

#4159 Upload artifacts to Minio on build_and_release
  .github/workflows/build_and_release.yml
Labels: kind/enhancement

#4164 feat: add on zero results benchmark
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench.rs
  crates/runtime/benches/bench_object_store/mod.rs
  crates/runtime/benches/setup/mod.rs
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q10.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q11.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q12.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q13.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q16.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q18.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q19.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q2.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q20.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q21.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q22.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q3.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q4.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q5.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q6.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q7.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q8.snap
  crates/runtime/benches/snapshots/bench__s3_arrow_memory_use_source_tpch_q9.snap
Labels: kind/enhancement

#4161 Update spice.ai connector tests
  .github/workflows/integration.yml
  crates/runtime/tests/federation/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/mysql/federation.rs
  crates/runtime/tests/mysql/mod.rs
  crates/runtime/tests/snapshots/integration__spiceai__select.snap
  crates/runtime/tests/snapshots/integration__spiceai_federation_test_select.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_avg_gas_used.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_eth_logs.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_max_blocks_number.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_max_num.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_number_filter.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_number_subquery.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_sum_tx_receipt_gas_used.snap
  crates/runtime/tests/snapshots/integration__spiceai_integration_test_single_source_federation_push_down_select_union_all.snap
  crates/runtime/tests/spiceai/mod.rs
Labels: kind/enhancement, data-connector/spice.ai

#4146 Promote Spicepod version to V1
  README.md
  bin/spice/pkg/spec/spicepod_test.go
  bin/spice/pkg/spicepod/spicepod.go
  crates/spicepod/src/spec.rs
  deploy/chart/values.yaml
  test/arrow-types/create_arrow_types_test_data.py
  test/models/spicepod_hf.yml
  test/models/spicepod_openai.yml
  test/scripts/clickbench/setup-clickbench-spicepod.bash
  test/scripts/clickbench/setup-file.bash
  test/scripts/setup-semi-structure-spicepod.bash
  test/scripts/setup-tpc-spicepod.bash
  test/tpc-bench/Makefile
  test/tpc-bench/tpch-spicepod/spicepod.yaml
  tools/evalconverter/src/main.rs
Labels: kind/enhancement, breaking change

#4148 Postgres: add schema validation for record batches during write
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#4173 Fix the Windows build
  crates/test-framework/Cargo.toml
  crates/test-framework/src/spiced/mod.rs
Labels: kind/bug

#4156 Fix model name in `xAI`; add to `runtime/llms` tests
  crates/llms/src/embeddings/candle/util.rs
  crates/llms/src/xai.rs
  crates/llms/tests/llms/create.rs
  crates/llms/tests/llms/mod.rs
  crates/llms/tests/llms/snapshots/integration__llms__basic_xai_message_keys.snap
  crates/llms/tests/llms/snapshots/integration__llms__basic_xai_replied_appropriately.snap
  crates/llms/tests/llms/snapshots/integration__llms__system_prompt_xai_assistant_response.snap
  crates/llms/tests/llms/snapshots/integration__llms__system_prompt_xai_replied_appropriately.snap
  crates/llms/tests/llms/snapshots/integration__llms__tool_use_xai_finish_reason.snap
  crates/llms/tests/llms/snapshots/integration__llms__tool_use_xai_tool_choice.snap
  crates/llms/tests/llms/snapshots/integration__llms__tool_use_xai_valid_function_args.snap
  crates/runtime/src/model/chat.rs
Labels: kind/bug, area/ai, area/ci

#4185 docs: Lower connector stable scale
  docs/criteria/connectors/stable.md
Labels: kind/documentation

#4186 fix: Remove eth traces test
  crates/runtime/tests/refresh_sql/mod.rs
Labels: kind/bug

#4180 Update datafusion-federation & datafusion-table-provider patches
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#4174 Flight DoPut: update write error tracing
  crates/runtime/src/flight/do_put.rs
Labels: kind/bug

#4188 Disable spice.ai connector integration test
  crates/runtime/tests/spiceai/mod.rs
Labels: kind/bug

#4189 Fix windows
  crates/test-framework/src/spiced/mod.rs
Labels: kind/bug

#4176 v1.0.0-rc.4 Release Notes
  docs/release_notes/v1.0.0-rc.4.md
Labels: kind/documentation

#4158 Ensure non-nullity of primary keys in `MemTable`; check validity of initial data.
  Cargo.lock
  crates/data_components/src/arrow.rs
  crates/data_components/src/arrow/write.rs
Labels: kind/bug

#4191 Bump version to v1.0.0 stable
  Cargo.lock
  Cargo.toml
  version.txt
Labels: kind/enhancement

#4193 Fix metal + models download
  .github/workflows/build_and_release.yml
Labels: kind/bug

#4194 Update spice.ai connector beta roadmap
  docs/ROADMAP.md
Labels: kind/documentation

#4196 Add throughput test module to `test-framework`
  crates/runtime/tests/rehydration/mod.rs
  crates/test-framework/src/lib.rs
  crates/test-framework/src/spiced/mod.rs
  crates/test-framework/src/throughput/mod.rs
  crates/test-framework/src/throughput/worker.rs
Labels: kind/enhancement

#4202 Update Spice.ai TPCH snapshots
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q10_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q11_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q12_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q16_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q19_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q20_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q22_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q3_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q4_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q5_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q6_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q8_explain.snap
Labels: kind/bug

#4138 Run Clickbench for Dremio
  crates/runtime/benches/bench_dremio/mod.rs
  crates/runtime/benches/queries/clickbench/dremio/q21.sql
  crates/runtime/benches/queries/clickbench/dremio/q22.sql
  crates/runtime/benches/queries/clickbench/dremio/q23.sql
  crates/runtime/benches/queries/clickbench/dremio/q24.sql
  crates/test-framework/src/queries/clickbench/dremio/q21.sql
  crates/test-framework/src/queries/clickbench/dremio/q22.sql
  crates/test-framework/src/queries/clickbench/dremio/q23.sql
  crates/test-framework/src/queries/clickbench/dremio/q24.sql
  crates/test-framework/src/queries/mod.rs
Labels: kind/enhancement, area/data-connectors

#4213 Fix the typo in connector stable criteria
  docs/criteria/connectors/stable.md
Labels: kind/enhancement, area/data-connectors

#4214 feat: Add throughput test example
  .gitignore
  crates/spicepod/src/lib.rs
  crates/spicepod/src/reader.rs
  crates/test-framework/src/spiced/mod.rs
  crates/test-framework/src/throughput/mod.rs
  crates/test-framework/src/throughput/worker.rs
  test/spicepods/file_tpch.yaml
  tools/testoperator/Cargo.toml
  tools/testoperator/src/main.rs
  tools/testoperator/src/tests/throughput/mod.rs
Labels: kind/enhancement

#4215 feat: calculate throughput test query percentiles
  .gitignore
  crates/runtime/benches/bench_dremio/mod.rs
  crates/runtime/benches/bench_duckdb/mod.rs
  crates/runtime/benches/bench_mysql/mod.rs
  crates/runtime/benches/bench_object_store/file.rs
  crates/runtime/benches/bench_object_store/mod.rs
  crates/runtime/benches/bench_odbc_athena/mod.rs
  crates/runtime/benches/bench_postgres/mod.rs
  crates/runtime/benches/bench_spark/mod.rs
  crates/test-framework/src/queries/mod.rs
  crates/test-framework/src/throughput/mod.rs
  crates/test-framework/src/throughput/worker.rs
  test/spicepods/duckdb_tpch.yaml
  test/spicepods/file_tpch.yaml
  tools/testoperator/Cargo.toml
  tools/testoperator/README.md
  tools/testoperator/src/commands/mod.rs
  tools/testoperator/src/main.rs
  tools/testoperator/src/tests/throughput/mod.rs
Labels: kind/enhancement

#4220 Improve clarity and concison of use-cases
  README.md
Labels: kind/documentation

#4221 Remove macOS Intel build
  .github/workflows/build_and_release.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_release_install.yml
  install/install-spiced.sh
  install/install.sh
Labels: kind/enhancement

#4222 fix: Test operator throughput test workflow
  .github/workflows/testoperator_run_throughput.yml
  test/spicepods/s3_tpch.yaml
Labels: kind/enhancement

#4226 DynamoDB: Automatically load AWS credentials from IAM roles if access key not provided
  crates/runtime/src/dataconnector/dynamodb.rs
Labels: kind/enhancement

#4225 File connector clickbench snapshots results
  crates/runtime/benches/snapshots/bench__file_clickbench_q1.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q10.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q11.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q12.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q13.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q14.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q15.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q16.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q17.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q18.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q19.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q2.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q20.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q21.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q22.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q23.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q24.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q25.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q26.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q27.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q28.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q29.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q3.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q30.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q31.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q32.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q33.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q34.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q35.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q36.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q37.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q38.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q39.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q4.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q40.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q41.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q42.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q43.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q5.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q6.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q7.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q8.snap
  crates/runtime/benches/snapshots/bench__file_clickbench_q9.snap
Labels: kind/enhancement

#4204 Spice.ai Catalog Connector
  crates/data_components/src/iceberg/catalog.rs
  crates/data_components/src/iceberg/provider.rs
  crates/data_components/src/lib.rs
  crates/data_components/src/spice_cloud/mod.rs
  crates/data_components/src/spice_cloud/provider.rs
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/runtime/src/catalogconnector/mod.rs
  crates/runtime/src/catalogconnector/spice_cloud.rs
  crates/runtime/src/component/catalog.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/mod.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/dynamodb.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/localpod.rs
  crates/runtime/src/dataconnector/memory.rs
  crates/runtime/src/dataconnector/mssql.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/sharepoint.rs
  crates/runtime/src/dataconnector/sink.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/extension.rs
  crates/runtime/src/parameters.rs
  crates/spice_cloud/src/catalog.rs
  crates/spice_cloud/src/lib.rs
  crates/spice_cloud/src/schema.rs
Labels: kind/enhancement, breaking change

#4227 feat: Add test framework metrics collection
  Cargo.lock
  crates/test-framework/Cargo.toml
  crates/test-framework/src/lib.rs
  crates/test-framework/src/metrics/mod.rs
  crates/test-framework/src/throughput/mod.rs
  crates/test-framework/src/throughput/worker.rs
  tools/testoperator/src/tests/throughput/mod.rs
Labels: kind/enhancement

#4228 Add badges for build/test status on README.md
  README.md
Labels: kind/documentation

#4224 Release Dremio to RC
  README.md
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
  docs/criteria/connectors/rc.md
Labels: kind/enhancement, kind/task

#4229 feat: Add more test spicepods
  .github/workflows/testoperator_run_throughput.yml
  test/spicepods/tpcds/file.yaml
  test/spicepods/tpcds/s3.yaml
  test/spicepods/tpch/accelerated/file_arrow.yaml
  test/spicepods/tpch/accelerated/file_duckdb_file.yaml
  test/spicepods/tpch/accelerated/file_duckdb_memory.yaml
  test/spicepods/tpch/accelerated/s3_arrow.yaml
  test/spicepods/tpch/accelerated/s3_duckdb_file.yaml
  test/spicepods/tpch/accelerated/s3_duckdb_memory.yaml
  test/spicepods/tpch/duckdb.yaml
  test/spicepods/tpch/file.yaml
  test/spicepods/tpch/s3.yaml
Labels: kind/enhancement

#4231 feat: Add load test to testoperator
  .github/workflows/testoperator_run_load.yml
  Cargo.lock
  crates/test-framework/Cargo.toml
  crates/test-framework/src/spiced/mod.rs
  crates/test-framework/src/throughput/mod.rs
  crates/test-framework/src/throughput/worker.rs
  docs/criteria/accelerators/stable.md
  docs/criteria/connectors/stable.md
  tools/testoperator/src/main.rs
  tools/testoperator/src/tests/load/mod.rs
  tools/testoperator/src/tests/mod.rs
  tools/testoperator/src/tests/throughput/mod.rs
Labels: kind/enhancement

#4192 Add TSV format to all `object_store`-based connectors
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/file.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/dataconnector/listing/mod.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/parameters.rs
Labels: kind/bug

#4230 Move test-framework to dev-dependencies for Runtime
  crates/runtime/Cargo.toml
Labels: kind/bug

#4235 Document limitation for correlated subqueries in TPCH for Spice.ai connector
  crates/test-framework/src/queries/README.md
Labels: kind/enhancement

#4130 Changes for CUDA
  .github/workflows/build_and_release.yml
  .github/workflows/spiced_docker.yml
  Cargo.lock
  Cargo.toml
  Dockerfile-cuda
  bin/spice/cmd/chat.go
  bin/spice/pkg/github/runtime_release.go
  crates/llms/Cargo.toml
  crates/llms/build.rs
  crates/llms/src/chat/mistral.rs
Labels: kind/enhancement, area/ai

#4243 Suppress opentelemetry_sdk warnings - they aren't useful
  bin/spiced/src/tracing.rs
Labels: kind/bug

#4248 feat: Re-enable defaults on test spicepods
  test/spicepods/tpcds/accelerated/file_arrow.yaml
  test/spicepods/tpcds/accelerated/file_duckdb_file.yaml
  test/spicepods/tpcds/accelerated/file_duckdb_memory.yaml
  test/spicepods/tpcds/file.yaml
  test/spicepods/tpcds/s3.yaml
  test/spicepods/tpch/accelerated/file_arrow.yaml
  test/spicepods/tpch/accelerated/file_duckdb_file.yaml
  test/spicepods/tpch/accelerated/file_duckdb_memory.yaml
  test/spicepods/tpch/accelerated/s3_arrow.yaml
  test/spicepods/tpch/accelerated/s3_duckdb_file.yaml
  test/spicepods/tpch/accelerated/s3_duckdb_memory.yaml
  test/spicepods/tpch/duckdb.yaml
  test/spicepods/tpch/file.yaml
  test/spicepods/tpch/s3.yaml
Labels: kind/enhancement

#4232 Add usage for streaming local models; Fix spice chat usage bar TPS expansion
  Cargo.lock
  crates/llms/Cargo.toml
Labels: kind/bug, area/ai

#4246 refactor: Use composite testoperator setup, add query overrides
  .github/actions/setup-testoperator/action.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
Labels: kind/refactor

#4237 Enable expand_views_at_output for DF optimizer and transform schema to expanded view types
  Cargo.lock
  crates/arrow_tools/Cargo.toml
  crates/arrow_tools/src/schema.rs
  crates/runtime/benches/bench_spicecloud/mod.rs
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q1.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q14.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_simple_q3_explain.snap
  crates/runtime/src/dataconnector/listing/connector.rs
  crates/runtime/src/datafusion/builder.rs
  crates/runtime/tests/refresh_sql/mod.rs
Labels: kind/bug

#4241 Add throughput test spicepod for databricks delta mode connector
  .github/workflows/testoperator_run_throughput.yml
  test/spicepods/tpcds/databricks_delta.yaml
  test/spicepods/tpch/databricks_delta.yaml
Labels: kind/enhancement

#4254 Increase the timeout minutes of load test to 10 hours
  .github/workflows/testoperator_run_load.yml
Labels: kind/optimization

#4247 Improve partition column counts error for delta table
  crates/data_components/src/delta_lake.rs
Labels: kind/enhancement

#4255 Add e2e test for databricks catalog connector (mode: delta_lake)
  .github/workflows/e2e_test_ci.yml
Labels: kind/enhancement

#4256 Spark connector integration tests
  .github/workflows/integration.yml
  crates/runtime/tests/integration.rs
  crates/runtime/tests/snapshots/integration__spark__spark_select.snap
  crates/runtime/tests/snapshots/integration__spark_test_select.snap
  crates/runtime/tests/spark/mod.rs
Labels: kind/enhancement, data-connector/spark

#4257 Configure databricks delta secrets to run load test
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
Labels: kind/enhancement

#4249 Support `properties` for emitted telemetry
  bin/spiced/src/lib.rs
  crates/spicepod/src/component/runtime.rs
  crates/telemetry/src/anonymous.rs
Labels: kind/enhancement

#4259 feat: Add `ready_wait` test operator workflow input
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
Labels: kind/enhancement

#4263 Handle 'LargeStringArray' for embedding tables
  crates/runtime/src/embeddings/execution_plan.rs
Labels: kind/bug, area/ci

#4261 `llms` tests for alpha/beta model criteria
  crates/llms/tests/llms/mod.rs
  crates/llms/tests/llms/util.rs
Labels: kind/enhancement, area/ai, area/ci

#4262 Configurable runner type for load and throughput tests
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
Labels: kind/enhancement

#4264 Handle NULL partition columns for Delta Lake tables
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/delta_lake.rs
  crates/llms/Cargo.toml
  crates/runtime/tests/delta_lake/mod.rs
Labels: kind/bug

#4266 Add integration test for Snowflake
  crates/runtime/tests/integration.rs
  crates/runtime/tests/snapshots/integration__snowflake__snowflake_select.snap
  crates/runtime/tests/snapshots/integration__snowflake_test_select.snap
  crates/runtime/tests/snowflake/mod.rs
Labels: kind/enhancement

#4268 Add Snowflake TPCH queries
  crates/test-framework/src/queries/mod.rs
  crates/test-framework/src/queries/tpch/snowflake/q1.sql
  crates/test-framework/src/queries/tpch/snowflake/q10.sql
  crates/test-framework/src/queries/tpch/snowflake/q11.sql
  crates/test-framework/src/queries/tpch/snowflake/q12.sql
  crates/test-framework/src/queries/tpch/snowflake/q13.sql
  crates/test-framework/src/queries/tpch/snowflake/q14.sql
  crates/test-framework/src/queries/tpch/snowflake/q16.sql
  crates/test-framework/src/queries/tpch/snowflake/q17.sql
  crates/test-framework/src/queries/tpch/snowflake/q18.sql
  crates/test-framework/src/queries/tpch/snowflake/q19.sql
  crates/test-framework/src/queries/tpch/snowflake/q2.sql
  crates/test-framework/src/queries/tpch/snowflake/q20.sql
  crates/test-framework/src/queries/tpch/snowflake/q21.sql
  crates/test-framework/src/queries/tpch/snowflake/q22.sql
  crates/test-framework/src/queries/tpch/snowflake/q3.sql
  crates/test-framework/src/queries/tpch/snowflake/q4.sql
  crates/test-framework/src/queries/tpch/snowflake/q5.sql
  crates/test-framework/src/queries/tpch/snowflake/q6.sql
  crates/test-framework/src/queries/tpch/snowflake/q7.sql
  crates/test-framework/src/queries/tpch/snowflake/q8.sql
  crates/test-framework/src/queries/tpch/snowflake/q9.sql
  crates/test-framework/src/queries/tpch/snowflake/simple_q1.sql
  crates/test-framework/src/queries/tpch/snowflake/simple_q2.sql
  crates/test-framework/src/queries/tpch/snowflake/simple_q3.sql
  crates/test-framework/src/queries/tpch/snowflake/simple_q4.sql
  crates/test-framework/src/queries/tpch/snowflake/simple_q5.sql
  crates/test-framework/src/queries/tpch/snowflake/simple_q6.sql
  crates/test-framework/src/queries/tpch/snowflake/simple_q7.sql
  test/spicepods/tpch/snowflake_sf1.yaml
  test/spicepods/tpch/snowflake_sf100.yaml
Labels: kind/enhancement

#4265 Handle `LargeStringArray` in `v1/search`.
  crates/runtime/src/embeddings/execution_plan.rs
  crates/runtime/src/embeddings/mod.rs
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/bug, area/ci

#4269 Fix `build_cuda` in Update spiced_docker.yml
  .github/workflows/spiced_docker.yml
Labels: kind/bug, area/ai

#4270 Run Snowflake benchmark in GitHub Actions
  .github/workflows/testoperator_run_bench.yml
  tools/testoperator/src/commands/mod.rs
Labels: kind/enhancement

#4271 Allow Snowflake query override for CI tests
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
Labels: kind/enhancement

#4272 Don't run GPU builds for trunk
  .github/workflows/build_and_release.yml
Labels: kind/enhancement, area/ai, github_actions

#4273 Fix InvalidTypeAction not working
  crates/runtime/src/dataconnector.rs
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
  crates/runtime/tests/acceleration/on_conflict.rs
  crates/runtime/tests/acceleration/query_push_down.rs
  crates/runtime/tests/postgres/common.rs
  crates/runtime/tests/postgres/mod.rs
Labels: kind/bug

#4274 Add xAI key to llm integration tests
  .github/workflows/integration_llms.yml
Labels: kind/bug, area/ai, area/ci

#4275 Update openai snapshots
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_completion.snap
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_chunking_response.snap
Labels: kind/bug, area/ai, area/ci

#4276 Fix federation bug for correlated subqueries
  Cargo.lock
  Cargo.toml
  crates/test-framework/src/queries/mod.rs
Labels: kind/bug

#4277 Promote Snowflake to Beta
  README.md
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
Labels: kind/documentation

#4283 Set version to 1.0.0-rc.5
  Cargo.toml
  version.txt
Labels: kind/enhancement

#4284 Enable spice.ai data connector integration test
  crates/runtime/tests/snapshots/integration__spiceai__select.snap
  crates/runtime/tests/snapshots/integration__spiceai_federation_test_select.snap
  crates/runtime/tests/spiceai/mod.rs
Labels: kind/bug

#4285 Update cargo.lock
  Cargo.lock
Labels: kind/bug

#4281 Update spice.ai data connector snapshots
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q17.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q17_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q21_explain.snap
  crates/runtime/benches/snapshots/bench__spice.ai_tpch_q2_explain.snap
Labels: kind/enhancement

#4282 Promote the Spice.ai Data Connector to Beta
  README.md
  crates/runtime/tests/catalog/mod.rs
  crates/runtime/tests/snapshots/integration__spiceai__select.snap
  crates/runtime/tests/snapshots/integration__spiceai_federation_test_select.snap
  crates/runtime/tests/spiceai/mod.rs
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
  docs/criteria/connectors/rc.md
  docs/criteria/connectors/stable.md
Labels: kind/enhancement

#4279 Revert change to `integration_models__models__search__openai_chunking_response.snap`
  crates/runtime/tests/models/snapshots/integration_models__models__search__openai_chunking_response.snap
Labels: kind/bug, area/ai, area/ci

#4280 Allow for a subset of build artifacts to be published to minio
  .github/workflows/build_and_release.yml
Labels: kind/bug, area/ci

#4286 Promote File Data Connector to Stable
  README.md
  docs/criteria/connectors/stable.md
Labels: kind/enhancement

#4287 Add Iceberg to Supported Catalogs
  README.md
Labels: kind/bug

#4295 Fix Spark benchmark credentials, add back overrides
  .github/workflows/benchmarks.yml
  crates/runtime/benches/bench_spark/mod.rs
Labels: kind/bug, area/ci

#4296 Promote Spark Data Connector to Beta
  README.md
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
Labels: kind/documentation, kind/enhancement

#4233 Add Dremio throughput test spicepod
  .github/workflows/testoperator_run_throughput.yml
  test/spicepods/tpcds/dremio.yaml
  test/spicepods/tpch/dremio.yaml
Labels: kind/enhancement, kind/task

#4299 Add error message for invalid databricks mode parameter
  crates/runtime/src/dataconnector/databricks.rs
Labels: kind/optimization

#4300 Fix pre-release check to look for `build` string
  bin/spice/cmd/version.go
Labels: kind/bug

#4301 Promote databricks catalog connector (mode: delta_lake) to beta
  docs/criteria/catalogs/alpha.md
  docs/criteria/catalogs/beta.md
  docs/criteria/catalogs/rc.md
Labels: kind/enhancement

#4303 Properly delegate `load_table` to Rest Catalog
  crates/data_components/src/iceberg/catalog.rs
Labels: kind/bug

#4306 docs: Update ROADMAP.md
  docs/ROADMAP.md
Labels: kind/documentation

#4298 v1.0.0-rc.5 Release Notes
  docs/release_notes/v1.0.0-rc.5.md
Labels: kind/documentation

#4307 Revert "Promote databricks catalog connector (mode: delta_lake) to beta (#4301)"
  docs/criteria/catalogs/alpha.md
  docs/criteria/catalogs/beta.md
  docs/criteria/catalogs/rc.md
Labels: kind/optimization

#4309 v1.0.0-rc.5 release notes changelog update
  docs/release_notes/v1.0.0-rc.5.md
Labels: kind/documentation

#4311 feat: Update load test criteria, testoperator updates
  .github/actions/setup-testoperator/action.yml
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
  Cargo.lock
  crates/test-framework/Cargo.toml
  crates/test-framework/src/spiced/mod.rs
  crates/test-framework/src/spicetest/mod.rs
  crates/test-framework/src/spicetest/worker.rs
  docs/criteria/accelerators/stable.md
  docs/criteria/connectors/stable.md
  docs/criteria/definitions.md
  test/spicepods/tpcds/duckdb.yaml
  tools/testoperator/src/commands/mod.rs
  tools/testoperator/src/main.rs
  tools/testoperator/src/tests/bench/mod.rs
  tools/testoperator/src/tests/load/mod.rs
  tools/testoperator/src/tests/mod.rs
  tools/testoperator/src/tests/throughput/mod.rs
Labels: kind/enhancement

#4313 Update helm for v1.0.0-rc.5
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#4314 Bump version to v1.0.0, update SECURITY.md
  Cargo.lock
  Cargo.toml
  SECURITY.md
  version.txt
Labels: kind/enhancement

#4223 Initial criteria for models, embeddings
  docs/criteria/PRINCIPLES.md
  docs/criteria/connectors/stable.md
  docs/criteria/embeddings/alpha.md
  docs/criteria/embeddings/beta.md
  docs/criteria/embeddings/rc.md
  docs/criteria/embeddings/stable.md
  docs/criteria/models/alpha.md
  docs/criteria/models/beta.md
  docs/criteria/models/rc.md
  docs/criteria/models/stable.md
Labels: kind/enhancement, area/ai

#4315 Add dremio param for running load test
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
Labels: kind/enhancement

#4328 Promote Databricks (mode: delta_lake) connector to stable
  README.md
  docs/criteria/connectors/stable.md
Labels: kind/enhancement

#4327 Handle failed query in load test
  crates/test-framework/src/metrics/mod.rs
  tools/testoperator/src/tests/load/mod.rs
Labels: kind/bug

#4334 feat: Use load test hours for baseline query sets
  docs/criteria/accelerators/stable.md
  docs/criteria/connectors/stable.md
  tools/testoperator/src/tests/load/mod.rs
Labels: kind/enhancement

#4329 Fix typo in 1.0.0-rc.5 release notes
  docs/release_notes/v1.0.0-rc.5.md
Labels: kind/documentation

#4319 feat: add testoperator data consistency
  crates/runtime/src/execution_plan/fallback_on_zero_results.rs
  crates/test-framework/src/queries/mod.rs
  crates/test-framework/src/spicetest/mod.rs
  crates/test-framework/src/spicetest/worker.rs
  test/spicepods/clickbench/accelerated/on_zero_results/file_duckdb_file.yaml
  test/spicepods/clickbench/accelerated/on_zero_results/file_duckdb_memory.yaml
  test/spicepods/clickbench/file_small.yaml
  test/spicepods/tpcds/accelerated/on_zero_results/file_duckdb_file.yaml
  test/spicepods/tpcds/accelerated/on_zero_results/file_duckdb_memory.yaml
  test/spicepods/tpch/accelerated/on_zero_results/file_duckdb_file.yaml
  test/spicepods/tpch/accelerated/on_zero_results/file_duckdb_memory.yaml
  tools/testoperator/README.md
  tools/testoperator/src/commands/mod.rs
  tools/testoperator/src/main.rs
  tools/testoperator/src/tests/bench/mod.rs
  tools/testoperator/src/tests/data_consistency/mod.rs
  tools/testoperator/src/tests/mod.rs
Labels: kind/enhancement

#4335 docs: Release DuckDB connector stable
  README.md
  docs/criteria/connectors/stable.md
Labels: kind/documentation

#4339 Fix DocumentDB -> DynamoDB
  README.md
Labels: kind/documentation

#4343 Remove evil averages
  crates/test-framework/src/metrics/mod.rs
Labels: kind/enhancement

#4344 Don't run builds on non-code changes
  .github/workflows/build_and_release.yml
  .github/workflows/e2e_test_ci.yml
  .github/workflows/e2e_test_ci_models.yml
  .github/workflows/integration.yml
  .github/workflows/integration_models.yml
  .github/workflows/makefile_targets.yml
Labels: kind/enhancement

#4345 Remove streaming requirement from Databricks spark Beta and Spark connector Beta
  docs/criteria/connectors/beta.md
Labels: kind/documentation

#4346 Update s3 tpcds spicepods
  test/spicepods/tpcds/s3.yaml
  test/spicepods/tpcds/s3_sf5.yaml
Labels: kind/enhancement

#4347 Explicitly set required scale factor for throughput and load tests
  docs/criteria/accelerators/stable.md
  docs/criteria/connectors/stable.md
Labels: kind/documentation

#4348 Fix s3 tpcds dataset name
  test/spicepods/tpcds/s3.yaml
Labels: kind/bug

#4350 Promote Iceberg Catalog Connector to Beta
  .github/workflows/e2e_test_ci.yml
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
  README.md
  crates/data_components/src/iceberg/provider.rs
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/test-framework/src/queries/mod.rs
  crates/test-framework/src/queries/tpch/iceberg_sf1/q1.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q10.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q11.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q12.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q13.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q14.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q16.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q17.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q18.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q19.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q2.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q20.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q21.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q22.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q3.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q4.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q5.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q6.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q7.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q8.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/q9.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/simple_q1.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/simple_q2.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/simple_q3.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/simple_q4.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/simple_q5.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/simple_q6.sql
  crates/test-framework/src/queries/tpch/iceberg_sf1/simple_q7.sql
  docs/criteria/catalogs/alpha.md
  docs/criteria/catalogs/beta.md
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
  docs/criteria/connectors/rc.md
  docs/criteria/connectors/stable.md
  test/spicepods/tpch/iceberg_catalog.yaml
  tools/testoperator/src/commands/mod.rs
Labels: kind/enhancement

#4351 Update s3 clickbench benchmark snapshots
  crates/runtime/benches/snapshots/bench__s3_clickbench_q1.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q10.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q11.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q12.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q13.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q14.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q15.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q16.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q17.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q18.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q19.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q2.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q20.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q21.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q22.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q23.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q24.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q25.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q26.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q27.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q28.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q29.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q3.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q30.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q31.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q32.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q33.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q34.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q35.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q36.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q37.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q38.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q39.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q4.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q40.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q41.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q42.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q43.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q5.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q6.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q7.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q8.snap
  crates/runtime/benches/snapshots/bench__s3_clickbench_q9.snap
Labels: kind/enhancement

#4349 fix: DuckDB clickbench on zero results
  Cargo.lock
  Cargo.toml
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/test-framework/src/queries/clickbench/duckdb/q11.sql
  crates/test-framework/src/queries/clickbench/duckdb/q12.sql
  crates/test-framework/src/queries/clickbench/duckdb/q13.sql
  crates/test-framework/src/queries/clickbench/duckdb/q14.sql
  crates/test-framework/src/queries/clickbench/duckdb/q15.sql
  crates/test-framework/src/queries/clickbench/duckdb/q22.sql
  crates/test-framework/src/queries/clickbench/duckdb/q23.sql
  crates/test-framework/src/queries/clickbench/duckdb/q25.sql
  crates/test-framework/src/queries/clickbench/duckdb/q26.sql
  crates/test-framework/src/queries/clickbench/duckdb/q27.sql
  crates/test-framework/src/queries/clickbench/duckdb/q28.sql
  crates/test-framework/src/queries/clickbench/duckdb/q29.sql
  crates/test-framework/src/queries/clickbench/duckdb/q31.sql
  crates/test-framework/src/queries/clickbench/duckdb/q32.sql
  crates/test-framework/src/queries/clickbench/duckdb/q37.sql
  crates/test-framework/src/queries/clickbench/duckdb/q38.sql
  crates/test-framework/src/queries/mod.rs
Labels: kind/bug

#4353 Add integration test with snapshots for databricks catalog connector
  crates/runtime/tests/databricks_delta_catalog/mod.rs
  crates/runtime/tests/databricks_spark_catalog/mod.rs
  crates/runtime/tests/integration.rs
  crates/runtime/tests/snapshots/integration__databricks_delta_catalog__test_select_tpcds.snap
  crates/runtime/tests/snapshots/integration__databricks_delta_catalog__test_select_tpch.snap
  crates/runtime/tests/snapshots/integration__databricks_spark_catalog__test_select_tpcds.snap
  crates/runtime/tests/snapshots/integration__databricks_spark_catalog__test_select_tpch.snap
Labels: kind/enhancement

#4355 New test operator: HTTP consistency
  Cargo.lock
  crates/test-framework/Cargo.toml
  crates/test-framework/src/spicetest/consistency/mod.rs
  crates/test-framework/src/spicetest/consistency/worker.rs
  crates/test-framework/src/spicetest/mod.rs
  tools/testoperator/Cargo.toml
  tools/testoperator/README.md
  tools/testoperator/src/commands/consistency.rs
  tools/testoperator/src/commands/dataset.rs
  tools/testoperator/src/commands/mod.rs
  tools/testoperator/src/main.rs
  tools/testoperator/src/tests/bench/mod.rs
  tools/testoperator/src/tests/data_consistency/mod.rs
  tools/testoperator/src/tests/http_consistency/mod.rs
  tools/testoperator/src/tests/load/mod.rs
  tools/testoperator/src/tests/mod.rs
  tools/testoperator/src/tests/throughput/mod.rs
  tools/testoperator/temp.file
Labels: kind/enhancement, area/ai, area/ci

#4297 Fix Bug: No field named body_embedding when do vector search with refresh sql containing subset of columns
  crates/arrow_tools/src/schema.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/datafusion/refresh_sql.rs
  crates/runtime/src/embeddings/table.rs
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/mod.rs
  crates/runtime/tests/models/openai.rs
Labels: kind/bug

#4359 refactor: HTTP testoperator
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
  crates/test-framework/src/lib.rs
  crates/test-framework/src/metrics/mod.rs
  crates/test-framework/src/spicetest/consistency/mod.rs
  crates/test-framework/src/spicetest/datasets/mod.rs
  crates/test-framework/src/spicetest/datasets/worker.rs
  crates/test-framework/src/spicetest/http/component.rs
  crates/test-framework/src/spicetest/http/mod.rs
  crates/test-framework/src/spicetest/http/worker.rs
  crates/test-framework/src/spicetest/mod.rs
  tools/testoperator/src/commands/consistency.rs
  tools/testoperator/src/commands/dataset.rs
  tools/testoperator/src/commands/mod.rs
  tools/testoperator/src/main.rs
  tools/testoperator/src/tests/bench/mod.rs
  tools/testoperator/src/tests/http_consistency/mod.rs
  tools/testoperator/src/tests/load/mod.rs
  tools/testoperator/src/tests/mod.rs
  tools/testoperator/src/tests/throughput/mod.rs
Labels: kind/refactor

#4365 Add TPCH/TPCDS test spicepods for MySQL
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
  test/spicepods/tpcds/mysql.yaml
  test/spicepods/tpch/mysql.yaml
Labels: kind/enhancement

#4367 Update ROADMAP - Iceberg catalog alpha for v1.0
  docs/ROADMAP.md
Labels: kind/documentation

#4369 Promote databricks catalog and databricks (spark_connect) connector to beta
  README.md
  docs/criteria/catalogs/alpha.md
  docs/criteria/catalogs/beta.md
  docs/criteria/connectors/alpha.md
  docs/criteria/connectors/beta.md
Labels: kind/enhancement

#4373 Update Roadmap - Iceberg beta
  docs/ROADMAP.md
Labels: kind/documentation

#4320 Build CUDA binaries for Linux
  .github/actions/spiced-cuda-build/action.yaml
  .github/workflows/build_and_release.yml
Labels: kind/enhancement, area/ai, area/ci

#4380 Promote Nvidia NIM as Alpha
  docs/criteria/models/alpha.md
Labels: kind/enhancement

#4375 Setup http consistency workflow
  .github/workflows/testoperator_run_http_consistency.yml
  crates/test-framework/src/metrics/mod.rs
  test/payloads/model-openai-completions-payload.jsonl
  test/payloads/model-openai-embeddings-payload.jsonl
  test/spicepods/models/openai.yaml
  tools/testoperator/src/tests/http/consistency.rs
  tools/testoperator/src/tests/load/mod.rs
Labels: kind/enhancement

#4381 Promote xai to alpha
  docs/criteria/models/alpha.md
Labels: kind/enhancement

#4383 Update stable criteria for object store based connectors
  docs/criteria/connectors/stable.md
Labels: kind/documentation

#4385 Promote S3 Data Connector to Stable
  README.md
  docs/criteria/connectors/stable.md
Labels: kind/documentation

#4356 Download platform-supported CUDA binary version on Linux
  bin/spice/pkg/github/runtime_release.go
Labels: kind/enhancement

#4388 feat: Add Postgres test spicepods
  .github/workflows/testoperator_run_bench.yml
  .github/workflows/testoperator_run_data_consistency.yml
  .github/workflows/testoperator_run_load.yml
  .github/workflows/testoperator_run_throughput.yml
  Cargo.toml
  crates/test-framework/src/queries/mod.rs
  test/spicepods/tpcds/accelerated/file_arrow.yaml
  test/spicepods/tpcds/accelerated/file_duckdb_file.yaml
  test/spicepods/tpcds/accelerated/file_duckdb_memory.yaml
  test/spicepods/tpcds/accelerated/postgres_arrow.yaml
  test/spicepods/tpcds/accelerated/postgres_duckdb_file.yaml
  test/spicepods/tpcds/accelerated/postgres_duckdb_memory.yaml
  test/spicepods/tpcds/duckdb.yaml
  test/spicepods/tpcds/postgres.yaml
  test/spicepods/tpcds/s3.yaml
  test/spicepods/tpcds/s3_sf5.yaml
  test/spicepods/tpch/accelerated/postgres_arrow.yaml
  test/spicepods/tpch/accelerated/postgres_duckdb_file.yaml
  test/spicepods/tpch/accelerated/postgres_duckdb_memory.yaml
  test/spicepods/tpch/postgres.yaml
  test/tpc-bench/Makefile
  test/tpc-bench/tpcds_index.sql
  test/tpc-bench/tpch_index.sql
Labels: kind/enhancement

#4389 Fix federation bug for correlated subqueries of deeply nested Dremio tables
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#4390 Fix http overhead workflow
  .github/workflows/testoperator_run_http_overhead.yml
  test/payloads/model-openai-completions-payload.jsonl
  test/payloads/model-openai-embeddings-payload.jsonl
  test/spicepods/models/openai.yaml
  tools/testoperator/src/commands/http.rs
  tools/testoperator/src/tests/http/consistency.rs
Labels: kind/bug
