Repository spiceai/spiceai, pull requests merged in 2025-02, with the labels that each got.

#4591 Add paths verification when loading local models
  crates/runtime/src/init/model.rs
  crates/spicepod/src/component/model.rs
Labels: kind/bug

#4592 Add `generation_config.json` support for Filesystem models
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/llms/tests/llms/create.rs
  crates/runtime/src/model/chat.rs
  crates/spicepod/src/component/model.rs
Labels: kind/bug

#4593 Promote Filesystem model provider to RC
  README.md
  docs/criteria/models/rc.md
Labels: kind/documentation

#4550 docs: Add models grading criteria
  docs/criteria/models/grading.md
Labels: kind/documentation

#4588 Fix typo in Alpha Release Criteria (models)
  docs/criteria/models/alpha.md
Labels: kind/documentation

#4579 feat: add schema inference for the Spice.ai Data Connector
  crates/data_components/src/spice_cloud/catalog.rs
  crates/runtime/src/dataconnector/spiceai.rs
Labels: kind/enhancement

#4595 fix: Retry AI integration tests
  crates/runtime/tests/models/hf.rs
  crates/runtime/tests/models/openai.rs
Labels: kind/bug

#4495 Run LLM integration tests on Macs; add running local models.
  .github/workflows/integration_llms.yml
  .github/workflows/integration_models.yml
  crates/llms/tests/llms/mod.rs
Labels: kind/refactor, area/ai, area/ci

#4607 Remove 'tools: builtin'
  crates/runtime/src/tools/builtin/catalog.rs
  crates/runtime/src/tools/options.rs
Labels: kind/enhancement, area/ai, breaking change

#4587 feat: Add initial IMAP connector
  Cargo.lock
  Cargo.toml
  crates/data_components/Cargo.toml
  crates/data_components/src/imap/mod.rs
  crates/data_components/src/imap/provider.rs
  crates/data_components/src/imap/session.rs
  crates/data_components/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/imap.rs
  tools/testoperator/Cargo.toml
Labels: kind/enhancement

#4601 Improve UX of downloading GGUF from HF
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/llms/tests/llms/create.rs
  crates/runtime/src/init/model.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/tests/models/hf.rs
Labels: kind/enhancement, area/ai

#4531 Update roadmap link in readme
  README.md
Labels: kind/documentation

#4616 feat: Add email content loading
  bin/spiced/Cargo.toml
  crates/data_components/src/imap/mod.rs
  crates/data_components/src/imap/provider.rs
  crates/runtime/src/dataconnector/imap.rs
Labels: kind/enhancement, area/data-connectors

#4613 feat: Add SSL and Auth parameters for IMAP
  crates/data_components/src/imap/mod.rs
  crates/data_components/src/imap/session.rs
  crates/runtime/src/dataconnector/imap.rs
Labels: kind/enhancement, area/data-accelerators

#4624 Change /v1/models to be OpenAI compatible
  bin/spice/cmd/chat.go
  bin/spice/cmd/models.go
  bin/spice/cmd/nsql.go
  bin/spice/pkg/api/model.go
  bin/spice/pkg/api/util.go
  crates/runtime/src/http/v1/models.rs
Labels: kind/enhancement, breaking change

#4626 Promote Huggingface model provider to rc
  README.md
  docs/criteria/models/rc.md
Labels: kind/enhancement, kind/task

#4615 Use `pdf-extract` crate to extract text from PDF documents
  Cargo.lock
  crates/document_parse/Cargo.toml
  crates/document_parse/src/pdf.rs
Labels: kind/enhancement

#4623 Improve the UX of using huggingface models & embeddings
  Cargo.lock
  crates/model_components/src/modelsource/huggingface.rs
  crates/spicepod/Cargo.toml
  crates/spicepod/src/component/embeddings.rs
  crates/spicepod/src/component/model.rs
Labels: kind/bug

#4629 Improve `spice trace` CLI command
  bin/spice/cmd/trace.go
Labels: kind/enhancement

#4631 GGUF, hide metadata
  Cargo.lock
  crates/llms/Cargo.toml
Labels: kind/bug, area/ai

#4627 Add 1.0.2 release notes
  docs/release_notes/v1.0.2.md
Labels: kind/documentation

#4638 Add more improvements to 1.0.2
  Cargo.lock
  README.md
  bin/spice/cmd/trace.go
  crates/llms/Cargo.toml
  crates/model_components/src/modelsource/huggingface.rs
  crates/spicepod/Cargo.toml
  crates/spicepod/src/component/embeddings.rs
  crates/spicepod/src/component/model.rs
  docs/criteria/models/rc.md
  docs/release_notes/v1.0.2.md
Labels: kind/enhancement

#4640 Revert "feat: add schema inference for the Spice.ai Data Connector"
  crates/data_components/src/spice_cloud/catalog.rs
  crates/runtime/src/dataconnector/spiceai.rs
Labels: kind/bug

#4641 Update v1.0.2 release notes
  docs/release_notes/v1.0.2.md
Labels: kind/documentation

#4651 Add cuda build fix to 1.0.2
  Cargo.lock
  crates/llms/Cargo.toml
Labels: kind/bug

#4649 Fix cuda::ffi
  Cargo.lock
  crates/llms/Cargo.toml
Labels: kind/bug, area/ai, area/ci

#4647 Endgame Issue template improvements
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#4652 feat: setup sccache for PR checks
  .github/actions/setup-sccache/action.yml
  .github/workflows/pr.yml
Labels: kind/enhancement

#4648 Run `build_and_release_cuda.yml` when `crates/llms/Cargo.toml` changes
  .github/workflows/build_and_release_cuda.yml
Labels: kind/bug, area/ai, area/ci

#4653 Update E2E installation tests to match model runtime version
  .github/workflows/e2e_test_release_install.yml
Labels: kind/bug

#4664 fix: Postgres LargeUtf8 is equal to Utf8
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#4632 Better error for spicepod parsing
  bin/spiced/src/lib.rs
Labels: kind/bug

#4670 Update datafusion-table-providers (MySQL improvements)
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#4672 Handle delta tables partitioned by a date column with large date values
  Cargo.lock
  Cargo.toml
  crates/arrow_tools/Cargo.toml
  crates/arrow_tools/src/record_batch.rs
  crates/data_components/src/delta_lake.rs
  crates/runtime/tests/delta_lake/mod.rs
Labels: kind/bug

#4549 Add SQL Benchmark with sample eval configuration based on TPCH
  .gitignore
  test/nsql_bench/README.md
  test/nsql_bench/spicepod.yaml
  test/nsql_bench/tpch_nsql.jsonl
Labels: kind/enhancement

#4655 Update Helm chart to Spice v1.0.2
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/optimization

#4639 Update v1.0.2 release notes
  docs/release_notes/v1.0.2.md
Labels: kind/enhancement

#4675 Fix E2E AI release install test on self-hosted runners (macos)
  .github/workflows/e2e_test_release_install_ai.yml
Labels: kind/bug

#4646 For local models, use 'content=""' instead of None
  Cargo.lock
  crates/llms/Cargo.toml
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
Labels: kind/bug, area/ai

#4673 Perplexity Sonar LLM component.
  crates/llms/src/anthropic/mod.rs
  crates/llms/src/config.rs
  crates/llms/src/lib.rs
  crates/llms/src/perplexity/chat.rs
  crates/llms/src/perplexity/mod.rs
  crates/llms/src/perplexity/types.rs
  crates/llms/tests/llms/create.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/model/wrapper.rs
  crates/spicepod/src/component/model.rs
Labels: kind/enhancement, area/ai

#4679 Update async openai fork & support reasoning effort parameter
  Cargo.lock
  Cargo.toml
  crates/llms/src/anthropic/chat.rs
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/llms/tests/llms/util.rs
  crates/runtime/src/model/eval/scorer/fuzzy_match.rs
  crates/runtime/src/model/eval/scorer/includes.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/model/wrapper.rs
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_1_response_choices.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_completion.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_response_choices.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_completion.snap
Labels: kind/enhancement, kind/task

#4681 Main performance metrics calculation for Text to SQL Benchmark
  crates/runtime/src/model/eval/runs.rs
  test/nsql_bench/README.md
  test/nsql_bench/spicepod.yaml
Labels: kind/enhancement

#4688 Add testoperator for `evals` running
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  test/nsql_bench/README.md
  test/nsql_bench/data/tpch_nsql.jsonl
  test/nsql_bench/spicepod.yaml
  tools/testoperator/README.md
  tools/testoperator/src/args/evals.rs
  tools/testoperator/src/args/mod.rs
  tools/testoperator/src/commands/evals/mod.rs
  tools/testoperator/src/commands/mod.rs
  tools/testoperator/src/main.rs
Labels: kind/enhancement

#4687 Web search tool
  crates/llms/src/perplexity/mod.rs
  crates/runtime/src/http/v1/tools.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/model/wrapper.rs
  crates/runtime/src/tools/builtin/catalog.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
  crates/runtime/src/tools/builtin/get_readiness.rs
  crates/runtime/src/tools/builtin/list_datasets.rs
  crates/runtime/src/tools/builtin/mod.rs
  crates/runtime/src/tools/builtin/sample/tool.rs
  crates/runtime/src/tools/builtin/sql.rs
  crates/runtime/src/tools/builtin/table_schema.rs
  crates/runtime/src/tools/builtin/web_search/mod.rs
  crates/runtime/src/tools/builtin/web_search/perplexity.rs
  crates/runtime/src/tools/builtin/web_search/tool.rs
  crates/runtime/src/tools/factory/mod.rs
  crates/runtime/src/tools/memory/load.rs
  crates/runtime/src/tools/memory/store.rs
  crates/runtime/src/tools/mod.rs
Labels: kind/enhancement, area/ai

#4690 Setup `tpc-extension`
  Cargo.lock
  bin/spiced/Cargo.toml
  bin/spiced/src/lib.rs
  bin/spiced/src/tracing.rs
  crates/tpc_extension/Cargo.toml
  crates/tpc_extension/src/lib.rs
Labels: kind/enhancement

#4689 Add GH Workflow to run Text to SQL benchmark
  .github/workflows/ai_benchmark_nsql.yml
  test/nsql_bench/spicepod_hf.yaml
  tools/testoperator/src/args/evals.rs
  tools/testoperator/src/commands/evals/mod.rs
Labels: kind/enhancement

#4695 Add 1.0.2 as supported version to SECURITY.md
  SECURITY.md
Labels: kind/documentation

#4705 Text-To-SQL benchmark: trace failed tests
  Cargo.lock
  tools/testoperator/Cargo.toml
  tools/testoperator/src/commands/evals/mod.rs
Labels: kind/enhancement

#4707 Text-To-SQL benchmark: extend list of benchmarking models
  .github/workflows/ai_benchmark_nsql.yml
  test/nsql_bench/spicepod_claude-3-5-sonnet.yaml
  test/nsql_bench/spicepod_gpt-4o-mini.yaml
  test/nsql_bench/spicepod_gpt-4o.yaml
  test/nsql_bench/spicepod_grok2.yaml
  test/nsql_bench/spicepod_llama3-3b.yaml
  test/nsql_bench/spicepod_o1.yaml
  test/nsql_bench/spicepod_o3_mini.yaml
Labels: kind/enhancement

#4716 fix: Use PostgreSQL interval style for Spice.ai
  crates/runtime/src/dataconnector/spiceai.rs
Labels: kind/bug

#4699 Fix `spice upgrade` command
  bin/spice/cmd/upgrade.go
Labels: kind/bug

#4717 Fix bug: Ensure refresh only retrieves data within the retention period
  crates/runtime/src/datafusion.rs
Labels: kind/bug

#4713 Text-To-SQL: increase sql coverage, add more advanced tests
  test/nsql_bench/data/tpch_nsql.jsonl
Labels: kind/enhancement

#4719 Implement `unsupported_type_action: string` for Postgres JSONB support
  Cargo.lock
  Cargo.toml
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/github/github_app_token_provider.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/tests/postgres/common.rs
  crates/runtime/tests/postgres/mod.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#4721 Fix the get latest release logic
  bin/spice/pkg/github/release.go
Labels: kind/bug

#4723 Fix Spice.ai E2E test
  .github/workflows/e2e_test_ci.yml
Labels: kind/bug

#4731 Prepare 1.0.3 release
  Cargo.lock
  Cargo.toml
  bin/spice/cmd/trace.go
  bin/spice/cmd/upgrade.go
  bin/spice/pkg/github/release.go
  bin/spiced/Cargo.toml
  bin/spiced/src/lib.rs
  bin/spiced/src/tracing.rs
  crates/llms/Cargo.toml
  crates/llms/src/anthropic/chat.rs
  crates/llms/src/anthropic/mod.rs
  crates/llms/src/chat/mistral.rs
  crates/llms/src/chat/mod.rs
  crates/llms/src/config.rs
  crates/llms/src/lib.rs
  crates/llms/src/perplexity/chat.rs
  crates/llms/src/perplexity/mod.rs
  crates/llms/src/perplexity/types.rs
  crates/llms/tests/llms/create.rs
  crates/llms/tests/llms/util.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/github/github_app_token_provider.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/http/v1/tools.rs
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/eval/scorer/fuzzy_match.rs
  crates/runtime/src/model/eval/scorer/includes.rs
  crates/runtime/src/model/mod.rs
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/model/wrapper.rs
  crates/runtime/src/tools/builtin/catalog.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
  crates/runtime/src/tools/builtin/get_readiness.rs
  crates/runtime/src/tools/builtin/list_datasets.rs
  crates/runtime/src/tools/builtin/mod.rs
  crates/runtime/src/tools/builtin/sample/tool.rs
  crates/runtime/src/tools/builtin/sql.rs
  crates/runtime/src/tools/builtin/table_schema.rs
  crates/runtime/src/tools/builtin/web_search/mod.rs
  crates/runtime/src/tools/builtin/web_search/perplexity.rs
  crates/runtime/src/tools/builtin/web_search/tool.rs
  crates/runtime/src/tools/factory/mod.rs
  crates/runtime/src/tools/memory/load.rs
  crates/runtime/src/tools/memory/store.rs
  crates/runtime/src/tools/mod.rs
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_1_response_choices.snap
  crates/runtime/tests/models/snapshots/integration_models__models__hf__chat_completion.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_response_choices.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_completion.snap
  crates/runtime/tests/postgres/common.rs
  crates/runtime/tests/postgres/mod.rs
  crates/spicepod/src/component/dataset.rs
  crates/spicepod/src/component/model.rs
  crates/tpc_extension/Cargo.toml
  crates/tpc_extension/src/lib.rs
  version.txt
Labels: kind/enhancement

#4722 Truncate embedding columns within sampling tools
  crates/arrow_tools/src/format.rs
  crates/arrow_tools/src/lib.rs
  crates/arrow_tools/src/record_batch.rs
  crates/runtime/src/tools/builtin/sample/tool.rs
Labels: kind/bug, area/ai

#4718 Return non-existing model for v1/chat endpoint
  crates/runtime/src/http/v1/chat.rs
Labels: kind/optimization

#4736 Validate primary key columns during accelerated dataset initialization
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/dataset/acceleration/constraints.rs
  crates/runtime/src/dataaccelerator.rs
Labels: kind/bug

#4738 Add additional fixes to 1.0.3
  crates/arrow_tools/src/format.rs
  crates/arrow_tools/src/lib.rs
  crates/arrow_tools/src/record_batch.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/component/dataset/acceleration/constraints.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/tools/builtin/sample/tool.rs
  docs/release_notes/v1.0.3.md
Labels: kind/optimization

#4742 Update Helm chart for 1.0.3
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement

#4741 Fix tool call arguments in Grok messages
  crates/llms/src/xai.rs
Labels: kind/bug, area/ai

#4740 Update dependencies
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  go.mod
  go.sum
  tools/evalconverter/Cargo.toml
  tools/spiceschema/Cargo.toml
Labels: kind/dependencies

#4745 Update SECURITY.md with 1.0.3
  SECURITY.md
  docs/release_notes/v1.0.3.md
Labels: kind/documentation

#4735 Add basic smoke test of perplexity LLM to llm integration tests.
  .github/workflows/integration_llms.yml
  crates/llms/tests/llms/create.rs
  crates/llms/tests/llms/mod.rs
  crates/llms/tests/llms/snapshots/integration__llms__basic_perplexity_replied_appropriately.snap
  crates/llms/tests/llms/snapshots/integration__llms__usage_perplexity_has_completion_tokens.snap
  crates/llms/tests/llms/snapshots/integration__llms__usage_perplexity_has_prompt_tokens.snap
  crates/llms/tests/llms/snapshots/integration__llms__usage_perplexity_has_total_tokens.snap
  crates/llms/tests/llms/snapshots/integration__llms__usage_perplexity_total_tokens_gt_completion_tokens.snap
  crates/llms/tests/llms/snapshots/integration__llms__usage_perplexity_total_tokens_gt_prompt_tokens.snap
Labels: kind/enhancement, area/ai, area/ci

#4751 Don't run integration tests on PRs when only CLI is changed
  .github/workflows/integration.yml
  .github/workflows/integration_models.yml
Labels: kind/bug, area/cli, area/ci

#4750 Update 'spice trace' output format
  bin/spice/cmd/trace.go
  bin/spice/pkg/taskhistory/format.go
  bin/spice/pkg/taskhistory/taskhistory.go
  bin/spice/pkg/util/out.go
Labels: kind/enhancement, area/cli, area/ai

#4757 feat: Add vector search tracing
  bin/spice/cmd/trace.go
Labels: kind/enhancement

#4747 Prompt user to download runtime when running spice sql
  bin/spice/cmd/sql.go
Labels: kind/optimization

#4759 feat: Search with keyword filtering
  crates/runtime/benches/vector_search.rs
  crates/runtime/src/embeddings/vector_search.rs
  crates/runtime/src/http/v1/search.rs
  crates/runtime/src/tools/builtin/document_similarity.rs
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_1_ai_completion_input.snap
  crates/runtime/tests/models/snapshots/integration_models__models__openai__chat_2_document_similarity_tasks.snap
Labels: kind/enhancement

#4765 Fix search benchmark
  .github/workflows/benchmarks_search.yml
  crates/runtime/benches/bench_search/setup.rs
  crates/runtime/benches/vector_search.rs
Labels: kind/bug

#4771 feat: Add truncate command for spice trace
  bin/spice/cmd/trace.go
Labels: kind/enhancement

#4769 feat: Add IMAP access token parameter
  crates/runtime/src/dataconnector/imap.rs
Labels: kind/enhancement

#4776 Mark trunk builds as unstable
  Cargo.lock
  Cargo.toml
  crates/flightrepl/src/config.rs
  version.txt
Labels: kind/enhancement

#4753 feat: Release Spice.ai RC
  Cargo.lock
  Cargo.toml
  README.md
  crates/data_components/src/iceberg/catalog.rs
  docs/criteria/connectors/rc.md
Labels: kind/enhancement

#4785 Fix constraint verification for columns with uppercase letters
  .github/workflows/e2e_test_ci.yml
  Cargo.lock
  Cargo.toml
  test/scripts/setup-data-mysql.sql
Labels: kind/bug

#4783 Implement partition pruning for Delta Lake tables
  crates/data_components/src/delta_lake.rs
  crates/data_components/src/delta_lake/pruning.rs
  crates/runtime/tests/delta_lake/mod.rs
Labels: kind/enhancement

#4798 Run models E2E tests on PR
  .github/workflows/e2e_test_ci_models.yml
Labels: kind/optimization

#4787 Prevent the automatic normalization of `refresh_sql` columns to lowercase
  .github/workflows/e2e_test_ci.yml
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/datafusion/builder.rs
Labels: kind/bug

#4784 Add support for a `time_partition_column`
  crates/runtime/src/accelerated_table.rs
  crates/runtime/src/accelerated_table/refresh.rs
  crates/runtime/src/accelerated_table/refresh_task.rs
  crates/runtime/src/component/dataset.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/datafusion/filter_converter.rs
  crates/runtime/src/init/eval.rs
  crates/runtime/src/spice_metrics.rs
  crates/runtime/src/task_history.rs
  crates/runtime/tests/delta_lake/snapshots/integration__delta_lake__query_delta_lake_with_partition_pruning.snap
  crates/spice_cloud/src/lib.rs
  crates/spicepod/src/component/dataset.rs
Labels: kind/enhancement

#4781 fix: models runtime not required for cloud chat
  bin/spice/cmd/chat.go
  bin/spice/cmd/search.go
Labels: kind/bug

#4807 Only open one PR for openapi.json
  .github/workflows/generate-openapi.yml
Labels: kind/bug

#4809 Add Results-Cache-Status to indicate query result came from cache
  .github/workflows/e2e_test_ci.yml
  crates/cache/src/lib.rs
  crates/flightrepl/src/lib.rs
  crates/runtime/src/datafusion/query.rs
  crates/runtime/src/flight.rs
  crates/runtime/src/flight/util.rs
  crates/runtime/src/http/v1/mod.rs
  crates/runtime/tests/results_cache/mod.rs
Labels: kind/enhancement

#4764 Initial spice cli e2e tests with spice upgrade tests
  .github/actions/install-spice-cli/action.yml
  .github/actions/install-spice/action.yml
  .github/workflows/e2e_test_spice_cli.yml
Labels: kind/optimization

#4813 Fix Snowflake Case-Sensitive Identifiers support
  crates/data_components/src/snowflake.rs
Labels: kind/bug

#4802 Do no return underlying content of chunked embedding column by default during `tool_use::document_similarity`
  crates/runtime/src/embeddings/vector_search.rs
Labels: kind/bug, area/ai

#4816 Log CLI and Runtime Versions on startup
  bin/spice/cmd/spice.go
  bin/spiced/src/main.rs
Labels: kind/enhancement

#4826 Prepare for 1.0.4 release
  bin/spice/cmd/spice.go
  bin/spiced/src/main.rs
  crates/data_components/src/snowflake.rs
  docs/release_notes/v1.0.4.md
Labels: kind/enhancement

#4766 Sort keys for openai
  crates/runtime/tests/models/openai.rs
Labels: kind/bug, area/ai, area/ci

#4832 Remove docs index trigger from the endgame template
  .github/ISSUE_TEMPLATE/end_game.md
Labels: kind/documentation

#4827 Release notes for v1.0.4
  docs/ROADMAP.md
  docs/release_notes/v1.0.4.md
Labels: kind/documentation

#4829 Update SECURITY.md
  SECURITY.md
Labels: kind/documentation

#4838 Don't print URL
  bin/spice/cmd/spice.go
Labels: kind/bug

#4841 add 'eval_run' to 'spice trace'
  bin/spice/cmd/trace.go
Labels: kind/bug

#4843 Run benchmark tests w/o uploading test results (pending improvements)
  .github/workflows/benchmarks.yml
Labels: kind/bug

#4835 Fix 'actual" and "output" columns in `eval.results`.
  crates/runtime/src/model/eval/mod.rs
  crates/runtime/src/model/eval/result.rs
  crates/runtime/src/model/eval/scorer/mod.rs
Labels: kind/bug, area/ai, breaking change

#4849 fix: Update OpenAI model health check
  crates/llms/src/openai/chat.rs
Labels: kind/bug

#4844 Fix string escaping of system prompt
  crates/runtime/src/model/chat.rs
  crates/runtime/src/model/wrapper.rs
Labels: kind/bug, area/ai

#4828 update helm chart to v1.0.4
  deploy/chart/Chart.yaml
  deploy/chart/values.yaml
Labels: kind/enhancement, kind/task

#4851 fix: Skip sccache in PR for external users
  .github/workflows/pr.yml
Labels: kind/bug

#4804 fix: Return BAD_REQUEST when not embeddings are configured
  crates/runtime/src/http/v1/search.rs
Labels: kind/bug

#4852 Debug log cuda detection failure in spice
  bin/spice/pkg/github/runtime_release.go
Labels: kind/bug

#4854 fix: Set RUSTC wrapper explicitly
  .github/workflows/pr.yml
Labels: kind/bug

#4853 Improve trace UX for `ai_completion`, fix infinite tool calls
  crates/runtime/src/model/tool_use.rs
  crates/runtime/src/model/wrapper.rs
Labels: kind/bug, area/ai

#4811 Allow homebrew spice cli to upgrade the runtime
  .github/workflows/e2e_test_spice_cli.yml
  bin/spice/cmd/upgrade.go
Labels: kind/optimization

#4867 fix: Rustc wrapper actions
  .github/workflows/pr.yml
Labels: kind/bug

#4840 Provide link to supported OS list when user platform is not supported
  install/install-spiced.sh
  install/install.sh
Labels: kind/enhancement

#4761 Always download spice runtime version matched with spice cli version
  .github/workflows/e2e_test_spice_cli.yml
  bin/spice/cmd/install.go
  bin/spice/cmd/upgrade.go
  bin/spice/pkg/context/context.go
  bin/spice/pkg/github/release.go
  bin/spice/pkg/github/runtime_release.go
  bin/spice/pkg/runtime/runtime.go
Labels: kind/bug

#4842 Upgrade to DuckDB v1.2.0
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#4871 Disable flaky integration test
  crates/runtime/tests/models/openai.rs
Labels: kind/bug

#4873 fix: sccache actions setup
  .github/workflows/pr.yml
Labels: kind/bug

#4868 Fixing Go installation in the setup script for Linux Arm64
  CONTRIBUTING.md
Labels: kind/bug

#4874 DuckDB acceleration: Use temp table only for append with conflict resolution
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#4879 Gracefully shutdown the runtime and deallocate static resources
  Cargo.toml
  bin/spiced/src/lib.rs
  crates/document_parse/src/lib.rs
  crates/runtime/src/catalogconnector/mod.rs
  crates/runtime/src/dataaccelerator.rs
  crates/runtime/src/dataconnector.rs
  crates/runtime/src/datafusion.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/tools/factory/mod.rs
  crates/runtime/tests/acceleration/checkpoint_duckdb.rs
  crates/runtime/tests/acceleration/checkpoint_postgres.rs
  crates/runtime/tests/acceleration/checkpoint_sqlite.rs
  crates/runtime/tests/acceleration/single_instance_duckdb.rs
  crates/runtime/tests/rehydration/mod.rs
Labels: kind/bug

#4886 Revert "DuckDB acceleration: Use temp table only for append with conflict resolution"
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#4892 Allow overriding spicerack base url in the CLI
  bin/spice/pkg/registry/spicerack.go
Labels: kind/enhancement

#4887 Add support for Map Arrow type for DuckDB acceleration
  Cargo.lock
  Cargo.toml
Labels: kind/enhancement

#4833 Refactor Parameter Handling
  crates/runtime/src/catalogconnector/databricks.rs
  crates/runtime/src/catalogconnector/iceberg.rs
  crates/runtime/src/catalogconnector/spice_cloud.rs
  crates/runtime/src/catalogconnector/unity_catalog.rs
  crates/runtime/src/dataaccelerator/duckdb.rs
  crates/runtime/src/dataaccelerator/postgres.rs
  crates/runtime/src/dataaccelerator/sqlite.rs
  crates/runtime/src/dataconnector/abfs.rs
  crates/runtime/src/dataconnector/clickhouse.rs
  crates/runtime/src/dataconnector/databricks.rs
  crates/runtime/src/dataconnector/debezium.rs
  crates/runtime/src/dataconnector/delta_lake.rs
  crates/runtime/src/dataconnector/dremio.rs
  crates/runtime/src/dataconnector/duckdb.rs
  crates/runtime/src/dataconnector/dynamodb.rs
  crates/runtime/src/dataconnector/flightsql.rs
  crates/runtime/src/dataconnector/ftp.rs
  crates/runtime/src/dataconnector/github/mod.rs
  crates/runtime/src/dataconnector/graphql.rs
  crates/runtime/src/dataconnector/https.rs
  crates/runtime/src/dataconnector/imap.rs
  crates/runtime/src/dataconnector/listing/mod.rs
  crates/runtime/src/dataconnector/mssql.rs
  crates/runtime/src/dataconnector/mysql.rs
  crates/runtime/src/dataconnector/odbc.rs
  crates/runtime/src/dataconnector/postgres.rs
  crates/runtime/src/dataconnector/s3.rs
  crates/runtime/src/dataconnector/sftp.rs
  crates/runtime/src/dataconnector/sharepoint.rs
  crates/runtime/src/dataconnector/snowflake.rs
  crates/runtime/src/dataconnector/spark.rs
  crates/runtime/src/dataconnector/spiceai.rs
  crates/runtime/src/parameters.rs
Labels: kind/refactor

#4894 DuckDB: fix error handling during record batch insertion
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#4898 Add test Spicepod for DuckDB append acceleration with constraints
  test/spicepods/tpch/accelerated/constraints/append_query.sql
  test/spicepods/tpch/accelerated/constraints/duckdb_append_with_pk_and_indexes.yaml
  test/spicepods/tpch/accelerated/constraints/oha_test_append.sh
  test/spicepods/tpch/accelerated/constraints/oha_test_full.sh
  test/spicepods/tpch/accelerated/constraints/simulate_append_data.sh
Labels: kind/bug
